import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Candidates.Owner

/-!
# Relation closure for quotient candidates

This file owns finite derivations generated by relation ledgers.

The derivation syntax records how two raw quotient candidates are related by
available relation generators.  It is still pre-quotient data: no quotient type
or equivalence-class constructor is introduced here.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
A finite derivation that two quotient candidates are related by a finite
relation ledger.
-/
inductive TraceCorQRelationClosure :
    TraceCorQRelationLedger →
      TraceCorQQuotientCandidate →
        TraceCorQQuotientCandidate →
          Sort _ where
  | refl (ledger : TraceCorQRelationLedger)
      (candidate : TraceCorQQuotientCandidate) :
      TraceCorQRelationClosure ledger candidate candidate
  | step (ledger : TraceCorQRelationLedger)
      (relation : TraceCorQRelationGenerator) :
      TraceCorQRelationClosure
        (TraceCorQRelationLedger.append
          (TraceCorQRelationLedger.singleton relation)
          ledger)
        (TraceCorQQuotientInput.ofFormalSumLedger
          relation.support
          (TraceCorQRelationLedger.singleton relation))
        TraceCorQQuotientCandidate.empty
  | symm (ledger : TraceCorQRelationLedger)
      (left right : TraceCorQQuotientCandidate)
      (derivation :
        TraceCorQRelationClosure ledger left right) :
      TraceCorQRelationClosure ledger right left
  | trans (firstLedger secondLedger : TraceCorQRelationLedger)
      (left middle right : TraceCorQQuotientCandidate)
      (first :
        TraceCorQRelationClosure firstLedger left middle)
      (second :
        TraceCorQRelationClosure secondLedger middle right) :
      TraceCorQRelationClosure
        (TraceCorQRelationLedger.append firstLedger secondLedger)
        left
        right
  | addCongr (leftLedger rightLedger : TraceCorQRelationLedger)
      (left₁ left₂ right₁ right₂ : TraceCorQQuotientCandidate)
      (leftDerivation :
        TraceCorQRelationClosure leftLedger left₁ left₂)
      (rightDerivation :
        TraceCorQRelationClosure rightLedger right₁ right₂) :
      TraceCorQRelationClosure
        (TraceCorQRelationLedger.append leftLedger rightLedger)
        (TraceCorQQuotientCandidate.add left₁ right₁)
        (TraceCorQQuotientCandidate.add left₂ right₂)
  | smulCongr (ledger : TraceCorQRelationLedger)
      (coefficient : Rat)
      (left right : TraceCorQQuotientCandidate)
      (derivation :
        TraceCorQRelationClosure ledger left right) :
      TraceCorQRelationClosure
        ledger
        (TraceCorQQuotientCandidate.smul coefficient left)
        (TraceCorQQuotientCandidate.smul coefficient right)
  | compCongr (leftLedger rightLedger : TraceCorQRelationLedger)
      (left₁ left₂ right₁ right₂ : TraceCorQQuotientCandidate)
      (leftDerivation :
        TraceCorQRelationClosure leftLedger left₁ left₂)
      (rightDerivation :
        TraceCorQRelationClosure rightLedger right₁ right₂) :
      TraceCorQRelationClosure
        (TraceCorQRelationLedger.append leftLedger rightLedger)
        (TraceCorQQuotientCandidate.comp left₁ right₁)
        (TraceCorQQuotientCandidate.comp left₂ right₂)
  | sameFormalSum (ledger : TraceCorQRelationLedger)
      (left right : TraceCorQQuotientCandidate)
      (formalSum_eq : left.formalSum = right.formalSum) :
      TraceCorQRelationClosure ledger left right
  | permFormalSum (ledger : TraceCorQRelationLedger)
      (left right : TraceCorQQuotientCandidate)
      (formalSum_perm : List.Perm left.formalSum right.formalSum) :
      TraceCorQRelationClosure ledger left right
  | cancelAdjacentOpposite (ledger : TraceCorQRelationLedger)
      (leftContext suffix : TraceCorQFormalSum)
      (coefficient : Rat)
      (generator : TraceCorQGenerator) :
      TraceCorQRelationClosure
        ledger
        (TraceCorQQuotientInput.ofFormalSumLedger
          (leftContext ++
            (coefficient, generator) ::
              (-coefficient, generator) ::
                suffix)
          ledger)
        (TraceCorQQuotientInput.ofFormalSumLedger
          (leftContext ++ suffix)
          ledger)
  | combineAdjacentSame (ledger : TraceCorQRelationLedger)
      (leftContext suffix : TraceCorQFormalSum)
      (leftCoefficient rightCoefficient : Rat)
      (generator : TraceCorQGenerator) :
      TraceCorQRelationClosure
        ledger
        (TraceCorQQuotientInput.ofFormalSumLedger
          (leftContext ++
            (leftCoefficient, generator) ::
              (rightCoefficient, generator) ::
                suffix)
          ledger)
        (TraceCorQQuotientInput.ofFormalSumLedger
          (leftContext ++
            (leftCoefficient + rightCoefficient, generator) ::
              suffix)
          ledger)

/-- Reflexive relation-closure derivation for a candidate. -/
def TraceCorQRelationClosure.reflDerivation
    (ledger : TraceCorQRelationLedger)
    (candidate : TraceCorQQuotientCandidate) :
    TraceCorQRelationClosure ledger candidate candidate :=
  TraceCorQRelationClosure.refl ledger candidate

/-- Single relation-generator derivation under a ledger extension. -/
def TraceCorQRelationClosure.stepDerivation
    (ledger : TraceCorQRelationLedger)
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationClosure
      (TraceCorQRelationLedger.append
        (TraceCorQRelationLedger.singleton relation)
        ledger)
      (TraceCorQQuotientInput.ofFormalSumLedger
        relation.support
        (TraceCorQRelationLedger.singleton relation))
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationClosure.step ledger relation

/-- A single relation-generator derivation is exactly the primitive step. -/
theorem TraceCorQRelationClosure.stepDerivation_eq_step
    (ledger : TraceCorQRelationLedger)
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationClosure.stepDerivation ledger relation =
      TraceCorQRelationClosure.step ledger relation :=
  rfl

/-- Symmetry for finite relation-closure derivations. -/
def TraceCorQRelationClosure.symmDerivation
    (ledger : TraceCorQRelationLedger)
    (left right : TraceCorQQuotientCandidate)
    (derivation :
      TraceCorQRelationClosure ledger left right) :
    TraceCorQRelationClosure ledger right left :=
  TraceCorQRelationClosure.symm ledger left right derivation

/-- Transitivity for finite relation-closure derivations. -/
def TraceCorQRelationClosure.transDerivation
    (firstLedger secondLedger : TraceCorQRelationLedger)
    (left middle right : TraceCorQQuotientCandidate)
    (first :
      TraceCorQRelationClosure firstLedger left middle)
    (second :
      TraceCorQRelationClosure secondLedger middle right) :
    TraceCorQRelationClosure
      (TraceCorQRelationLedger.append firstLedger secondLedger)
      left
      right :=
  TraceCorQRelationClosure.trans
    firstLedger secondLedger left middle right first second

/-- Additive compatibility for finite relation-closure derivations. -/
def TraceCorQRelationClosure.addCongrDerivation
    (leftLedger rightLedger : TraceCorQRelationLedger)
    (left₁ left₂ right₁ right₂ : TraceCorQQuotientCandidate)
    (leftDerivation :
      TraceCorQRelationClosure leftLedger left₁ left₂)
    (rightDerivation :
      TraceCorQRelationClosure rightLedger right₁ right₂) :
    TraceCorQRelationClosure
      (TraceCorQRelationLedger.append leftLedger rightLedger)
      (TraceCorQQuotientCandidate.add left₁ right₁)
      (TraceCorQQuotientCandidate.add left₂ right₂) :=
  TraceCorQRelationClosure.addCongr
    leftLedger rightLedger
    left₁ left₂ right₁ right₂
    leftDerivation rightDerivation

/-- Scalar compatibility for finite relation-closure derivations. -/
def TraceCorQRelationClosure.smulCongrDerivation
    (ledger : TraceCorQRelationLedger)
    (coefficient : Rat)
    (left right : TraceCorQQuotientCandidate)
    (derivation :
      TraceCorQRelationClosure ledger left right) :
    TraceCorQRelationClosure
      ledger
      (TraceCorQQuotientCandidate.smul coefficient left)
      (TraceCorQQuotientCandidate.smul coefficient right) :=
  TraceCorQRelationClosure.smulCongr
    ledger coefficient left right derivation

/-- Composition compatibility for finite relation-closure derivations. -/
def TraceCorQRelationClosure.compCongrDerivation
    (leftLedger rightLedger : TraceCorQRelationLedger)
    (left₁ left₂ right₁ right₂ : TraceCorQQuotientCandidate)
    (leftDerivation :
      TraceCorQRelationClosure leftLedger left₁ left₂)
    (rightDerivation :
      TraceCorQRelationClosure rightLedger right₁ right₂) :
    TraceCorQRelationClosure
      (TraceCorQRelationLedger.append leftLedger rightLedger)
      (TraceCorQQuotientCandidate.comp left₁ right₁)
      (TraceCorQQuotientCandidate.comp left₂ right₂) :=
  TraceCorQRelationClosure.compCongr
    leftLedger rightLedger
    left₁ left₂ right₁ right₂
    leftDerivation rightDerivation

/-- Candidates with the same formal sum are related, regardless of ledger bookkeeping. -/
def TraceCorQRelationClosure.sameFormalSumDerivation
    (ledger : TraceCorQRelationLedger)
    (left right : TraceCorQQuotientCandidate)
    (formalSum_eq : left.formalSum = right.formalSum) :
    TraceCorQRelationClosure ledger left right :=
  TraceCorQRelationClosure.sameFormalSum
    ledger
    left
    right
    formalSum_eq

/-- Candidates with permuted formal sums are related, regardless of ledger bookkeeping. -/
def TraceCorQRelationClosure.permFormalSumDerivation
    (ledger : TraceCorQRelationLedger)
    (left right : TraceCorQQuotientCandidate)
    (formalSum_perm : List.Perm left.formalSum right.formalSum) :
    TraceCorQRelationClosure ledger left right :=
  TraceCorQRelationClosure.permFormalSum
    ledger
    left
    right
    formalSum_perm

/-- Adjacent opposite rational multiples of the same generator cancel. -/
def TraceCorQRelationClosure.cancelAdjacentOppositeDerivation
    (ledger : TraceCorQRelationLedger)
    (leftContext suffix : TraceCorQFormalSum)
    (coefficient : Rat)
    (generator : TraceCorQGenerator) :
    TraceCorQRelationClosure
      ledger
      (TraceCorQQuotientInput.ofFormalSumLedger
        (leftContext ++
          (coefficient, generator) ::
            (-coefficient, generator) ::
              suffix)
        ledger)
      (TraceCorQQuotientInput.ofFormalSumLedger
        (leftContext ++ suffix)
        ledger) :=
  TraceCorQRelationClosure.cancelAdjacentOpposite
    ledger
    leftContext
    suffix
    coefficient
    generator

/-- Adjacent rational multiples of the same generator combine. -/
def TraceCorQRelationClosure.combineAdjacentSameDerivation
    (ledger : TraceCorQRelationLedger)
    (leftContext suffix : TraceCorQFormalSum)
    (leftCoefficient rightCoefficient : Rat)
    (generator : TraceCorQGenerator) :
    TraceCorQRelationClosure
      ledger
      (TraceCorQQuotientInput.ofFormalSumLedger
        (leftContext ++
          (leftCoefficient, generator) ::
            (rightCoefficient, generator) ::
              suffix)
        ledger)
      (TraceCorQQuotientInput.ofFormalSumLedger
        (leftContext ++
          (leftCoefficient + rightCoefficient, generator) ::
            suffix)
        ledger) :=
  TraceCorQRelationClosure.combineAdjacentSame
    ledger
    leftContext
    suffix
    leftCoefficient
    rightCoefficient
    generator

end AnalyticMotives
end LFunctions
end Boundary
