import Mathlib.CategoryTheory.Localization.Triangulated
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homotopy.NullSubcategory.Owner

/-!
# The analytic Verdier quotient

The stable analytic motive category is the localization of the additive
analytic homotopy category at the morphisms whose cones lie in the stable null
subcategory generated by analytic localization cones.

The `Triangulated` subdirectory exposes the quotient functor's triangulated
structure and distinguished-triangle transport theorem.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- The stable analytic motive category obtained by Verdier localization. -/
abbrev TraceAnalyticStableMotiveCategory :=
  TraceAnalyticStableNullSubcategory.invertedMorphisms.Localization

/-- The quotient functor from additive analytic homotopy motives to stable analytic motives. -/
def TraceAnalyticStableMotiveCategory.quotientFunctor :
    TraceAnalyticAdditiveHomotopyCategory ⥤
      TraceAnalyticStableMotiveCategory :=
  TraceAnalyticStableNullSubcategory.invertedMorphisms.Q

/-- The stable analytic motive represented by an additive analytic homotopy object. -/
def TraceAnalyticStableMotiveCategory.objectOf
    (object : TraceAnalyticAdditiveHomotopyCategory) :
    TraceAnalyticStableMotiveCategory :=
  TraceAnalyticStableMotiveCategory.quotientFunctor.obj object

/-- The stable analytic motive morphism represented by an additive homotopy morphism. -/
def TraceAnalyticStableMotiveCategory.mapOf
    {source target : TraceAnalyticAdditiveHomotopyCategory}
    (hom : source ⟶ target) :
    TraceAnalyticStableMotiveCategory.objectOf source ⟶
      TraceAnalyticStableMotiveCategory.objectOf target :=
  TraceAnalyticStableMotiveCategory.quotientFunctor.map hom

/-- The object map is the object part of the Verdier quotient functor. -/
theorem TraceAnalyticStableMotiveCategory.objectOf_eq
    (object : TraceAnalyticAdditiveHomotopyCategory) :
    TraceAnalyticStableMotiveCategory.objectOf object =
      TraceAnalyticStableMotiveCategory.quotientFunctor.obj object :=
  rfl

/-- The morphism map is the morphism part of the Verdier quotient functor. -/
theorem TraceAnalyticStableMotiveCategory.mapOf_eq
    {source target : TraceAnalyticAdditiveHomotopyCategory}
    (hom : source ⟶ target) :
    TraceAnalyticStableMotiveCategory.mapOf hom =
      TraceAnalyticStableMotiveCategory.quotientFunctor.map hom :=
  rfl

/-- Stable analytic motives inherit integer shifts from Verdier localization. -/
def TraceAnalyticStableMotiveCategory.hasShiftStructure :
    CategoryTheory.HasShift TraceAnalyticStableMotiveCategory ℤ :=
  CategoryTheory.HasShift.localization

/-- The stable analytic motive category inherits a pretriangulated structure. -/
def TraceAnalyticStableMotiveCategory.pretriangulatedStructure :
    CategoryTheory.Pretriangulated TraceAnalyticStableMotiveCategory :=
  CategoryTheory.Triangulated.Localization.pretriangulated
    TraceAnalyticStableMotiveCategory.quotientFunctor
    TraceAnalyticStableNullSubcategory.invertedMorphisms

/-- The stable analytic motive category inherits a triangulated structure. -/
def TraceAnalyticStableMotiveCategory.triangulatedStructure :
    CategoryTheory.IsTriangulated TraceAnalyticStableMotiveCategory :=
  CategoryTheory.Triangulated.Localization.isTriangulated
    TraceAnalyticStableMotiveCategory.quotientFunctor
    TraceAnalyticStableNullSubcategory.invertedMorphisms

/-- Distinguished triangles in the stable analytic motive category. -/
def TraceAnalyticStableMotiveCategory.distinguishedTriangles :
    Set (CategoryTheory.Pretriangulated.Triangle
      TraceAnalyticStableMotiveCategory) :=
  CategoryTheory.Pretriangulated.distTriang
    TraceAnalyticStableMotiveCategory

/-- Stable analytic distinguished triangles are Mathlib's distinguished triangles. -/
theorem TraceAnalyticStableMotiveCategory.distinguishedTriangles_eq :
    TraceAnalyticStableMotiveCategory.distinguishedTriangles =
      CategoryTheory.Pretriangulated.distTriang
        TraceAnalyticStableMotiveCategory :=
  rfl

/-- The Verdier quotient functor inverts the first map of every stable acyclic generator. -/
theorem TraceAnalyticStableMotiveCategory.generator_firstMap_isIso
    (generator : TraceAnalyticStableAcyclicGenerator) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map generator.firstMap) :=
  CategoryTheory.Localization.inverts
    TraceAnalyticStableMotiveCategory.quotientFunctor
    TraceAnalyticStableNullSubcategory.invertedMorphisms
    generator.firstMap
    (TraceAnalyticStableNullSubcategory.generator_firstMap_inverted generator)

/-- The Verdier quotient functor inverts every analytic localization input's stable map. -/
theorem TraceAnalyticStableMotiveCategory.localizationInput_stableMap_isIso
    (input : TraceLocalizationInput) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map input.stableMap) :=
  Eq.subst
    (motive :=
      fun hom =>
        IsIso
          (TraceAnalyticStableMotiveCategory.quotientFunctor.map hom))
    (TraceAnalyticStableAcyclicGenerator.firstMap_eq_input_stableMap
      ({ input := input } : TraceAnalyticStableAcyclicGenerator))
    (TraceAnalyticStableMotiveCategory.generator_firstMap_isIso
      ({ input := input } : TraceAnalyticStableAcyclicGenerator))

/-- The Verdier quotient inverts the stable descent-channel map. -/
theorem TraceAnalyticStableMotiveCategory.descentChannel_stableMap_isIso
    (source target : QTraceExpression) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map
        (TraceLocalizationInput.descentChannel source target).stableMap) :=
  TraceAnalyticStableMotiveCategory.localizationInput_stableMap_isIso
    (TraceLocalizationInput.descentChannel source target)

/-- The Verdier quotient inverts the stable descent-refinement map. -/
theorem TraceAnalyticStableMotiveCategory.descentRefinement_stableMap_isIso
    (source target : QTraceExpression) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map
        (TraceLocalizationInput.descentRefinement source target).stableMap) :=
  TraceAnalyticStableMotiveCategory.localizationInput_stableMap_isIso
    (TraceLocalizationInput.descentRefinement source target)

/-- The Verdier quotient inverts the stable descent-schedule map. -/
theorem TraceAnalyticStableMotiveCategory.descentSchedule_stableMap_isIso
    (source target : QTraceExpression) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map
        (TraceLocalizationInput.descentSchedule source target).stableMap) :=
  TraceAnalyticStableMotiveCategory.localizationInput_stableMap_isIso
    (TraceLocalizationInput.descentSchedule source target)

/-- The Verdier quotient inverts the stable interval-Stokes map. -/
theorem TraceAnalyticStableMotiveCategory.intervalStokes_stableMap_isIso
    (source target : QTraceExpression) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map
        (TraceLocalizationInput.intervalStokes source target).stableMap) :=
  TraceAnalyticStableMotiveCategory.localizationInput_stableMap_isIso
    (TraceLocalizationInput.intervalStokes source target)

/-- The Verdier quotient inverts the stable interval-Fubini map. -/
theorem TraceAnalyticStableMotiveCategory.intervalFubini_stableMap_isIso
    (source target : QTraceExpression) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map
        (TraceLocalizationInput.intervalFubini source target).stableMap) :=
  TraceAnalyticStableMotiveCategory.localizationInput_stableMap_isIso
    (TraceLocalizationInput.intervalFubini source target)

/-- The Verdier quotient inverts the stable Tate-weight-drop map. -/
theorem TraceAnalyticStableMotiveCategory.tateWeightDrop_stableMap_isIso
    (source target : QTraceExpression) :
    IsIso
      (TraceAnalyticStableMotiveCategory.quotientFunctor.map
        (TraceLocalizationInput.tateWeightDrop source target).stableMap) :=
  TraceAnalyticStableMotiveCategory.localizationInput_stableMap_isIso
    (TraceLocalizationInput.tateWeightDrop source target)

end AnalyticMotives
end LFunctions
end Boundary
