import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleTangentConvergence.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleTraceCorQ.Owner

/-!
# Zero-pole analytic trace chain

This file names the first concrete analytic trace chain in the completed-zeta
adapter.

The chain is not asserted as a categorical composition.  It packages the raw
one-step paths and the analytic convergence certificates that relate the
finite-square residue seed, tangent-boundary convergence, decay inputs, and the
right vertical channel.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The raw path list currently present in the zero-pole analytic chain. -/
def completedZetaZeroPoleAnalyticChainPaths : List TraceRewritePath :=
  [completedZetaZeroPoleResiduePath,
    completedZetaZeroPoleChannelPath]

/-- The first raw path in the zero-pole analytic chain is residue extraction. -/
theorem completedZetaZeroPoleAnalyticChainPaths_first :
    completedZetaZeroPoleAnalyticChainPaths =
      completedZetaZeroPoleResiduePath ::
        completedZetaZeroPoleChannelPath ::
          [] :=
  rfl

/-- The Q-linear formal sum generated by the current zero-pole analytic chain. -/
def completedZetaZeroPoleAnalyticChainTraceCorQFormalSum :
    TraceCorQFormalSum :=
  completedZetaZeroPoleSeedTraceCorQFormalSum

/-- The chain formal sum is the sum of the residue and channel correspondences. -/
theorem completedZetaZeroPoleAnalyticChainTraceCorQFormalSum_eq :
    completedZetaZeroPoleAnalyticChainTraceCorQFormalSum =
      TraceCorQFormalSum.add
        completedZetaZeroPoleResidueTraceCorQFormalSum
        completedZetaZeroPoleChannelTraceCorQFormalSum :=
  rfl

/-- The residue step of the zero-pole analytic chain is analytically sound. -/
theorem completedZetaZeroPoleAnalyticChain_residue_sound
    (f : ZetaAdmissibleFunction) (hPhi : ZetaPhiAnalyticControl f)
    {R : ℝ} (hR : 0 < R) :
    completedZetaZeroPoleFiniteSquareBoundaryTrace f R =
      completedZetaZeroPoleFiniteSquareResidueTrace f :=
  completedZetaZeroPoleFiniteSquareResidueGenerator_sound
    f hPhi hR

/-- The channel step of the zero-pole analytic chain is analytically sound. -/
theorem completedZetaZeroPoleAnalyticChain_channel_sound
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    completedZetaZeroPoleLeftVerticalTrace f F h u =
      completedZetaZeroPoleRightVerticalTrace f F h u +
        completedZetaZeroPoleHorizontalTrace f F h u -
        completedZetaZeroPoleRectangleBoundaryTrace f F h u :=
  completedZetaZeroPoleChannelGenerator_sound
    f F h u

/-- The tangent-boundary step of the zero-pole analytic chain converges to the residue trace. -/
theorem completedZetaZeroPoleAnalyticChain_tangentBoundary_tendsto
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) :
    Tendsto
      (completedZetaZeroPoleScheduledTangentBoundaryTraceFunction f F h)
      atTop
      (𝓝 (completedZetaZeroPoleFiniteSquareResidueTrace f)) :=
  completedZetaZeroPoleScheduledTangentBoundaryTrace_tendsto_finiteSquareResidueTrace
    f F h

/-- The current zero-pole analytic chain reaches the right vertical channel limit. -/
theorem completedZetaZeroPoleAnalyticChain_rightVertical_tendsto
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) :
    Tendsto
      (completedZetaZeroPoleScheduledRightVerticalTraceFunction f F h)
      atTop
      (𝓝 (-(completedZetaZeroPoleFiniteSquareResidueTrace f * Complex.I))) :=
  completedZetaZeroPoleRightVerticalTrace_tendsto_of_tangentBoundaryConvergence
    f F h

end AnalyticMotives
end LFunctions
end Boundary
