import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.InversionAcyclicBridge.Named.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Complexes.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Triangulated.Owner

/-!
# Stable homotopy images of analytic localization inputs

Each concrete analytic localization input gives a degree-zero map of additive
complexes.  This file records its image in the additive analytic homotopy
category and the distinguished mapping-cone triangle generated by that image.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- The stable additive-homotopy source object of a localization input. -/
def TraceLocalizationInput.stableSource
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.objectOf input.additiveSourceComplex

/-- The stable additive-homotopy target object of a localization input. -/
def TraceLocalizationInput.stableTarget
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.objectOf input.additiveTargetComplex

/-- The stable additive-homotopy map induced by a localization input. -/
def TraceLocalizationInput.stableMap
    (input : TraceLocalizationInput) :
    input.stableSource ⟶ input.stableTarget :=
  TraceAnalyticAdditiveHomotopyCategory.mapOf input.additiveComplexHom

/-- The stable source is the homotopy image of the source complex. -/
theorem TraceLocalizationInput.stableSource_eq
    (input : TraceLocalizationInput) :
    input.stableSource =
      TraceAnalyticAdditiveHomotopyCategory.objectOf input.additiveSourceComplex :=
  rfl

/-- The stable target is the homotopy image of the target complex. -/
theorem TraceLocalizationInput.stableTarget_eq
    (input : TraceLocalizationInput) :
    input.stableTarget =
      TraceAnalyticAdditiveHomotopyCategory.objectOf input.additiveTargetComplex :=
  rfl

/-- The stable map is the homotopy image of the additive complex map. -/
theorem TraceLocalizationInput.stableMap_eq
    (input : TraceLocalizationInput) :
    input.stableMap =
      TraceAnalyticAdditiveHomotopyCategory.mapOf input.additiveComplexHom :=
  rfl

/-- The stable mapping-cone triangle attached to a localization input. -/
def TraceLocalizationInput.stableMappingConeTriangle
    (input : TraceLocalizationInput) :
    Triangle TraceAnalyticAdditiveHomotopyCategory :=
  CochainComplex.mappingCone.triangleh input.additiveComplexHom

/-- The stable localization-input mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.stableMappingConeTriangle_distinguished
    (input : TraceLocalizationInput) :
    input.stableMappingConeTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceAnalyticAdditiveHomotopyCategory.mappingCone_triangle_distinguished
    input.additiveComplexHom

/-- The first morphism of the stable mapping-cone triangle is the stable localization map. -/
theorem TraceLocalizationInput.stableMappingConeTriangle_mor₁
    (input : TraceLocalizationInput) :
    input.stableMappingConeTriangle.mor₁ =
      input.stableMap :=
  rfl

/-- The stable descent-channel source object. -/
def TraceLocalizationInput.descentChannel_stableSource
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.descentChannel source target).stableSource

/-- The stable descent-channel target object. -/
def TraceLocalizationInput.descentChannel_stableTarget
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.descentChannel source target).stableTarget

/-- The stable descent-channel map. -/
def TraceLocalizationInput.descentChannel_stableMap
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentChannel_stableSource source target ⟶
      TraceLocalizationInput.descentChannel_stableTarget source target :=
  (TraceLocalizationInput.descentChannel source target).stableMap

/-- The stable descent-channel mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.descentChannel_stableMappingConeTriangle_distinguished
    (source target : QTraceExpression) :
    (TraceLocalizationInput.descentChannel source target).stableMappingConeTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  (TraceLocalizationInput.descentChannel source target).stableMappingConeTriangle_distinguished

/-- The stable descent-refinement source object. -/
def TraceLocalizationInput.descentRefinement_stableSource
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.descentRefinement source target).stableSource

/-- The stable descent-refinement target object. -/
def TraceLocalizationInput.descentRefinement_stableTarget
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.descentRefinement source target).stableTarget

/-- The stable descent-refinement map. -/
def TraceLocalizationInput.descentRefinement_stableMap
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentRefinement_stableSource source target ⟶
      TraceLocalizationInput.descentRefinement_stableTarget source target :=
  (TraceLocalizationInput.descentRefinement source target).stableMap

/-- The stable descent-refinement mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.descentRefinement_stableMappingConeTriangle_distinguished
    (source target : QTraceExpression) :
    (TraceLocalizationInput.descentRefinement source target).stableMappingConeTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  (TraceLocalizationInput.descentRefinement source target).stableMappingConeTriangle_distinguished

/-- The stable descent-schedule source object. -/
def TraceLocalizationInput.descentSchedule_stableSource
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.descentSchedule source target).stableSource

/-- The stable descent-schedule target object. -/
def TraceLocalizationInput.descentSchedule_stableTarget
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.descentSchedule source target).stableTarget

/-- The stable descent-schedule map. -/
def TraceLocalizationInput.descentSchedule_stableMap
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentSchedule_stableSource source target ⟶
      TraceLocalizationInput.descentSchedule_stableTarget source target :=
  (TraceLocalizationInput.descentSchedule source target).stableMap

/-- The stable descent-schedule mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.descentSchedule_stableMappingConeTriangle_distinguished
    (source target : QTraceExpression) :
    (TraceLocalizationInput.descentSchedule source target).stableMappingConeTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  (TraceLocalizationInput.descentSchedule source target).stableMappingConeTriangle_distinguished

/-- The stable interval-Stokes source object. -/
def TraceLocalizationInput.intervalStokes_stableSource
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.intervalStokes source target).stableSource

/-- The stable interval-Stokes target object. -/
def TraceLocalizationInput.intervalStokes_stableTarget
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.intervalStokes source target).stableTarget

/-- The stable interval-Stokes map. -/
def TraceLocalizationInput.intervalStokes_stableMap
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalStokes_stableSource source target ⟶
      TraceLocalizationInput.intervalStokes_stableTarget source target :=
  (TraceLocalizationInput.intervalStokes source target).stableMap

/-- The stable interval-Stokes mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.intervalStokes_stableMappingConeTriangle_distinguished
    (source target : QTraceExpression) :
    (TraceLocalizationInput.intervalStokes source target).stableMappingConeTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  (TraceLocalizationInput.intervalStokes source target).stableMappingConeTriangle_distinguished

/-- The stable interval-Fubini source object. -/
def TraceLocalizationInput.intervalFubini_stableSource
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.intervalFubini source target).stableSource

/-- The stable interval-Fubini target object. -/
def TraceLocalizationInput.intervalFubini_stableTarget
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.intervalFubini source target).stableTarget

/-- The stable interval-Fubini map. -/
def TraceLocalizationInput.intervalFubini_stableMap
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalFubini_stableSource source target ⟶
      TraceLocalizationInput.intervalFubini_stableTarget source target :=
  (TraceLocalizationInput.intervalFubini source target).stableMap

/-- The stable interval-Fubini mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.intervalFubini_stableMappingConeTriangle_distinguished
    (source target : QTraceExpression) :
    (TraceLocalizationInput.intervalFubini source target).stableMappingConeTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  (TraceLocalizationInput.intervalFubini source target).stableMappingConeTriangle_distinguished

/-- The stable Tate-weight-drop source object. -/
def TraceLocalizationInput.tateWeightDrop_stableSource
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.tateWeightDrop source target).stableSource

/-- The stable Tate-weight-drop target object. -/
def TraceLocalizationInput.tateWeightDrop_stableTarget
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveHomotopyCategory :=
  (TraceLocalizationInput.tateWeightDrop source target).stableTarget

/-- The stable Tate-weight-drop map. -/
def TraceLocalizationInput.tateWeightDrop_stableMap
    (source target : QTraceExpression) :
    TraceLocalizationInput.tateWeightDrop_stableSource source target ⟶
      TraceLocalizationInput.tateWeightDrop_stableTarget source target :=
  (TraceLocalizationInput.tateWeightDrop source target).stableMap

/-- The stable Tate-weight-drop mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.tateWeightDrop_stableMappingConeTriangle_distinguished
    (source target : QTraceExpression) :
    (TraceLocalizationInput.tateWeightDrop source target).stableMappingConeTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  (TraceLocalizationInput.tateWeightDrop source target).stableMappingConeTriangle_distinguished

end AnalyticMotives
end LFunctions
end Boundary
