import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Functor.Singleton.Owner

/-!
# Singleton additive objects at the comparison source endpoint

This file owns the first source-side passage from a certified trace object to
the comparison source: the trace presentation is viewed as a one-component
object of the analytic additive envelope, and its analytic payload is recovered
from the zero component.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The singleton additive object generated by a certified trace object at the
comparison source endpoint. -/
def TraceAnalyticMotiveComparison.sourceTraceAdditiveObject
    (object : TraceCorQObject) :
    TraceAnalyticAdditiveObject :=
  TraceAnalyticAdditiveObject.singleton object

/-- The endpoint singleton additive object is the additive-envelope singleton. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_eq_singleton
    (object : TraceCorQObject) :
    TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object =
      TraceAnalyticAdditiveObject.singleton object :=
  rfl

/-- The endpoint singleton additive object is the object part of the singleton
additive-envelope functor. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_eq_singletonFunctor_obj
    (object : TraceCorQObject) :
    TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object =
      TraceAnalyticAdditiveObject.singletonFunctor.obj object :=
  rfl

/-- The singleton additive-envelope morphism generated by a trace
correspondence at the comparison source endpoint. -/
def TraceAnalyticMotiveComparison.sourceTraceAdditiveMap
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticMotiveComparison.sourceTraceAdditiveObject source ⟶
      TraceAnalyticMotiveComparison.sourceTraceAdditiveObject target :=
  TraceAnalyticAdditiveObject.singletonFunctor.map hom

/-- The endpoint singleton additive map is the map part of the singleton
additive-envelope functor. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveMap_eq_singletonFunctor_map
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticMotiveComparison.sourceTraceAdditiveMap hom =
      TraceAnalyticAdditiveObject.singletonFunctor.map hom :=
  rfl

/-- The endpoint singleton additive map is the singleton matrix of the trace
correspondence. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveMap_eq_singletonMap
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticMotiveComparison.sourceTraceAdditiveMap hom =
      TraceAnalyticAdditiveHom.singletonMap hom :=
  rfl

/-- The endpoint singleton additive object has one component. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_length
    (object : TraceCorQObject) :
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).length =
      1 :=
  TraceAnalyticAdditiveObject.singleton_length object

/-- The zero component of the endpoint singleton additive object is the
certified trace object. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
    (object : TraceCorQObject) :
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component 0 =
      object :=
  TraceAnalyticAdditiveObject.singleton_component_zero object

/-- The zero component preserves the certified trace source expression. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_source
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).source =
      object.source :=
  congrArg
    TraceCorQObject.source
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the certified trace residue ledger. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_ledger
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).ledger =
      object.ledger :=
  congrArg
    TraceCorQObject.ledger
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the certified trace channel list. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_channels
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).channels =
      object.channels :=
  congrArg
    TraceCorQObject.channels
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the certified trace schedule. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_schedule
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).schedule =
      object.schedule :=
  congrArg
    TraceCorQObject.schedule
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the analytic certificate ledger. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_certificateLedger
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).certificateLedger =
      object.certificateLedger :=
  congrArg
    TraceCorQObject.certificateLedger
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the imported finite-rectangle count. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_importedRectangleCount
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).importedRectangleCount =
      object.importedRectangleCount :=
  congrArg
    TraceCorQObject.importedRectangleCount
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the imported finite rectangles. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_importedRectangles
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).importedRectangles =
      object.importedRectangles :=
  congrArg
    TraceCorQObject.importedRectangles
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the trace-bookkeeping count. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_traceBookkeepingCount
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).traceBookkeepingCount =
      object.traceBookkeepingCount :=
  congrArg
    TraceCorQObject.traceBookkeepingCount
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

/-- The zero component preserves the rewrite-step count. -/
theorem TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero_rewriteStepCount
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object).component
      0).rewriteStepCount =
      object.rewriteStepCount :=
  congrArg
    TraceCorQObject.rewriteStepCount
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveObject_component_zero
      object)

end AnalyticMotives
end LFunctions
end Boundary
