import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Presheaves.RewriteMaps.ByKind.Facts.Owner

/-!
# Presheaf maps grouped by analytic rewrite kind

This aggregate exposes the by-kind endpoint, trace-morphism, representable-map,
lifted-Yoneda-map, and map-comparison facts generated by each concrete kind of
analytic trace rewrite.
-/
