import Boundary.LFunctionsRootedTreeFinal.Final.RiemannHypothesisBridge.Bridge.WeilCriterion.ProbeInterface.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.RiemannHypothesisBridge.Bridge.WeilCriterion.Zero.ZetaWeilShared.AutocorrelationInterface.AutocorrelationCore.Owner

/-!
# Boundary autocorrelation interface

This file names the autocorrelation-generated probes without pulling the
criterion layer into the transform/probe construction stack.
-/

namespace Boundary
namespace LFunctions

noncomputable section

/-- The probe is generated by the admissible convolution autocorrelation of a seed. -/
def IsZetaConvolutionAutocorrelationProbe (φ : ZetaProbe) : Prop :=
  ∃ f : ZetaAdmissibleFunction,
    φ.toZetaTestFunction' =
      (ZetaAdmissibleFunction.convolutionAutocorrelation f).toZetaTestFunction'

/-- Historical name for convolution-autocorrelation probes. The RH-lane autocorrelation
surface is the convolution autocorrelation, not the pointwise presentation. -/
abbrev IsZetaAutocorrelationProbe (φ : ZetaProbe) : Prop :=
  IsZetaConvolutionAutocorrelationProbe φ

end
end LFunctions
end Boundary
