import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.MotivicTStructure.MathlibFields.Monotonicity.Owner

/-!
# Iso-closed analytic motivic aisle and coaisle predicates

Mathlib's `TStructure` record requires aisle and coaisle predicates to be
closed under isomorphism.  This file applies Mathlib's `isoClosure` operation
to the concrete representative-defined analytic predicates and proves the
corresponding closure and adjacent monotonicity fields.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- Iso-closed analytic nonpositive aisle at the cut `cut`, generated by the
concrete shifted-bounded representative aisle predicate. -/
abbrev TraceAnalyticMotivicTStructure.aisleLEIsoClosed
    (cut : ℤ) :
    TraceAnalyticDMgmComparisonSource → Prop :=
  CategoryTheory.isoClosure
    (TraceAnalyticMotivicTStructure.aisleLE cut)

/-- Iso-closed analytic nonnegative coaisle at the cut `cut`, generated by the
concrete shifted-bounded representative coaisle predicate. -/
abbrev TraceAnalyticMotivicTStructure.coaisleGEIsoClosed
    (cut : ℤ) :
    TraceAnalyticDMgmComparisonSource → Prop :=
  CategoryTheory.isoClosure
    (TraceAnalyticMotivicTStructure.coaisleGE cut)

/-- The concrete aisle predicate maps into its iso-closed Mathlib-ready
predicate. -/
theorem TraceAnalyticMotivicTStructure.aisleLE_le_aisleLEIsoClosed
    (cut : ℤ) :
    TraceAnalyticMotivicTStructure.aisleLE cut ≤
      TraceAnalyticMotivicTStructure.aisleLEIsoClosed cut :=
  CategoryTheory.le_isoClosure
    (TraceAnalyticMotivicTStructure.aisleLE cut)

/-- The concrete coaisle predicate maps into its iso-closed Mathlib-ready
predicate. -/
theorem TraceAnalyticMotivicTStructure.coaisleGE_le_coaisleGEIsoClosed
    (cut : ℤ) :
    TraceAnalyticMotivicTStructure.coaisleGE cut ≤
      TraceAnalyticMotivicTStructure.coaisleGEIsoClosed cut :=
  CategoryTheory.le_isoClosure
    (TraceAnalyticMotivicTStructure.coaisleGE cut)

/-- The iso-closed aisle predicate is closed under isomorphism. -/
def TraceAnalyticMotivicTStructure.aisleLEIsoClosed_closedUnderIsomorphisms
    (cut : ℤ) :
    CategoryTheory.ClosedUnderIsomorphisms
      (TraceAnalyticMotivicTStructure.aisleLEIsoClosed cut) :=
  inferInstance

/-- The iso-closed coaisle predicate is closed under isomorphism. -/
def TraceAnalyticMotivicTStructure.coaisleGEIsoClosed_closedUnderIsomorphisms
    (cut : ℤ) :
    CategoryTheory.ClosedUnderIsomorphisms
      (TraceAnalyticMotivicTStructure.coaisleGEIsoClosed cut) :=
  inferInstance

/-- Iso-closed analytic aisle predicates are monotone in the cut. -/
theorem TraceAnalyticMotivicTStructure.aisleLEIsoClosed_monotone :
    Monotone TraceAnalyticMotivicTStructure.aisleLEIsoClosed :=
  fun lower upper cut_le =>
    CategoryTheory.monotone_isoClosure
      (TraceAnalyticMotivicTStructure.aisleLE_mono cut_le)

/-- Iso-closed analytic coaisle predicates are antitone in the cut. -/
theorem TraceAnalyticMotivicTStructure.coaisleGEIsoClosed_antitone :
    Antitone TraceAnalyticMotivicTStructure.coaisleGEIsoClosed :=
  fun lower upper cut_le =>
    CategoryTheory.monotone_isoClosure
      (TraceAnalyticMotivicTStructure.coaisleGE_mono cut_le)

/-- Mathlib `TStructure.LE_zero_le` field for the iso-closed analytic aisle
predicates. -/
theorem TraceAnalyticMotivicTStructure.aisleLEIsoClosed_zero_le :
    TraceAnalyticMotivicTStructure.aisleLEIsoClosed 0 ≤
      TraceAnalyticMotivicTStructure.aisleLEIsoClosed 1 :=
  TraceAnalyticMotivicTStructure.aisleLEIsoClosed_monotone
    (zero_le_one : (0 : ℤ) ≤ 1)

/-- Mathlib `TStructure.GE_one_le` field for the iso-closed analytic coaisle
predicates. -/
theorem TraceAnalyticMotivicTStructure.coaisleGEIsoClosed_one_le :
    TraceAnalyticMotivicTStructure.coaisleGEIsoClosed 1 ≤
      TraceAnalyticMotivicTStructure.coaisleGEIsoClosed 0 :=
  TraceAnalyticMotivicTStructure.coaisleGEIsoClosed_antitone
    (zero_le_one : (0 : ℤ) ≤ 1)

end AnalyticMotives
end LFunctions
end Boundary
