import Mathlib.CategoryTheory.FullSubcategory
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Source.Bounded.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Weights.Source.Bounds.IsoClosure.Owner

/-!
# Stable source objects represented by degreewise iso-closure bounded complexes

This file names the stable comparison-source objects represented by concrete
analytic cochain complexes whose degree objects are bounded up to iso-closure.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

namespace TraceAnalyticDMgmComparisonSource

/-- Stable comparison-source representatives carried by a concrete analytic
cochain complex whose degree objects are bounded up to iso-closure. -/
def degreewiseIsoClosureBoundedStableRepresentative
    (object : TraceAnalyticDMgmComparisonSource) :
    Prop :=
  ∃ (bound : Nat),
    ∃ (complex : TraceAnalyticAdditiveCochainComplex),
      TraceAnalyticMotiveComparison
          .sourceComplexDegreewiseIsoClosureBoundedBy complex bound ∧
        object =
          TraceAnalyticDMgmComparisonSource.objectOf
            (TraceAnalyticAdditiveHomotopyCategory.objectOf complex)

/-- The iso-closed stable comparison-source predicate generated by concrete
degreewise iso-closure bounded analytic cochain complexes. -/
abbrev degreewiseIsoClosureBoundedStableObject :
    TraceAnalyticDMgmComparisonSource → Prop :=
  CategoryTheory.isoClosure
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableRepresentative

/-- A literally bounded stable source representative is represented by a
degreewise iso-closure bounded complex. -/
theorem degreewiseIsoClosureBoundedStableRepresentative_of_sourceStableWeightBoundedObject
    {bound : Nat}
    (complex :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableRepresentative
        (TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject
          complex) :=
  Exists.intro
    bound
    (Exists.intro
      complex.complex
      (And.intro
        (TraceAnalyticMotiveComparison
          .sourceComplexDegreewiseIsoClosureBoundedBy_of_weightBounded
            complex)
        (Eq.trans
          (TraceAnalyticMotiveComparison
            .sourceStableWeightBoundedObject_eq complex)
          (congrArg
            TraceAnalyticDMgmComparisonSource.objectOf
            (TraceAnalyticMotiveComparison
              .sourceWeightBoundedHomotopyObject_eq complex)))))

/-- A literally bounded stable source object belongs to the iso-closure
bounded stable source predicate. -/
theorem degreewiseIsoClosureBoundedStableObject_of_sourceStableWeightBoundedObject
    {bound : Nat}
    (complex :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject
        (TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject
          complex) :=
  CategoryTheory.le_isoClosure
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableRepresentative
    (TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject complex)
    (TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableRepresentative_of_sourceStableWeightBoundedObject
        complex)

/-- The iso-closed bounded stable source predicate is contained in the
degreewise iso-closure bounded stable source predicate. -/
theorem degreewiseIsoClosureBoundedStableObject_of_boundedStableObject
    {object : TraceAnalyticDMgmComparisonSource}
    (membership :
      TraceAnalyticDMgmComparisonSource.boundedStableObject object) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject object :=
  Exists.elim
    membership
    (fun representative representativeData =>
      Exists.elim
        representativeData
        (fun representativeMembership representativeIsoData =>
          Nonempty.elim
            representativeIsoData
            (fun representativeIso =>
              Exists.elim
                representativeMembership
                (fun bound boundData =>
                  Exists.elim
                    boundData
                    (fun complex representative_eq =>
                      let representative_degreewise :
                          TraceAnalyticDMgmComparisonSource
                            .degreewiseIsoClosureBoundedStableObject
                            representative :=
                        Eq.subst
                          (motive := fun candidate =>
                            TraceAnalyticDMgmComparisonSource
                              .degreewiseIsoClosureBoundedStableObject
                              candidate)
                          (Eq.symm representative_eq)
                          (TraceAnalyticDMgmComparisonSource
                            .degreewiseIsoClosureBoundedStableObject_of_sourceStableWeightBoundedObject
                              complex)
                      CategoryTheory.mem_of_iso
                        (P := TraceAnalyticDMgmComparisonSource
                          .degreewiseIsoClosureBoundedStableObject)
                        representativeIso.symm
                        representative_degreewise)))))

end TraceAnalyticDMgmComparisonSource

end AnalyticMotives
end LFunctions
end Boundary
