import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Presheaves.DescentLocalization.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Comparison.DMgmQQ.Correspondences.Owner

/-!
# Descent comparison with `DM_gm(ℚ)_ℚ`

This file owns the comparison between contour descent and algebraic descent.
The intended cover calculus is generated by contour refinements together with
analytified algebraic descent data.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
Comparison between conservative contour descent and target motivic descent.
The analytic side remains generated by contour descent covers on transfer
presheaves.
-/
structure DMgmQQDescentComparison
    {T : DMgmQQTargetInterface}
    (M : DMgmQQMorphismInterface T) where
  analyticPresheaf : DescentLocalAnalyticPresheaf
  CoverIndex : Type
  cover :
    CoverIndex →
      TransferPresheafDescentCover
        analyticPresheaf.presheafWithTransfers
  targetDescentObject : CoverIndex → T.Object

namespace DMgmQQDescentComparison

/-- The analytic descent-local presheaf in a descent comparison. -/
def analytic {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQDescentComparison M) :
    DescentLocalAnalyticPresheaf :=
  D.analyticPresheaf

/-- The target object assigned to a descent-cover index. -/
def targetAt {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQDescentComparison M)
    (i : D.CoverIndex) : T.Object :=
  D.targetDescentObject i

/-- The contour descent cover selected by an index in a descent comparison. -/
def coverAt {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQDescentComparison M)
    (i : D.CoverIndex) :
    TransferPresheafDescentCover D.analyticPresheaf.presheafWithTransfers :=
  D.cover i

/-- The presheaf with transfers underlying the analytic descent comparison. -/
def presheafWithTransfers {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQDescentComparison M) :
    AnalyticPresheafWithTransfers :=
  D.analyticPresheaf.presheafWithTransfers

/-- The descent-locality data used in the analytic descent comparison. -/
def descentLocality {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQDescentComparison M) :
    ContourDescentLocalObject D.analyticPresheaf.presheafWithTransfers :=
  D.analyticPresheaf.descentLocality

end DMgmQQDescentComparison

/--
Descent comparison attached to a bulk-generated analytic presheaf
construction.  This records that the analytic descent object used by the
comparison is the descent-local presheaf generated from the bulk contour
correspondence calculus.
-/
structure DMgmQQBulkGeneratedDescentComparison
    {T : DMgmQQTargetInterface}
    (M : DMgmQQMorphismInterface T) where
  bulkConstruction : BulkAnalyticMotiveConstruction
  descentComparison : DMgmQQDescentComparison M
  analyticPresheaf_eq :
    descentComparison.analyticPresheaf =
      bulkConstruction.presheaves.descent.forget

namespace DMgmQQBulkGeneratedDescentComparison

/-- The bulk construction generating the analytic descent comparison. -/
def bulk {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQBulkGeneratedDescentComparison M) :
    BulkAnalyticMotiveConstruction :=
  D.bulkConstruction

/-- The downstream descent comparison. -/
def comparison {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQBulkGeneratedDescentComparison M) :
    DMgmQQDescentComparison M :=
  D.descentComparison

/-- The analytic descent comparison is generated from the bulk construction. -/
theorem analyticPresheaf_compatibility
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQBulkGeneratedDescentComparison M) :
    D.descentComparison.analyticPresheaf =
      D.bulkConstruction.presheaves.descent.forget :=
  D.analyticPresheaf_eq

/-- The analytic presheaf with transfers generated by the bulk construction. -/
def bulkPresheafWithTransfers
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQBulkGeneratedDescentComparison M) :
    AnalyticPresheafWithTransfers :=
  D.bulkConstruction.presheaves.transfers.forget

/-- The rational category used by the bulk-generated descent comparison. -/
def rationalCategory
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQBulkGeneratedDescentComparison M) :
    RationalContourCategoryData :=
  D.bulkConstruction.rationalCategory

/--
The rational transfers used by the descent comparison are linearized from the
bulk contour-correspondence calculus.
-/
theorem rational_correspondenceLaws_compatibility
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (D : DMgmQQBulkGeneratedDescentComparison M) :
    D.rationalCategory.correspondenceLaws =
      D.bulkConstruction.correspondenceCalculus.laws :=
  BulkAnalyticMotiveConstruction.rational_correspondenceLaws_compatibility
    D.bulkConstruction

end DMgmQQBulkGeneratedDescentComparison

end AnalyticMotives
end LFunctions
end Boundary
