import Mathlib.CategoryTheory.Triangulated.Subcategory
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homotopy.LocalizationInput.AcyclicGenerators.Owner

/-!
# The stable null subcategory generated by analytic localization cones

This file defines the Verdier-null class generated by the concrete stable
acyclic generators.  The closure operations are zero, integer shifts, and
distinguished extensions in the additive analytic homotopy category.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- Objects in the stable null class generated by analytic localization cones. -/
inductive TraceAnalyticStableNullObject :
    TraceAnalyticAdditiveHomotopyCategory → Prop
  | zero :
      TraceAnalyticStableNullObject 0
  | generator (generator : TraceAnalyticStableAcyclicGenerator) :
      TraceAnalyticStableNullObject generator.object
  | shift
      (object : TraceAnalyticAdditiveHomotopyCategory)
      (degree : ℤ)
      (_ : TraceAnalyticStableNullObject object) :
      TraceAnalyticStableNullObject (object⟦degree⟧)
  | extension
      (triangle : Triangle TraceAnalyticAdditiveHomotopyCategory)
      (_ : triangle ∈
        TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles)
      (_ : TraceAnalyticStableNullObject triangle.obj₁)
      (_ : TraceAnalyticStableNullObject triangle.obj₃) :
      TraceAnalyticStableNullObject triangle.obj₂

/-- The zero object belongs to the stable null class. -/
theorem TraceAnalyticStableNullObject.zero_mem :
    TraceAnalyticStableNullObject 0 :=
  TraceAnalyticStableNullObject.zero

/-- Every concrete stable acyclic generator belongs to the stable null class. -/
theorem TraceAnalyticStableNullObject.generator_mem
    (generator : TraceAnalyticStableAcyclicGenerator) :
    TraceAnalyticStableNullObject generator.object :=
  TraceAnalyticStableNullObject.generator generator

/-- The stable null class is closed under integer shifts. -/
theorem TraceAnalyticStableNullObject.shift_mem
    (object : TraceAnalyticAdditiveHomotopyCategory)
    (degree : ℤ)
    (mem : TraceAnalyticStableNullObject object) :
    TraceAnalyticStableNullObject (object⟦degree⟧) :=
  TraceAnalyticStableNullObject.shift object degree mem

/-- The stable null class is closed under distinguished extensions. -/
theorem TraceAnalyticStableNullObject.extension_mem
    (triangle : Triangle TraceAnalyticAdditiveHomotopyCategory)
    (distinguished : triangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles)
    (left : TraceAnalyticStableNullObject triangle.obj₁)
    (right : TraceAnalyticStableNullObject triangle.obj₃) :
    TraceAnalyticStableNullObject triangle.obj₂ :=
  TraceAnalyticStableNullObject.extension triangle distinguished left right

/-- The stable null class as a triangulated subcategory. -/
def TraceAnalyticStableNullSubcategory :
    CategoryTheory.Triangulated.Subcategory
      TraceAnalyticAdditiveHomotopyCategory :=
  CategoryTheory.Triangulated.Subcategory.mk'
    TraceAnalyticStableNullObject
    TraceAnalyticStableNullObject.zero_mem
    TraceAnalyticStableNullObject.shift_mem
    TraceAnalyticStableNullObject.extension_mem

/-- The null subcategory predicate is the stable null object predicate. -/
theorem TraceAnalyticStableNullSubcategory_P
    (object : TraceAnalyticAdditiveHomotopyCategory) :
    TraceAnalyticStableNullSubcategory.P object =
      TraceAnalyticStableNullObject object :=
  rfl

/-- Stable acyclic generator objects belong to the null subcategory. -/
theorem TraceAnalyticStableNullSubcategory.generator_mem
    (generator : TraceAnalyticStableAcyclicGenerator) :
    TraceAnalyticStableNullSubcategory.P generator.object :=
  TraceAnalyticStableNullObject.generator_mem generator

/-- The morphisms inverted by the analytic Verdier localization. -/
def TraceAnalyticStableNullSubcategory.invertedMorphisms :
    CategoryTheory.MorphismProperty
      TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticStableNullSubcategory.W

/-- A distinguished triangle whose third vertex is null gives an inverted first map. -/
theorem TraceAnalyticStableNullSubcategory.inverted_firstMap_of_triangle
    {triangle : Triangle TraceAnalyticAdditiveHomotopyCategory}
    (distinguished : triangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles)
    (null : TraceAnalyticStableNullSubcategory.P triangle.obj₃) :
    TraceAnalyticStableNullSubcategory.invertedMorphisms triangle.mor₁ :=
  CategoryTheory.Triangulated.Subcategory.W.mk
    TraceAnalyticStableNullSubcategory
    distinguished
    null

/-- The first map of every stable acyclic generator triangle is inverted. -/
theorem TraceAnalyticStableNullSubcategory.generator_firstMap_inverted
    (generator : TraceAnalyticStableAcyclicGenerator) :
    TraceAnalyticStableNullSubcategory.invertedMorphisms generator.firstMap :=
  TraceAnalyticStableNullSubcategory.inverted_firstMap_of_triangle
    generator.triangle_distinguished
    (TraceAnalyticStableNullSubcategory.generator_mem generator)

end AnalyticMotives
end LFunctions
end Boundary
