import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Source.Bounded.IsoClosure.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Weights.Source.Bounds.IsoClosure.Shift.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homotopy.Shift.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homotopy.VerdierQuotient.Shift.Owner

/-!
# Shifts of degreewise iso-closure bounded stable source objects

This file proves that the stable comparison-source predicate generated by
degreewise iso-closure bounded cochain complexes is closed under the ambient
stable shift.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

namespace TraceAnalyticDMgmComparisonSource

/-- A degreewise iso-closure bounded stable representative remains in the
iso-closed degreewise predicate after ambient stable shift. -/
theorem degreewiseIsoClosureBoundedStableObject_shift_of_representative
    {object : TraceAnalyticDMgmComparisonSource}
    (membership :
      TraceAnalyticDMgmComparisonSource
        .degreewiseIsoClosureBoundedStableRepresentative object)
    (shift : ℤ) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject
        (object⟦shift⟧) :=
  Exists.elim
    membership
    (fun bound boundData =>
      Exists.elim
        boundData
        (fun complex complexData =>
          And.elim
            complexData
            (fun complexMembership object_eq =>
              let shiftedComplex :
                  TraceAnalyticAdditiveCochainComplex :=
                (CochainComplex.shiftFunctor
                  TraceAnalyticAdditiveCategoryObject
                  shift).obj complex
              let shiftedRepresentative :
                  TraceAnalyticDMgmComparisonSource :=
                TraceAnalyticDMgmComparisonSource.objectOf
                  (TraceAnalyticAdditiveHomotopyCategory.objectOf
                    shiftedComplex)
              let shiftedRepresentative_mem :
                  TraceAnalyticDMgmComparisonSource
                    .degreewiseIsoClosureBoundedStableRepresentative
                    shiftedRepresentative :=
                Exists.intro
                  bound
                  (Exists.intro
                    shiftedComplex
                    (And.intro
                      (TraceAnalyticMotiveComparison
                        .sourceComplexDegreewiseIsoClosureBoundedBy_shift
                          complexMembership
                          shift)
                      rfl))
              let homotopyShiftIso :
                  TraceAnalyticAdditiveHomotopyCategory.objectOf
                      shiftedComplex ≅
                    (TraceAnalyticAdditiveHomotopyCategory.objectOf
                      complex)⟦shift⟧ :=
                (TraceAnalyticAdditiveHomotopyCategory
                  .quotientFunctor.commShiftIso shift).app complex
              let stableShiftIso :
                  shiftedRepresentative ≅
                    (TraceAnalyticDMgmComparisonSource.objectOf
                      (TraceAnalyticAdditiveHomotopyCategory.objectOf
                        complex))⟦shift⟧ :=
                TraceAnalyticStableMotiveCategory.quotientFunctor.mapIso
                    homotopyShiftIso ≪≫
                  TraceAnalyticStableMotiveCategory.objectOfShiftIso
                    (TraceAnalyticAdditiveHomotopyCategory.objectOf
                      complex)
                    shift
              let objectShiftIso :
                  (TraceAnalyticDMgmComparisonSource.objectOf
                    (TraceAnalyticAdditiveHomotopyCategory.objectOf
                      complex))⟦shift⟧ ≅
                    object⟦shift⟧ :=
                (shiftFunctor TraceAnalyticDMgmComparisonSource shift).mapIso
                  (eqToIso (Eq.symm object_eq))
              CategoryTheory.mem_of_iso
                (P := TraceAnalyticDMgmComparisonSource
                  .degreewiseIsoClosureBoundedStableObject)
                (stableShiftIso ≪≫ objectShiftIso)
                (CategoryTheory.le_isoClosure
                  TraceAnalyticDMgmComparisonSource
                    .degreewiseIsoClosureBoundedStableRepresentative
                  shiftedRepresentative
                  shiftedRepresentative_mem))))

/-- The degreewise iso-closure bounded stable source predicate is closed under
ambient stable shifts. -/
theorem degreewiseIsoClosureBoundedStableObject_shift
    {object : TraceAnalyticDMgmComparisonSource}
    (membership :
      TraceAnalyticDMgmComparisonSource
        .degreewiseIsoClosureBoundedStableObject object)
    (shift : ℤ) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject
        (object⟦shift⟧) :=
  Exists.elim
    membership
    (fun representative representativeData =>
      Exists.elim
        representativeData
        (fun representativeMembership representativeIsoData =>
          Nonempty.elim
            representativeIsoData
            (fun representativeIso =>
              let shiftedRepresentative_mem :
                  TraceAnalyticDMgmComparisonSource
                    .degreewiseIsoClosureBoundedStableObject
                    (representative⟦shift⟧) :=
                TraceAnalyticDMgmComparisonSource
                  .degreewiseIsoClosureBoundedStableObject_shift_of_representative
                    representativeMembership
                    shift
              CategoryTheory.mem_of_iso
                (P := TraceAnalyticDMgmComparisonSource
                  .degreewiseIsoClosureBoundedStableObject)
                ((shiftFunctor
                  TraceAnalyticDMgmComparisonSource
                  shift).mapIso representativeIso).symm
                shiftedRepresentative_mem)))

end TraceAnalyticDMgmComparisonSource

end AnalyticMotives
end LFunctions
end Boundary
