import Mathlib.Data.List.Perm.Basic
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.FormalSums.Core.Terms.Owner

/-!
# Basic finite formal sums of trace correspondences

This file owns finite formal sums of weighted trace-correspondence generators,
their basic constructors, and their primitive certificate-payload accounting.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A finite Q-linear formal sum of trace-correspondence generators. -/
abbrev TraceCorQFormalSum :=
  List TraceCorQTerm

/-- The analytic certificate ledger generated by a formal trace-correspondence sum. -/
def TraceCorQFormalSum.certificateLedger :
    TraceCorQFormalSum → ResidueChannelCertificateLedger
  | [] => ResidueChannelCertificateLedger.empty
  | term :: tail =>
      ResidueChannelCertificateLedger.append
        term.certificateLedger
        (TraceCorQFormalSum.certificateLedger tail)

/-- The imported finite explicit-formula rectangles carried by a formal trace-correspondence sum. -/
def TraceCorQFormalSum.importedRectangles
    (formalSum : TraceCorQFormalSum) :
    List ZetaAdmissibleFunction.ExplicitFormulaRectangle :=
  formalSum.certificateLedger.importedRectangles

/-- The imported finite-rectangle analytic payload carried by a formal sum. -/
def TraceCorQFormalSum.importedRectangleCount
    (formalSum : TraceCorQFormalSum) :
    Nat :=
  formalSum.certificateLedger.importedRectangleCount

/-- The internal trace-bookkeeping payload carried by a formal sum. -/
def TraceCorQFormalSum.traceBookkeepingCount
    (formalSum : TraceCorQFormalSum) :
    Nat :=
  formalSum.certificateLedger.traceBookkeepingCount

/-- The explicit rewrite-step payload carried by a formal sum. -/
def TraceCorQFormalSum.rewriteStepCount
    (formalSum : TraceCorQFormalSum) :
    Nat :=
  formalSum.certificateLedger.rewriteStepCount

/-- The zero formal trace-correspondence sum. -/
def TraceCorQFormalSum.zero : TraceCorQFormalSum :=
  []

/-- The singleton formal trace-correspondence sum. -/
def TraceCorQFormalSum.singleton
    (coefficient : Rat) (generator : TraceCorQGenerator) :
    TraceCorQFormalSum :=
  [(coefficient, generator)]

/-- Addition of formal trace-correspondence sums is list concatenation. -/
def TraceCorQFormalSum.add
    (left right : TraceCorQFormalSum) : TraceCorQFormalSum :=
  left ++ right

/-- Scalar multiplication of formal sums scales every rational coefficient. -/
def TraceCorQFormalSum.smul
    (coefficient : Rat)
    (formalSum : TraceCorQFormalSum) :
    TraceCorQFormalSum :=
  formalSum.map
    (fun term => (coefficient * term.1, term.2))

/-- The zero formal sum carries the empty analytic certificate ledger. -/
theorem TraceCorQFormalSum.zero_certificateLedger :
    TraceCorQFormalSum.zero.certificateLedger =
      ResidueChannelCertificateLedger.empty :=
  rfl

/-- The zero formal sum carries no imported finite-rectangle payload. -/
theorem TraceCorQFormalSum.zero_importedRectangleCount :
    TraceCorQFormalSum.zero.importedRectangleCount =
      0 :=
  rfl

/-- The zero formal sum exposes no imported finite explicit-formula rectangles. -/
theorem TraceCorQFormalSum.zero_importedRectangles :
    TraceCorQFormalSum.zero.importedRectangles =
      [] :=
  rfl

/-- The zero formal sum carries no internal trace-bookkeeping payload. -/
theorem TraceCorQFormalSum.zero_traceBookkeepingCount :
    TraceCorQFormalSum.zero.traceBookkeepingCount =
      0 :=
  rfl

/-- The zero formal sum carries no explicit rewrite-step payload. -/
theorem TraceCorQFormalSum.zero_rewriteStepCount :
    TraceCorQFormalSum.zero.rewriteStepCount =
      0 :=
  rfl

/-- A singleton formal sum carries the certificate ledger of its generator. -/
theorem TraceCorQFormalSum.singleton_certificateLedger
    (coefficient : Rat) (generator : TraceCorQGenerator) :
    (TraceCorQFormalSum.singleton coefficient generator).certificateLedger =
      ResidueChannelCertificateLedger.append
        generator.certificateLedger
        ResidueChannelCertificateLedger.empty :=
  rfl

/-- A singleton formal sum imports the generator payload plus the empty-tail payload. -/
theorem TraceCorQFormalSum.singleton_importedRectangleCount
    (coefficient : Rat) (generator : TraceCorQGenerator) :
    (TraceCorQFormalSum.singleton coefficient generator).importedRectangleCount =
      generator.importedRectangleCount +
        ResidueChannelCertificateLedger.empty.importedRectangleCount :=
  ResidueChannelCertificateLedger.append_importedRectangleCount
    generator.certificateLedger
    ResidueChannelCertificateLedger.empty

/-- A singleton formal sum exposes the imported rectangles of its generator. -/
theorem TraceCorQFormalSum.singleton_importedRectangles
    (coefficient : Rat) (generator : TraceCorQGenerator) :
    (TraceCorQFormalSum.singleton coefficient generator).importedRectangles =
      generator.importedRectangles ++
        ResidueChannelCertificateLedger.empty.importedRectangles :=
  ResidueChannelCertificateLedger.append_importedRectangles
    generator.certificateLedger
    ResidueChannelCertificateLedger.empty

/-- A singleton formal sum keeps the generator bookkeeping plus the empty-tail payload. -/
theorem TraceCorQFormalSum.singleton_traceBookkeepingCount
    (coefficient : Rat) (generator : TraceCorQGenerator) :
    (TraceCorQFormalSum.singleton coefficient generator).traceBookkeepingCount =
      generator.traceBookkeepingCount +
        ResidueChannelCertificateLedger.empty.traceBookkeepingCount :=
  ResidueChannelCertificateLedger.append_traceBookkeepingCount
    generator.certificateLedger
    ResidueChannelCertificateLedger.empty

/-- A singleton formal sum keeps the generator rewrite-step payload plus the empty-tail payload. -/
theorem TraceCorQFormalSum.singleton_rewriteStepCount
    (coefficient : Rat) (generator : TraceCorQGenerator) :
    (TraceCorQFormalSum.singleton coefficient generator).rewriteStepCount =
      generator.rewriteStepCount +
        ResidueChannelCertificateLedger.empty.rewriteStepCount :=
  ResidueChannelCertificateLedger.append_rewriteStepCount
    generator.certificateLedger
    ResidueChannelCertificateLedger.empty

/-- The certificate ledger of a formal-sum cons is head certificates followed by tail certificates. -/
theorem TraceCorQFormalSum.cons_certificateLedger
    (term : TraceCorQTerm) (tail : TraceCorQFormalSum) :
    TraceCorQFormalSum.certificateLedger (term :: tail) =
      ResidueChannelCertificateLedger.append
        term.certificateLedger
        tail.certificateLedger :=
  rfl

/-- The imported payload of a cons formal sum is head payload plus tail payload. -/
theorem TraceCorQFormalSum.cons_importedRectangleCount
    (term : TraceCorQTerm) (tail : TraceCorQFormalSum) :
    TraceCorQFormalSum.importedRectangleCount (term :: tail) =
      term.importedRectangleCount +
        tail.importedRectangleCount :=
  ResidueChannelCertificateLedger.append_importedRectangleCount
    term.certificateLedger
    tail.certificateLedger

/-- The imported rectangles of a cons formal sum are head rectangles followed by tail rectangles. -/
theorem TraceCorQFormalSum.cons_importedRectangles
    (term : TraceCorQTerm) (tail : TraceCorQFormalSum) :
    TraceCorQFormalSum.importedRectangles (term :: tail) =
      term.importedRectangles ++
        tail.importedRectangles :=
  ResidueChannelCertificateLedger.append_importedRectangles
    term.certificateLedger
    tail.certificateLedger

/-- A formal sum's imported-rectangle count is the length of its extracted rectangle list. -/
theorem TraceCorQFormalSum.importedRectangleCount_eq_length_importedRectangles
    (formalSum : TraceCorQFormalSum) :
    formalSum.importedRectangleCount =
      formalSum.importedRectangles.length :=
  ResidueChannelCertificateLedger.importedRectangleCount_eq_length_importedRectangles
    formalSum.certificateLedger

/-- The bookkeeping payload of a cons formal sum is head payload plus tail payload. -/
theorem TraceCorQFormalSum.cons_traceBookkeepingCount
    (term : TraceCorQTerm) (tail : TraceCorQFormalSum) :
    TraceCorQFormalSum.traceBookkeepingCount (term :: tail) =
      term.traceBookkeepingCount +
        tail.traceBookkeepingCount :=
  ResidueChannelCertificateLedger.append_traceBookkeepingCount
    term.certificateLedger
    tail.certificateLedger

/-- The rewrite-step payload of a cons formal sum is head payload plus tail payload. -/
theorem TraceCorQFormalSum.cons_rewriteStepCount
    (term : TraceCorQTerm) (tail : TraceCorQFormalSum) :
    TraceCorQFormalSum.rewriteStepCount (term :: tail) =
      term.rewriteStepCount +
        tail.rewriteStepCount :=
  ResidueChannelCertificateLedger.append_rewriteStepCount
    term.certificateLedger
    tail.certificateLedger

end AnalyticMotives
end LFunctions
end Boundary
