import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.Core.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Owner

/-!
# Bounded-triangle package generated by a bounded analytic map

The mapping-cone construction turns a bounded chain map into a distinguished
triangle in the analytic homotopy category.  This file records that triangle as
a bounded distinguished triangle.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The bounded distinguished triangle generated by a bounded chain map. -/
def TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedTriangle bound where
  first := source
  second := target
  triangle :=
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle hom
  distinguished :=
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle_distinguished
      hom

/-- The first bounded representative of the packaged mapping-cone triangle. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_first
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
      hom).first = source :=
  rfl

/-- The second bounded representative of the packaged mapping-cone triangle. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_second
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
      hom).second = target :=
  rfl

/-- The packaged bounded triangle has the usual mapping-cone triangle underneath. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_triangle
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
      hom).triangle =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle hom :=
  rfl

/-- The packaged bounded triangle is distinguished. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_distinguished
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
      hom).triangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedTriangle.triangle_distinguished
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
      hom)

end AnalyticMotives
end LFunctions
end Boundary
