import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Presheaves.TateStabilization.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Comparison.DMgmQQ.Descent.Owner

/-!
# Tate comparison with `DM_gm(ℚ)_ℚ`

This file owns compatibility of analytic Tate stabilization with the Tate
object on the algebraic motivic side.  It is downstream from descent and
correspondence comparison.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
Compatibility of analytic Tate stabilization with a target Tate object in the
abstract `DM_gm(ℚ)_ℚ` comparison interface.
-/
structure DMgmQQTateComparison
    {T : DMgmQQTargetInterface}
    (M : DMgmQQMorphismInterface T) where
  analyticTate : AnalyticTateObject
  analyticStabilization : TateStabilizedAnalyticPresheaf
  targetTateObject : T.Object
  descentComparison : DMgmQQDescentComparison M

namespace DMgmQQTateComparison

/-- The analytic Tate object in Tate comparison data. -/
def analytic {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQTateComparison M) : AnalyticTateObject :=
  C.analyticTate

/-- The target Tate object in Tate comparison data. -/
def target {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQTateComparison M) : T.Object :=
  C.targetTateObject

/-- The analytic Tate-stabilized presheaf in Tate comparison data. -/
def stabilization {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQTateComparison M) :
    TateStabilizedAnalyticPresheaf :=
  C.analyticStabilization

/-- The descent comparison used by Tate comparison data. -/
def descent {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQTateComparison M) :
    DMgmQQDescentComparison M :=
  C.descentComparison

/-- The descent-local presheaf underlying the Tate comparison. -/
def descentLocalPresheaf {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQTateComparison M) :
    DescentLocalAnalyticPresheaf :=
  C.descentComparison.analyticPresheaf

/-- The analytic Tate object carried by the stabilized presheaf. -/
def stabilizationTateObject {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQTateComparison M) :
    AnalyticTateObject :=
  C.analyticStabilization.tateObject

end DMgmQQTateComparison

/--
Tate comparison attached to a bulk-generated analytic presheaf construction.
This records that the comparison's analytic Tate object and stabilized
presheaf are the Tate object and stabilization produced by the bulk lane.
-/
structure DMgmQQBulkGeneratedTateComparison
    {T : DMgmQQTargetInterface}
    (M : DMgmQQMorphismInterface T) where
  bulkDescent : DMgmQQBulkGeneratedDescentComparison M
  tateComparison : DMgmQQTateComparison M
  descentComparison_eq :
    tateComparison.descentComparison =
      bulkDescent.descentComparison
  analyticTate_eq :
    tateComparison.analyticTate =
      bulkDescent.bulkConstruction.presheaves.tate.tateObject
  analyticStabilization_eq :
    tateComparison.analyticStabilization =
      bulkDescent.bulkConstruction.presheaves.tate.forget

namespace DMgmQQBulkGeneratedTateComparison

/-- The bulk-generated descent comparison underlying the Tate comparison. -/
def descent {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    DMgmQQBulkGeneratedDescentComparison M :=
  C.bulkDescent

/-- The downstream Tate comparison. -/
def comparison {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    DMgmQQTateComparison M :=
  C.tateComparison

/-- The bulk construction generating the analytic Tate comparison. -/
def bulk {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    BulkAnalyticMotiveConstruction :=
  C.bulkDescent.bulkConstruction

/-- The Tate comparison uses the bulk-generated descent comparison. -/
theorem descentComparison_compatibility
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    C.tateComparison.descentComparison =
      C.bulkDescent.descentComparison :=
  C.descentComparison_eq

/-- The analytic Tate object is generated by the bulk construction. -/
theorem analyticTate_compatibility
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    C.tateComparison.analyticTate =
      C.bulk.presheaves.tate.tateObject :=
  C.analyticTate_eq

/-- The analytic Tate stabilization is generated by the bulk construction. -/
theorem analyticStabilization_compatibility
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    C.tateComparison.analyticStabilization =
      C.bulk.presheaves.tate.forget :=
  C.analyticStabilization_eq

/-- The rational category used by the bulk-generated Tate comparison. -/
def rationalCategory {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    RationalContourCategoryData :=
  C.bulk.rationalCategory

/--
The rational transfers used by the Tate comparison are linearized from the
bulk contour-correspondence calculus.
-/
theorem rational_correspondenceLaws_compatibility
    {T : DMgmQQTargetInterface}
    {M : DMgmQQMorphismInterface T}
    (C : DMgmQQBulkGeneratedTateComparison M) :
    C.rationalCategory.correspondenceLaws =
      C.bulk.correspondenceCalculus.laws :=
  BulkAnalyticMotiveConstruction.rational_correspondenceLaws_compatibility
    C.bulk

end DMgmQQBulkGeneratedTateComparison

end AnalyticMotives
end LFunctions
end Boundary
