import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleTransports.Owner

/-!
# Zero-pole rectangle certificates

This file attaches the concrete finite-square rectangle parameter used by the
zero-pole residue theorem to the certified trace-presentation layer.

The parameter is explicit: the finite-square theorem uses a positive real
height `R`, and the imported rectangle API records the corresponding rectangle
as center coordinate `0` and height `R`.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The finite-square rectangle used by the zero-pole residue theorem at height `R`. -/
def completedZetaZeroPoleFiniteSquareRectangle
    (R : ℝ) :
    ZetaAdmissibleFunction.ExplicitFormulaRectangle where
  c := 0
  T := R

/-- The zero-pole finite-square rectangle has center coordinate zero. -/
theorem completedZetaZeroPoleFiniteSquareRectangle_c
    (R : ℝ) :
    (completedZetaZeroPoleFiniteSquareRectangle R).c =
      0 :=
  rfl

/-- The zero-pole finite-square rectangle has height coordinate `R`. -/
theorem completedZetaZeroPoleFiniteSquareRectangle_T
    (R : ℝ) :
    (completedZetaZeroPoleFiniteSquareRectangle R).T =
      R :=
  rfl

/-- Positivity of `R` is positivity of the recorded rectangle height. -/
theorem completedZetaZeroPoleFiniteSquareRectangle_positiveHeight
    {R : ℝ} (hR : 0 < R) :
    0 < (completedZetaZeroPoleFiniteSquareRectangle R).T :=
  hR

/-- The certificate ledger generated by the zero-pole finite-square rectangle. -/
def completedZetaZeroPoleFiniteSquareRectangleCertificateLedger
    (R : ℝ) :
    ResidueChannelCertificateLedger :=
  ResidueChannelCertificateLedger.ofExplicitFormulaRectangle
    (completedZetaZeroPoleFiniteSquareRectangle R)

/-- The rectangle certificate ledger carries one imported rectangle. -/
theorem completedZetaZeroPoleFiniteSquareRectangleCertificateLedger_importedRectangleCount
    (R : ℝ) :
    (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R).importedRectangleCount =
      1 + 0 :=
  rfl

/-- The rectangle certificate ledger exposes exactly the finite-square rectangle. -/
theorem completedZetaZeroPoleFiniteSquareRectangleCertificateLedger_importedRectangles
    (R : ℝ) :
    (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R).importedRectangles =
      [completedZetaZeroPoleFiniteSquareRectangle R] ++ [] :=
  rfl

/-- The rectangle certificate ledger carries no trace-bookkeeping atom. -/
theorem completedZetaZeroPoleFiniteSquareRectangleCertificateLedger_traceBookkeepingCount
    (R : ℝ) :
    (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R).traceBookkeepingCount =
      0 + 0 :=
  rfl

/-- The residue presentation with the actual finite-square rectangle certificate attached. -/
def completedZetaZeroPoleResiduePresentationWithRectangle
    (R : ℝ) :
    CertifiedResidueChannelPresentation :=
  completedZetaZeroPoleResiduePresentation.withAdditionalCertificates
    (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R)

/-- Adding the rectangle certificate does not change the residue presentation spine. -/
theorem completedZetaZeroPoleResiduePresentationWithRectangle_spine
    (R : ℝ) :
    (completedZetaZeroPoleResiduePresentationWithRectangle R).spine =
      completedZetaZeroPoleResiduePresentationSpine :=
  rfl

/-- Adding the rectangle certificate does not change the residue presentation source. -/
theorem completedZetaZeroPoleResiduePresentationWithRectangle_source
    (R : ℝ) :
    (completedZetaZeroPoleResiduePresentationWithRectangle R).source =
      completedZetaZeroPoleFiniteSquareBoundaryExpression :=
  rfl

/--
The rectangle-certified residue presentation is sound at the same height as
the rectangle certificate attached to it.
-/
theorem completedZetaZeroPoleResiduePresentationWithRectangle_sound
    (f : ZetaAdmissibleFunction) (hPhi : ZetaPhiAnalyticControl f)
    {R : ℝ} (hR : 0 < R) :
    completedZetaZeroPoleFiniteSquareBoundaryTrace f R =
      completedZetaZeroPoleFiniteSquareResidueTrace f :=
  completedZetaZeroPoleFiniteSquareResidueGenerator_sound
    f hPhi hR

/--
The rectangle-certified residue presentation is sound when the recorded
rectangle height is positive.
-/
theorem completedZetaZeroPoleResiduePresentationWithRectangle_sound_of_rectangleHeight
    (f : ZetaAdmissibleFunction) (hPhi : ZetaPhiAnalyticControl f)
    {R : ℝ}
    (hT : 0 < (completedZetaZeroPoleFiniteSquareRectangle R).T) :
    completedZetaZeroPoleFiniteSquareBoundaryTrace f R =
      completedZetaZeroPoleFiniteSquareResidueTrace f :=
  completedZetaZeroPoleResiduePresentationWithRectangle_sound
    f hPhi hT

/-- The rectangle-certified residue presentation imports exactly the rectangle certificate. -/
theorem completedZetaZeroPoleResiduePresentationWithRectangle_importedRectangleCount
    (R : ℝ) :
    (completedZetaZeroPoleResiduePresentationWithRectangle R).importedRectangleCount =
      completedZetaZeroPoleResiduePresentation.importedRectangleCount +
        (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R).importedRectangleCount :=
  CertifiedResidueChannelPresentation.withAdditionalCertificates_importedRectangleCount
    completedZetaZeroPoleResiduePresentation
    (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R)

/-- The rectangle-certified residue presentation exposes original rectangles then the new rectangle. -/
theorem completedZetaZeroPoleResiduePresentationWithRectangle_importedRectangles
    (R : ℝ) :
    (completedZetaZeroPoleResiduePresentationWithRectangle R).importedRectangles =
      completedZetaZeroPoleResiduePresentation.importedRectangles ++
        (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R).importedRectangles :=
  CertifiedResidueChannelPresentation.withAdditionalCertificates_importedRectangles
    completedZetaZeroPoleResiduePresentation
    (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R)

/-- The rectangle-certified residue presentation preserves the original bookkeeping count. -/
theorem completedZetaZeroPoleResiduePresentationWithRectangle_traceBookkeepingCount
    (R : ℝ) :
    (completedZetaZeroPoleResiduePresentationWithRectangle R).traceBookkeepingCount =
      completedZetaZeroPoleResiduePresentation.traceBookkeepingCount +
        (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R).traceBookkeepingCount :=
  CertifiedResidueChannelPresentation.withAdditionalCertificates_traceBookkeepingCount
    completedZetaZeroPoleResiduePresentation
    (completedZetaZeroPoleFiniteSquareRectangleCertificateLedger R)

/-- The residue transport whose source presentation carries the actual rectangle certificate. -/
def completedZetaZeroPoleResidueTransportWithRectangle
    (R : ℝ) :
    TraceTransport :=
  {
    source := completedZetaZeroPoleResiduePresentationWithRectangle R
    target := completedZetaZeroPoleResidueOutput
    path := completedZetaZeroPoleResiduePath
    path_source := completedZetaZeroPoleResiduePath_source
    path_target := completedZetaZeroPoleResiduePath_target
  }

/-- The rectangle-certified residue transport starts at the rectangle-certified presentation. -/
theorem completedZetaZeroPoleResidueTransportWithRectangle_source
    (R : ℝ) :
    (completedZetaZeroPoleResidueTransportWithRectangle R).source =
      completedZetaZeroPoleResiduePresentationWithRectangle R :=
  rfl

/-- The rectangle-certified residue transport targets the certified residue output. -/
theorem completedZetaZeroPoleResidueTransportWithRectangle_target
    (R : ℝ) :
    (completedZetaZeroPoleResidueTransportWithRectangle R).target =
      completedZetaZeroPoleResidueOutput :=
  rfl

/-- The rectangle-certified residue transport carries the residue path. -/
theorem completedZetaZeroPoleResidueTransportWithRectangle_path
    (R : ℝ) :
    (completedZetaZeroPoleResidueTransportWithRectangle R).path =
      completedZetaZeroPoleResiduePath :=
  rfl

/--
The rectangle-certified transport is analytically sound at the height recorded
by its source rectangle certificate.
-/
theorem completedZetaZeroPoleResidueTransportWithRectangle_sound
    (f : ZetaAdmissibleFunction) (hPhi : ZetaPhiAnalyticControl f)
    {R : ℝ} (hR : 0 < R) :
    completedZetaZeroPoleFiniteSquareBoundaryTrace f R =
      completedZetaZeroPoleFiniteSquareResidueTrace f :=
  completedZetaZeroPoleResiduePresentationWithRectangle_sound
    f hPhi hR

/--
The rectangle-certified transport is sound when the recorded rectangle height
is positive.
-/
theorem completedZetaZeroPoleResidueTransportWithRectangle_sound_of_rectangleHeight
    (f : ZetaAdmissibleFunction) (hPhi : ZetaPhiAnalyticControl f)
    {R : ℝ}
    (hT : 0 < (completedZetaZeroPoleFiniteSquareRectangle R).T) :
    completedZetaZeroPoleFiniteSquareBoundaryTrace f R =
      completedZetaZeroPoleFiniteSquareResidueTrace f :=
  completedZetaZeroPoleResidueTransportWithRectangle_sound
    f hPhi hT

/-- The rectangle-certified transport ledger records source, target, and path certificates. -/
theorem completedZetaZeroPoleResidueTransportWithRectangle_certificateLedger
    (R : ℝ) :
    (completedZetaZeroPoleResidueTransportWithRectangle R).certificateLedger =
      ResidueChannelCertificateLedger.append
        (completedZetaZeroPoleResiduePresentationWithRectangle R).certificateLedger
        (ResidueChannelCertificateLedger.append
          completedZetaZeroPoleResidueOutput.certificateLedger
          (ResidueChannelCertificateLedger.ofRewritePath
            completedZetaZeroPoleResiduePath)) :=
  rfl

/-- The rectangle-certified transport exposes the imported rectangle through its ledger. -/
theorem completedZetaZeroPoleResidueTransportWithRectangle_importedRectangleCount_eq_ledger
    (R : ℝ) :
    (completedZetaZeroPoleResidueTransportWithRectangle R).importedRectangleCount =
      (completedZetaZeroPoleResidueTransportWithRectangle R).certificateLedger.importedRectangleCount :=
  rfl

/-- The rectangle-certified transport exposes source, target, and path rectangle lists. -/
theorem completedZetaZeroPoleResidueTransportWithRectangle_importedRectangles_split
    (R : ℝ) :
    (completedZetaZeroPoleResidueTransportWithRectangle R).importedRectangles =
      (completedZetaZeroPoleResiduePresentationWithRectangle R).importedRectangles ++
        (completedZetaZeroPoleResidueOutput.importedRectangles ++
          (completedZetaZeroPoleResidueTransportWithRectangle
            R).pathCertificateLedger.importedRectangles) :=
  TraceTransport.importedRectangles_eq_source_target_path
    (completedZetaZeroPoleResidueTransportWithRectangle R)

end AnalyticMotives
end LFunctions
end Boundary
