import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.ResidueChannelPresentation.ResidueLedger.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.ResidueChannelPresentation.Channels.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.ResidueChannelPresentation.Schedules.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceRewrite.Coherence.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.RiemannHypothesisBridge.Bridge.WeilCriterion.Zero.ZetaWeilShared.ZetaZeroSideDefinitions.ZetaCenteredZeroCounting.ZetaCompletedLogDerivativeBridge.ZetaExplicitFormulaComplexAnalysis.ZetaExplicitFormulaContour.ZetaExplicitFormulaRectangleAPI.Owner

/-!
# Analytic certificates

This file owns the finite analytic certificate ledger attached to a
residue-channel presentation.

The ledger is concrete trace-calculus syntax.  Its atoms record the analytic
moves available to a presentation: finite rectangles, residue ledgers, channel
decompositions, schedule changes, and higher coherence cells.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
One analytic certificate atom attached to a residue-channel presentation.

The `explicitFormulaRectangle` constructor is an imported finite-rectangle
artifact from the RH lane.  The remaining constructors are zeta-independent
trace-calculus atoms: they bind certificates to Q-linear trace expressions,
residue ledgers, channel decompositions, schedules, rewrite paths, and higher
coherence cells.
-/
inductive ResidueChannelCertificateAtom where
  | sourceExpression (expression : QTraceExpression)
  | residueLedger (ledger : ResidueLedger)
  | channelExpression (channel : ResidueChannelExpression)
  | channelList (channels : ResidueChannelExpressionList)
  | traceSchedule (schedule : TraceSchedule)
  | rewritePath (path : TraceRewritePath)
  | coherenceCell (cell : TraceCoherenceCell)
  | explicitFormulaRectangle
      (rectangle :
        ZetaAdmissibleFunction.ExplicitFormulaRectangle)

/-- A finite analytic certificate ledger. -/
abbrev ResidueChannelCertificateLedger :=
  List ResidueChannelCertificateAtom

/-- The empty analytic certificate ledger. -/
def ResidueChannelCertificateLedger.empty :
    ResidueChannelCertificateLedger :=
  []

/-- Add one analytic certificate atom at the front of a ledger. -/
def ResidueChannelCertificateLedger.cons
    (atom : ResidueChannelCertificateAtom)
    (ledger : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger :=
  atom :: ledger

/-- The singleton analytic certificate ledger. -/
def ResidueChannelCertificateLedger.singleton
    (atom : ResidueChannelCertificateAtom) :
    ResidueChannelCertificateLedger :=
  [atom]

/-- The certificate ledger generated by one rewrite path. -/
def ResidueChannelCertificateLedger.ofRewritePath
    (path : TraceRewritePath) :
    ResidueChannelCertificateLedger :=
  ResidueChannelCertificateLedger.singleton
    (ResidueChannelCertificateAtom.rewritePath path)

/--
The certificate ledger generated by one higher coherence cell together with
the two rewrite paths it compares.
-/
def ResidueChannelCertificateLedger.ofCertifiedCoherenceCell
    (cell : TraceCoherenceCell) :
    ResidueChannelCertificateLedger :=
  [
    ResidueChannelCertificateAtom.rewritePath cell.source,
    ResidueChannelCertificateAtom.rewritePath cell.target,
    ResidueChannelCertificateAtom.coherenceCell cell
  ]

/-- The certificate ledger generated by one finite explicit-formula rectangle. -/
def ResidueChannelCertificateLedger.ofExplicitFormulaRectangle
    (rectangle :
      ZetaAdmissibleFunction.ExplicitFormulaRectangle) :
    ResidueChannelCertificateLedger :=
  ResidueChannelCertificateLedger.singleton
    (ResidueChannelCertificateAtom.explicitFormulaRectangle rectangle)

/-- Append two analytic certificate ledgers. -/
def ResidueChannelCertificateLedger.append
    (first second : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger :=
  first ++ second

/-- Adding the empty certificate ledger on the left changes nothing. -/
theorem ResidueChannelCertificateLedger.empty_append
    (ledger : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger.append
      ResidueChannelCertificateLedger.empty
      ledger =
      ledger :=
  rfl

/-- Certificate-ledger cons is list cons. -/
theorem ResidueChannelCertificateLedger.cons_eq_cons
    (atom : ResidueChannelCertificateAtom)
    (ledger : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger.cons atom ledger =
      atom :: ledger :=
  rfl

/-- A singleton certificate ledger is a cons over the empty ledger. -/
theorem ResidueChannelCertificateLedger.singleton_eq_cons_empty
    (atom : ResidueChannelCertificateAtom) :
    ResidueChannelCertificateLedger.singleton atom =
      ResidueChannelCertificateLedger.cons
        atom
        ResidueChannelCertificateLedger.empty :=
  rfl

/-- The rewrite-path certificate ledger is the corresponding singleton. -/
theorem ResidueChannelCertificateLedger.ofRewritePath_eq_singleton
    (path : TraceRewritePath) :
    ResidueChannelCertificateLedger.ofRewritePath path =
      ResidueChannelCertificateLedger.singleton
        (ResidueChannelCertificateAtom.rewritePath path) :=
  rfl

/-- A certified coherence-cell ledger records source path, target path, then cell. -/
theorem ResidueChannelCertificateLedger.ofCertifiedCoherenceCell_eq_paths_cell
    (cell : TraceCoherenceCell) :
    ResidueChannelCertificateLedger.ofCertifiedCoherenceCell cell =
      ResidueChannelCertificateAtom.rewritePath cell.source ::
        ResidueChannelCertificateAtom.rewritePath cell.target ::
          ResidueChannelCertificateAtom.coherenceCell cell ::
            ResidueChannelCertificateLedger.empty :=
  rfl

/-- The explicit-formula rectangle certificate ledger is the corresponding singleton. -/
theorem ResidueChannelCertificateLedger.ofExplicitFormulaRectangle_eq_singleton
    (rectangle :
      ZetaAdmissibleFunction.ExplicitFormulaRectangle) :
    ResidueChannelCertificateLedger.ofExplicitFormulaRectangle rectangle =
      ResidueChannelCertificateLedger.singleton
        (ResidueChannelCertificateAtom.explicitFormulaRectangle rectangle) :=
  rfl

/-- Certificate-ledger append is list append. -/
theorem ResidueChannelCertificateLedger.append_eq_append
    (first second : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger.append first second =
      first ++ second :=
  rfl

/-- Adding the empty certificate ledger on the right changes nothing. -/
theorem ResidueChannelCertificateLedger.append_empty
    (ledger : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger.append
      ledger
      ResidueChannelCertificateLedger.empty =
      ledger :=
  List.append_nil ledger

/-- Appending analytic certificate ledgers is associative. -/
theorem ResidueChannelCertificateLedger.append_assoc
    (first second third : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger.append
      (ResidueChannelCertificateLedger.append first second)
      third =
      ResidueChannelCertificateLedger.append
        first
        (ResidueChannelCertificateLedger.append second third) :=
  List.append_assoc first second third

/-- The certificate root exposes the empty ledger. -/
theorem ResidueChannelCertificate.empty_eq_nil :
    ResidueChannelCertificateLedger.empty = [] :=
  rfl

/-- The certificate root exposes singleton ledgers. -/
theorem ResidueChannelCertificate.singleton_eq_cons_empty
    (atom : ResidueChannelCertificateAtom) :
    ResidueChannelCertificateLedger.singleton atom =
      ResidueChannelCertificateLedger.cons
        atom
        ResidueChannelCertificateLedger.empty :=
  ResidueChannelCertificateLedger.singleton_eq_cons_empty
    atom

/-- The certificate root exposes rewrite-path certificate ledgers. -/
theorem ResidueChannelCertificate.ofRewritePath_eq_singleton
    (path : TraceRewritePath) :
    ResidueChannelCertificateLedger.ofRewritePath path =
      ResidueChannelCertificateLedger.singleton
        (ResidueChannelCertificateAtom.rewritePath path) :=
  ResidueChannelCertificateLedger.ofRewritePath_eq_singleton
    path

/-- The certificate root exposes certificate-ledger associativity. -/
theorem ResidueChannelCertificate.append_assoc
    (first second third : ResidueChannelCertificateLedger) :
    ResidueChannelCertificateLedger.append
      (ResidueChannelCertificateLedger.append first second)
      third =
      ResidueChannelCertificateLedger.append
        first
        (ResidueChannelCertificateLedger.append second third) :=
  ResidueChannelCertificateLedger.append_assoc
    first
    second
    third

end AnalyticMotives
end LFunctions
end Boundary
