import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourAdmissible.DescentInterval.DescentCovers.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Presheaves.LinearTransfers.ContourCorQConstruction.Owner

/-!
# Constructed descent covers for `ContourCor_Q` presheaves

This owner specializes the conservative contour-cover calculus to constructed
linear presheaves on `ContourCor_Q`.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
A contour descent cover as seen by a constructed `ContourCor_Q` linear
presheaf.  It records the target bulk and the object-layer contour cover.
-/
structure ConstructedContourPresheafDescentCover
    (F : ConstructedContourPresheafObject) where
  target : ContourAdmissibleBulk
  cover : AnalyticContourDescentCover target.contour

namespace ConstructedContourPresheafDescentCover

/-- Build a constructed presheaf descent cover from an object-layer cover. -/
def ofContourCover
    (F : ConstructedContourPresheafObject)
    (X : ContourAdmissibleBulk)
    (D : AnalyticContourDescentCover X.contour) :
    ConstructedContourPresheafDescentCover F where
  target := X
  cover := D

/-- The selected descent cover carried by a contour-admissible bulk. -/
def selected
    (F : ConstructedContourPresheafObject)
    (X : ContourAdmissibleBulk)
    (i : X.descentInterval.CoverIndex) :
    ConstructedContourPresheafDescentCover F :=
  ofContourCover F X (X.descentCoverAt i)

/-- The singleton cover at one contour stage of a bulk. -/
def singleton
    (F : ConstructedContourPresheafObject)
    (X : ContourAdmissibleBulk)
    (target : X.contour.exhaustion.Stage) :
    ConstructedContourPresheafDescentCover F :=
  ofContourCover F X (AnalyticContourDescentCover.singleton target)

/-- A singleton cover generated by one explicit contour refinement. -/
def singletonRefinement
    (F : ConstructedContourPresheafObject)
    (X : ContourAdmissibleBulk)
    {refined target : X.contour.exhaustion.Stage}
    (R : AnalyticContourRefinement
        (X.contour.exhaustion.chain refined)
        (X.contour.exhaustion.chain target)) :
    ConstructedContourPresheafDescentCover F :=
  ofContourCover F X (AnalyticContourDescentCover.singletonRefinement R)

/-- The target bulk of a constructed presheaf descent cover. -/
def targetBulk {F : ConstructedContourPresheafObject}
    (C : ConstructedContourPresheafDescentCover F) :
    ContourAdmissibleBulk :=
  C.target

/-- The object-layer contour descent cover. -/
def contourCover {F : ConstructedContourPresheafObject}
    (C : ConstructedContourPresheafDescentCover F) :
    AnalyticContourDescentCover C.target.contour :=
  C.cover

/-- The target contour stage of the cover. -/
def targetStage {F : ConstructedContourPresheafObject}
    (C : ConstructedContourPresheafDescentCover F) :
    C.target.contour.exhaustion.Stage :=
  C.cover.targetStage

/-- The contour stage indexed by one cover piece. -/
def stageAt {F : ConstructedContourPresheafObject}
    (C : ConstructedContourPresheafDescentCover F)
    (i : C.cover.CoverIndex) :
    C.target.contour.exhaustion.Stage :=
  C.cover.stage i

/-- The contour refinement indexed by one cover piece. -/
def refinementAt {F : ConstructedContourPresheafObject}
    (C : ConstructedContourPresheafDescentCover F)
    (i : C.cover.CoverIndex) :
    AnalyticContourRefinement
      (C.target.contour.exhaustion.chain (C.stageAt i))
      (C.target.contour.exhaustion.chain C.targetStage) :=
  C.cover.refinementAt i

/-- Selected constructed covers have the selected target bulk. -/
theorem selected_targetBulk
    (F : ConstructedContourPresheafObject)
    (X : ContourAdmissibleBulk)
    (i : X.descentInterval.CoverIndex) :
    (selected F X i).targetBulk = X :=
  rfl

/-- Singleton constructed covers have the selected target bulk. -/
theorem singleton_targetBulk
    (F : ConstructedContourPresheafObject)
    (X : ContourAdmissibleBulk)
    (target : X.contour.exhaustion.Stage) :
    (singleton F X target).targetBulk = X :=
  rfl

/-- Singleton constructed covers have the selected target stage. -/
theorem singleton_targetStage
    (F : ConstructedContourPresheafObject)
    (X : ContourAdmissibleBulk)
    (target : X.contour.exhaustion.Stage) :
    (singleton F X target).targetStage = target :=
  rfl

end ConstructedContourPresheafDescentCover

end AnalyticMotives
end LFunctions
end Boundary
