import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homs.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Objects.LocalizationInput.Owner

/-!
# Localization-input homs in the analytic additive envelope

Each concrete localization input contributes its trace correspondence as a
one-entry matrix between the singleton additive source and target objects.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The additive-envelope matrix map generated by a concrete localization input. -/
def TraceLocalizationInput.additiveHom
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveHom
      input.additiveSourceObject
      input.additiveTargetObject :=
  TraceAnalyticAdditiveHom.singletonMap input.traceHom

/-- The zero-zero entry of a localization input's additive matrix is its trace hom. -/
theorem TraceLocalizationInput.additiveHom_entry_zero
    (input : TraceLocalizationInput) :
    input.additiveHom.entry 0 0 =
      input.traceHom :=
  TraceAnalyticAdditiveHom.singletonMap_entry_zero
    input.traceHom

end AnalyticMotives
end LFunctions
end Boundary
