import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Inputs.ByKind.Isomorphisms.Cancellation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Inputs.ByKind.Representatives.Owner

/-!
# Tate-stabilization localized arrows

This file exposes analytic weight-drop as an invertible arrow in the formal
localized word category.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized isomorphism generated by Tate weight-drop. -/
def TraceTateStabilizationLocalization.weightDropIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject
      (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject :=
  TraceLocalizationInput.tateWeightDropLocalizedIso source target

/-- The hom of the Tate weight-drop isomorphism is the named weight-drop forward arrow. -/
theorem TraceTateStabilizationLocalization.weightDropIso_hom
    (source target : QTraceExpression) :
    (TraceTateStabilizationLocalization.weightDropIso source target).hom =
      TraceLocalizationInput.tateWeightDropForwardArrow source target :=
  rfl

/-- The inverse of the Tate weight-drop isomorphism is the named weight-drop inverse arrow. -/
theorem TraceTateStabilizationLocalization.weightDropIso_inv
    (source target : QTraceExpression) :
    (TraceTateStabilizationLocalization.weightDropIso source target).inv =
      TraceLocalizationInput.tateWeightDropInverseArrow source target :=
  rfl

/-- The Tate weight-drop hom has a one-atom chosen representative. -/
theorem TraceTateStabilizationLocalization.weightDropIso_hom_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputForward
      (TraceLocalizationInput.tateWeightDrop source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.tateWeightDropForwardArrow_representative_atomCount
    source
    target

/-- The Tate weight-drop inverse has a one-atom chosen representative. -/
theorem TraceTateStabilizationLocalization.weightDropIso_inv_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputInverse
      (TraceLocalizationInput.tateWeightDrop source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.tateWeightDropInverseArrow_representative_atomCount
    source
    target

/-- Tate weight-drop hom followed by inverse is identity. -/
theorem TraceTateStabilizationLocalization.weightDropIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceTateStabilizationLocalization.weightDropIso source target).hom
        (TraceTateStabilizationLocalization.weightDropIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.tateWeightDrop source target).sourceObject :=
  TraceLocalizationInput.tateWeightDropLocalizedIso_hom_comp_inv source target

/-- Tate weight-drop inverse followed by hom is identity. -/
theorem TraceTateStabilizationLocalization.weightDropIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceTateStabilizationLocalization.weightDropIso source target).inv
        (TraceTateStabilizationLocalization.weightDropIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.tateWeightDrop source target).targetObject :=
  TraceLocalizationInput.tateWeightDropLocalizedIso_inv_comp_hom source target

/-- Tate weight-drop hom followed by inverse is categorical identity. -/
theorem TraceTateStabilizationLocalization.weightDropIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceTateStabilizationLocalization.weightDropIso source target).hom ≫
        (TraceTateStabilizationLocalization.weightDropIso source target).inv =
      (𝟙 (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject
          (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject) :=
  TraceLocalizationInput.tateWeightDropLocalizedIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Tate weight-drop inverse followed by hom is categorical identity. -/
theorem TraceTateStabilizationLocalization.weightDropIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceTateStabilizationLocalization.weightDropIso source target).inv ≫
        (TraceTateStabilizationLocalization.weightDropIso source target).hom =
      (𝟙 (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject
          (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject) :=
  TraceLocalizationInput.tateWeightDropLocalizedIso_inv_comp_hom_eq_categoryIdentity
    source
    target

end AnalyticMotives
end LFunctions
end Boundary
