import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourAdmissible.BoundarySystem.Incidence.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourAdmissible.ResidueLedger.Maps.Owner

/-!
# Residue-depth filtration for analytic bulks

This file owns the filtration generated by iterated boundary residues and face
incidence.  Geometric-contour weights are downstream from this filtration.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
A residue-depth filtration on the boundary faces of a boundary system.
Incidence maps are required to move from deeper faces to no-deeper faces.
-/
structure AnalyticResidueFiltration {X : AnalyticBulkCore}
    (B : AnalyticBoundarySystem X) where
  depth : B.FaceIndex → Nat
  incidence_depth :
    {lower upper : B.FaceIndex} →
      B.IncidenceIndex lower upper → depth upper ≤ depth lower

namespace AnalyticResidueFiltration

/-- The residue depth of a boundary face index. -/
def depthAt {X : AnalyticBulkCore} {B : AnalyticBoundarySystem X}
    (F : AnalyticResidueFiltration B) (i : B.FaceIndex) : Nat :=
  F.depth i

/-- Incidence does not increase residue depth. -/
theorem incidence_le {X : AnalyticBulkCore} {B : AnalyticBoundarySystem X}
    (F : AnalyticResidueFiltration B)
    {lower upper : B.FaceIndex} (I : B.IncidenceIndex lower upper) :
    F.depth upper ≤ F.depth lower :=
  F.incidence_depth I

end AnalyticResidueFiltration

end AnalyticMotives
end LFunctions
end Boundary
