import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleTransports.Owner

/-!
# Zero-pole Q-linear trace correspondences

This file exposes the two certified zero-pole trace transports as generators
and singleton formal sums in the raw `TraceCorQ` layer.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The Q-linear trace-correspondence generator for zero-pole residue extraction. -/
def completedZetaZeroPoleResidueTraceCorQGenerator : TraceCorQGenerator :=
  completedZetaZeroPoleResidueTransport

/-- The residue trace-correspondence generator has the expected source object. -/
theorem completedZetaZeroPoleResidueTraceCorQGenerator_source :
    completedZetaZeroPoleResidueTraceCorQGenerator.source =
      completedZetaZeroPoleResiduePresentationSpine :=
  completedZetaZeroPoleResidueTransport_source

/-- The residue trace-correspondence generator has the expected target object. -/
theorem completedZetaZeroPoleResidueTraceCorQGenerator_target :
    completedZetaZeroPoleResidueTraceCorQGenerator.target =
      completedZetaZeroPoleResidueOutputSpine :=
  completedZetaZeroPoleResidueTransport_target

/-- The singleton Q-linear correspondence generated by zero-pole residue extraction. -/
def completedZetaZeroPoleResidueTraceCorQFormalSum :
    TraceCorQFormalSum :=
  TraceCorQFormalSum.singleton
    1
    completedZetaZeroPoleResidueTraceCorQGenerator

/-- The Q-linear trace-correspondence generator for zero-pole channel decomposition. -/
def completedZetaZeroPoleChannelTraceCorQGenerator : TraceCorQGenerator :=
  completedZetaZeroPoleChannelTransport

/-- The channel trace-correspondence generator has the expected source object. -/
theorem completedZetaZeroPoleChannelTraceCorQGenerator_source :
    completedZetaZeroPoleChannelTraceCorQGenerator.source =
      completedZetaZeroPoleChannelPresentationSpine :=
  completedZetaZeroPoleChannelTransport_source

/-- The channel trace-correspondence generator has the expected target object. -/
theorem completedZetaZeroPoleChannelTraceCorQGenerator_target :
    completedZetaZeroPoleChannelTraceCorQGenerator.target =
      completedZetaZeroPoleChannelOutputSpine :=
  completedZetaZeroPoleChannelTransport_target

/-- The singleton Q-linear correspondence generated by zero-pole channel decomposition. -/
def completedZetaZeroPoleChannelTraceCorQFormalSum :
    TraceCorQFormalSum :=
  TraceCorQFormalSum.singleton
    1
    completedZetaZeroPoleChannelTraceCorQGenerator

/-- The formal sum containing both certified zero-pole correspondences. -/
def completedZetaZeroPoleSeedTraceCorQFormalSum :
    TraceCorQFormalSum :=
  TraceCorQFormalSum.add
    completedZetaZeroPoleResidueTraceCorQFormalSum
    completedZetaZeroPoleChannelTraceCorQFormalSum

end AnalyticMotives
end LFunctions
end Boundary
