import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleTransports.Owner

/-!
# Zero-pole Q-linear trace correspondences

This file exposes the two certified zero-pole trace transports as generators
and singleton formal sums in the raw `TraceCorQ` layer.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The Q-linear trace-correspondence generator for zero-pole residue extraction. -/
def completedZetaZeroPoleResidueTraceCorQGenerator : TraceCorQGenerator :=
  completedZetaZeroPoleResidueTransport

/-- The residue trace-correspondence generator has the expected source object. -/
theorem completedZetaZeroPoleResidueTraceCorQGenerator_source :
    completedZetaZeroPoleResidueTraceCorQGenerator.source =
      completedZetaZeroPoleResiduePresentation :=
  completedZetaZeroPoleResidueTransport_source

/-- The residue trace-correspondence generator has the expected target object. -/
theorem completedZetaZeroPoleResidueTraceCorQGenerator_target :
    completedZetaZeroPoleResidueTraceCorQGenerator.target =
      completedZetaZeroPoleResidueOutput :=
  completedZetaZeroPoleResidueTransport_target

/-- The current residue trace-correspondence generator carries no imported rectangle atom. -/
theorem completedZetaZeroPoleResidueTraceCorQGenerator_importedRectangleCount :
    completedZetaZeroPoleResidueTraceCorQGenerator.importedRectangleCount =
      0 :=
  completedZetaZeroPoleResidueTransport_importedRectangleCount

/-- The current residue trace-correspondence generator records endpoint and path bookkeeping. -/
theorem completedZetaZeroPoleResidueTraceCorQGenerator_traceBookkeepingCount :
    completedZetaZeroPoleResidueTraceCorQGenerator.traceBookkeepingCount =
      9 :=
  completedZetaZeroPoleResidueTransport_traceBookkeepingCount

/-- The singleton Q-linear correspondence generated by zero-pole residue extraction. -/
def completedZetaZeroPoleResidueTraceCorQFormalSum :
    TraceCorQFormalSum :=
  TraceCorQFormalSum.singleton
    1
    completedZetaZeroPoleResidueTraceCorQGenerator

/-- The residue singleton currently carries no imported rectangle atom. -/
theorem completedZetaZeroPoleResidueTraceCorQFormalSum_importedRectangleCount :
    completedZetaZeroPoleResidueTraceCorQFormalSum.importedRectangleCount =
      0 :=
  rfl

/-- The residue singleton records the bookkeeping of its generator. -/
theorem completedZetaZeroPoleResidueTraceCorQFormalSum_traceBookkeepingCount :
    completedZetaZeroPoleResidueTraceCorQFormalSum.traceBookkeepingCount =
      9 :=
  rfl

/-- The Q-linear trace-correspondence generator for zero-pole channel decomposition. -/
def completedZetaZeroPoleChannelTraceCorQGenerator : TraceCorQGenerator :=
  completedZetaZeroPoleChannelTransport

/-- The channel trace-correspondence generator has the expected source object. -/
theorem completedZetaZeroPoleChannelTraceCorQGenerator_source :
    completedZetaZeroPoleChannelTraceCorQGenerator.source =
      completedZetaZeroPoleChannelPresentation :=
  completedZetaZeroPoleChannelTransport_source

/-- The channel trace-correspondence generator has the expected target object. -/
theorem completedZetaZeroPoleChannelTraceCorQGenerator_target :
    completedZetaZeroPoleChannelTraceCorQGenerator.target =
      completedZetaZeroPoleChannelOutput :=
  completedZetaZeroPoleChannelTransport_target

/-- The current channel trace-correspondence generator carries no imported rectangle atom. -/
theorem completedZetaZeroPoleChannelTraceCorQGenerator_importedRectangleCount :
    completedZetaZeroPoleChannelTraceCorQGenerator.importedRectangleCount =
      0 :=
  completedZetaZeroPoleChannelTransport_importedRectangleCount

/-- The current channel trace-correspondence generator records endpoint and path bookkeeping. -/
theorem completedZetaZeroPoleChannelTraceCorQGenerator_traceBookkeepingCount :
    completedZetaZeroPoleChannelTraceCorQGenerator.traceBookkeepingCount =
      9 :=
  completedZetaZeroPoleChannelTransport_traceBookkeepingCount

/-- The singleton Q-linear correspondence generated by zero-pole channel decomposition. -/
def completedZetaZeroPoleChannelTraceCorQFormalSum :
    TraceCorQFormalSum :=
  TraceCorQFormalSum.singleton
    1
    completedZetaZeroPoleChannelTraceCorQGenerator

/-- The channel singleton currently carries no imported rectangle atom. -/
theorem completedZetaZeroPoleChannelTraceCorQFormalSum_importedRectangleCount :
    completedZetaZeroPoleChannelTraceCorQFormalSum.importedRectangleCount =
      0 :=
  rfl

/-- The channel singleton records the bookkeeping of its generator. -/
theorem completedZetaZeroPoleChannelTraceCorQFormalSum_traceBookkeepingCount :
    completedZetaZeroPoleChannelTraceCorQFormalSum.traceBookkeepingCount =
      9 :=
  rfl

/-- The formal sum containing both certified zero-pole correspondences. -/
def completedZetaZeroPoleSeedTraceCorQFormalSum :
    TraceCorQFormalSum :=
  TraceCorQFormalSum.add
    completedZetaZeroPoleResidueTraceCorQFormalSum
    completedZetaZeroPoleChannelTraceCorQFormalSum

/-- The current zero-pole seed formal sum carries no imported rectangle atom. -/
theorem completedZetaZeroPoleSeedTraceCorQFormalSum_importedRectangleCount :
    completedZetaZeroPoleSeedTraceCorQFormalSum.importedRectangleCount =
      0 :=
  rfl

/-- The current zero-pole seed formal sum records both one-step generators. -/
theorem completedZetaZeroPoleSeedTraceCorQFormalSum_traceBookkeepingCount :
    completedZetaZeroPoleSeedTraceCorQFormalSum.traceBookkeepingCount =
      18 :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
