import TraceCalc.LayerB.RealObjects.SwapSquare

/-!
# Real-objects formalization: chain-level administrative moves

**Phase 3B item 5f (2026-04-24).** Per user's verbatim 5f directive +
`INV AdminMove-Nonvacuity`: implement the chain-level adjacent-swap
admin move layer **without** collapsing to `PeelChain.replay_stable`.

## Honest scope (per user's stop-and-report clause)

The current `PeelChain` is indexed by a *literal*
`CompletedReconstructionRecord`. The two-step residues
`peelSink (peelSink R s) (peelSinkOtherIdx s t _)` and
`peelSink (peelSink R t) (peelSinkOtherIdx t s _)` are only
`RecordStructEquiv BoundaryAdminEquiv`, **not** definitionally equal,
so `AdminMove.adjacent_swap` cannot share a tail. The constructor
takes the two tails as *independent* `PeelChain` instances over the
two structurally-equivalent two-step records.

This is the honest minimal admin layer: it does **not** identify
chains that produce the same multiset of sinks unless their
post-swap tails are equal as `PeelChain`s of the respective records.
The chain-level admin equivalence captured here is the **head-prefix
swap relation**, generated by `adjacent_swap` and closed under
`refl`/`symm`/`trans`.

## Honest report on replay-level admin stability (deliverable 6)

A *replay-level* stability theorem under `AdminEquiv` is
*trivially* derivable from `PeelChain.replay_recordEquiv` (which
gives `RecordEquiv (replay c) R` for any `c`), `RecordEquiv.symm`,
`RecordEquiv.trans`, `RecordEquiv.toStructEquiv` (instantiating
`BR := Eq`), and a `BoundaryAdminEquiv.refl`-based reweakening of
`Eq` to `BoundaryAdminEquiv`. **It does not non-vacuously consume the
frontier theorem `peelSink_swap_structEquiv_admin`**, because the
strict replay always recovers `R` regardless of swap order.

This is a structural truth about replay, not a defect in our setup:
**the swap content lives at the truncated-frontier level, not at the
fully-replayed level.** Per `INV AdminMove-Nonvacuity`, we therefore:

1. Define `AdminMove` and `AdminEquiv` (deliverables 1, 4);
2. Prove the **frontier theorem** `AdminMove.frontier_structEquiv_admin`
   that **directly consumes** `peelSink_swap_structEquiv_admin`
   (deliverable 3 — the non-vacuity gate);
3. Lift to `AdminEquiv.frontier_structEquiv_admin` (deliverable 5).
4. **Defer** the replay-level corollary (deliverable 6) to a future
   item, where it should be stated against a more refined truncated
   replay or against a chain notion that survives `RecordStructEquiv`
   transport (item 5g).

The frontier viewpoint is the manuscript-honest locus: at
`thm:canonical-reconstruction-algorithm` (L1180), what is canonical
is the *boundary of each step*, not just the final residue.

## Architecture

* `PeelChain.AdminMove c₁ c₂` — inductive head-prefix adjacent-swap
  relation between two `PeelChain R`s, with one constructor
  `adjacent_swap` packaging the swap data `(s, t, h, hSinkS, hSinkT,
  tail₁, tail₂)`.
* `AdminMove.frontier_structEquiv_admin` — frontier theorem (the
  non-vacuity gate): for any `adjacent_swap` move, the two-step
  residues are `RecordStructEquiv BoundaryAdminEquiv`. **Consumes
  `peelSink_swap_structEquiv_admin` directly.**
* `PeelChain.AdminEquiv` — inductive equivalence closure with
  `refl`/`symm`/`trans`/`ofMove`.

## Manuscript anchor

`our_paper_draft.tex`:
* L1180 (`thm:canonical-reconstruction-algorithm`) — the canonicality
  clause stating any two valid recursive descents arrive at equivalent
  records; here realized at the chain level via head-prefix swap.
* L1186–L1192 — the per-step descent whose adjacent independent-sink
  swaps we now expose as a chain-level move.
-/

universe u

namespace TraceCalc
namespace LayerB
namespace RealObjects

namespace RewriteCalculusSetup

open CompletedReconstructionRecord

variable {setup : RewriteCalculusSetup.{u}}

namespace PeelChain

/-! ### Adjacent-swap admin moves -/

/-- **Chain-level adjacent-swap admin move.**

`AdminMove c₁ c₂` holds when `c₁` and `c₂` differ by a single adjacent
swap of two independent sinks at the head of the chain.

The constructor `adjacent_swap` packages:
* the swap data `(s, t : Fin R.n)` with `IndependentSinks R s t`;
* `IsSink` witnesses for both `s` and `t` in `R`;
* the two **independent** post-swap tails — one a `PeelChain` of
  `peelSink (peelSink R s) (peelSinkOtherIdx s t _)`, the other of
  `peelSink (peelSink R t) (peelSinkOtherIdx t s _)`.

Per the file-level *honest scope* note: the two tails are independent
`PeelChain` instances because the two two-step residues are only
`RecordStructEquiv BoundaryAdminEquiv` (not definitionally equal),
so they cannot share a single tail term. -/
inductive AdminMove :
    ∀ {R : CompletedReconstructionRecord setup}, PeelChain R → PeelChain R → Prop
  | adjacent_swap
      {R : CompletedReconstructionRecord setup} {s t : Fin R.n}
      (h : IndependentSinks R s t)
      (hSinkS : R.IsSink s) (hSinkT : R.IsSink t)
      (tail₁ : PeelChain
        (peelSink (peelSink R s) (peelSinkOtherIdx s t (Ne.symm h.s_ne_t))))
      (tail₂ : PeelChain
        (peelSink (peelSink R t) (peelSinkOtherIdx t s h.s_ne_t))) :
      AdminMove
        (.cons R s hSinkS
          (.cons (peelSink R s) (peelSinkOtherIdx s t (Ne.symm h.s_ne_t))
            (peelSinkOtherIdx_isSink s t (Ne.symm h.s_ne_t) hSinkT) tail₁))
        (.cons R t hSinkT
          (.cons (peelSink R t) (peelSinkOtherIdx t s h.s_ne_t)
            (peelSinkOtherIdx_isSink t s h.s_ne_t hSinkS) tail₂))

namespace AdminMove

/-- **Frontier theorem (the non-vacuity gate, per
`INV AdminMove-Nonvacuity`).** The two-step residues of an
`adjacent_swap` move are `RecordStructEquiv BoundaryAdminEquiv`.

This theorem **directly consumes** `peelSink_swap_structEquiv_admin`
at the swap frontier — it does *not* route through any replay/inverse
construction, and is not vacuously derivable from `replay_stable`. -/
theorem frontier_structEquiv_admin
    {R : CompletedReconstructionRecord setup} {s t : Fin R.n}
    (h : IndependentSinks R s t) :
    RecordStructEquiv (@BoundaryAdminEquiv setup)
      (peelSink (peelSink R s) (peelSinkOtherIdx s t (Ne.symm h.s_ne_t)))
      (peelSink (peelSink R t) (peelSinkOtherIdx t s h.s_ne_t)) :=
  peelSink_swap_structEquiv_admin h

end AdminMove

/-! ### Generated chain-level administrative equivalence -/

/-- **Chain-level administrative equivalence.**

The free equivalence relation generated by `AdminMove`. This is the
intended `BR`-analogue at the *chain level* for downstream global
canonicality: two chains over the same record are admin-equivalent
when they differ by a finite sequence of head-prefix adjacent swaps,
closed under `refl`/`symm`/`trans`.

Per `INV AdminMove-Nonvacuity`: any consumer of `AdminEquiv` for
non-vacuous structural conclusions must descend through `ofMove` to
reach `frontier_structEquiv_admin`. -/
inductive AdminEquiv :
    ∀ {R : CompletedReconstructionRecord setup}, PeelChain R → PeelChain R → Prop
  | refl {R : CompletedReconstructionRecord setup} (c : PeelChain R) :
      AdminEquiv c c
  | symm {R : CompletedReconstructionRecord setup} {c₁ c₂ : PeelChain R} :
      AdminEquiv c₁ c₂ → AdminEquiv c₂ c₁
  | trans {R : CompletedReconstructionRecord setup} {c₁ c₂ c₃ : PeelChain R} :
      AdminEquiv c₁ c₂ → AdminEquiv c₂ c₃ → AdminEquiv c₁ c₃
  | ofMove {R : CompletedReconstructionRecord setup} {c₁ c₂ : PeelChain R} :
      AdminMove c₁ c₂ → AdminEquiv c₁ c₂

namespace AdminEquiv

/-- Reflexivity (alias of the `refl` constructor for symmetry of API). -/
theorem refl' {R : CompletedReconstructionRecord setup} (c : PeelChain R) :
    AdminEquiv c c := AdminEquiv.refl c

/-- Symmetry (alias of the `symm` constructor). -/
theorem symm' {R : CompletedReconstructionRecord setup} {c₁ c₂ : PeelChain R}
    (h : AdminEquiv c₁ c₂) : AdminEquiv c₂ c₁ := h.symm

/-- Transitivity (alias of the `trans` constructor). -/
theorem trans' {R : CompletedReconstructionRecord setup}
    {c₁ c₂ c₃ : PeelChain R}
    (h₁ : AdminEquiv c₁ c₂) (h₂ : AdminEquiv c₂ c₃) :
    AdminEquiv c₁ c₃ := h₁.trans h₂

/-- The single-move embedding (alias of the `ofMove` constructor). -/
theorem ofMove' {R : CompletedReconstructionRecord setup}
    {c₁ c₂ : PeelChain R} (h : AdminMove c₁ c₂) : AdminEquiv c₁ c₂ :=
  AdminEquiv.ofMove h

end AdminEquiv

end PeelChain

/-! ### Honest replay-level note (deliverable 6 deferral)

The intended downstream consumer of `AdminEquiv` is a structural
stability theorem of the form

```
RecordStructEquiv BoundaryAdminEquiv (replay c₁) (replay c₂)
```

for `AdminEquiv c₁ c₂`. As noted in the file header, this version is
**vacuous** at the abstract setup level: both `replay c₁` and
`replay c₂` are `RecordEquiv` to the original `R` via
`PeelChain.replay_recordEquiv`, so the desired conclusion follows by
two transport steps and `RecordEquiv.toStructEquiv` followed by a
`BoundaryAdminEquiv.refl`-based reweakening — no use of the frontier
theorem is needed.

The **non-vacuous** replay-level statement requires a *truncated
replay* (replay only the first `k` peeling steps, leaving a
two-step or `k`-step residual record at the frontier). At that
truncated level, `frontier_structEquiv_admin` is genuinely required.

Item **5g** will introduce `truncatedReplay` and the truncated
admin-stability theorem; item 5f closes here.
-/

end RewriteCalculusSetup

end RealObjects
end LayerB
end TraceCalc
