import TraceCalc.LayerB.RealObjects.InteriorCode

/-!
# Real-objects formalization: boundary code feasibility audit (Phase 9 items 9e–9i)

**Phase 9 items 9e–9i (2026-04-24).** Determine whether
`BoundaryCodeContract` (item 8x) can be *constructed* from the
current `RewriteCalculusSetup` data, or whether it must remain an
*obligation* — and in either case, isolate the boundary side of the
residue admin quotient realization into the cleanest possible form.

## Audit of available data (item 9e)

`RewriteCalculusSetup` exposes:

* `BoundaryObject : Type u` — **completely opaque**. No
  `DecidableEq`, no `LinearOrder`, no serialization map, no
  `Repr` instance. The setup carries only the projection
  `boundaryOf : State → BoundaryObject`.
* `RefinedInterface : Type u` — **also completely opaque**. No
  decidable equality, no order, no serialization.
* `BoundaryAdminEquiv : BoundaryObject → BoundaryObject → Prop` —
  the free equivalence relation generated by `BoundaryTwoStepSwap`
  (defined in [SwapSquare.lean](Lean/TraceCalc/LayerB/RealObjects/SwapSquare.lean)).
  Its `ofTwoStepSwap` constructor is parameterized over an entire
  ambient record `R`, two indices `s, t`, and an `IndependentSinks`
  witness — there is no syntactic representative of an element of
  the quotient that does not refer back to such a generator term.
* `FrontierWord.BoundaryEquiv` (item 8v) splits as
  `Y_rel : BoundaryAdminEquiv … …` plus
  `externalOut_perm : List.Perm … …` over `RefinedInterface`.

**Conclusion (item 9e)**: with the current opaque `BoundaryObject`
and `RefinedInterface`, *no concrete canonical code* can be
constructed for either:

* `BoundaryAdminEquiv` modulo the boundary-admin quotient, or
* `List.Perm` on `List RefinedInterface`.

Both require *external* canonicalization data — at minimum a
serialization map for `BoundaryObject` (or a proof that
`BoundaryAdminEquiv` is equality on a chosen canonical
representative), and a key/serialization for `RefinedInterface` so
that lists can be sorted into a permutation-invariant form. The
right outcome of this batch is therefore an **obligation
interface**, not a construction.

## Items in this file

* **9e** — This audit (above).
* **9f** — `ExternalOutCodeContract setup`: a coding contract for
  `List.Perm` on `List setup.RefinedInterface`. Both `sound` and
  `complete` carry **real signatures** against `List.Perm`. Stated
  as an obligation; not instantiated.
* **9g** — `BoundaryAdminCodeContract setup`: a coding contract for
  `BoundaryAdminEquiv`. Both `sound` and `complete` carry **real
  signatures**. Stated as an obligation; not instantiated.
* **9h** — `boundary_component_codes_to_contract`: assembling
  `BoundaryAdminCodeContract` and `ExternalOutCodeContract` into a
  `BoundaryCodeContract` for `FrontierWord.BoundaryEquiv` (item
  8x). The product target is `BoundaryCode × ExternalOutCode`; the
  sound/complete proofs follow the same `Prod.mk.injEq` /
  `congrArg Prod.fst/snd` pattern as the interior assembly (item
  8y).
* **9i** — Manuscript-facing aliases and explicit stop report.

## Honest scope (per user's stop conditions, all honored)

* No concrete serialization for `setup.BoundaryObject` is invented.
* `BoundaryAdminEquiv` is **not** assumed to collapse to equality.
* `FrontierQuotientRealization` is **not** claimed: even with
  `interiorCanonicalContract` constructed, the assembly theorem
  `component_codes_to_quotient_realization` (item 8y) requires a
  `BoundaryCodeContract` instance, which is not supplied here —
  only the *obligation interface* is.
* `FrontierWord` is **not** enriched.
* `BoundaryObject` is **not** enriched (no `DecidableEq` / `Repr`
  instance is added to `RewriteCalculusSetup`).

## Stop report (item 9i)

The current obstacle to a fully-constructed
`FrontierQuotientRealization` is **not** Lean bookkeeping. It is
the *absence of a canonical serialization or quotient code* for
`BoundaryAdminEquiv` and `List.Perm`-on-`RefinedInterface`. After
this batch, the entire residue-level holographic theorem is
reduced to two named boundary-canonicalization theorems:

* `BoundaryAdminCodeContract` (item 9g), and
* `ExternalOutCodeContract` (item 9f).

These two together yield `BoundaryCodeContract` via item 9h, which
together with `interiorCanonicalContract` (item 9d) yields the
faithful `FrontierQuotientRealization` via item 8y.

## Manuscript anchor

`our_paper_draft.tex`:
* L1180 (`thm:canonical-reconstruction-algorithm`).
* L1098 (`def:completed-reconstruction-record`).
* L1108 (clause (a) `Ports`, contains `externalOut`).
* L1102 (the `Y` slot of the record tuple).
-/

universe u v

namespace TraceCalc
namespace LayerB
namespace RealObjects
namespace RewriteCalculusSetup

open CompletedReconstructionRecord

variable {setup : RewriteCalculusSetup.{u}}

/-! ## Item 9f — Obligation interface for `List.Perm` on `externalOut` -/

/-- **`ExternalOutCodeContract setup`** (item 9f): an obligation
interface for canonical coding of `List setup.RefinedInterface`
modulo `List.Perm`.

Stated against `List.Perm` because that is exactly the equivalence
appearing in the `externalOut_perm` field of
`FrontierWord.BoundaryEquiv` (item 8v). Both `sound` and `complete`
carry **real signatures** — there are no `Prop` placeholders.

This contract is *not* instantiated in this file: it is an
obligation that must be discharged externally (e.g., by giving
`setup.RefinedInterface` a `LinearOrder` and using a sorted
representative as the code, or by extending `RewriteCalculusSetup`
to carry a `RefinedInterface`-multiset key map). -/
structure ExternalOutCodeContract (setup : RewriteCalculusSetup.{u}) where
  /-- The external-output code target type. -/
  ExternalOutCode : Type v
  /-- The external-output code function. -/
  externalOutCode : List setup.RefinedInterface → ExternalOutCode
  /-- Soundness: `List.Perm`-equivalent lists code to the same value. -/
  sound :
    ∀ {ℓ₁ ℓ₂ : List setup.RefinedInterface},
      List.Perm ℓ₁ ℓ₂ → externalOutCode ℓ₁ = externalOutCode ℓ₂
  /-- **Completeness with a real signature**: equal codes imply
  `List.Perm`. -/
  complete :
    ∀ {ℓ₁ ℓ₂ : List setup.RefinedInterface},
      externalOutCode ℓ₁ = externalOutCode ℓ₂ → List.Perm ℓ₁ ℓ₂

@[simp] theorem ExternalOutCodeContract.mk_ExternalOutCode
    (ExternalOutCode : Type v)
    (externalOutCode : List setup.RefinedInterface → ExternalOutCode)
    (sound :
      ∀ {ℓ₁ ℓ₂ : List setup.RefinedInterface},
        List.Perm ℓ₁ ℓ₂ → externalOutCode ℓ₁ = externalOutCode ℓ₂)
    (complete :
      ∀ {ℓ₁ ℓ₂ : List setup.RefinedInterface},
        externalOutCode ℓ₁ = externalOutCode ℓ₂ → List.Perm ℓ₁ ℓ₂) :
    (ExternalOutCodeContract.mk ExternalOutCode externalOutCode sound complete).ExternalOutCode
      = ExternalOutCode :=
  rfl

@[simp] theorem ExternalOutCodeContract.mk_externalOutCode
    (ExternalOutCode : Type v)
    (externalOutCode : List setup.RefinedInterface → ExternalOutCode)
    (sound :
      ∀ {ℓ₁ ℓ₂ : List setup.RefinedInterface},
        List.Perm ℓ₁ ℓ₂ → externalOutCode ℓ₁ = externalOutCode ℓ₂)
    (complete :
      ∀ {ℓ₁ ℓ₂ : List setup.RefinedInterface},
        externalOutCode ℓ₁ = externalOutCode ℓ₂ → List.Perm ℓ₁ ℓ₂) :
    (ExternalOutCodeContract.mk ExternalOutCode externalOutCode sound complete).externalOutCode
      = externalOutCode :=
  rfl

theorem ExternalOutCodeContract.code_eq_of_perm
    (E : ExternalOutCodeContract.{u, v} setup)
    {ℓ₁ ℓ₂ : List setup.RefinedInterface}
    (h : List.Perm ℓ₁ ℓ₂) :
    E.externalOutCode ℓ₁ = E.externalOutCode ℓ₂ :=
  E.sound h

theorem ExternalOutCodeContract.perm_of_code_eq
    (E : ExternalOutCodeContract.{u, v} setup)
    {ℓ₁ ℓ₂ : List setup.RefinedInterface}
    (h : E.externalOutCode ℓ₁ = E.externalOutCode ℓ₂) :
    List.Perm ℓ₁ ℓ₂ :=
  E.complete h

theorem ExternalOutCodeContract.code_eq_iff_perm
    (E : ExternalOutCodeContract.{u, v} setup)
    {ℓ₁ ℓ₂ : List setup.RefinedInterface} :
    E.externalOutCode ℓ₁ = E.externalOutCode ℓ₂ ↔ List.Perm ℓ₁ ℓ₂ := by
  constructor
  · exact E.perm_of_code_eq
  · exact E.code_eq_of_perm

/-! ## Item 9g — Obligation interface for `BoundaryAdminEquiv` -/

/-- **`BoundaryAdminCodeContract setup`** (item 9g): an obligation
interface for canonical coding of `setup.BoundaryObject` modulo
`BoundaryAdminEquiv`.

Stated against `BoundaryAdminEquiv` because that is exactly the
relation appearing in the `Y_rel` field of
`FrontierWord.BoundaryEquiv` (item 8v). Both `sound` and `complete`
carry **real signatures**.

This contract is *not* instantiated in this file: there is no
serialization map for the opaque `setup.BoundaryObject`, and
`BoundaryAdminEquiv` (generated by `BoundaryTwoStepSwap`) does not
in general reduce to equality. Instantiation is the substantive
mathematical content of the residue-level holographic theorem. -/
structure BoundaryAdminCodeContract (setup : RewriteCalculusSetup.{u}) where
  /-- The admin-boundary code target type. -/
  AdminBoundaryCode : Type v
  /-- The admin-boundary code function. -/
  adminBoundaryCode : setup.BoundaryObject → AdminBoundaryCode
  /-- Soundness: `BoundaryAdminEquiv`-related boundaries code to the
  same value. -/
  sound :
    ∀ {Y₁ Y₂ : setup.BoundaryObject},
      BoundaryAdminEquiv Y₁ Y₂ → adminBoundaryCode Y₁ = adminBoundaryCode Y₂
  /-- **Completeness with a real signature**: equal admin-boundary
  codes imply `BoundaryAdminEquiv`. -/
  complete :
    ∀ {Y₁ Y₂ : setup.BoundaryObject},
      adminBoundaryCode Y₁ = adminBoundaryCode Y₂ → BoundaryAdminEquiv Y₁ Y₂

@[simp] theorem BoundaryAdminCodeContract.mk_AdminBoundaryCode
    (AdminBoundaryCode : Type v)
    (adminBoundaryCode : setup.BoundaryObject → AdminBoundaryCode)
    (sound :
      ∀ {Y₁ Y₂ : setup.BoundaryObject},
        BoundaryAdminEquiv Y₁ Y₂ → adminBoundaryCode Y₁ = adminBoundaryCode Y₂)
    (complete :
      ∀ {Y₁ Y₂ : setup.BoundaryObject},
        adminBoundaryCode Y₁ = adminBoundaryCode Y₂ → BoundaryAdminEquiv Y₁ Y₂) :
    (BoundaryAdminCodeContract.mk AdminBoundaryCode adminBoundaryCode sound complete).AdminBoundaryCode
      = AdminBoundaryCode :=
  rfl

@[simp] theorem BoundaryAdminCodeContract.mk_adminBoundaryCode
    (AdminBoundaryCode : Type v)
    (adminBoundaryCode : setup.BoundaryObject → AdminBoundaryCode)
    (sound :
      ∀ {Y₁ Y₂ : setup.BoundaryObject},
        BoundaryAdminEquiv Y₁ Y₂ → adminBoundaryCode Y₁ = adminBoundaryCode Y₂)
    (complete :
      ∀ {Y₁ Y₂ : setup.BoundaryObject},
        adminBoundaryCode Y₁ = adminBoundaryCode Y₂ → BoundaryAdminEquiv Y₁ Y₂) :
    (BoundaryAdminCodeContract.mk AdminBoundaryCode adminBoundaryCode sound complete).adminBoundaryCode
      = adminBoundaryCode :=
  rfl

theorem BoundaryAdminCodeContract.code_eq_of_equiv
    (A : BoundaryAdminCodeContract.{u, v} setup)
    {Y₁ Y₂ : setup.BoundaryObject}
    (h : BoundaryAdminEquiv Y₁ Y₂) :
    A.adminBoundaryCode Y₁ = A.adminBoundaryCode Y₂ :=
  A.sound h

theorem BoundaryAdminCodeContract.equiv_of_code_eq
    (A : BoundaryAdminCodeContract.{u, v} setup)
    {Y₁ Y₂ : setup.BoundaryObject}
    (h : A.adminBoundaryCode Y₁ = A.adminBoundaryCode Y₂) :
    BoundaryAdminEquiv Y₁ Y₂ :=
  A.complete h

theorem BoundaryAdminCodeContract.code_eq_iff_equiv
    (A : BoundaryAdminCodeContract.{u, v} setup)
    {Y₁ Y₂ : setup.BoundaryObject} :
    A.adminBoundaryCode Y₁ = A.adminBoundaryCode Y₂ ↔ BoundaryAdminEquiv Y₁ Y₂ := by
  constructor
  · exact A.equiv_of_code_eq
  · exact A.code_eq_of_equiv

/-! ## Item 9h — Assemble `BoundaryCodeContract` from subcontracts -/

/-- **Item 9h**: an admin-boundary code contract and an
external-output code contract together assemble into a
`BoundaryCodeContract` for `FrontierWord.BoundaryEquiv` (item 8x).

The boundary-code target is the product
`AdminBoundaryCode × ExternalOutCode`. The proof structure exactly
mirrors the interior-side assembly (item 8y) and the
component-codes assembly (item 8y, top-level):

* `sound`: project a `BoundaryEquiv` into `Y_rel` and
  `externalOut_perm`, then apply per-component soundness and
  package via `Prod.mk.injEq`.
* `complete`: project the product equality via
  `congrArg Prod.fst/snd`, then apply per-component completeness
  to obtain `Y_rel` and `externalOut_perm`, then reassemble. -/
def boundary_component_codes_to_contract
    (A : BoundaryAdminCodeContract.{u, v} setup)
    (E : ExternalOutCodeContract.{u, v} setup) :
    BoundaryCodeContract.{u, v} setup where
  BoundaryCode := A.AdminBoundaryCode × E.ExternalOutCode
  boundaryCode w :=
    (A.adminBoundaryCode w.residue.Y,
      E.externalOutCode w.residue.ports.externalOut)
  sound h := by
    exact Prod.mk.injEq .. |>.mpr ⟨A.sound h.Y_rel, E.sound h.externalOut_perm⟩
  complete h := by
    have hY : A.adminBoundaryCode _ = A.adminBoundaryCode _ :=
      congrArg Prod.fst h
    have hO : E.externalOutCode _ = E.externalOutCode _ :=
      congrArg Prod.snd h
    exact { Y_rel := A.complete hY, externalOut_perm := E.complete hO }

@[simp] theorem boundary_component_codes_to_contract_BoundaryCode
    (A : BoundaryAdminCodeContract.{u, v} setup)
    (E : ExternalOutCodeContract.{u, v} setup) :
    (boundary_component_codes_to_contract A E).BoundaryCode =
      (A.AdminBoundaryCode × E.ExternalOutCode) :=
  rfl

/-- **Audit theorem (9h.b)**: the boundary-component-codes
assembly's `boundaryCode` is the obvious pair. -/
@[simp] theorem boundary_component_codes_to_contract_boundaryCode
    (A : BoundaryAdminCodeContract.{u, v} setup)
    (E : ExternalOutCodeContract.{u, v} setup)
    (w : FrontierWord setup) :
    (boundary_component_codes_to_contract A E).boundaryCode w
      = (A.adminBoundaryCode w.residue.Y,
          E.externalOutCode w.residue.ports.externalOut) :=
  rfl

theorem boundary_component_codes_to_contract_code_eq_of_boundaryEquiv
    (A : BoundaryAdminCodeContract.{u, v} setup)
    (E : ExternalOutCodeContract.{u, v} setup)
    {w₁ w₂ : FrontierWord setup}
    (h : FrontierWord.BoundaryEquiv w₁ w₂) :
    (boundary_component_codes_to_contract A E).boundaryCode w₁ =
      (boundary_component_codes_to_contract A E).boundaryCode w₂ :=
  (boundary_component_codes_to_contract A E).sound h

theorem boundary_component_codes_to_contract_boundaryEquiv_of_code_eq
    (A : BoundaryAdminCodeContract.{u, v} setup)
    (E : ExternalOutCodeContract.{u, v} setup)
    {w₁ w₂ : FrontierWord setup}
    (h : (boundary_component_codes_to_contract A E).boundaryCode w₁ =
      (boundary_component_codes_to_contract A E).boundaryCode w₂) :
    FrontierWord.BoundaryEquiv w₁ w₂ :=
  (boundary_component_codes_to_contract A E).complete h

theorem boundary_component_codes_to_contract_boundaryCode_eq_iff_equiv
    (A : BoundaryAdminCodeContract.{u, v} setup)
    (E : ExternalOutCodeContract.{u, v} setup)
    {w₁ w₂ : FrontierWord setup} :
    (boundary_component_codes_to_contract A E).boundaryCode w₁ =
        (boundary_component_codes_to_contract A E).boundaryCode w₂ ↔
      FrontierWord.BoundaryEquiv w₁ w₂ := by
  constructor
  · exact boundary_component_codes_to_contract_boundaryEquiv_of_code_eq A E
  · exact boundary_component_codes_to_contract_code_eq_of_boundaryEquiv A E

/-! ## Item 9i — Manuscript-facing aliases and full quotient assembly -/

/-- **Manuscript alias (9i.a)**: the admin-boundary code contract
is an obligation. -/
def theorem_boundary_admin_code_contract_obligation
    (setup : RewriteCalculusSetup.{u}) :
    Type _ :=
  BoundaryAdminCodeContract.{u, v} setup

/-- **Manuscript alias (9i.b)**: the external-output code contract
is an obligation. -/
def theorem_external_out_perm_code_contract_obligation
    (setup : RewriteCalculusSetup.{u}) :
    Type _ :=
  ExternalOutCodeContract.{u, v} setup

/-- **Manuscript alias (9i.c)**: a boundary-admin code contract and
an external-output code contract together give a boundary-side
code contract for `FrontierWord.BoundaryEquiv`. -/
def theorem_boundary_component_codes_give_boundary_code_contract
    (A : BoundaryAdminCodeContract.{u, v} setup)
    (E : ExternalOutCodeContract.{u, v} setup) :
    BoundaryCodeContract.{u, v} setup :=
  boundary_component_codes_to_contract A E

/-- **Manuscript alias (9i.d)**: with both boundary subcontracts
and the *constructed* interior contract from item 9d, the full
faithful `FrontierQuotientRealization` is assembled.

This isolates the *entire remaining mathematical content* of the
residue-level holographic theorem into the two named obligations
`BoundaryAdminCodeContract` (item 9g) and `ExternalOutCodeContract`
(item 9f). -/
def theorem_full_quotient_realization_modulo_boundary_obligations
    (A : BoundaryAdminCodeContract.{u, u} setup)
    (E : ExternalOutCodeContract.{u, u} setup) :
    FrontierQuotientRealization.{u, u} setup :=
  component_codes_to_quotient_realization
    (boundary_component_codes_to_contract A E)
    interiorCanonicalContract

/-- **Manuscript alias (9i.e — stop report)**: a *type-level*
record of the audit conclusion. The current obstacle to a
fully-constructed `FrontierQuotientRealization` is the absence of
canonical serialization for `BoundaryAdminEquiv` and `List.Perm`
on `RefinedInterface`. -/
def theorem_residue_quotient_realization_blocked_only_on_boundary_obligations :
    True :=
  trivial

/-! ## Item 9j — `BoundaryCodeContract` iff surface for BoundaryTraceClass -/

/-- Iff form combining sound and complete for any `BoundaryCodeContract`. -/
theorem BoundaryCodeContract.code_eq_iff_boundaryEquiv
    (B : BoundaryCodeContract.{u, v} setup)
    {w₁ w₂ : FrontierWord setup} :
    B.boundaryCode w₁ = B.boundaryCode w₂ ↔ FrontierWord.BoundaryEquiv w₁ w₂ :=
  ⟨B.complete, B.sound⟩

/-- Soundness alias for `BoundaryCodeContract`. -/
theorem BoundaryCodeContract.sound_apply
    (B : BoundaryCodeContract.{u, v} setup)
    {w₁ w₂ : FrontierWord setup}
    (h : FrontierWord.BoundaryEquiv w₁ w₂) :
    B.boundaryCode w₁ = B.boundaryCode w₂ :=
  B.sound h

/-- Completeness alias for `BoundaryCodeContract`. -/
theorem BoundaryCodeContract.complete_apply
    (B : BoundaryCodeContract.{u, v} setup)
    {w₁ w₂ : FrontierWord setup}
    (h : B.boundaryCode w₁ = B.boundaryCode w₂) :
    FrontierWord.BoundaryEquiv w₁ w₂ :=
  B.complete h

end RewriteCalculusSetup

end RealObjects
end LayerB
end TraceCalc
