import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Presheaves.Representables.Subcategory.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Owner

/-!
# Compact geometric analytic generators

This file owns the concrete generator objects available before forming any
stable or triangulated closure: a certified trace object, its representable
trace presheaf, and its object in the formal localized word category.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A compact geometric analytic generator is a certified trace object. -/
structure TraceAnalyticGeometricGenerator where
  traceObject : TraceCorQObject

/-- Build a compact geometric analytic generator from a trace object. -/
def TraceAnalyticGeometricGenerator.ofTraceObject
    (object : TraceCorQObject) :
    TraceAnalyticGeometricGenerator where
  traceObject := object

/-- The representable trace presheaf generated by a compact geometric analytic generator. -/
def TraceAnalyticGeometricGenerator.presheaf
    (generator : TraceAnalyticGeometricGenerator) :
    TraceCorQPresheaf :=
  TraceCorQPresheaf.representable generator.traceObject

/-- The lifted representable-subcategory object generated by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.representableObject
    (generator : TraceAnalyticGeometricGenerator) :
    TraceCorQRepresentablePresheaf :=
  (TraceCorQRepresentablePresheaf.yoneda).obj generator.traceObject

/-- The localized-word object generated by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.localizedObject
    (generator : TraceAnalyticGeometricGenerator) :
    TraceLocalizedWordObject :=
  TraceLocalizedWordObject.ofTraceObject generator.traceObject

/-- Constructing a generator from a trace object remembers that trace object. -/
theorem TraceAnalyticGeometricGenerator.ofTraceObject_traceObject
    (object : TraceCorQObject) :
    (TraceAnalyticGeometricGenerator.ofTraceObject object).traceObject =
      object :=
  rfl

/-- The generator presheaf is the representable presheaf of its trace object. -/
theorem TraceAnalyticGeometricGenerator.presheaf_eq_representable
    (generator : TraceAnalyticGeometricGenerator) :
    generator.presheaf =
      TraceCorQPresheaf.representable generator.traceObject :=
  rfl

/-- The representable-subcategory object has the generator presheaf as ambient presheaf. -/
theorem TraceAnalyticGeometricGenerator.representableObject_presheaf
    (generator : TraceAnalyticGeometricGenerator) :
    generator.representableObject.presheaf =
      generator.presheaf :=
  rfl

/-- The representable-subcategory object is the lifted Yoneda object of the trace object. -/
theorem TraceAnalyticGeometricGenerator.representableObject_eq_yoneda
    (generator : TraceAnalyticGeometricGenerator) :
    generator.representableObject =
      (TraceCorQRepresentablePresheaf.yoneda).obj generator.traceObject :=
  rfl

/-- The localized object has the generator trace object as underlying trace object. -/
theorem TraceAnalyticGeometricGenerator.localizedObject_underlying
    (generator : TraceAnalyticGeometricGenerator) :
    generator.localizedObject.underlying =
      generator.traceObject :=
  rfl

/-- The localized object is the wrapped trace object of the generator. -/
theorem TraceAnalyticGeometricGenerator.localizedObject_eq_ofTraceObject
    (generator : TraceAnalyticGeometricGenerator) :
    generator.localizedObject =
      TraceLocalizedWordObject.ofTraceObject generator.traceObject :=
  rfl

/-- The source expression carried by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.source
    (generator : TraceAnalyticGeometricGenerator) :
    QTraceExpression :=
  generator.traceObject.source

/-- The certificate ledger carried by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.certificateLedger
    (generator : TraceAnalyticGeometricGenerator) :
    ResidueChannelCertificateLedger :=
  generator.traceObject.certificateLedger

/-- The imported finite-rectangle count carried by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.importedRectangleCount
    (generator : TraceAnalyticGeometricGenerator) :
    Nat :=
  generator.traceObject.importedRectangleCount

/-- The imported finite explicit-formula rectangles carried by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.importedRectangles
    (generator : TraceAnalyticGeometricGenerator) :
    List ZetaAdmissibleFunction.ExplicitFormulaRectangle :=
  generator.traceObject.importedRectangles

/-- The trace-bookkeeping count carried by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.traceBookkeepingCount
    (generator : TraceAnalyticGeometricGenerator) :
    Nat :=
  generator.traceObject.traceBookkeepingCount

/-- The rewrite-step count carried by a compact analytic generator. -/
def TraceAnalyticGeometricGenerator.rewriteStepCount
    (generator : TraceAnalyticGeometricGenerator) :
    Nat :=
  generator.traceObject.rewriteStepCount

/-- Generator certificates are the certificates of the underlying trace object. -/
theorem TraceAnalyticGeometricGenerator.certificateLedger_eq_traceObject
    (generator : TraceAnalyticGeometricGenerator) :
    generator.certificateLedger =
      generator.traceObject.certificateLedger :=
  rfl

/-- Generator imported rectangle count is inherited from the underlying trace object. -/
theorem TraceAnalyticGeometricGenerator.importedRectangleCount_eq_traceObject
    (generator : TraceAnalyticGeometricGenerator) :
    generator.importedRectangleCount =
      generator.traceObject.importedRectangleCount :=
  rfl

/-- Generator imported rectangles are inherited from the underlying trace object. -/
theorem TraceAnalyticGeometricGenerator.importedRectangles_eq_traceObject
    (generator : TraceAnalyticGeometricGenerator) :
    generator.importedRectangles =
      generator.traceObject.importedRectangles :=
  rfl

/-- Generator trace-bookkeeping count is inherited from the underlying trace object. -/
theorem TraceAnalyticGeometricGenerator.traceBookkeepingCount_eq_traceObject
    (generator : TraceAnalyticGeometricGenerator) :
    generator.traceBookkeepingCount =
      generator.traceObject.traceBookkeepingCount :=
  rfl

/-- Generator rewrite-step count is inherited from the underlying trace object. -/
theorem TraceAnalyticGeometricGenerator.rewriteStepCount_eq_traceObject
    (generator : TraceAnalyticGeometricGenerator) :
    generator.rewriteStepCount =
      generator.traceObject.rewriteStepCount :=
  rfl

/-- Generator imported rectangle count is counted by its certificate ledger. -/
theorem TraceAnalyticGeometricGenerator.importedRectangleCount_eq_certificateLedger
    (generator : TraceAnalyticGeometricGenerator) :
    generator.importedRectangleCount =
      generator.certificateLedger.importedRectangleCount :=
  TraceCorQObject.importedRectangleCount_eq_certificateLedger_count
    generator.traceObject

/-- Generator imported rectangles are extracted from its certificate ledger. -/
theorem TraceAnalyticGeometricGenerator.importedRectangles_eq_certificateLedger
    (generator : TraceAnalyticGeometricGenerator) :
    generator.importedRectangles =
      generator.certificateLedger.importedRectangles :=
  TraceCorQObject.importedRectangles_eq_certificateLedger_rectangles
    generator.traceObject

/-- Generator imported rectangle count is the length of its rectangle list. -/
theorem TraceAnalyticGeometricGenerator.importedRectangleCount_eq_length_importedRectangles
    (generator : TraceAnalyticGeometricGenerator) :
    generator.importedRectangleCount =
      generator.importedRectangles.length :=
  TraceCorQObject.importedRectangleCount_eq_length_importedRectangles
    generator.traceObject

/-- Generator trace-bookkeeping count is counted by its certificate ledger. -/
theorem TraceAnalyticGeometricGenerator.traceBookkeepingCount_eq_certificateLedger
    (generator : TraceAnalyticGeometricGenerator) :
    generator.traceBookkeepingCount =
      generator.certificateLedger.traceBookkeepingCount :=
  TraceCorQObject.traceBookkeepingCount_eq_certificateLedger_count
    generator.traceObject

/-- Generator rewrite-step count is counted by its certificate ledger. -/
theorem TraceAnalyticGeometricGenerator.rewriteStepCount_eq_certificateLedger
    (generator : TraceAnalyticGeometricGenerator) :
    generator.rewriteStepCount =
      generator.certificateLedger.rewriteStepCount :=
  TraceCorQObject.rewriteStepCount_eq_certificateLedger_count
    generator.traceObject

end AnalyticMotives
end LFunctions
end Boundary
