import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.ThirdIsoBounded.ShortComplex.Vertices.Owner

/-!
# Short complexes of localization-input bounded mapping-cone triangles

This file specializes the full bounded mapping-cone short complex to the
concrete bounded maps generated by localization inputs.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- The short complex attached to the localization-input bounded mapping-cone triangle. -/
def TraceLocalizationInput.boundedMappingConeShortComplex
    (input : TraceLocalizationInput) :
    ShortComplex TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_shortComplex
    input.boundedAdditiveComplexHom

/-- The localization-input bounded mapping-cone short complex has the source object as
its left vertex. -/
theorem TraceLocalizationInput.boundedMappingConeShortComplex_X₁
    (input : TraceLocalizationInput) :
    input.boundedMappingConeShortComplex.X₁ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_shortComplex_leftVertex
    input.boundedAdditiveComplexHom

/-- The localization-input bounded mapping-cone short complex has the target object as
its middle vertex. -/
theorem TraceLocalizationInput.boundedMappingConeShortComplex_X₂
    (input : TraceLocalizationInput) :
    input.boundedMappingConeShortComplex.X₂ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_shortComplex_middleVertex
    input.boundedAdditiveComplexHom

/-- The localization-input bounded mapping-cone short complex has the cone object as its
right vertex. -/
theorem TraceLocalizationInput.boundedMappingConeShortComplex_X₃
    (input : TraceLocalizationInput) :
    input.boundedMappingConeShortComplex.X₃ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_shortComplex_rightVertex
    input.boundedAdditiveComplexHom

/-- The first morphism of the localization-input bounded mapping-cone short complex is
the bounded map. -/
theorem TraceLocalizationInput.boundedMappingConeShortComplex_f
    (input : TraceLocalizationInput) :
    input.boundedMappingConeShortComplex.f =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_shortComplex_firstMap
    input.boundedAdditiveComplexHom

/-- The second morphism of the localization-input bounded mapping-cone short complex is
the cone-inclusion map. -/
theorem TraceLocalizationInput.boundedMappingConeShortComplex_g
    (input : TraceLocalizationInput) :
    input.boundedMappingConeShortComplex.g =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondMap
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_shortComplex_secondMap
    input.boundedAdditiveComplexHom

/-- The localization-input bounded mapping-cone short complex has zero composite. -/
theorem TraceLocalizationInput.boundedMappingConeShortComplex_zero
    (input : TraceLocalizationInput) :
    input.boundedMappingConeShortComplex.f ≫
        input.boundedMappingConeShortComplex.g =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_shortComplex_zero
    input.boundedAdditiveComplexHom

end AnalyticMotives
end LFunctions
end Boundary
