import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Descent.Localization.Owner

/-!
# Descent calculus localization inventory
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized isomorphism generated by channel descent. -/
def TraceCalculusLocalization.descentChannelIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentChannel source target).localizedSourceObject
      (TraceLocalizationInput.descentChannel source target).localizedTargetObject :=
  TraceDescentLocalization.channelIso source target

/-- The localized isomorphism generated by refinement descent. -/
def TraceCalculusLocalization.descentRefinementIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentRefinement source target).localizedSourceObject
      (TraceLocalizationInput.descentRefinement source target).localizedTargetObject :=
  TraceDescentLocalization.refinementIso source target

/-- The localized isomorphism generated by schedule descent. -/
def TraceCalculusLocalization.descentScheduleIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentSchedule source target).localizedSourceObject
      (TraceLocalizationInput.descentSchedule source target).localizedTargetObject :=
  TraceDescentLocalization.scheduleIso source target

/-- Channel descent in the calculus inventory is the descent-localization isomorphism. -/
theorem TraceCalculusLocalization.descentChannelIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.descentChannelIso source target =
      TraceDescentLocalization.channelIso source target :=
  rfl

/-- Channel descent in the calculus inventory has the descent-channel forward arrow as hom. -/
theorem TraceCalculusLocalization.descentChannelIso_hom
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentChannelIso source target).hom =
      TraceLocalizationInput.descentChannelForwardArrow source target :=
  rfl

/-- Channel descent in the calculus inventory has the descent-channel inverse arrow as inverse. -/
theorem TraceCalculusLocalization.descentChannelIso_inv
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentChannelIso source target).inv =
      TraceLocalizationInput.descentChannelInverseArrow source target :=
  rfl

/-- Refinement descent in the calculus inventory is the descent-localization isomorphism. -/
theorem TraceCalculusLocalization.descentRefinementIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.descentRefinementIso source target =
      TraceDescentLocalization.refinementIso source target :=
  rfl

/-- Refinement descent in the calculus inventory has the refinement forward arrow as hom. -/
theorem TraceCalculusLocalization.descentRefinementIso_hom
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentRefinementIso source target).hom =
      TraceLocalizationInput.descentRefinementForwardArrow source target :=
  rfl

/-- Refinement descent in the calculus inventory has the refinement inverse arrow as inverse. -/
theorem TraceCalculusLocalization.descentRefinementIso_inv
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentRefinementIso source target).inv =
      TraceLocalizationInput.descentRefinementInverseArrow source target :=
  rfl

/-- Schedule descent in the calculus inventory is the descent-localization isomorphism. -/
theorem TraceCalculusLocalization.descentScheduleIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.descentScheduleIso source target =
      TraceDescentLocalization.scheduleIso source target :=
  rfl

/-- Schedule descent in the calculus inventory has the schedule forward arrow as hom. -/
theorem TraceCalculusLocalization.descentScheduleIso_hom
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentScheduleIso source target).hom =
      TraceLocalizationInput.descentScheduleForwardArrow source target :=
  rfl

/-- Schedule descent in the calculus inventory has the schedule inverse arrow as inverse. -/
theorem TraceCalculusLocalization.descentScheduleIso_inv
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentScheduleIso source target).inv =
      TraceLocalizationInput.descentScheduleInverseArrow source target :=
  rfl

/-- Channel descent hom followed by inverse is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentChannelIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.descentChannelIso source target).hom
        (TraceCalculusLocalization.descentChannelIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentChannel source target).sourceObject :=
  TraceDescentLocalization.channelIso_hom_comp_inv
    source
    target

/-- Channel descent inverse followed by hom is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentChannelIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.descentChannelIso source target).inv
        (TraceCalculusLocalization.descentChannelIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentChannel source target).targetObject :=
  TraceDescentLocalization.channelIso_inv_comp_hom
    source
    target

/-- Channel descent hom followed by inverse is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentChannelIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentChannelIso source target).hom ≫
        (TraceCalculusLocalization.descentChannelIso source target).inv =
      (𝟙 (TraceLocalizationInput.descentChannel source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentChannel source target).localizedSourceObject
          (TraceLocalizationInput.descentChannel source target).localizedSourceObject) :=
  TraceDescentLocalization.channelIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Channel descent inverse followed by hom is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentChannelIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentChannelIso source target).inv ≫
        (TraceCalculusLocalization.descentChannelIso source target).hom =
      (𝟙 (TraceLocalizationInput.descentChannel source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentChannel source target).localizedTargetObject
          (TraceLocalizationInput.descentChannel source target).localizedTargetObject) :=
  TraceDescentLocalization.channelIso_inv_comp_hom_eq_categoryIdentity
    source
    target

/-- Refinement descent hom followed by inverse is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentRefinementIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.descentRefinementIso source target).hom
        (TraceCalculusLocalization.descentRefinementIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentRefinement source target).sourceObject :=
  TraceDescentLocalization.refinementIso_hom_comp_inv
    source
    target

/-- Refinement descent inverse followed by hom is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentRefinementIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.descentRefinementIso source target).inv
        (TraceCalculusLocalization.descentRefinementIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentRefinement source target).targetObject :=
  TraceDescentLocalization.refinementIso_inv_comp_hom
    source
    target

/-- Refinement descent hom followed by inverse is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentRefinementIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentRefinementIso source target).hom ≫
        (TraceCalculusLocalization.descentRefinementIso source target).inv =
      (𝟙 (TraceLocalizationInput.descentRefinement source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentRefinement source target).localizedSourceObject
          (TraceLocalizationInput.descentRefinement source target).localizedSourceObject) :=
  TraceDescentLocalization.refinementIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Refinement descent inverse followed by hom is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentRefinementIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentRefinementIso source target).inv ≫
        (TraceCalculusLocalization.descentRefinementIso source target).hom =
      (𝟙 (TraceLocalizationInput.descentRefinement source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentRefinement source target).localizedTargetObject
          (TraceLocalizationInput.descentRefinement source target).localizedTargetObject) :=
  TraceDescentLocalization.refinementIso_inv_comp_hom_eq_categoryIdentity
    source
    target

/-- Schedule descent hom followed by inverse is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentScheduleIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.descentScheduleIso source target).hom
        (TraceCalculusLocalization.descentScheduleIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentSchedule source target).sourceObject :=
  TraceDescentLocalization.scheduleIso_hom_comp_inv
    source
    target

/-- Schedule descent inverse followed by hom is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentScheduleIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.descentScheduleIso source target).inv
        (TraceCalculusLocalization.descentScheduleIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentSchedule source target).targetObject :=
  TraceDescentLocalization.scheduleIso_inv_comp_hom
    source
    target

/-- Schedule descent hom followed by inverse is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentScheduleIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentScheduleIso source target).hom ≫
        (TraceCalculusLocalization.descentScheduleIso source target).inv =
      (𝟙 (TraceLocalizationInput.descentSchedule source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentSchedule source target).localizedSourceObject
          (TraceLocalizationInput.descentSchedule source target).localizedSourceObject) :=
  TraceDescentLocalization.scheduleIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Schedule descent inverse followed by hom is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.descentScheduleIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.descentScheduleIso source target).inv ≫
        (TraceCalculusLocalization.descentScheduleIso source target).hom =
      (𝟙 (TraceLocalizationInput.descentSchedule source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentSchedule source target).localizedTargetObject
          (TraceLocalizationInput.descentSchedule source target).localizedTargetObject) :=
  TraceDescentLocalization.scheduleIso_inv_comp_hom_eq_categoryIdentity
    source
    target

end AnalyticMotives
end LFunctions
end Boundary
