import Boundary.Cycles.Divisors

/-!
# Rational equivalence of cycles

This file records the standard Fulton-style rational-equivalence subgroup:
it is generated by principal divisor cycles on integral support atoms.

The intended classical reference is Fulton, *Intersection Theory*, §1.3 and
§1.4, together with Hartshorne, *Algebraic Geometry*, Ch. I, §6 for the
divisor picture on integral subschemes.
-/

universe u

open AlgebraicGeometry

namespace Boundary
namespace Cycles

noncomputable section

/-- The subgroup of algebraic cycles generated by principal divisor cycles on
integral support atoms. This is the standard rational-equivalence relation
subgroup in the Chow-group construction. -/
def RationalEquivalenceSubmodule (X : Scheme.{u}) :
    Submodule ℤ (AlgCycle X) :=
  Submodule.span ℤ (Set.range (fun D : PrincipalDivisorGenerator X => D.toCycle))

/-- A principal divisor cycle lies in the rational-equivalence subgroup by
construction. -/
theorem principalDivisorGenerator_mem_rationalEquivalenceSubmodule
    {X : Scheme.{u}} (D : PrincipalDivisorGenerator X) :
    D.toCycle ∈ RationalEquivalenceSubmodule X := by
  exact Submodule.subset_span ⟨D, rfl⟩

/-- The additive subgroup underlying rational equivalence. -/
abbrev RationalEquivalenceAddSubgroup (X : Scheme.{u}) :
    AddSubgroup (AlgCycle X) :=
  (RationalEquivalenceSubmodule X).toAddSubgroup

/-- Two cycles are rationally equivalent if they differ by an element of the
principal-divisor-generated subgroup. -/
def RationallyEquivalent {X : Scheme.{u}} (c d : AlgCycle X) : Prop :=
  c - d ∈ RationalEquivalenceAddSubgroup X

/-- Rational equivalence as a setoid on algebraic cycles. -/
def rationalEquivalenceSetoid (X : Scheme.{u}) : Setoid (AlgCycle X) where
  r := RationallyEquivalent
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro c
      exact rationallyEquivalent_refl c
    · intro c d
      exact rationallyEquivalent_symm
    · intro c d e
      exact rationallyEquivalent_trans

@[simp] theorem rationallyEquivalent_refl {X : Scheme.{u}} (c : AlgCycle X) :
    RationallyEquivalent c c := by
  change 0 ∈ RationalEquivalenceAddSubgroup X
  exact zero_mem _

@[simp] theorem rationallyEquivalent_symm {X : Scheme.{u}}
    {c d : AlgCycle X} :
    RationallyEquivalent c d → RationallyEquivalent d c := by
  intro h
  change -(c - d) ∈ RationalEquivalenceAddSubgroup X
  exact AddSubgroup.neg_mem (RationalEquivalenceAddSubgroup X) h

@[simp] theorem rationallyEquivalent_trans {X : Scheme.{u}}
    {c d e : AlgCycle X} :
    RationallyEquivalent c d → RationallyEquivalent d e →
      RationallyEquivalent c e := by
  intro hcd hde
  have hsum : (c - d) + (d - e) ∈ RationalEquivalenceAddSubgroup X :=
    AddSubgroup.add_mem (RationalEquivalenceAddSubgroup X) hcd hde
  have hrewrite : c - e = (c - d) + (d - e) := by
    calc
      c - e = c + (-e) := by
        rw [sub_eq_add_neg]
      _ = c + (-d + (d + -e)) := by
        rw [← neg_add_cancel_left d (-e)]
      _ = (c + -d) + (d + -e) := by
        rw [add_assoc]
      _ = (c - d) + (d - e) := by
        rw [sub_eq_add_neg, sub_eq_add_neg]
  rw [← hrewrite]
  exact hsum

end

end Cycles
end Boundary
