import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Objects.Singleton.Owner

/-!
# Localization-input objects in the analytic additive envelope

This file sends each concrete localization input to the singleton additive
objects generated by its certified source and target trace presentations.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The additive-envelope source object generated by a localization input. -/
def TraceLocalizationInput.additiveSourceObject
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveObject :=
  TraceAnalyticAdditiveObject.singleton input.sourceObject

/-- The additive-envelope target object generated by a localization input. -/
def TraceLocalizationInput.additiveTargetObject
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveObject :=
  TraceAnalyticAdditiveObject.singleton input.targetObject

/-- The additive source object of a localization input has one component. -/
theorem TraceLocalizationInput.additiveSourceObject_length
    (input : TraceLocalizationInput) :
    input.additiveSourceObject.length =
      1 :=
  TraceAnalyticAdditiveObject.singleton_length
    input.sourceObject

/-- The additive target object of a localization input has one component. -/
theorem TraceLocalizationInput.additiveTargetObject_length
    (input : TraceLocalizationInput) :
    input.additiveTargetObject.length =
      1 :=
  TraceAnalyticAdditiveObject.singleton_length
    input.targetObject

/-- The zero-index component of the additive source object is the certified source object. -/
theorem TraceLocalizationInput.additiveSourceObject_component_zero
    (input : TraceLocalizationInput) :
    input.additiveSourceObject.component 0 =
      input.sourceObject :=
  TraceAnalyticAdditiveObject.singleton_component_zero
    input.sourceObject

/-- The zero-index component of the additive target object is the certified target object. -/
theorem TraceLocalizationInput.additiveTargetObject_component_zero
    (input : TraceLocalizationInput) :
    input.additiveTargetObject.component 0 =
      input.targetObject :=
  TraceAnalyticAdditiveObject.singleton_component_zero
    input.targetObject

/-- The additive source object's zero-index component has the input source expression. -/
theorem TraceLocalizationInput.additiveSourceObject_component_zero_source
    (input : TraceLocalizationInput) :
    (input.additiveSourceObject.component 0).source =
      input.sourceExpression :=
  Eq.trans
    (congrArg
      TraceCorQObject.source
      (TraceLocalizationInput.additiveSourceObject_component_zero input))
    (TraceLocalizationInput.sourceObject_source input)

/-- The additive target object's zero-index component has the input target expression. -/
theorem TraceLocalizationInput.additiveTargetObject_component_zero_source
    (input : TraceLocalizationInput) :
    (input.additiveTargetObject.component 0).source =
      input.targetExpression :=
  Eq.trans
    (congrArg
      TraceCorQObject.source
      (TraceLocalizationInput.additiveTargetObject_component_zero input))
    (TraceLocalizationInput.targetObject_source input)

/-- The additive source object's weight is the maximum of the certified source-object
weight and zero. -/
theorem TraceLocalizationInput.additiveSourceObject_weightLevel
    (input : TraceLocalizationInput) :
    input.additiveSourceObject.weightLevel =
      Nat.max input.sourceObject.weightLevel 0 :=
  TraceAnalyticAdditiveObject.singleton_weightLevel
    input.sourceObject

/-- The additive target object's weight is the maximum of the certified target-object
weight and zero. -/
theorem TraceLocalizationInput.additiveTargetObject_weightLevel
    (input : TraceLocalizationInput) :
    input.additiveTargetObject.weightLevel =
      Nat.max input.targetObject.weightLevel 0 :=
  TraceAnalyticAdditiveObject.singleton_weightLevel
    input.targetObject

end AnalyticMotives
end LFunctions
end Boundary
