import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.CalculusLocalization.Interval.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.TateStabilization.Localization.Owner

/-!
# Tate calculus localization inventory
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized isomorphism generated by Tate weight-drop. -/
def TraceCalculusLocalization.tateWeightDropIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject
      (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject :=
  TraceTateStabilizationLocalization.weightDropIso source target

/-- Tate weight-drop in the calculus inventory is the Tate-localization isomorphism. -/
theorem TraceCalculusLocalization.tateWeightDropIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.tateWeightDropIso source target =
      TraceTateStabilizationLocalization.weightDropIso source target :=
  rfl

/-- Tate weight-drop in the calculus inventory has the weight-drop forward arrow as hom. -/
theorem TraceCalculusLocalization.tateWeightDropIso_hom
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.tateWeightDropIso source target).hom =
      TraceLocalizationInput.tateWeightDropForwardArrow source target :=
  rfl

/-- Tate weight-drop in the calculus inventory has the weight-drop inverse arrow as inverse. -/
theorem TraceCalculusLocalization.tateWeightDropIso_inv
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.tateWeightDropIso source target).inv =
      TraceLocalizationInput.tateWeightDropInverseArrow source target :=
  rfl

/-- Tate weight-drop hom followed by inverse is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.tateWeightDropIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.tateWeightDropIso source target).hom
        (TraceCalculusLocalization.tateWeightDropIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.tateWeightDrop source target).sourceObject :=
  TraceTateStabilizationLocalization.weightDropIso_hom_comp_inv
    source
    target

/-- Tate weight-drop inverse followed by hom is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.tateWeightDropIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.tateWeightDropIso source target).inv
        (TraceCalculusLocalization.tateWeightDropIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.tateWeightDrop source target).targetObject :=
  TraceTateStabilizationLocalization.weightDropIso_inv_comp_hom
    source
    target

/-- Tate weight-drop hom followed by inverse is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.tateWeightDropIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.tateWeightDropIso source target).hom ≫
        (TraceCalculusLocalization.tateWeightDropIso source target).inv =
      (𝟙 (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject
          (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject) :=
  TraceTateStabilizationLocalization.weightDropIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Tate weight-drop inverse followed by hom is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.tateWeightDropIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.tateWeightDropIso source target).inv ≫
        (TraceCalculusLocalization.tateWeightDropIso source target).hom =
      (𝟙 (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject
          (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject) :=
  TraceTateStabilizationLocalization.weightDropIso_inv_comp_hom_eq_categoryIdentity
    source
    target

end AnalyticMotives
end LFunctions
end Boundary
