import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleQuotientCandidate.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Generators.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Relation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Setoid.Owner

/-!
# Zero-pole relation witness

This file records the canonical concrete relation witness generated by the
completed-zeta zero-pole residue-channel relation generator.

It is still pre-quotient data.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The support candidate for the completed-zeta zero-pole relation generator. -/
def completedZetaZeroPoleRelationSupportCandidate :
    TraceCorQQuotientCandidate :=
  TraceCorQRelationGenerator.supportCandidate
    completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator

/-- The zero-pole support candidate has the analytic chain formal sum. -/
theorem completedZetaZeroPoleRelationSupportCandidate_formalSum :
    completedZetaZeroPoleRelationSupportCandidate.formalSum =
      completedZetaZeroPoleAnalyticChainTraceCorQFormalSum :=
  rfl

/-- The zero-pole support candidate has the singleton zero-pole relation ledger. -/
theorem completedZetaZeroPoleRelationSupportCandidate_ledger :
    completedZetaZeroPoleRelationSupportCandidate.ledger =
      TraceCorQRelationLedger.singleton
        completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator :=
  rfl

/-- The zero-pole support candidate has the same input as the zero-pole quotient candidate. -/
theorem completedZetaZeroPoleRelationSupportCandidate_input_eq_quotientCandidate_input :
    completedZetaZeroPoleRelationSupportCandidate.input =
      completedZetaZeroPoleTraceCorQQuotientCandidate.input :=
  rfl

/-- The canonical support candidate is the zero-pole quotient candidate. -/
theorem completedZetaZeroPoleRelationSupportCandidate_eq_quotientCandidate :
    completedZetaZeroPoleRelationSupportCandidate =
      completedZetaZeroPoleTraceCorQQuotientCandidate :=
  rfl

/-- The canonical relation witness generated by the zero-pole relation generator. -/
def completedZetaZeroPoleRelationSupportWitness :
    TraceCorQRelationWitness
      completedZetaZeroPoleRelationSupportCandidate
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationGenerator.supportWitness
    completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator

/-- The zero-pole support witness has singleton zero-pole relation ledger. -/
theorem completedZetaZeroPoleRelationSupportWitness_ledger :
    completedZetaZeroPoleRelationSupportWitness.ledger =
      TraceCorQRelationLedger.singleton
        completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator :=
  rfl

/-- The zero-pole quotient candidate is killed by the zero-pole relation generator. -/
def completedZetaZeroPoleQuotientCandidateSupportWitness :
    TraceCorQRelationWitness
      completedZetaZeroPoleTraceCorQQuotientCandidate
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationWitness.transportEndpoints
    completedZetaZeroPoleRelationSupportCandidate_eq_quotientCandidate
    rfl
    completedZetaZeroPoleRelationSupportWitness

/-- The transported zero-pole witness keeps the singleton zero-pole ledger. -/
theorem completedZetaZeroPoleQuotientCandidateSupportWitness_ledger :
    completedZetaZeroPoleQuotientCandidateSupportWitness.ledger =
      TraceCorQRelationLedger.singleton
        completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator :=
  rfl

/-- The zero-pole quotient candidate is related to the empty candidate. -/
def completedZetaZeroPoleQuotientCandidateRelation :
    TraceCorQQuotientRelation
      completedZetaZeroPoleTraceCorQQuotientCandidate
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    completedZetaZeroPoleQuotientCandidateSupportWitness

/-- The zero-pole quotient candidate has the empty quotient class. -/
theorem completedZetaZeroPoleQuotientClass_eq_empty :
    TraceCorQQuotient.ofCandidate
        completedZetaZeroPoleTraceCorQQuotientCandidate =
      TraceCorQQuotient.ofCandidate TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound
    completedZetaZeroPoleQuotientCandidateRelation

end AnalyticMotives
end LFunctions
end Boundary
