import Mathlib.CategoryTheory.FullSubcategory
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Weights.Source.Bounds.Stable.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Shift.Representatives.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.MotivicTStructure.Aisles.Owner

/-!
# Bounded stable analytic comparison source

The representative-defined motivic aisle and coaisle calculus is generated by
bounded analytic complexes.  This file names the corresponding iso-closed
bounded stable subcategory of the analytic comparison source and proves that
the concrete aisle and coaisle predicates land in it.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

namespace TraceAnalyticDMgmComparisonSource

/-- Concrete bounded stable comparison-source representatives. -/
def boundedStableRepresentative
    (object : TraceAnalyticDMgmComparisonSource) :
    Prop :=
  ∃ (bound : Nat),
    ∃ (complex :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound),
      object =
        TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject complex

/-- The iso-closed bounded stable analytic comparison-source predicate. -/
abbrev boundedStableObject :
    TraceAnalyticDMgmComparisonSource → Prop :=
  CategoryTheory.isoClosure
    TraceAnalyticDMgmComparisonSource.boundedStableRepresentative

/-- The full subcategory of bounded stable analytic comparison-source objects. -/
abbrev BoundedStable :=
  CategoryTheory.FullSubcategory
    TraceAnalyticDMgmComparisonSource.boundedStableObject

/-- The ambient stable object carried by a bounded stable source object. -/
def BoundedStable.object
    (object : TraceAnalyticDMgmComparisonSource.BoundedStable) :
    TraceAnalyticDMgmComparisonSource :=
  object.obj

/-- The bounded-source membership carried by a bounded stable source object. -/
def BoundedStable.membership
    (object : TraceAnalyticDMgmComparisonSource.BoundedStable) :
    TraceAnalyticDMgmComparisonSource.boundedStableObject object.object :=
  object.property

/-- The inclusion of bounded stable source objects into the stable analytic
comparison source. -/
abbrev BoundedStable.inclusion :
    TraceAnalyticDMgmComparisonSource.BoundedStable ⥤
      TraceAnalyticDMgmComparisonSource :=
  CategoryTheory.fullSubcategoryInclusion
    TraceAnalyticDMgmComparisonSource.boundedStableObject

/-- The inclusion sends a bounded stable source object to its ambient object. -/
theorem BoundedStable.inclusion_obj
    (object : TraceAnalyticDMgmComparisonSource.BoundedStable) :
    TraceAnalyticDMgmComparisonSource.BoundedStable.inclusion.obj object =
      object.object :=
  rfl

/-- A stable object represented by a bounded analytic complex is a concrete
bounded stable representative. -/
theorem boundedStableRepresentative_of_sourceStableWeightBoundedObject
    {bound : Nat}
    (complex :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound) :
    TraceAnalyticDMgmComparisonSource.boundedStableRepresentative
      (TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject
        complex) :=
  Exists.intro
    bound
    (Exists.intro
      complex
      rfl)

/-- A stable object represented by a bounded analytic complex belongs to the
iso-closed bounded stable source. -/
theorem boundedStableObject_of_sourceStableWeightBoundedObject
    {bound : Nat}
    (complex :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound) :
    TraceAnalyticDMgmComparisonSource.boundedStableObject
      (TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject
        complex) :=
  CategoryTheory.le_isoClosure
    TraceAnalyticDMgmComparisonSource.boundedStableRepresentative
    (TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject complex)
    (TraceAnalyticDMgmComparisonSource
      .boundedStableRepresentative_of_sourceStableWeightBoundedObject
        complex)

/-- A shifted bounded stable representative belongs to the iso-closed bounded
stable source. -/
theorem boundedStableObject_of_sourceStableShiftedWeightBoundedObject
    {bound : Nat}
    (complex :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound)
    (degree : ℤ) :
    TraceAnalyticDMgmComparisonSource.boundedStableObject
      (TraceAnalyticMotiveComparison.sourceStableShiftedWeightBoundedObject
        complex
        degree) :=
  let unshifted_mem :
      TraceAnalyticDMgmComparisonSource.boundedStableObject
        (TraceAnalyticMotiveComparison.sourceStableWeightBoundedObject
          (complex.shift degree)) :=
    TraceAnalyticDMgmComparisonSource
      .boundedStableObject_of_sourceStableWeightBoundedObject
        (complex.shift degree)
  CategoryTheory.mem_of_iso
    (P := TraceAnalyticDMgmComparisonSource.boundedStableObject)
    (TraceAnalyticStableMotiveCategory.quotientFunctor.mapIso
      (TraceAnalyticAdditiveHomotopyCategory
        .shiftedWeightBoundedObjectRepresentativeIso
          complex
          degree))
    unshifted_mem

/-- Concrete analytic motivic aisle membership implies bounded stable source
membership. -/
theorem boundedStableObject_of_aisleLE
    (cut : ℤ)
    {object : TraceAnalyticDMgmComparisonSource}
    (membership : TraceAnalyticMotivicTStructure.aisleLE cut object) :
    TraceAnalyticDMgmComparisonSource.boundedStableObject object :=
  Exists.elim
    membership
    (fun bound boundMembership =>
      Exists.elim
        boundMembership
        (fun complex complexMembership =>
          Exists.elim
            complexMembership
            (fun degree degreeMembership =>
              And.elim
                degreeMembership
                (fun _ object_eq =>
                  Eq.subst
                    (motive := fun candidate =>
                      TraceAnalyticDMgmComparisonSource
                        .boundedStableObject candidate)
                    (Eq.symm object_eq)
                    (TraceAnalyticDMgmComparisonSource
                      .boundedStableObject_of_sourceStableShiftedWeightBoundedObject
                        complex
                        degree)))))

/-- Concrete analytic motivic coaisle membership implies bounded stable source
membership. -/
theorem boundedStableObject_of_coaisleGE
    (cut : ℤ)
    {object : TraceAnalyticDMgmComparisonSource}
    (membership : TraceAnalyticMotivicTStructure.coaisleGE cut object) :
    TraceAnalyticDMgmComparisonSource.boundedStableObject object :=
  Exists.elim
    membership
    (fun bound boundMembership =>
      Exists.elim
        boundMembership
        (fun complex complexMembership =>
          Exists.elim
            complexMembership
            (fun degree degreeMembership =>
              And.elim
                degreeMembership
                (fun _ object_eq =>
                  Eq.subst
                    (motive := fun candidate =>
                      TraceAnalyticDMgmComparisonSource
                        .boundedStableObject candidate)
                    (Eq.symm object_eq)
                    (TraceAnalyticDMgmComparisonSource
                      .boundedStableObject_of_sourceStableShiftedWeightBoundedObject
                        complex
                        degree)))))

end TraceAnalyticDMgmComparisonSource

end AnalyticMotives
end LFunctions
end Boundary
