import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Inputs.Owner

/-!
# Named localization-input arrows by kind

This file exposes the forward and inverse localized arrows generated by each
concrete localization-input constructor.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized forward arrow generated by a descent-channel input. -/
def TraceLocalizationInput.descentChannelForwardArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.descentChannel source target).localizedSourceObject
      (TraceLocalizationInput.descentChannel source target).localizedTargetObject :=
  (TraceLocalizationInput.descentChannel source target).localizedForwardArrow

/-- The localized inverse arrow generated by a descent-channel input. -/
def TraceLocalizationInput.descentChannelInverseArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.descentChannel source target).localizedTargetObject
      (TraceLocalizationInput.descentChannel source target).localizedSourceObject :=
  (TraceLocalizationInput.descentChannel source target).localizedInverseArrow

/-- The localized forward arrow generated by a descent-refinement input. -/
def TraceLocalizationInput.descentRefinementForwardArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.descentRefinement source target).localizedSourceObject
      (TraceLocalizationInput.descentRefinement source target).localizedTargetObject :=
  (TraceLocalizationInput.descentRefinement source target).localizedForwardArrow

/-- The localized inverse arrow generated by a descent-refinement input. -/
def TraceLocalizationInput.descentRefinementInverseArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.descentRefinement source target).localizedTargetObject
      (TraceLocalizationInput.descentRefinement source target).localizedSourceObject :=
  (TraceLocalizationInput.descentRefinement source target).localizedInverseArrow

/-- The localized forward arrow generated by a descent-schedule input. -/
def TraceLocalizationInput.descentScheduleForwardArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.descentSchedule source target).localizedSourceObject
      (TraceLocalizationInput.descentSchedule source target).localizedTargetObject :=
  (TraceLocalizationInput.descentSchedule source target).localizedForwardArrow

/-- The localized inverse arrow generated by a descent-schedule input. -/
def TraceLocalizationInput.descentScheduleInverseArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.descentSchedule source target).localizedTargetObject
      (TraceLocalizationInput.descentSchedule source target).localizedSourceObject :=
  (TraceLocalizationInput.descentSchedule source target).localizedInverseArrow

/-- The localized forward arrow generated by an interval-Stokes input. -/
def TraceLocalizationInput.intervalStokesForwardArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.intervalStokes source target).localizedSourceObject
      (TraceLocalizationInput.intervalStokes source target).localizedTargetObject :=
  (TraceLocalizationInput.intervalStokes source target).localizedForwardArrow

/-- The localized inverse arrow generated by an interval-Stokes input. -/
def TraceLocalizationInput.intervalStokesInverseArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.intervalStokes source target).localizedTargetObject
      (TraceLocalizationInput.intervalStokes source target).localizedSourceObject :=
  (TraceLocalizationInput.intervalStokes source target).localizedInverseArrow

/-- The localized forward arrow generated by an interval-Fubini input. -/
def TraceLocalizationInput.intervalFubiniForwardArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.intervalFubini source target).localizedSourceObject
      (TraceLocalizationInput.intervalFubini source target).localizedTargetObject :=
  (TraceLocalizationInput.intervalFubini source target).localizedForwardArrow

/-- The localized inverse arrow generated by an interval-Fubini input. -/
def TraceLocalizationInput.intervalFubiniInverseArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.intervalFubini source target).localizedTargetObject
      (TraceLocalizationInput.intervalFubini source target).localizedSourceObject :=
  (TraceLocalizationInput.intervalFubini source target).localizedInverseArrow

/-- The localized forward arrow generated by a Tate-weight-drop input. -/
def TraceLocalizationInput.tateWeightDropForwardArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject
      (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject :=
  (TraceLocalizationInput.tateWeightDrop source target).localizedForwardArrow

/-- The localized inverse arrow generated by a Tate-weight-drop input. -/
def TraceLocalizationInput.tateWeightDropInverseArrow
    (source target : QTraceExpression) :
    TraceLocalizedWordHom
      (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject
      (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject :=
  (TraceLocalizationInput.tateWeightDrop source target).localizedInverseArrow

/-- The named descent-channel forward arrow is the generic forward arrow. -/
theorem TraceLocalizationInput.descentChannelForwardArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentChannelForwardArrow source target =
      (TraceLocalizationInput.descentChannel source target).localizedForwardArrow :=
  rfl

/-- The named descent-channel inverse arrow is the generic inverse arrow. -/
theorem TraceLocalizationInput.descentChannelInverseArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentChannelInverseArrow source target =
      (TraceLocalizationInput.descentChannel source target).localizedInverseArrow :=
  rfl

/-- The named descent-refinement forward arrow is the generic forward arrow. -/
theorem TraceLocalizationInput.descentRefinementForwardArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentRefinementForwardArrow source target =
      (TraceLocalizationInput.descentRefinement source target).localizedForwardArrow :=
  rfl

/-- The named descent-refinement inverse arrow is the generic inverse arrow. -/
theorem TraceLocalizationInput.descentRefinementInverseArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentRefinementInverseArrow source target =
      (TraceLocalizationInput.descentRefinement source target).localizedInverseArrow :=
  rfl

/-- The named descent-schedule forward arrow is the generic forward arrow. -/
theorem TraceLocalizationInput.descentScheduleForwardArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentScheduleForwardArrow source target =
      (TraceLocalizationInput.descentSchedule source target).localizedForwardArrow :=
  rfl

/-- The named descent-schedule inverse arrow is the generic inverse arrow. -/
theorem TraceLocalizationInput.descentScheduleInverseArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentScheduleInverseArrow source target =
      (TraceLocalizationInput.descentSchedule source target).localizedInverseArrow :=
  rfl

/-- The named interval-Stokes forward arrow is the generic forward arrow. -/
theorem TraceLocalizationInput.intervalStokesForwardArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalStokesForwardArrow source target =
      (TraceLocalizationInput.intervalStokes source target).localizedForwardArrow :=
  rfl

/-- The named interval-Stokes inverse arrow is the generic inverse arrow. -/
theorem TraceLocalizationInput.intervalStokesInverseArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalStokesInverseArrow source target =
      (TraceLocalizationInput.intervalStokes source target).localizedInverseArrow :=
  rfl

/-- The named interval-Fubini forward arrow is the generic forward arrow. -/
theorem TraceLocalizationInput.intervalFubiniForwardArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalFubiniForwardArrow source target =
      (TraceLocalizationInput.intervalFubini source target).localizedForwardArrow :=
  rfl

/-- The named interval-Fubini inverse arrow is the generic inverse arrow. -/
theorem TraceLocalizationInput.intervalFubiniInverseArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalFubiniInverseArrow source target =
      (TraceLocalizationInput.intervalFubini source target).localizedInverseArrow :=
  rfl

/-- The named Tate-weight-drop forward arrow is the generic forward arrow. -/
theorem TraceLocalizationInput.tateWeightDropForwardArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.tateWeightDropForwardArrow source target =
      (TraceLocalizationInput.tateWeightDrop source target).localizedForwardArrow :=
  rfl

/-- The named Tate-weight-drop inverse arrow is the generic inverse arrow. -/
theorem TraceLocalizationInput.tateWeightDropInverseArrow_eq
    (source target : QTraceExpression) :
    TraceLocalizationInput.tateWeightDropInverseArrow source target =
      (TraceLocalizationInput.tateWeightDrop source target).localizedInverseArrow :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
