import Boundary.LFunctions.EndomorphismK0Core
import Boundary.LFunctions.EndomorphismK0Relations
import Boundary.LFunctions.EndomorphismK0ShortExact

namespace Boundary
namespace EndomorphismK0

noncomputable section

open LinearEulerFactor

variable (K : Type u) [Field K]

/-- The determinant character on the free virtual group, valued additively in
the unit group of `RatFunc K`. -/
def determinantCharacter : VirtualEndomorphism K →+ Additive ((RatFunc K)ˣ) :=
  FreeAbelianGroup.lift fun A => Additive.ofMul (EndomorphismObject.determinantUnit A)

@[simp]
theorem determinantCharacter_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacter K (of K A) =
      Additive.ofMul (EndomorphismObject.determinantUnit A) := by
  rfl

/-- The determinant character kills the direct-sum relation. -/
@[simp]
theorem determinantCharacter_directSumRelation (A B : EndomorphismObject.{u, v} K) :
    determinantCharacter K (directSumRelation K A B) = 0 := by
  calc
    determinantCharacter K (directSumRelation K A B)
        = determinantCharacter K (of K (EndomorphismObject.product A B)) -
            determinantCharacter K (of K A) -
            determinantCharacter K (of K B) := by
          rfl
    _ = Additive.ofMul (EndomorphismObject.determinantUnit (EndomorphismObject.product A B)) -
          Additive.ofMul (EndomorphismObject.determinantUnit A) -
          Additive.ofMul (EndomorphismObject.determinantUnit B) := by
          rw [determinantCharacter_of, determinantCharacter_of, determinantCharacter_of]
    _ = 0 := by
          exact sub_eq_zero.mpr (by
            simp [EndomorphismObject.determinantUnit_product])

theorem determinantCharacter_conjRelation
    (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    determinantCharacter K (conjRelation K A e) = 0 := by
  calc
    determinantCharacter K (conjRelation K A e)
        = determinantCharacter K (of K (EndomorphismObject.conj A e)) -
            determinantCharacter K (of K A) := by
          rfl
    _ = Additive.ofMul (EndomorphismObject.determinantUnit (EndomorphismObject.conj A e)) -
          Additive.ofMul (EndomorphismObject.determinantUnit A) := by
          rw [determinantCharacter_of, determinantCharacter_of]
    _ = 0 := by
          exact sub_eq_zero.mpr (by
            exact congrArg Additive.ofMul (EndomorphismObject.determinantUnit_conj A e))

@[simp]
theorem determinantCharacter_zeroObject (A : EndomorphismObject.{u, v} K)
    (hA : IsZeroObject K A) :
    determinantCharacter K (of K A) = 0 := by
  rw [determinantCharacter_of, determinantUnit_zeroObject (K := K) A hA]
  rfl

/-- The determinant character kills the subgroup generated by direct-sum
relations. -/
theorem directSumSubgroup_le_determinantCharacter_ker :
    directSumSubgroup K ≤ (determinantCharacter K).ker := by
  rw [directSumSubgroup, AddSubgroup.closure_le]
  rintro x (⟨A, B, rfl⟩ | ⟨A, B, e, rfl⟩ | ⟨A, hA, rfl⟩)
  · change determinantCharacter K (directSumRelation K A B) = 0
    exact determinantCharacter_directSumRelation K A B
  · change determinantCharacter K (conjRelation K A e) = 0
    exact determinantCharacter_conjRelation K A e
  · exact determinantCharacter_zeroObject K A hA

/-- The determinant character descended to the direct-sum quotient. Its target
is written additively because the quotient source is an additive group. -/
def determinantCharacterK0 : K0 K →+ Additive ((RatFunc K)ˣ) :=
  QuotientAddGroup.lift (directSumSubgroup K) (determinantCharacter K)
    (directSumSubgroup_le_determinantCharacter_ker K)

/-- Multiplicative form of the determinant character on the direct-sum
quotient. -/
def determinantCharacterK0Mul : Multiplicative (K0 K) →* (RatFunc K)ˣ where
  toFun x := Additive.toMul (determinantCharacterK0 K (Multiplicative.toAdd x))
  map_one' := by
    simp [determinantCharacterK0]
  map_mul' x y := by
    simp [determinantCharacterK0]

@[simp]
theorem determinantCharacterK0_mk (x : VirtualEndomorphism K) :
    determinantCharacterK0 K (mk K x) = determinantCharacter K x := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (directSumSubgroup_le_determinantCharacter_ker K) x

@[simp]
theorem determinantCharacterK0_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacterK0 K (mk K (of K A)) =
      Additive.ofMul (EndomorphismObject.determinantUnit A) := by
  exact determinantCharacterK0_mk (K := K) (of K A)

@[simp]
theorem determinantCharacterK0Mul_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacterK0Mul K (Multiplicative.ofAdd (mk K (of K A))) =
      EndomorphismObject.determinantUnit A := by
  exact congrArg Additive.toMul (determinantCharacterK0_of (K := K) A)

/-- The trace-power character on the free virtual group. -/
def traceCharacter (n : ℕ) : VirtualEndomorphism K →+ K :=
  FreeAbelianGroup.lift fun A => EndomorphismObject.tracePower n A

/-- A zero-object endomorphism has vanishing trace powers. -/
theorem tracePower_zeroObject (n : ℕ) (A : EndomorphismObject.{u, v} K)
    (hA : IsZeroObject K A) : EndomorphismObject.tracePower n A = 0 := by
  haveI : Subsingleton A.carrier := hA
  have hfin : Module.finrank K A.carrier = 0 :=
    Module.finrank_zero_of_subsingleton
  change EndomorphismObject.tracePower n A = 0
  by_cases hn : n = 0
  · subst n
    simp [EndomorphismObject.tracePower, LinearMap.trace_one, hfin]
  · have hpow : A.endomorphism ^ n = 0 := by
      ext x
      exact Subsingleton.elim _ _
    simp [EndomorphismObject.tracePower, hpow]

@[simp]
theorem traceCharacter_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    traceCharacter K n (of K A) = EndomorphismObject.tracePower n A := by
  rfl

/-- The trace-power character kills the direct-sum relation. -/
@[simp]
theorem traceCharacter_directSumRelation (n : ℕ) (A B : EndomorphismObject.{u, v} K) :
    traceCharacter K n (directSumRelation K A B) = 0 := by
  calc
    traceCharacter K n (directSumRelation K A B)
        = traceCharacter K n (of K (EndomorphismObject.product A B)) -
            traceCharacter K n (of K A) -
            traceCharacter K n (of K B) := by
          rfl
    _ = EndomorphismObject.tracePower n (EndomorphismObject.product A B) -
          EndomorphismObject.tracePower n A -
          EndomorphismObject.tracePower n B := by
          rw [traceCharacter_of, traceCharacter_of, traceCharacter_of]
    _ = 0 := by
          exact sub_eq_zero.mpr (by
            simp [EndomorphismObject.tracePower_product])

theorem traceCharacter_conjRelation (n : ℕ) (A : EndomorphismObject.{u, v} K)
    {B : EndomorphismObject.{u, v} K} (e : A.carrier ≃ₗ[K] B.carrier) :
    traceCharacter K n (conjRelation K A e) = 0 := by
  calc
    traceCharacter K n (conjRelation K A e)
        = traceCharacter K n (of K (EndomorphismObject.conj A e)) -
            traceCharacter K n (of K A) := by
          rfl
    _ = EndomorphismObject.tracePower n (EndomorphismObject.conj A e) -
          EndomorphismObject.tracePower n A := by
          rw [traceCharacter_of, traceCharacter_of]
    _ = 0 := by
          exact sub_eq_zero.mpr (EndomorphismObject.tracePower_conj n A e)

@[simp]
theorem traceCharacter_zeroObject (n : ℕ) (A : EndomorphismObject.{u, v} K)
    (hA : IsZeroObject K A) :
    traceCharacter K n (of K A) = 0 := by
  rw [traceCharacter_of]
  exact tracePower_zeroObject (K := K) n A hA

/-- The first trace character kills the direct-sum relation. -/
@[simp]
theorem traceCharacter_one_directSumRelation (A B : EndomorphismObject.{u, v} K) :
    traceCharacter K 1 (directSumRelation K A B) = 0 :=
  traceCharacter_directSumRelation K 1 A B

/-- The trace-power character kills the subgroup generated by direct-sum
relations. -/
theorem directSumSubgroup_le_traceCharacter_ker (n : ℕ) :
    directSumSubgroup K ≤ (traceCharacter K n).ker := by
  rw [directSumSubgroup, AddSubgroup.closure_le]
  rintro x (⟨A, B, rfl⟩ | ⟨A, B, e, rfl⟩ | ⟨A, hA, rfl⟩)
  · change traceCharacter K n (directSumRelation K A B) = 0
    exact traceCharacter_directSumRelation K n A B
  · change traceCharacter K n (conjRelation K A e) = 0
    exact traceCharacter_conjRelation K n A e
  · exact traceCharacter_zeroObject K n A hA

/-- The first trace character kills the subgroup generated by direct-sum
relations. -/
theorem directSumSubgroup_le_traceCharacter_one_ker :
    directSumSubgroup K ≤ (traceCharacter K 1).ker :=
  directSumSubgroup_le_traceCharacter_ker K 1

/-- The trace-power character descended to the direct-sum quotient. -/
def traceCharacterK0 (n : ℕ) : K0 K →+ K :=
  QuotientAddGroup.lift (directSumSubgroup K) (traceCharacter K n)
    (directSumSubgroup_le_traceCharacter_ker K n)

@[simp]
theorem traceCharacterK0_mk (n : ℕ) (x : VirtualEndomorphism K) :
    traceCharacterK0 K n (mk K x) = traceCharacter K n x := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (directSumSubgroup_le_traceCharacter_ker K n) x

@[simp]
theorem traceCharacterK0_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    traceCharacterK0 K n (mk K (of K A)) = EndomorphismObject.tracePower n A := by
  exact traceCharacterK0_mk K n (of K A)

/-- The virtual power map `[V,F] ↦ [V,F^n]` on the free group. -/
def powerMapVirtual (n : ℕ) : VirtualEndomorphism K →+ VirtualEndomorphism K :=
  FreeAbelianGroup.lift fun A => of K (EndomorphismObject.power A n)

@[simp]
theorem powerMapVirtual_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    powerMapVirtual K n (of K A) = of K (EndomorphismObject.power A n) := by
  rfl

/-- The virtual power map sends direct-sum relations to direct-sum relations. -/
theorem powerMapVirtual_directSumRelation
    (n : ℕ) (A B : EndomorphismObject.{u, v} K) :
    powerMapVirtual K n (directSumRelation K A B) =
      directSumRelation K (EndomorphismObject.power A n)
        (EndomorphismObject.power B n) := by
  calc
    powerMapVirtual K n (directSumRelation K A B)
        = powerMapVirtual K n
            (of K (EndomorphismObject.product A B) - (of K A + of K B)) := by
          rfl
    _ = powerMapVirtual K n (of K (EndomorphismObject.product A B)) -
          powerMapVirtual K n (of K A + of K B) := by
          exact map_sub (powerMapVirtual K n) _ _
    _ = of K (EndomorphismObject.power (EndomorphismObject.product A B) n) -
          (powerMapVirtual K n (of K A) + powerMapVirtual K n (of K B)) := by
          congr 1
          exact map_add (powerMapVirtual K n) (of K A) (of K B)
    _ = of K (EndomorphismObject.product (EndomorphismObject.power A n)
            (EndomorphismObject.power B n)) -
          of K (EndomorphismObject.power A n) -
          of K (EndomorphismObject.power B n) := by
          congr 1
          exact EndomorphismObject.power_product A B n
    _ = directSumRelation K (EndomorphismObject.power A n)
        (EndomorphismObject.power B n) := by
          rfl

/-- The virtual power map carries a conjugacy relation to the conjugacy
relation of the powered endomorphism objects. -/
theorem powerMapVirtual_conjRelation
    (n : ℕ) (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    powerMapVirtual K n (conjRelation K A e) =
      conjRelation K (EndomorphismObject.power A n) e := by
  calc
    powerMapVirtual K n (conjRelation K A e)
        = powerMapVirtual K n (of K (EndomorphismObject.conj A e) - of K A) := by
          rfl
    _ = powerMapVirtual K n (of K (EndomorphismObject.conj A e)) -
          powerMapVirtual K n (of K A) := by
          exact map_sub (powerMapVirtual K n) _ _
    _ = of K (EndomorphismObject.power (EndomorphismObject.conj A e) n) -
          of K (EndomorphismObject.power A n) := by
          rw [powerMapVirtual_of, powerMapVirtual_of]
    _ = of K (EndomorphismObject.conj (EndomorphismObject.power A n) e) -
            of K (EndomorphismObject.power A n) := by
          rw [EndomorphismObject.conj_pow n A e]
    _ = conjRelation K (EndomorphismObject.power A n) e := by
          rfl

/-- The virtual power map sends conjugacy relations into the direct-sum
relation subgroup. -/
theorem powerMapVirtual_conjRelation_mem_directSumSubgroup
    (n : ℕ) (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    powerMapVirtual K n (conjRelation K A e) ∈ directSumSubgroup K := by
  rw [powerMapVirtual_conjRelation]
  exact conjRelation_mem_directSumSubgroup K (EndomorphismObject.power A n) e

/-- The virtual power map sends direct-sum relations into the direct-sum
relation subgroup. -/
theorem powerMapVirtual_directSumRelation_mem_directSumSubgroup
    (n : ℕ) (A B : EndomorphismObject.{u, v} K) :
    powerMapVirtual K n (directSumRelation K A B) ∈ directSumSubgroup K := by
  rw [powerMapVirtual_directSumRelation]
  exact directSumRelation_mem_directSumSubgroup K
    (EndomorphismObject.power A n) (EndomorphismObject.power B n)

theorem powerMapVirtual_zeroObject_mem_directSumSubgroup
    (n : ℕ) (A : EndomorphismObject.{u, v} K) (hA : IsZeroObject K A) :
    powerMapVirtual K n (of K A) ∈ directSumSubgroup K := by
  exact
    (powerMapVirtual_of (K := K) n A).symm ▸
      zeroObject_mem_directSumSubgroup K (EndomorphismObject.power A n) hA

/-- The virtual power map preserves the direct-sum relation subgroup. -/
theorem powerMapVirtual_directSumSubgroup_le (n : ℕ) :
    directSumSubgroup K ≤
      (directSumSubgroup K).comap (powerMapVirtual K n) := by
  rw [directSumSubgroup, AddSubgroup.closure_le]
  rintro x (⟨A, B, rfl⟩ | ⟨A, B, e, rfl⟩ | ⟨A, hA, rfl⟩)
  · exact powerMapVirtual_directSumRelation_mem_directSumSubgroup K n A B
  · exact powerMapVirtual_conjRelation_mem_directSumSubgroup K n A e
  · exact powerMapVirtual_zeroObject_mem_directSumSubgroup K n A hA

/-- The descended power operation on the direct-sum K₀ group. -/
def powerMapK0 (n : ℕ) : K0 K →+ K0 K :=
  QuotientAddGroup.lift (directSumSubgroup K)
    ((mk K).comp (powerMapVirtual K n))
    (by
      intro x hx
      exact (QuotientAddGroup.eq_zero_iff
        (N := directSumSubgroup K) (powerMapVirtual K n x)).2
          (powerMapVirtual_directSumSubgroup_le K n hx))

@[simp]
theorem powerMapK0_mk (n : ℕ) (x : VirtualEndomorphism K) :
    powerMapK0 K n (mk K x) = mk K (powerMapVirtual K n x) := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (by
      intro x hx
      exact (QuotientAddGroup.eq_zero_iff
        (N := directSumSubgroup K) (powerMapVirtual K n x)).2
          (powerMapVirtual_directSumSubgroup_le K n hx))
    x

@[simp]
theorem powerMapK0_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    powerMapK0 K n (mk K (of K A)) =
      mk K (of K (EndomorphismObject.power A n)) := by
  exact powerMapK0_mk K n (of K A)

/-- The trace character compatibility with `powerMapK0` on a generator. -/
theorem traceCharacterK0_one_powerMapK0_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (of K A))) =
      traceCharacterK0 K n (mk K (of K A)) := by
  calc
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (of K A)))
        = traceCharacterK0 K 1 (mk K (of K (EndomorphismObject.power A n))) := by
          rfl
    _ = EndomorphismObject.tracePower 1 (EndomorphismObject.power A n) := by
          exact traceCharacterK0_of (K := K) 1 (EndomorphismObject.power A n)
    _ = EndomorphismObject.tracePower n A := by
          exact EndomorphismObject.tracePower_one_power A n
    _ = traceCharacterK0 K n (mk K (of K A)) := by
          symm
          exact traceCharacterK0_of (K := K) n A

/-- The trace-power compatibility proof respects additive recursion on the free
abelian group. -/
theorem traceCharacterK0_one_powerMapK0_induction
    (n : ℕ) (y : FreeAbelianGroup EndomorphismObject.{u, v} K) :
    traceCharacterK0 K 1 (powerMapK0 K n (mk K y)) =
      traceCharacterK0 K n (mk K y) := by
  induction y using FreeAbelianGroup.induction_on' with
  | C0 =>
      rfl
  | C1 A =>
      exact traceCharacterK0_one_powerMapK0_of (K := K) n A
  | Cn y hy =>
      exact congrArg Neg.neg hy
  | Cp y z hy hz =>
      exact congrArg₂ HAdd.hAdd hy hz

/-- Applying the ordinary trace character to the powered K₀ class recovers the
`n`th trace-power character. -/
theorem traceCharacterK0_one_powerMapK0 (n : ℕ) (x : K0 K) :
    traceCharacterK0 K 1 (powerMapK0 K n x) =
      traceCharacterK0 K n x := by
  refine Quotient.inductionOn' x ?_
  intro y
  exact traceCharacterK0_one_powerMapK0_induction (K := K) n y

/-- The power map fixes the `n=1` generator. -/
theorem powerMapK0_one_of (A : EndomorphismObject.{u, v} K) :
    powerMapK0 K 1 (mk K (of K A)) = mk K (of K A) := by
  calc
    powerMapK0 K 1 (mk K (of K A))
        = mk K (of K (EndomorphismObject.power A 1)) := by
          exact powerMapK0_of (K := K) 1 A
    _ = mk K (of K A) := by
          congr 1
          exact EndomorphismObject.power_one A

/-- The `n=1` power-map compatibility proof respects additive recursion on the
free abelian group. -/
theorem powerMapK0_one_induction
    (y : FreeAbelianGroup EndomorphismObject.{u, v} K) :
    powerMapK0 K 1 (mk K y) = mk K y := by
  induction y using FreeAbelianGroup.induction_on' with
  | C0 =>
      rfl
  | C1 A =>
      exact powerMapK0_one_of (K := K) A
  | Cn y hy =>
      exact congrArg Neg.neg hy
  | Cp y z hy hz =>
      exact congrArg₂ HAdd.hAdd hy hz

@[simp]
theorem powerMapK0_one (x : K0 K) :
    powerMapK0 K 1 x = x := by
  refine Quotient.inductionOn' x ?_
  intro y
  exact powerMapK0_one_induction (K := K) y

/-- The power maps compose on generators by multiplication of exponents. -/
theorem powerMapK0_comp_of (m n : ℕ) (A : EndomorphismObject.{u, v} K) :
    powerMapK0 K n (powerMapK0 K m (mk K (of K A))) =
      powerMapK0 K (m * n) (mk K (of K A)) := by
  calc
    powerMapK0 K n (powerMapK0 K m (mk K (of K A)))
        = mk K (of K (EndomorphismObject.power (EndomorphismObject.power A m) n)) := by
          exact powerMapK0_mk (K := K) n (of K (EndomorphismObject.power A m))
    _ = mk K (of K (EndomorphismObject.power A (m * n))) := by
          congr 1
          exact EndomorphismObject.power_power A m n
    _ = powerMapK0 K (m * n) (mk K (of K A)) := by
          symm
          exact powerMapK0_of (K := K) (m * n) A

/-- Composition of power maps respects additive recursion on the free abelian
group. -/
theorem powerMapK0_comp_induction
    (m n : ℕ) (y : FreeAbelianGroup EndomorphismObject.{u, v} K) :
    powerMapK0 K n (powerMapK0 K m (mk K y)) =
      powerMapK0 K (m * n) (mk K y) := by
  induction y using FreeAbelianGroup.induction_on' with
  | C0 =>
      rfl
  | C1 A =>
      exact powerMapK0_comp_of (K := K) m n A
  | Cn y hy =>
      exact congrArg Neg.neg hy
  | Cp y z hy hz =>
      exact congrArg₂ HAdd.hAdd hy hz

/-- Composing K₀ power maps multiplies the exponents. -/
theorem powerMapK0_comp (m n : ℕ) (x : K0 K) :
    powerMapK0 K n (powerMapK0 K m x) =
      powerMapK0 K (m * n) x := by
  refine Quotient.inductionOn' x ?_
  intro y
  exact powerMapK0_comp_induction (K := K) m n y

/-- The first trace character descended to the direct-sum quotient. -/
def traceCharacterOneK0 : K0 K →+ K :=
  traceCharacterK0 K 1

@[simp]
theorem traceCharacterOneK0_mk (x : VirtualEndomorphism K) :
    traceCharacterOneK0 K (mk K x) = traceCharacter K 1 x := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (directSumSubgroup_le_traceCharacter_one_ker K) x

@[simp]
theorem traceCharacterOneK0_of (A : EndomorphismObject.{u, v} K) :
    traceCharacterOneK0 K (mk K (of K A)) = EndomorphismObject.tracePower 1 A := by
  exact traceCharacterOneK0_mk K (of K A)

/-- The determinant character kills the short exact sequence relation. -/
theorem determinantCharacter_shortExactRelation (K : Type u) [Field K]
    (S : ShortExactSequence.{u, v} K) :
    determinantCharacter K (shortExactRelation K S) = 0 := by
  calc
    determinantCharacter K (shortExactRelation K S)
        = determinantCharacter K (of K S.middle) -
            determinantCharacter K (of K S.left) -
            determinantCharacter K (of K S.right) := by
          rfl
    _ = Additive.ofMul (EndomorphismObject.determinantUnit S.middle) -
          Additive.ofMul (EndomorphismObject.determinantUnit S.left) -
          Additive.ofMul (EndomorphismObject.determinantUnit S.right) := by
          rw [determinantCharacter_of, determinantCharacter_of, determinantCharacter_of]
    _ = 0 := by
          exact sub_eq_zero.mpr (by
            exact S.shortExact_determinantUnit_mul)

/-- The first trace character kills the short exact sequence relation. -/
theorem traceCharacter_one_shortExactRelation (K : Type u) [Field K]
    (S : ShortExactSequence.{u, v} K) :
    traceCharacter K 1 (shortExactRelation K S) = 0 := by
  calc
    traceCharacter K 1 (shortExactRelation K S)
        = traceCharacter K 1 (of K S.middle) -
            traceCharacter K 1 (of K S.left) -
            traceCharacter K 1 (of K S.right) := by
          rfl
    _ = EndomorphismObject.tracePower 1 S.middle -
          EndomorphismObject.tracePower 1 S.left -
          EndomorphismObject.tracePower 1 S.right := by
          rw [traceCharacter_of, traceCharacter_of, traceCharacter_of]
    _ = 0 := by
          exact sub_eq_zero.mpr (by
            exact S.shortExact_trace_additivity)

/-- The determinant character kills the full exact-sequence relation subgroup. -/
theorem shortExactSubgroup_le_determinantCharacter_ker :
    shortExactSubgroup K ≤ (determinantCharacter K).ker := by
  rw [shortExactSubgroup, AddSubgroup.closure_le]
  rintro x (⟨A, B, rfl⟩ | ⟨A, B, e, rfl⟩ | ⟨A, hA, rfl⟩ | ⟨S, rfl⟩)
  · exact determinantCharacter_directSumRelation K A B
  · exact determinantCharacter_conjRelation K A e
  · exact determinantCharacter_zeroObject K A hA
  · exact determinantCharacter_shortExactRelation K S

/-- The determinant character descends to the exact-sequence quotient. -/
def determinantCharacterK0Exact : K0Exact K →+ Additive ((RatFunc K)ˣ) :=
  QuotientAddGroup.lift (shortExactSubgroup K) (determinantCharacter K)
    (shortExactSubgroup_le_determinantCharacter_ker (K := K))

/-- Multiplicative form of the determinant character on the exact-sequence
quotient. -/
def determinantCharacterK0ExactMul : Multiplicative (K0Exact K) →* (RatFunc K)ˣ where
  toFun x := Additive.toMul (determinantCharacterK0Exact (K := K) (Multiplicative.toAdd x))
  map_one' := by
    rfl
  map_mul' x y := by
    rfl

@[simp]
theorem determinantCharacterK0ExactMul_ofAdd (x : K0Exact K) :
    determinantCharacterK0ExactMul K (Multiplicative.ofAdd x) =
      Additive.toMul (determinantCharacterK0Exact K x) := by
  rfl

@[simp]
theorem determinantCharacterK0Exact_mk (x : VirtualEndomorphism K) :
    determinantCharacterK0Exact (mkExact K x) = determinantCharacter K x := by
  exact QuotientAddGroup.lift_mk (shortExactSubgroup K)
    (shortExactSubgroup_le_determinantCharacter_ker (K := K)) x

@[simp]
theorem determinantCharacterK0Exact_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacterK0Exact (mkExact K (of K A)) =
      Additive.ofMul (EndomorphismObject.determinantUnit A) := by
  exact determinantCharacterK0Exact_mk (K := K) (of K A)

@[simp]
theorem determinantCharacterK0ExactMul_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacterK0ExactMul (K := K) (Multiplicative.ofAdd (mkExact K (of K A))) =
      EndomorphismObject.determinantUnit A := by
  exact (determinantCharacterK0ExactMul_ofAdd (K := K) (mkExact K (of K A))).trans
    (congrArg Additive.toMul (determinantCharacterK0Exact_of (K := K) A))

/-- The first trace character kills the full exact-sequence relation subgroup. -/
theorem shortExactSubgroup_le_traceCharacter_one_ker :
    shortExactSubgroup K ≤ (traceCharacter K 1).ker := by
  rw [shortExactSubgroup, AddSubgroup.closure_le]
  rintro x (⟨A, B, rfl⟩ | ⟨A, B, e, rfl⟩ | ⟨A, hA, rfl⟩ | ⟨S, rfl⟩)
  · exact traceCharacter_directSumRelation K 1 A B
  · exact traceCharacter_conjRelation K 1 A e
  · exact traceCharacter_zeroObject K 1 A hA
  · exact traceCharacter_one_shortExactRelation K S

/-- The first trace character descends to the exact-sequence quotient. -/
def traceCharacterOneK0Exact : K0Exact K →+ K :=
  QuotientAddGroup.lift (shortExactSubgroup K) (traceCharacter K 1)
    (shortExactSubgroup_le_traceCharacter_one_ker (K := K))

@[simp]
theorem traceCharacterOneK0Exact_mk (x : VirtualEndomorphism K) :
    traceCharacterOneK0Exact (mkExact K x) = traceCharacter K 1 x := by
  exact QuotientAddGroup.lift_mk (shortExactSubgroup K)
    (shortExactSubgroup_le_traceCharacter_one_ker (K := K)) x

@[simp]
theorem traceCharacterOneK0Exact_of (A : EndomorphismObject.{u, v} K) :
    traceCharacterOneK0Exact (mkExact K (of K A)) = EndomorphismObject.tracePower 1 A := by
  change traceCharacter K 1 (of K A) = EndomorphismObject.tracePower 1 A
  exact traceCharacter_of (K := K) 1 A

end

end EndomorphismK0
end Boundary
