import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.LedgeredTransports.CoherenceRelations.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Generators.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Relation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Add.Laws.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Comp.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Zero.Support.Owner

/-!
# Core identity support relations for quotient trace composition

This file exposes the concrete quotient relations generated by the analytic
left- and right-identity coherence cells for ledgered trace transports.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The quotient candidate represented by left-identity coherence support. -/
def LedgeredTraceTransport.leftIdentitySupportCandidate
    (transport : LedgeredTraceTransport) :
    TraceCorQQuotientCandidate :=
  TraceCorQRelationGenerator.supportCandidate
    (LedgeredTraceTransport.leftIdentityRelationGenerator transport)

/-- The quotient candidate represented by right-identity coherence support. -/
def LedgeredTraceTransport.rightIdentitySupportCandidate
    (transport : LedgeredTraceTransport) :
    TraceCorQQuotientCandidate :=
  TraceCorQRelationGenerator.supportCandidate
    (LedgeredTraceTransport.rightIdentityRelationGenerator transport)

/-- The left-identity support candidate has the expected support. -/
theorem LedgeredTraceTransport.leftIdentitySupportCandidate_formalSum
    (transport : LedgeredTraceTransport) :
    (LedgeredTraceTransport.leftIdentitySupportCandidate
      transport).formalSum =
      LedgeredTraceTransport.coherenceSupport
        ((LedgeredTraceTransport.id transport.source).comp transport)
        transport :=
  rfl

/-- The right-identity support candidate has the expected support. -/
theorem LedgeredTraceTransport.rightIdentitySupportCandidate_formalSum
    (transport : LedgeredTraceTransport) :
    (LedgeredTraceTransport.rightIdentitySupportCandidate
      transport).formalSum =
      LedgeredTraceTransport.coherenceSupport
        (transport.comp (LedgeredTraceTransport.id transport.target))
        transport :=
  rfl

/-- The finite witness killing left-identity support. -/
def LedgeredTraceTransport.leftIdentitySupportWitness
    (transport : LedgeredTraceTransport) :
    TraceCorQRelationWitness
      (LedgeredTraceTransport.leftIdentitySupportCandidate transport)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationGenerator.supportWitness
    (LedgeredTraceTransport.leftIdentityRelationGenerator transport)

/-- The finite witness killing right-identity support. -/
def LedgeredTraceTransport.rightIdentitySupportWitness
    (transport : LedgeredTraceTransport) :
    TraceCorQRelationWitness
      (LedgeredTraceTransport.rightIdentitySupportCandidate transport)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationGenerator.supportWitness
    (LedgeredTraceTransport.rightIdentityRelationGenerator transport)

/-- The quotient relation generated by left-identity coherence support. -/
def LedgeredTraceTransport.leftIdentitySupportRelation
    (transport : LedgeredTraceTransport) :
    TraceCorQQuotientRelation
      (LedgeredTraceTransport.leftIdentitySupportCandidate transport)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.supportZero
    (LedgeredTraceTransport.leftIdentityRelationGenerator transport)

/-- The quotient relation generated by right-identity coherence support. -/
def LedgeredTraceTransport.rightIdentitySupportRelation
    (transport : LedgeredTraceTransport) :
    TraceCorQQuotientRelation
      (LedgeredTraceTransport.rightIdentitySupportCandidate transport)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.supportZero
    (LedgeredTraceTransport.rightIdentityRelationGenerator transport)

/-- Left-identity support is zero in the quotient. -/
theorem LedgeredTraceTransport.leftIdentitySupportQuotient_eq_zero
    (transport : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.leftIdentitySupportCandidate transport) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.supportZero_eq_zero
    (LedgeredTraceTransport.leftIdentityRelationGenerator transport)

/-- Right-identity support is zero in the quotient. -/
theorem LedgeredTraceTransport.rightIdentitySupportQuotient_eq_zero
    (transport : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.rightIdentitySupportCandidate transport) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.supportZero_eq_zero
    (LedgeredTraceTransport.rightIdentityRelationGenerator transport)

end AnalyticMotives
end LFunctions
end Boundary
