import Mathlib.CategoryTheory.Linear.Yoneda
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Presheaves.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Category.Linear.Owner

open scoped CategoryTheory

/-!
# Representable trace presheaves

This file owns the Q-linear representable presheaves generated by objects of
the analytic trace-correspondence category.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The Q-linear Yoneda embedding for analytic trace correspondences. -/
abbrev TraceCorQPresheaf.yoneda :
    TraceCorQObject ⥤ TraceCorQPresheaf :=
  CategoryTheory.linearYoneda Rat TraceCorQObject

/-- The representable Q-module-valued trace presheaf generated by one trace object. -/
def TraceCorQPresheaf.representable
    (object : TraceCorQObject) :
    TraceCorQPresheaf :=
  (TraceCorQPresheaf.yoneda).obj object

/-- The Q-linear representable embedding is full. -/
instance TraceCorQPresheaf.yonedaFull :
    (TraceCorQPresheaf.yoneda).Full :=
  CategoryTheory.full_linearYoneda Rat TraceCorQObject

/-- The Q-linear representable embedding is faithful. -/
instance TraceCorQPresheaf.yonedaFaithful :
    (TraceCorQPresheaf.yoneda).Faithful :=
  CategoryTheory.faithful_linearYoneda Rat TraceCorQObject

/-- The representable presheaf is the object part of linear Yoneda. -/
theorem TraceCorQPresheaf.representable_eq_yoneda_obj
    (object : TraceCorQObject) :
    TraceCorQPresheaf.representable object =
      (TraceCorQPresheaf.yoneda).obj object :=
  rfl

/-- Sections of a representable trace presheaf are the Q-module of trace correspondences. -/
theorem TraceCorQPresheaf.representable_sections
    (source target : TraceCorQObject) :
    (TraceCorQPresheaf.representable target).sections source =
      ModuleCat.of Rat (source ⟶ target) :=
  rfl

/-- Pullback on a representable trace presheaf is left composition of trace correspondences. -/
theorem TraceCorQPresheaf.representable_pullback
    {source middle : TraceCorQObject}
    (target : TraceCorQObject)
    (morphism : source ⟶ middle) :
    (TraceCorQPresheaf.representable target).pullback morphism =
      ModuleCat.asHom
        (CategoryTheory.Linear.leftComp Rat target morphism) :=
  rfl

/-- A trace correspondence induces a morphism of representable trace presheaves. -/
def TraceCorQPresheaf.representableMap
    {source target : TraceCorQObject}
    (morphism : source ⟶ target) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable source)
      (TraceCorQPresheaf.representable target) :=
  (TraceCorQPresheaf.yoneda).map morphism

/-- Representable maps are the morphism part of linear Yoneda. -/
theorem TraceCorQPresheaf.representableMap_eq_yoneda_map
    {source target : TraceCorQObject}
    (morphism : source ⟶ target) :
    TraceCorQPresheaf.representableMap morphism =
      (TraceCorQPresheaf.yoneda).map morphism :=
  rfl

/-- Equality of representable maps reflects equality of trace correspondences. -/
theorem TraceCorQPresheaf.eq_of_representableMap_eq
    {source target : TraceCorQObject}
    {left right : source ⟶ target}
    (map_eq :
      TraceCorQPresheaf.representableMap left =
        TraceCorQPresheaf.representableMap right) :
    left = right :=
  (TraceCorQPresheaf.yoneda).map_injective map_eq

/-- The trace correspondence represented by a morphism between representable presheaves. -/
noncomputable def TraceCorQPresheaf.representablePreimage
    {source target : TraceCorQObject}
    (morphism :
      TraceCorQPresheafHom
        (TraceCorQPresheaf.representable source)
        (TraceCorQPresheaf.representable target)) :
    source ⟶ target :=
  (TraceCorQPresheaf.yoneda).preimage morphism

/-- The representable preimage of a representable map is the original trace correspondence. -/
theorem TraceCorQPresheaf.representablePreimage_representableMap
    {source target : TraceCorQObject}
    (morphism : source ⟶ target) :
    TraceCorQPresheaf.representablePreimage
      (TraceCorQPresheaf.representableMap morphism) =
      morphism :=
  (TraceCorQPresheaf.yoneda).preimage_map morphism

/-- Every morphism between representable trace presheaves is represented by its trace preimage. -/
theorem TraceCorQPresheaf.representableMap_representablePreimage
    {source target : TraceCorQObject}
    (morphism :
      TraceCorQPresheafHom
        (TraceCorQPresheaf.representable source)
        (TraceCorQPresheaf.representable target)) :
    TraceCorQPresheaf.representableMap
      (TraceCorQPresheaf.representablePreimage morphism) =
      morphism :=
  (TraceCorQPresheaf.yoneda).map_preimage morphism

/-- Trace correspondences are equivalent to morphisms between their representable presheaves. -/
noncomputable def TraceCorQPresheaf.representableHomEquiv
    (source target : TraceCorQObject) :
    (source ⟶ target) ≃
      TraceCorQPresheafHom
        (TraceCorQPresheaf.representable source)
        (TraceCorQPresheaf.representable target) where
  toFun := fun morphism =>
    TraceCorQPresheaf.representableMap morphism
  invFun := fun morphism =>
    TraceCorQPresheaf.representablePreimage morphism
  left_inv := fun morphism =>
    TraceCorQPresheaf.representablePreimage_representableMap morphism
  right_inv := fun morphism =>
    TraceCorQPresheaf.representableMap_representablePreimage morphism

/-- The forward map of the representable hom equivalence is `representableMap`. -/
theorem TraceCorQPresheaf.representableHomEquiv_apply
    {source target : TraceCorQObject}
    (morphism : source ⟶ target) :
    TraceCorQPresheaf.representableHomEquiv source target morphism =
      TraceCorQPresheaf.representableMap morphism :=
  rfl

/-- The inverse map of the representable hom equivalence is `representablePreimage`. -/
theorem TraceCorQPresheaf.representableHomEquiv_symm_apply
    {source target : TraceCorQObject}
    (morphism :
      TraceCorQPresheafHom
        (TraceCorQPresheaf.representable source)
        (TraceCorQPresheaf.representable target)) :
    (TraceCorQPresheaf.representableHomEquiv source target).symm morphism =
      TraceCorQPresheaf.representablePreimage morphism :=
  rfl

/-- The trace preimage of the identity morphism of a representable is the identity trace. -/
theorem TraceCorQPresheaf.representablePreimage_id
    (object : TraceCorQObject) :
    TraceCorQPresheaf.representablePreimage
      (𝟙 (TraceCorQPresheaf.representable object)) =
      𝟙 object :=
  (TraceCorQPresheaf.yoneda).preimage_id

/-- Trace preimage sends composition of representable morphisms to composition of traces. -/
theorem TraceCorQPresheaf.representablePreimage_comp
    {first second third : TraceCorQObject}
    (left :
      TraceCorQPresheafHom
        (TraceCorQPresheaf.representable first)
        (TraceCorQPresheaf.representable second))
    (right :
      TraceCorQPresheafHom
        (TraceCorQPresheaf.representable second)
        (TraceCorQPresheaf.representable third)) :
    TraceCorQPresheaf.representablePreimage (left ≫ right) =
      TraceCorQPresheaf.representablePreimage left ≫
        TraceCorQPresheaf.representablePreimage right :=
  (TraceCorQPresheaf.yoneda).preimage_comp left right

/-- The component of a representable map at an object is the linear-Yoneda component. -/
theorem TraceCorQPresheaf.representableMap_component
    {source target : TraceCorQObject}
    (morphism : source ⟶ target)
    (object : TraceCorQObject) :
    (TraceCorQPresheaf.representableMap morphism).component object =
      ((TraceCorQPresheaf.yoneda).map morphism).app (Opposite.op object) :=
  rfl

/-- Representable maps preserve identity trace correspondences. -/
theorem TraceCorQPresheaf.representableMap_id
    (object : TraceCorQObject) :
    TraceCorQPresheaf.representableMap (𝟙 object) =
      𝟙 (TraceCorQPresheaf.representable object) :=
  (TraceCorQPresheaf.yoneda).map_id object

/-- Representable maps preserve composition of trace correspondences. -/
theorem TraceCorQPresheaf.representableMap_comp
    {first second third : TraceCorQObject}
    (left : first ⟶ second)
    (right : second ⟶ third) :
    TraceCorQPresheaf.representableMap (left ≫ right) =
      TraceCorQPresheaf.representableMap left ≫
        TraceCorQPresheaf.representableMap right :=
  (TraceCorQPresheaf.yoneda).map_comp left right

end AnalyticMotives
end LFunctions
end Boundary
