import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.ThirdIsoBounded.Rotation.Owner

/-!
# Rotations of localization-input bounded mapping-cone triangles

This file exposes the rotated and inverse-rotated full bounded mapping-cone
triangles generated by localization inputs.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The rotated full bounded mapping-cone triangle generated by a localization input. -/
def TraceLocalizationInput.boundedMappingConeRotatedTriangle
    (input : TraceLocalizationInput) :
    Triangle TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedTriangle
    input.boundedAdditiveComplexHom

/-- The rotated localization-input bounded mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedTriangle_distinguished
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedTriangle_distinguished
    input.boundedAdditiveComplexHom

/-- The inverse-rotated full bounded mapping-cone triangle generated by a localization
input. -/
def TraceLocalizationInput.boundedMappingConeInverseRotatedTriangle
    (input : TraceLocalizationInput) :
    Triangle TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedTriangle
    input.boundedAdditiveComplexHom

/-- The inverse-rotated localization-input bounded mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedTriangle_distinguished
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedTriangle_distinguished
    input.boundedAdditiveComplexHom

end AnalyticMotives
end LFunctions
end Boundary
