import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.Rotation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.ThirdIsoBounded.Rotation.Exactness.Owner

/-!
# Exactness of localization-input rotated bounded mapping-cone triangles

This file specializes rotated and inverse-rotated full bounded mapping-cone
exactness to the concrete bounded maps generated by localization inputs.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The first two morphisms of the localization-input rotated bounded cone compose to
zero. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedTriangle_first_comp_second
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedTriangle.mor₁ ≫
        input.boundedMappingConeRotatedTriangle.mor₂ =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedTriangle_first_comp_second
    input.boundedAdditiveComplexHom

/-- The second and third morphisms of the localization-input rotated bounded cone compose
to zero. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedTriangle_second_comp_third
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedTriangle.mor₂ ≫
        input.boundedMappingConeRotatedTriangle.mor₃ =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedTriangle_second_comp_third
    input.boundedAdditiveComplexHom

/-- The third morphism followed by the shifted first morphism of the localization-input
rotated bounded cone is zero. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedTriangle_third_comp_shifted_first
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedTriangle.mor₃ ≫
        input.boundedMappingConeRotatedTriangle.mor₁⟦(1 : ℤ)⟧' =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedTriangle_third_comp_shifted_first
    input.boundedAdditiveComplexHom

/-- The first two morphisms of the localization-input inverse-rotated bounded cone compose
to zero. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedTriangle_first_comp_second
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedTriangle.mor₁ ≫
        input.boundedMappingConeInverseRotatedTriangle.mor₂ =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedTriangle_first_comp_second
    input.boundedAdditiveComplexHom

/-- The second and third morphisms of the localization-input inverse-rotated bounded cone
compose to zero. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedTriangle_second_comp_third
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedTriangle.mor₂ ≫
        input.boundedMappingConeInverseRotatedTriangle.mor₃ =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedTriangle_second_comp_third
    input.boundedAdditiveComplexHom

/-- The third morphism followed by the shifted first morphism of the localization-input
inverse-rotated bounded cone is zero. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedTriangle_third_comp_shifted_first
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedTriangle.mor₃ ≫
        input.boundedMappingConeInverseRotatedTriangle.mor₁⟦(1 : ℤ)⟧' =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedTriangle_third_comp_shifted_first
    input.boundedAdditiveComplexHom

end AnalyticMotives
end LFunctions
end Boundary
