import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Owner

/-!
# Relation-generator witnesses

This file turns a relation generator into its canonical concrete witness.

The left endpoint is the quotient candidate represented by the generator's
formal support.  The right endpoint is the empty candidate.  This is still
pre-quotient data: it records the finite derivation supplied by the generator.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The quotient input represented by the formal support of a relation generator. -/
def TraceCorQRelationGenerator.supportQuotientInput
    (relation : TraceCorQRelationGenerator) :
    TraceCorQQuotientInput :=
  TraceCorQQuotientInput.ofFormalSumLedger
    relation.support
    (TraceCorQRelationLedger.singleton relation)

/-- The support quotient input has the relation generator support as formal sum. -/
theorem TraceCorQRelationGenerator.supportQuotientInput_formalSum
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportQuotientInput relation).formalSum =
      relation.support :=
  rfl

/-- The support quotient input carries the singleton relation ledger. -/
theorem TraceCorQRelationGenerator.supportQuotientInput_ledger
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportQuotientInput relation).ledger =
      TraceCorQRelationLedger.singleton relation :=
  rfl

/-- The quotient candidate represented by the formal support of a relation generator. -/
def TraceCorQRelationGenerator.supportCandidate
    (relation : TraceCorQRelationGenerator) :
    TraceCorQQuotientCandidate :=
  TraceCorQQuotientCandidate.ofInput
    (TraceCorQRelationGenerator.supportQuotientInput relation)

/-- The support candidate is represented by the support quotient input. -/
theorem TraceCorQRelationGenerator.supportCandidate_input
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportCandidate relation).input =
      TraceCorQRelationGenerator.supportQuotientInput relation :=
  rfl

/-- The support candidate has the relation generator support as formal sum. -/
theorem TraceCorQRelationGenerator.supportCandidate_formalSum
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportCandidate relation).formalSum =
      relation.support :=
  rfl

/-- The support candidate has singleton relation ledger. -/
theorem TraceCorQRelationGenerator.supportCandidate_ledger
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportCandidate relation).ledger =
      TraceCorQRelationLedger.singleton relation :=
  rfl

/-- The canonical closure derivation generated by a relation generator. -/
def TraceCorQRelationGenerator.supportClosure
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationClosure
      (TraceCorQRelationLedger.singleton relation)
      (TraceCorQRelationGenerator.supportCandidate relation)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationClosure.transportLedger
    (TraceCorQRelationLedger.append_empty
      (TraceCorQRelationLedger.singleton relation))
    (TraceCorQRelationClosure.stepDerivation
      TraceCorQRelationLedger.empty
      relation)

/-- The canonical support closure is the singleton-ledger transport of the primitive step. -/
theorem TraceCorQRelationGenerator.supportClosure_eq_transport_step
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationGenerator.supportClosure relation =
      TraceCorQRelationClosure.transportLedger
        (TraceCorQRelationLedger.append_empty
          (TraceCorQRelationLedger.singleton relation))
        (TraceCorQRelationClosure.stepDerivation
          TraceCorQRelationLedger.empty
          relation) :=
  rfl

/-- The canonical relation witness generated by a relation generator. -/
def TraceCorQRelationGenerator.supportWitness
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationWitness
      (TraceCorQRelationGenerator.supportCandidate relation)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationWitness.ofLedgerDerivation
    (TraceCorQRelationLedger.singleton relation)
    (TraceCorQRelationGenerator.supportClosure relation)

/-- The canonical support witness is built from the singleton ledger and support closure. -/
theorem TraceCorQRelationGenerator.supportWitness_eq_ofClosure
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationGenerator.supportWitness relation =
      TraceCorQRelationWitness.ofLedgerDerivation
        (TraceCorQRelationLedger.singleton relation)
        (TraceCorQRelationGenerator.supportClosure relation) :=
  rfl

/-- The canonical support witness has singleton relation ledger. -/
theorem TraceCorQRelationGenerator.supportWitness_ledger
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportWitness relation).ledger =
      TraceCorQRelationLedger.singleton relation :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
