import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourAdmissible.ContourSystem.Refinements.Owner

/-!
# Contour descent covers

This file owns the conservative contour descent cover calculus: contour
refinement covers together with analytified algebraic descent data.  Broader
analytic covers belong only after comparison behavior is controlled.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
A conservative contour descent cover generated by refinement data.  Broader
analytic covers should be added only after their comparison behavior with the
algebraic descent side is controlled.
-/
structure AnalyticContourDescentCover {X : AnalyticBulkCore}
    {B : AnalyticBoundarySystem X}
    (C : AnalyticContourSystem B) where
  target : C.exhaustion.Stage
  CoverIndex : Type
  stage : CoverIndex → C.exhaustion.Stage
  refines :
    (i : CoverIndex) →
      AnalyticContourRefinement
        (C.exhaustion.chain (stage i)) (C.exhaustion.chain target)

namespace AnalyticContourDescentCover

/-- A singleton contour descent cover generated by one refinement. -/
def singletonRefinement {X : AnalyticBulkCore} {B : AnalyticBoundarySystem X}
    {C : AnalyticContourSystem B}
    {refined target : C.exhaustion.Stage}
    (R : AnalyticContourRefinement
        (C.exhaustion.chain refined) (C.exhaustion.chain target)) :
    AnalyticContourDescentCover C where
  target := target
  CoverIndex := Unit
  stage := fun _ => refined
  refines := fun _ => R

/-- The trivial singleton cover of one contour stage. -/
def singleton {X : AnalyticBulkCore} {B : AnalyticBoundarySystem X}
    {C : AnalyticContourSystem B}
    (target : C.exhaustion.Stage) :
    AnalyticContourDescentCover C :=
  singletonRefinement
    (AnalyticContourRefinement.refl (C.exhaustion.chain target))

/-- The target contour stage of a contour descent cover. -/
def targetStage {X : AnalyticBulkCore} {B : AnalyticBoundarySystem X}
    {C : AnalyticContourSystem B}
    (D : AnalyticContourDescentCover C) : C.exhaustion.Stage :=
  D.target

/-- The refinement indexed by a member of a contour descent cover. -/
def refinementAt {X : AnalyticBulkCore} {B : AnalyticBoundarySystem X}
    {C : AnalyticContourSystem B}
    (D : AnalyticContourDescentCover C) (i : D.CoverIndex) :
    AnalyticContourRefinement
      (C.exhaustion.chain (D.stage i)) (C.exhaustion.chain D.target) :=
  D.refines i

/-- The singleton refinement cover has the selected target stage. -/
theorem singleton_targetStage {X : AnalyticBulkCore}
    {B : AnalyticBoundarySystem X}
    {C : AnalyticContourSystem B}
    (target : C.exhaustion.Stage) :
    (singleton target).targetStage = target :=
  rfl

/-- The singleton refinement cover has the selected indexed stage. -/
theorem singleton_stage {X : AnalyticBulkCore}
    {B : AnalyticBoundarySystem X}
    {C : AnalyticContourSystem B}
    (target : C.exhaustion.Stage)
    (i : (singleton target).CoverIndex) :
    (singleton target).stage i = target :=
  match i with
  | Unit.unit => rfl

end AnalyticContourDescentCover

end AnalyticMotives
end LFunctions
end Boundary
