import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.EffectiveRealization.Yoneda.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Endpoints.Source.GeometricGenerator.Owner

/-!
# Stable source boundary for effective realization

This file connects the effective-realization Yoneda source boundary to the
stable analytic comparison-source boundary.  The Yoneda source and stable source
use the same compact generators and the same underlying certified trace
objects; they differ only in the endpoint functor applied after forgetting.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- The stable source functor for effective realization, obtained from compact
geometric analytic generators by the comparison-source endpoint. -/
def TraceAnalyticEffectiveRealization.stableSourceFunctor :
    TraceAnalyticGeometricGenerator ⥤ TraceAnalyticDMgmComparisonSource :=
  TraceAnalyticMotiveComparison.sourceGeneratorFunctor

/-- The effective-realization stable source functor is the comparison source
generator endpoint. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_eq_sourceGenerator :
    TraceAnalyticEffectiveRealization.stableSourceFunctor =
      TraceAnalyticMotiveComparison.sourceGeneratorFunctor :=
  rfl

/-- The effective-realization stable source functor and Yoneda source functor
share the same forgetful prefix to certified trace correspondences. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_eq_forgetful_comp_sourceTrace :
    TraceAnalyticEffectiveRealization.stableSourceFunctor =
      TraceAnalyticGeometricGenerator.forgetfulFunctor ⋙
        TraceAnalyticMotiveComparison.sourceTraceFunctor :=
  rfl

/-- The effective-realization Yoneda source functor is the same forgetful
prefix followed by lifted trace Yoneda. -/
theorem TraceAnalyticEffectiveRealization.yonedaSourceFunctor_eq_commonForgetful_comp_yoneda :
    TraceAnalyticEffectiveRealization.yonedaSourceFunctor =
      TraceAnalyticGeometricGenerator.forgetfulFunctor ⋙
        TraceCorQRepresentablePresheaf.yoneda :=
  TraceAnalyticEffectiveRealization.yonedaSourceFunctor_eq_forgetful_comp_yoneda

/-- The effective-realization stable source functor is the full analytic
four-stage source construction after forgetting compact generators to certified
trace objects. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_eq_full_composite :
    TraceAnalyticEffectiveRealization.stableSourceFunctor =
      TraceAnalyticGeometricGenerator.forgetfulFunctor ⋙
        TraceAnalyticAdditiveObject.singletonFunctor ⋙
          CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject
            (0 : ℤ) ⋙
            TraceAnalyticAdditiveHomotopyCategory.quotientFunctor ⋙
              TraceAnalyticDMgmComparisonSource.quotientFunctor :=
  rfl

/-- Object formula for the effective-realization stable source functor. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_obj
    (generator : TraceAnalyticGeometricGenerator) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.obj generator =
      TraceAnalyticMotiveComparison.sourceGeneratorObject generator :=
  rfl

/-- Map formula for the effective-realization stable source functor. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_map
    {source target : TraceAnalyticGeometricGenerator}
    (hom : source ⟶ target) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.map hom =
      TraceAnalyticMotiveComparison.sourceGeneratorMap hom :=
  rfl

/-- The stable source object and Yoneda source object are generated by the same
underlying certified trace object. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_obj_eq_sourceTraceFunctor_obj_commonTrace
    (generator : TraceAnalyticGeometricGenerator) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.obj generator =
      TraceAnalyticMotiveComparison.sourceTraceFunctor.obj
        (TraceAnalyticGeometricGenerator.forgetfulFunctor.obj generator) :=
  rfl

/-- The stable source object is the comparison-source image of the underlying
endpoint trace homotopy object. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_obj_eq_sourceObjectOf
    (generator : TraceAnalyticGeometricGenerator) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.obj generator =
      TraceAnalyticMotiveComparison.sourceObjectOf
        (TraceAnalyticMotiveComparison.sourceTraceHomotopyObject
          generator.traceObject) :=
  rfl

/-- The stable source object is the stable analytic quotient image of the
underlying endpoint trace homotopy object. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_obj_eq_stable
    (generator : TraceAnalyticGeometricGenerator) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.obj generator =
      TraceAnalyticStableMotiveCategory.objectOf
        (TraceAnalyticMotiveComparison.sourceTraceHomotopyObject
          generator.traceObject) :=
  TraceAnalyticMotiveComparison.sourceGeneratorObject_eq_stable generator

/-- The stable source object is the Verdier quotient-functor image of the
underlying endpoint trace homotopy object. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_obj_eq_quotientFunctor_obj
    (generator : TraceAnalyticGeometricGenerator) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.obj generator =
      TraceAnalyticStableMotiveCategory.quotientFunctor.obj
        (TraceAnalyticMotiveComparison.sourceTraceHomotopyObject
          generator.traceObject) :=
  TraceAnalyticMotiveComparison.sourceGeneratorObject_eq_quotientFunctor_obj
    generator

/-- The stable source map and Yoneda source map are generated by the same
underlying certified trace correspondence. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_map_eq_sourceTraceFunctor_map_commonTrace
    {source target : TraceAnalyticGeometricGenerator}
    (hom : source ⟶ target) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.map hom =
      TraceAnalyticMotiveComparison.sourceTraceFunctor.map
        (TraceAnalyticGeometricGenerator.forgetfulFunctor.map hom) :=
  rfl

/-- The stable source map is the comparison-source image of the underlying
endpoint trace homotopy map. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_map_eq_sourceMapOf
    {source target : TraceAnalyticGeometricGenerator}
    (hom : source ⟶ target) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.map hom =
      TraceAnalyticMotiveComparison.sourceMapOf
        (TraceAnalyticMotiveComparison.sourceTraceHomotopyMap hom.traceHom) :=
  rfl

/-- The stable source map is the stable analytic quotient image of the
underlying endpoint trace homotopy map. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_map_eq_stable
    {source target : TraceAnalyticGeometricGenerator}
    (hom : source ⟶ target) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.map hom =
      TraceAnalyticStableMotiveCategory.mapOf
        (TraceAnalyticMotiveComparison.sourceTraceHomotopyMap hom.traceHom) :=
  TraceAnalyticMotiveComparison.sourceGeneratorMap_eq_stable hom

/-- The stable source map is the Verdier quotient-functor image of the
underlying endpoint trace homotopy map. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_map_eq_quotientFunctor_map
    {source target : TraceAnalyticGeometricGenerator}
    (hom : source ⟶ target) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.map hom =
      TraceAnalyticStableMotiveCategory.quotientFunctor.map
        (TraceAnalyticMotiveComparison.sourceTraceHomotopyMap hom.traceHom) :=
  TraceAnalyticMotiveComparison.sourceGeneratorMap_eq_quotientFunctor_map hom

/-- The stable source functor sends compact-generator identities to stable
source identities. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_map_id
    (generator : TraceAnalyticGeometricGenerator) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.map
        (𝟙 generator) =
      𝟙 (TraceAnalyticEffectiveRealization.stableSourceFunctor.obj generator) :=
  TraceAnalyticEffectiveRealization.stableSourceFunctor.map_id generator

/-- The stable source functor sends compact-generator composites to composites
of stable-source maps. -/
theorem TraceAnalyticEffectiveRealization.stableSourceFunctor_map_comp
    {first second third : TraceAnalyticGeometricGenerator}
    (left : first ⟶ second)
    (right : second ⟶ third) :
    TraceAnalyticEffectiveRealization.stableSourceFunctor.map
        (left ≫ right) =
      TraceAnalyticEffectiveRealization.stableSourceFunctor.map left ≫
        TraceAnalyticEffectiveRealization.stableSourceFunctor.map right :=
  TraceAnalyticEffectiveRealization.stableSourceFunctor.map_comp left right

end AnalyticMotives
end LFunctions
end Boundary
