import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleRelations.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.RelationLedgers.Owner

/-!
# Zero-pole trace-correspondence relation ledger

This file records the first finite relation ledger in the completed-zeta
finite-rectangle adapter.

The ledger is the singleton containing the zero-pole residue-channel relation
generator.  It remains pre-quotient data.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The singleton relation ledger for the completed-zeta zero-pole seed. -/
def completedZetaZeroPoleTraceCorQRelationLedger :
    TraceCorQRelationLedger :=
  TraceCorQRelationLedger.singleton
    completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator

/-- The zero-pole relation ledger is the singleton generated by residue-channel coherence. -/
theorem completedZetaZeroPoleTraceCorQRelationLedger_eq_singleton :
    completedZetaZeroPoleTraceCorQRelationLedger =
      [completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator] :=
  rfl

/-- Appending the zero-pole singleton relation ledger conses its relation generator. -/
theorem completedZetaZeroPoleTraceCorQRelationLedger_append
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.append
      completedZetaZeroPoleTraceCorQRelationLedger
      ledger =
      completedZetaZeroPoleResidueChannelTraceCorQRelationGenerator ::
        ledger :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
