import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Inputs.ByKind.Isomorphisms.Cancellation.Owner

/-!
# Interval-homotopy localized arrows

This file exposes Stokes deformation and Fubini interchange as invertible
arrows in the formal localized word category.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized isomorphism generated by interval Stokes deformation. -/
def TraceIntervalHomotopyLocalization.stokesIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalStokes source target).localizedSourceObject
      (TraceLocalizationInput.intervalStokes source target).localizedTargetObject :=
  TraceLocalizationInput.intervalStokesLocalizedIso source target

/-- The localized isomorphism generated by interval Fubini interchange. -/
def TraceIntervalHomotopyLocalization.fubiniIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalFubini source target).localizedSourceObject
      (TraceLocalizationInput.intervalFubini source target).localizedTargetObject :=
  TraceLocalizationInput.intervalFubiniLocalizedIso source target

/-- The hom of the interval-Stokes isomorphism is the named Stokes forward arrow. -/
theorem TraceIntervalHomotopyLocalization.stokesIso_hom
    (source target : QTraceExpression) :
    (TraceIntervalHomotopyLocalization.stokesIso source target).hom =
      TraceLocalizationInput.intervalStokesForwardArrow source target :=
  rfl

/-- The inverse of the interval-Stokes isomorphism is the named Stokes inverse arrow. -/
theorem TraceIntervalHomotopyLocalization.stokesIso_inv
    (source target : QTraceExpression) :
    (TraceIntervalHomotopyLocalization.stokesIso source target).inv =
      TraceLocalizationInput.intervalStokesInverseArrow source target :=
  rfl

/-- The hom of the interval-Fubini isomorphism is the named Fubini forward arrow. -/
theorem TraceIntervalHomotopyLocalization.fubiniIso_hom
    (source target : QTraceExpression) :
    (TraceIntervalHomotopyLocalization.fubiniIso source target).hom =
      TraceLocalizationInput.intervalFubiniForwardArrow source target :=
  rfl

/-- The inverse of the interval-Fubini isomorphism is the named Fubini inverse arrow. -/
theorem TraceIntervalHomotopyLocalization.fubiniIso_inv
    (source target : QTraceExpression) :
    (TraceIntervalHomotopyLocalization.fubiniIso source target).inv =
      TraceLocalizationInput.intervalFubiniInverseArrow source target :=
  rfl

/-- Interval-Stokes hom followed by inverse is identity. -/
theorem TraceIntervalHomotopyLocalization.stokesIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceIntervalHomotopyLocalization.stokesIso source target).hom
        (TraceIntervalHomotopyLocalization.stokesIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalStokes source target).sourceObject :=
  TraceLocalizationInput.intervalStokesLocalizedIso_hom_comp_inv source target

/-- Interval-Stokes inverse followed by hom is identity. -/
theorem TraceIntervalHomotopyLocalization.stokesIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceIntervalHomotopyLocalization.stokesIso source target).inv
        (TraceIntervalHomotopyLocalization.stokesIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalStokes source target).targetObject :=
  TraceLocalizationInput.intervalStokesLocalizedIso_inv_comp_hom source target

/-- Interval-Fubini hom followed by inverse is identity. -/
theorem TraceIntervalHomotopyLocalization.fubiniIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceIntervalHomotopyLocalization.fubiniIso source target).hom
        (TraceIntervalHomotopyLocalization.fubiniIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalFubini source target).sourceObject :=
  TraceLocalizationInput.intervalFubiniLocalizedIso_hom_comp_inv source target

/-- Interval-Fubini inverse followed by hom is identity. -/
theorem TraceIntervalHomotopyLocalization.fubiniIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceIntervalHomotopyLocalization.fubiniIso source target).inv
        (TraceIntervalHomotopyLocalization.fubiniIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalFubini source target).targetObject :=
  TraceLocalizationInput.intervalFubiniLocalizedIso_inv_comp_hom source target

end AnalyticMotives
end LFunctions
end Boundary
