import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Weights.Source.Bounds.Stable.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.ThirdObject.Maps.Connecting.Owner

/-!
# Bounded mapping-cone triangles for analytic comparison

This file exposes bounded mapping-cone triangles in the additive analytic
homotopy category under comparison-facing names, including the cone vertex,
cone-inclusion map, and connecting map.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- First comparison-source bounded representative in a bounded mapping-cone
triangle. -/
def TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstObject
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject hom

/-- Second comparison-source bounded representative in a bounded mapping-cone
triangle. -/
def TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondObject
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject hom

/-- Third comparison-source bounded representative in a bounded mapping-cone
triangle. -/
def TraceAnalyticMotiveComparison.SourceBoundedMappingCone.thirdObject
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject hom

/-- First morphism of a comparison-source bounded mapping-cone triangle. -/
def TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstMap
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstObject hom ⟶
      TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondObject hom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap hom

/-- Second morphism of a comparison-source bounded mapping-cone triangle. -/
def TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondMap
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondObject hom ⟶
      TraceAnalyticMotiveComparison.SourceBoundedMappingCone.thirdObject hom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondMap hom

/-- Connecting morphism of a comparison-source bounded mapping-cone triangle. -/
def TraceAnalyticMotiveComparison.SourceBoundedMappingCone.connectingMap
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.thirdObject hom ⟶
      (TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstObject
        hom)⟦(1 : ℤ)⟧ :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.connectingMap hom

/-- The comparison-source bounded mapping-cone triangle generated by a bounded
chain map. -/
def TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    Triangle TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle hom

/-- The first comparison-source bounded representative is the bounded homotopy
object of the source. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstObject_eq
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstObject hom =
      TraceAnalyticMotiveComparison.sourceWeightBoundedHomotopyObject source :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject_eq hom

/-- The second comparison-source bounded representative is the bounded homotopy
object of the target. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondObject_eq
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondObject hom =
      TraceAnalyticMotiveComparison.sourceWeightBoundedHomotopyObject target :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject_eq hom

/-- The third comparison-source bounded mapping-cone representative is the
homotopy image of the concrete mapping-cone complex. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.thirdObject_eq
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.thirdObject hom =
      TraceAnalyticAdditiveHomotopyCategory.objectOf
        (CochainComplex.mappingCone hom) :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject_eq hom

/-- The first comparison-source bounded mapping-cone map is the bounded
homotopy map. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstMap_eq
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.firstMap hom =
      TraceAnalyticMotiveComparison.sourceWeightBoundedHomotopyMap hom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap_eq hom

/-- The second comparison-source bounded mapping-cone map is the cone-inclusion
map into the concrete mapping-cone complex. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondMap_eq
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondMap hom =
      TraceAnalyticAdditiveHomotopyCategory.mapOf
        (CochainComplex.mappingCone.inr hom) :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondMap_eq hom

/-- The comparison-source bounded mapping-cone connecting map is the third
morphism of the bounded mapping-cone triangle. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.connectingMap_eq
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.connectingMap hom =
      (TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle hom).mor₃ :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.connectingMap_eq hom

/-- The third vertex of the comparison-source bounded mapping-cone triangle is
the named third object. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle_obj₃
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    (TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle hom).obj₃ =
      TraceAnalyticMotiveComparison.SourceBoundedMappingCone.thirdObject hom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle_obj₃ hom

/-- The second morphism of the comparison-source bounded mapping-cone triangle
is the named second map. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle_mor₂
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    (TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle hom).mor₂ =
      TraceAnalyticMotiveComparison.SourceBoundedMappingCone.secondMap hom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle_mor₂ hom

/-- The third morphism of the comparison-source bounded mapping-cone triangle
is the named connecting map. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle_mor₃
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    (TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle hom).mor₃ =
      TraceAnalyticMotiveComparison.SourceBoundedMappingCone.connectingMap hom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle_mor₃ hom

/-- The comparison-source bounded mapping-cone triangle is the ordinary
mapping-cone triangle of the underlying bounded chain map. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle_eq
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle hom =
      CochainComplex.mappingCone.triangleh hom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle_eq hom

/-- The comparison-source bounded mapping-cone triangle is distinguished. -/
theorem TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle_distinguished
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticMotiveComparison.SourceBoundedMappingCone.triangle hom ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle_distinguished
    hom

end AnalyticMotives
end LFunctions
end Boundary
