import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Presheaves.RewriteMaps.ByKind.Endpoints.Owner

/-!
# By-kind rewrite presheaf maps

This file names the representable presheaf maps and lifted Yoneda-subcategory
maps for the seven primitive analytic rewrite kinds.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The representable map generated by a Stokes cancellation rewrite. -/
def TraceRewriteGenerator.stokesRepresentableMap
    (source target : QTraceExpression) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.stokes source target).sourceObject)
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.stokes source target).targetObject) :=
  (TraceRewriteGenerator.stokes source target).representableMap

/-- The representable map generated by a residue-extraction rewrite. -/
def TraceRewriteGenerator.residueRepresentableMap
    (source target : QTraceExpression) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.residue source target).sourceObject)
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.residue source target).targetObject) :=
  (TraceRewriteGenerator.residue source target).representableMap

/-- The representable map generated by a channel-decomposition rewrite. -/
def TraceRewriteGenerator.channelRepresentableMap
    (source target : QTraceExpression) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.channel source target).sourceObject)
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.channel source target).targetObject) :=
  (TraceRewriteGenerator.channel source target).representableMap

/-- The representable map generated by a refinement-invariance rewrite. -/
def TraceRewriteGenerator.refinementRepresentableMap
    (source target : QTraceExpression) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.refinement source target).sourceObject)
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.refinement source target).targetObject) :=
  (TraceRewriteGenerator.refinement source target).representableMap

/-- The representable map generated by a schedule-exchange rewrite. -/
def TraceRewriteGenerator.scheduleRepresentableMap
    (source target : QTraceExpression) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.schedule source target).sourceObject)
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.schedule source target).targetObject) :=
  (TraceRewriteGenerator.schedule source target).representableMap

/-- The representable map generated by a weight-drop rewrite. -/
def TraceRewriteGenerator.weightDropRepresentableMap
    (source target : QTraceExpression) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.weightDrop source target).sourceObject)
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.weightDrop source target).targetObject) :=
  (TraceRewriteGenerator.weightDrop source target).representableMap

/-- The representable map generated by a Fubini coherence rewrite. -/
def TraceRewriteGenerator.fubiniRepresentableMap
    (source target : QTraceExpression) :
    TraceCorQPresheafHom
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.fubini source target).sourceObject)
      (TraceCorQPresheaf.representable
        (TraceRewriteGenerator.fubini source target).targetObject) :=
  (TraceRewriteGenerator.fubini source target).representableMap

/-- The lifted representable-subcategory map generated by a Stokes cancellation rewrite. -/
def TraceRewriteGenerator.stokesRepresentableSubcategoryMap
    (source target : QTraceExpression) :
    (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.stokes source target).sourceObject ⟶
      (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.stokes source target).targetObject :=
  (TraceRewriteGenerator.stokes source target).representableSubcategoryMap

/-- The lifted representable-subcategory map generated by a residue-extraction rewrite. -/
def TraceRewriteGenerator.residueRepresentableSubcategoryMap
    (source target : QTraceExpression) :
    (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.residue source target).sourceObject ⟶
      (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.residue source target).targetObject :=
  (TraceRewriteGenerator.residue source target).representableSubcategoryMap

/-- The lifted representable-subcategory map generated by a channel-decomposition rewrite. -/
def TraceRewriteGenerator.channelRepresentableSubcategoryMap
    (source target : QTraceExpression) :
    (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.channel source target).sourceObject ⟶
      (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.channel source target).targetObject :=
  (TraceRewriteGenerator.channel source target).representableSubcategoryMap

/-- The lifted representable-subcategory map generated by a refinement-invariance rewrite. -/
def TraceRewriteGenerator.refinementRepresentableSubcategoryMap
    (source target : QTraceExpression) :
    (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.refinement source target).sourceObject ⟶
      (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.refinement source target).targetObject :=
  (TraceRewriteGenerator.refinement source target).representableSubcategoryMap

/-- The lifted representable-subcategory map generated by a schedule-exchange rewrite. -/
def TraceRewriteGenerator.scheduleRepresentableSubcategoryMap
    (source target : QTraceExpression) :
    (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.schedule source target).sourceObject ⟶
      (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.schedule source target).targetObject :=
  (TraceRewriteGenerator.schedule source target).representableSubcategoryMap

/-- The lifted representable-subcategory map generated by a weight-drop rewrite. -/
def TraceRewriteGenerator.weightDropRepresentableSubcategoryMap
    (source target : QTraceExpression) :
    (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.weightDrop source target).sourceObject ⟶
      (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.weightDrop source target).targetObject :=
  (TraceRewriteGenerator.weightDrop source target).representableSubcategoryMap

/-- The lifted representable-subcategory map generated by a Fubini coherence rewrite. -/
def TraceRewriteGenerator.fubiniRepresentableSubcategoryMap
    (source target : QTraceExpression) :
    (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.fubini source target).sourceObject ⟶
      (TraceCorQRepresentablePresheaf.yoneda).obj
        (TraceRewriteGenerator.fubini source target).targetObject :=
  (TraceRewriteGenerator.fubini source target).representableSubcategoryMap

end AnalyticMotives
end LFunctions
end Boundary
