import Boundary.LFunctionsRootedTreeFinal.Final.RiemannHypothesisBridge.Bridge.WeilCriterion.Zero.ZetaWeilShared.ZetaZeroSideDefinitions.ZetaCenteredZeroCounting.ZetaCompletedLogDerivativeBridge.ZetaExplicitFormulaComplexAnalysis.FiniteRectangleResidues.OwnerParts.Part20Parts.Part20_12

/-!
# Explicit-formula finite rectangle residues

This owner layer contains finite-rectangle residue equalities, scheduled avoidance, and residue-window error transport.
-/

namespace Boundary
namespace LFunctions

noncomputable section

open Complex
open Filter
open MeasureTheory
open scoped Topology

namespace ZetaAdmissibleFunction

/-!
## Part20 13: XAdjacentTotals
-/

noncomputable def explicitFormulaRectangleHorizontalOuterSliceContribution
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily) (T : ℝ)
    {ρ : ℝ}
    (xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ) : ℂ :=
  explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
      f ((xpair.x₀, xpair.x₁), -T) -
    explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
      f ((xpair.x₀, xpair.x₁), T)

/-- The proof-carrying horizontal adjacent pair at a concrete index in the sorted
horizontal endpoint list.  This names the `List.ofFn` generator used by
`explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints`. -/
noncomputable def explicitFormulaRectangleXAdjacentEndpointPairAt
    (F : ExplicitFormulaContourFamily) (T ρ : ℝ)
    (i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1)) :
    ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ :=
  let xs := explicitFormulaRectangleSortedXEndpoints F T ρ
  let i₀ : Fin xs.length :=
    ⟨i.1,
      lt_trans (Nat.lt_succ_self i.1)
        ((Nat.lt_sub_iff_add_lt (a := i.1) (b := 1) (c := xs.length)).mp i.2)⟩
  let i₁ : Fin xs.length :=
    ⟨i.1 + 1,
      ((Nat.lt_sub_iff_add_lt (a := i.1) (b := 1) (c := xs.length)).mp i.2)⟩
  { x₀ := xs.get i₀
    x₁ := xs.get i₁
    hx₀ :=
      (explicitFormulaRectangleSortedXEndpoints_mem_iff F T ρ (xs.get i₀)).mp
        (List.get_mem xs i₀ i₀.2)
    hx₁ :=
      (explicitFormulaRectangleSortedXEndpoints_mem_iff F T ρ (xs.get i₁)).mp
        (List.get_mem xs i₁ i₁.2)
    hx_order :=
      (explicitFormulaRectangleSortedXEndpoints_sorted_lt F T ρ).rel_get_of_lt
        (show i₀ < i₁ from Nat.lt_succ_self i.1)
    hx_adj :=
      explicitFormulaRectangleSortedXEndpoints_noIntermediate_get_succ F T ρ i }

/-- The sorted horizontal adjacent-pair list is generated by
`explicitFormulaRectangleXAdjacentEndpointPairAt`. -/
theorem explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints_eq_ofFn_pairAt
    (F : ExplicitFormulaContourFamily) (T ρ : ℝ) :
    explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ =
      List.ofFn
        (fun i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1) =>
          explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i) := by
  rfl

/-- Recursive sums over the sorted horizontal adjacent-pair list are finite sums over the
named adjacent-pair generator. -/
theorem explicitFormulaRectangleListSum_XAdjacentEndpointPairsFromSortedEndpoints_eq_indexSum
    {F : ExplicitFormulaContourFamily} {T ρ : ℝ}
    (g : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ → ℂ) :
    explicitFormulaRectangleListSum g
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
      ∑ i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1),
        g (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i) := by
  calc
    explicitFormulaRectangleListSum g
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
        explicitFormulaRectangleListSum g
          (List.ofFn
            (fun i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1) =>
              explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i)) := by
      exact congrArg
        (fun xs : List (ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ) =>
          explicitFormulaRectangleListSum g xs)
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints_eq_ofFn_pairAt F T ρ)
    _ =
        ∑ i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1),
          g (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i) := by
      exact
        explicitFormulaRectangleListSum_ofFn
          (fun i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1) =>
            explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i)
          g

/-- The lower coordinate of the indexed horizontal adjacent pair is the clamped sorted
endpoint at the same index. -/
theorem explicitFormulaRectangleXAdjacentEndpointPairAt_x₀
    (F : ExplicitFormulaContourFamily) (T ρ : ℝ)
    (i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1)) :
    (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i).x₀ =
      explicitFormulaRectangleSortedXEndpointAt F T ρ i.1 := by
  let xs : List ℝ := explicitFormulaRectangleSortedXEndpoints F T ρ
  have hi_lt_len : i.1 < xs.length :=
    lt_trans (Nat.lt_succ_self i.1)
      ((Nat.lt_sub_iff_add_lt (a := i.1) (b := 1) (c := xs.length)).mp i.2)
  calc
    (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i).x₀ =
        xs.get ⟨i.1, hi_lt_len⟩ := by
      rfl
    _ = explicitFormulaRectangleSortedXEndpointAt F T ρ i.1 := by
      exact (explicitFormulaRectangleSortedXEndpointAt_of_lt F T ρ hi_lt_len).symm

/-- The upper coordinate of the indexed horizontal adjacent pair is the next clamped
sorted endpoint. -/
theorem explicitFormulaRectangleXAdjacentEndpointPairAt_x₁
    (F : ExplicitFormulaContourFamily) (T ρ : ℝ)
    (i : Fin ((explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1)) :
    (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i).x₁ =
      explicitFormulaRectangleSortedXEndpointAt F T ρ (i.1 + 1) := by
  let xs : List ℝ := explicitFormulaRectangleSortedXEndpoints F T ρ
  have hi_succ_lt_len : i.1 + 1 < xs.length :=
    ((Nat.lt_sub_iff_add_lt
      (a := i.1) (b := 1) (c := xs.length)).mp i.2)
  calc
    (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i).x₁ =
        xs.get ⟨i.1 + 1, hi_succ_lt_len⟩ := by
      rfl
    _ = explicitFormulaRectangleSortedXEndpointAt F T ρ (i.1 + 1) := by
      exact (explicitFormulaRectangleSortedXEndpointAt_of_lt F T ρ hi_succ_lt_len).symm

/-- Right vertical coordinate labels over all horizontal adjacent pairs are the forward
endpoint edge sequence. -/
theorem explicitFormulaRectangleXAdjacentEndpointPair_totalRightVerticalListSum_eq_ofFn
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    {T ρ : ℝ}
    (ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ) :
    let n : ℕ := (explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1
    explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₁))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
      explicitFormulaRectangleListSum
        (fun i : Fin n =>
          explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁),
              explicitFormulaRectangleSortedXEndpointAt F T ρ (i.1 + 1)))
        (List.ofFn (fun i : Fin n => i)) := by
  let n : ℕ := (explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1
  calc
    explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₁))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁),
                (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i).x₁))
          (List.ofFn (fun i : Fin n => i)) := by
      rfl
    _ =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁),
                explicitFormulaRectangleSortedXEndpointAt F T ρ (i.1 + 1)))
          (List.ofFn (fun i : Fin n => i)) := by
      exact congrArg
        (fun g : Fin n → ℂ =>
          explicitFormulaRectangleListSum g (List.ofFn (fun i : Fin n => i)))
        (funext
          (fun i =>
            congrArg
              (fun x : ℝ =>
                explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
                  f ((ypair.y₀, ypair.y₁), x))
              (explicitFormulaRectangleXAdjacentEndpointPairAt_x₁ F T ρ i)))

/-- Left vertical coordinate labels over all horizontal adjacent pairs are the backward
endpoint edge sequence. -/
theorem explicitFormulaRectangleXAdjacentEndpointPair_totalLeftVerticalListSum_eq_ofFn
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    {T ρ : ℝ}
    (ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ) :
    let n : ℕ := (explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1
    explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₀))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
      explicitFormulaRectangleListSum
        (fun i : Fin n =>
          explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁),
              explicitFormulaRectangleSortedXEndpointAt F T ρ i.1))
        (List.ofFn (fun i : Fin n => i)) := by
  let n : ℕ := (explicitFormulaRectangleSortedXEndpoints F T ρ).length - 1
  calc
    explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₀))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁),
                (explicitFormulaRectangleXAdjacentEndpointPairAt F T ρ i).x₀))
          (List.ofFn (fun i : Fin n => i)) := by
      rfl
    _ =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁),
                explicitFormulaRectangleSortedXEndpointAt F T ρ i.1))
          (List.ofFn (fun i : Fin n => i)) := by
      exact congrArg
        (fun g : Fin n → ℂ =>
          explicitFormulaRectangleListSum g (List.ofFn (fun i : Fin n => i)))
        (funext
          (fun i =>
            congrArg
              (fun x : ℝ =>
                explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
                  f ((ypair.y₀, ypair.y₁), x))
              (explicitFormulaRectangleXAdjacentEndpointPairAt_x₀ F T ρ i)))

/-- The paired right-minus-left scan over all horizontal adjacent pairs telescopes to the
outer right-minus-left vertical slice. -/
theorem explicitFormulaRectangleXAdjacentEndpointPair_totalVerticalScanSub_eq_outerSub
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    {T ρ : ℝ} (hρ : 0 < ρ)
    (hclosed :
      ∀ a : ℂ,
        a ∈ explicitFormulaRectangleRawSingularCoordinates T →
          Metric.closedBall a ρ ⊆ explicitFormulaContourFamilyInterior F T)
    (ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ) :
    explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₁))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) -
      explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₀))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
      explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
          f ((ypair.y₀, ypair.y₁), F.c) -
        explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
          f ((ypair.y₀, ypair.y₁), 1 - F.c) := by
  let xs : List ℝ := explicitFormulaRectangleSortedXEndpoints F T ρ
  let n : ℕ := xs.length - 1
  let endpoint : ℕ → ℂ :=
    fun k =>
      explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
        f ((ypair.y₀, ypair.y₁), explicitFormulaRectangleSortedXEndpointAt F T ρ k)
  have hfirst :
      explicitFormulaRectangleSortedXEndpointAt F T ρ 0 = 1 - F.c := by
    have h0 : 0 < xs.length :=
      explicitFormulaRectangleSortedXEndpoints_length_pos F T ρ
    calc
      explicitFormulaRectangleSortedXEndpointAt F T ρ 0 =
          xs.get ⟨0, h0⟩ := by
        exact explicitFormulaRectangleSortedXEndpointAt_of_lt F T ρ h0
      _ = 1 - F.c := by
        exact explicitFormulaRectangleSortedXEndpoints_first_eq_outerLeft F hρ hclosed
  have hlast :
      explicitFormulaRectangleSortedXEndpointAt F T ρ n = F.c := by
    have hlast_lt : xs.length - 1 < xs.length :=
      Nat.sub_lt
        (explicitFormulaRectangleSortedXEndpoints_length_pos F T ρ)
        Nat.zero_lt_one
    calc
      explicitFormulaRectangleSortedXEndpointAt F T ρ n =
          xs.get ⟨xs.length - 1, hlast_lt⟩ := by
        exact explicitFormulaRectangleSortedXEndpointAt_of_lt F T ρ hlast_lt
      _ = F.c := by
        exact explicitFormulaRectangleSortedXEndpoints_last_eq_outerRight F hρ hclosed
  have hpair :
      explicitFormulaRectangleListSum
          (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
            explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁), xpair.x₁))
          (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) -
        explicitFormulaRectangleListSum
          (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
            explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁), xpair.x₀))
          (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n => endpoint (i.1 + 1) - endpoint i.1)
          (List.ofFn (fun i : Fin n => i)) := by
    have hright :=
      explicitFormulaRectangleXAdjacentEndpointPair_totalRightVerticalListSum_eq_ofFn
        f F ypair
    have hleft :=
      explicitFormulaRectangleXAdjacentEndpointPair_totalLeftVerticalListSum_eq_ofFn
        f F ypair
    calc
      explicitFormulaRectangleListSum
          (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
            explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁), xpair.x₁))
          (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) -
        explicitFormulaRectangleListSum
          (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
            explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁), xpair.x₀))
          (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint (i.1 + 1))
            (List.ofFn (fun i : Fin n => i)) -
          explicitFormulaRectangleListSum
            (fun i : Fin n =>
              explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
                f ((ypair.y₀, ypair.y₁),
                  explicitFormulaRectangleSortedXEndpointAt F T ρ i.1))
            (List.ofFn (fun i : Fin n => i)) := by
        exact congrArg₂ HSub.hSub hright hleft
      _ =
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint (i.1 + 1))
            (List.ofFn (fun i : Fin n => i)) -
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint i.1)
            (List.ofFn (fun i : Fin n => i)) := by
        exact congrArg
          (fun z : ℂ =>
            explicitFormulaRectangleListSum
              (fun i : Fin n => endpoint (i.1 + 1))
              (List.ofFn (fun i : Fin n => i)) - z)
          (congrArg
            (fun g : Fin n → ℂ =>
              explicitFormulaRectangleListSum g (List.ofFn (fun i : Fin n => i)))
            (funext
              (fun i =>
                (explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral_eq_left_sameCoordinate
                  f ypair.y₀ ypair.y₁
                  (explicitFormulaRectangleSortedXEndpointAt F T ρ i.1)).symm)))
      _ =
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint (i.1 + 1) - endpoint i.1)
            (List.ofFn (fun i : Fin n => i)) := by
        exact
          (explicitFormulaRectangleListSum_sub
            (fun i : Fin n => endpoint (i.1 + 1))
            (fun i : Fin n => endpoint i.1)
            (List.ofFn (fun i : Fin n => i))).symm
  have htelescope :
      explicitFormulaRectangleListSum
          (fun i : Fin n => endpoint (i.1 + 1) - endpoint i.1)
          (List.ofFn (fun i : Fin n => i)) =
        endpoint n - endpoint 0 :=
    explicitFormulaRectangleListSum_ofFn_consecutiveForwardDifferences endpoint
  calc
    explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₁))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) -
      explicitFormulaRectangleListSum
        (fun xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ =>
          explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), xpair.x₀))
        (explicitFormulaRectangleXAdjacentEndpointPairsFromSortedEndpoints F T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n => endpoint (i.1 + 1) - endpoint i.1)
          (List.ofFn (fun i : Fin n => i)) := by
      exact hpair
    _ = endpoint n - endpoint 0 := by
      exact htelescope
    _ =
        explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), F.c) -
          explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), 1 - F.c) := by
      exact congrArg₂ HSub.hSub
        (congrArg
          (fun x : ℝ =>
            explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁), x))
          hlast)
        (congrArg
          (fun x : ℝ =>
            explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
              f ((ypair.y₀, ypair.y₁), x))
          hfirst)
    _ =
        explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), F.c) -
          explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), 1 - F.c) := by
      exact congrArg
        (fun z : ℂ =>
          explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
            f ((ypair.y₀, ypair.y₁), F.c) - z)
        (explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral_eq_left_sameCoordinate
          f ypair.y₀ ypair.y₁ (1 - F.c))

/-- A sorted horizontal adjacent-pair subspan lies on the horizontal side of a raw
inscribed-square hole.  This is a containment predicate because the global vertical
subdivision can split one hole side into several adjacent subspans. -/

end ZetaAdmissibleFunction

end
end LFunctions
end Boundary
