import Boundary.LFunctionsRootedTreeFinal.Final.RiemannHypothesisBridge.Bridge.WeilCriterion.Zero.ZetaWeilShared.ZetaZeroSideDefinitions.ZetaCenteredZeroCounting.ZetaCompletedLogDerivativeBridge.ZetaExplicitFormulaComplexAnalysis.FiniteRectangleResidues.OwnerParts.Part20Parts.Part20_07

/-!
# Explicit-formula finite rectangle residues

This owner layer contains finite-rectangle residue equalities, scheduled avoidance, and residue-window error transport.
-/

namespace Boundary
namespace LFunctions

noncomputable section

open Complex
open Filter
open MeasureTheory
open scoped Topology

namespace ZetaAdmissibleFunction

/-!
## Part20 08: TotalHorizontalTelescopes
-/

theorem explicitFormulaRectangleListSum_selectSub_eq_totalSub_sub_rejectSub
    {α : Type} (P : α → Prop) [DecidablePred P]
    (lower upper : α → ℂ) (xs : List α) :
    explicitFormulaRectangleListSum
        (fun x : α => if _h : P x then lower x else 0) xs -
      explicitFormulaRectangleListSum
        (fun x : α => if _h : P x then upper x else 0) xs =
      (explicitFormulaRectangleListSum lower xs -
        explicitFormulaRectangleListSum upper xs) -
        (explicitFormulaRectangleListSum
          (fun x : α => if _h : P x then 0 else lower x) xs -
          explicitFormulaRectangleListSum
            (fun x : α => if _h : P x then 0 else upper x) xs) := by
  let selectedLower : ℂ :=
    explicitFormulaRectangleListSum
      (fun x : α => if _h : P x then lower x else 0) xs
  let selectedUpper : ℂ :=
    explicitFormulaRectangleListSum
      (fun x : α => if _h : P x then upper x else 0) xs
  let totalLower : ℂ := explicitFormulaRectangleListSum lower xs
  let totalUpper : ℂ := explicitFormulaRectangleListSum upper xs
  let rejectedLower : ℂ :=
    explicitFormulaRectangleListSum
      (fun x : α => if _h : P x then 0 else lower x) xs
  let rejectedUpper : ℂ :=
    explicitFormulaRectangleListSum
      (fun x : α => if _h : P x then 0 else upper x) xs
  have hlower :
      selectedLower = totalLower - rejectedLower :=
    explicitFormulaRectangleListSum_select_eq_total_sub_reject P lower xs
  have hupper :
      selectedUpper = totalUpper - rejectedUpper :=
    explicitFormulaRectangleListSum_select_eq_total_sub_reject P upper xs
  have hpaired :
      (totalLower - totalUpper) - (rejectedLower - rejectedUpper) =
        (totalLower - rejectedLower) - (totalUpper - rejectedUpper) :=
    explicitFormulaRectangle_outerMinusHole_sub_eq_sub_sub
      totalLower totalUpper rejectedLower rejectedUpper
  calc
    selectedLower - selectedUpper =
        (totalLower - rejectedLower) - selectedUpper := by
      exact congrArg (fun z : ℂ => z - selectedUpper) hlower
    _ = (totalLower - rejectedLower) - (totalUpper - rejectedUpper) := by
      exact congrArg (fun z : ℂ => (totalLower - rejectedLower) - z) hupper
    _ = (totalLower - totalUpper) - (rejectedLower - rejectedUpper) := by
      exact hpaired.symm

/-- Outer vertical contribution carried by one sorted vertical slice. -/
noncomputable def explicitFormulaRectangleVerticalOuterSliceContribution
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily) (T : ℝ)
    {ρ : ℝ}
    (ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ) : ℂ :=
  explicitFormulaRectangleRightVerticalEndpointDataEdgeIntegral
      f ((ypair.y₀, ypair.y₁), F.c) -
    explicitFormulaRectangleLeftVerticalEndpointDataEdgeIntegral
      f ((ypair.y₀, ypair.y₁), 1 - F.c)

/-- The proof-carrying vertical adjacent pair at a concrete index in the sorted vertical
endpoint list.  This names the `List.ofFn` generator used by
`explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints`. -/
noncomputable def explicitFormulaRectangleYAdjacentEndpointPairAt
    (T ρ : ℝ)
    (i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1)) :
    ExplicitFormulaRectangleYAdjacentEndpointPair T ρ :=
  let ys := explicitFormulaRectangleSortedYEndpoints T ρ
  let i₀ : Fin ys.length :=
    ⟨i.1,
      lt_trans (Nat.lt_succ_self i.1)
        ((Nat.lt_sub_iff_add_lt (a := i.1) (b := 1) (c := ys.length)).mp i.2)⟩
  let i₁ : Fin ys.length :=
    ⟨i.1 + 1,
      ((Nat.lt_sub_iff_add_lt (a := i.1) (b := 1) (c := ys.length)).mp i.2)⟩
  { y₀ := ys.get i₀
    y₁ := ys.get i₁
    hy₀ :=
      (explicitFormulaRectangleSortedYEndpoints_mem_iff T ρ (ys.get i₀)).mp
        (List.get_mem ys i₀ i₀.2)
    hy₁ :=
      (explicitFormulaRectangleSortedYEndpoints_mem_iff T ρ (ys.get i₁)).mp
        (List.get_mem ys i₁ i₁.2)
    hy_order :=
      (explicitFormulaRectangleSortedYEndpoints_sorted_lt T ρ).rel_get_of_lt
        (show i₀ < i₁ from Nat.lt_succ_self i.1)
    hy_adj :=
      explicitFormulaRectangleSortedYEndpoints_noIntermediate_get_succ T ρ i }

/-- The sorted vertical adjacent-pair list is generated by
`explicitFormulaRectangleYAdjacentEndpointPairAt`. -/
theorem explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints_eq_ofFn_pairAt
    (T ρ : ℝ) :
    explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ =
      List.ofFn
        (fun i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1) =>
          explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i) := by
  rfl

/-- Recursive sums over the sorted vertical adjacent-pair list are finite sums over the
named adjacent-pair generator. -/
theorem explicitFormulaRectangleListSum_YAdjacentEndpointPairsFromSortedEndpoints_eq_indexSum
    {T ρ : ℝ}
    (g : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ → ℂ) :
    explicitFormulaRectangleListSum g
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
      ∑ i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1),
        g (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i) := by
  calc
    explicitFormulaRectangleListSum g
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
        explicitFormulaRectangleListSum g
          (List.ofFn
            (fun i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1) =>
              explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i)) := by
      exact congrArg
        (fun xs : List (ExplicitFormulaRectangleYAdjacentEndpointPair T ρ) =>
          explicitFormulaRectangleListSum g xs)
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints_eq_ofFn_pairAt T ρ)
    _ =
        ∑ i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1),
          g (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i) := by
      exact
        explicitFormulaRectangleListSum_ofFn
          (fun i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1) =>
            explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i)
          g

/-- The lower coordinate of the indexed vertical adjacent pair is the clamped sorted
endpoint at the same index. -/
theorem explicitFormulaRectangleYAdjacentEndpointPairAt_y₀
    (T ρ : ℝ)
    (i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1)) :
    (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i).y₀ =
      explicitFormulaRectangleSortedYEndpointAt T ρ i.1 := by
  let ys : List ℝ := explicitFormulaRectangleSortedYEndpoints T ρ
  have hi_lt_len : i.1 < ys.length :=
    lt_trans (Nat.lt_succ_self i.1)
      ((Nat.lt_sub_iff_add_lt (a := i.1) (b := 1) (c := ys.length)).mp i.2)
  calc
    (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i).y₀ =
        ys.get ⟨i.1, hi_lt_len⟩ := by
      rfl
    _ = explicitFormulaRectangleSortedYEndpointAt T ρ i.1 := by
      exact (explicitFormulaRectangleSortedYEndpointAt_of_lt T ρ hi_lt_len).symm

/-- The upper coordinate of the indexed vertical adjacent pair is the next clamped
sorted endpoint. -/
theorem explicitFormulaRectangleYAdjacentEndpointPairAt_y₁
    (T ρ : ℝ)
    (i : Fin ((explicitFormulaRectangleSortedYEndpoints T ρ).length - 1)) :
    (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i).y₁ =
      explicitFormulaRectangleSortedYEndpointAt T ρ (i.1 + 1) := by
  let ys : List ℝ := explicitFormulaRectangleSortedYEndpoints T ρ
  have hi_succ_lt_len : i.1 + 1 < ys.length :=
    ((Nat.lt_sub_iff_add_lt (a := i.1) (b := 1) (c := ys.length)).mp i.2)
  calc
    (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i).y₁ =
        ys.get ⟨i.1 + 1, hi_succ_lt_len⟩ := by
      rfl
    _ = explicitFormulaRectangleSortedYEndpointAt T ρ (i.1 + 1) := by
      exact (explicitFormulaRectangleSortedYEndpointAt_of_lt T ρ hi_succ_lt_len).symm

/-- Bottom horizontal coordinate labels over all vertical adjacent pairs are the forward
endpoint edge sequence. -/
theorem explicitFormulaRectangleYAdjacentEndpointPair_totalBottomHorizontalListSum_eq_ofFn
    (f : ZetaAdmissibleFunction)
    {F : ExplicitFormulaContourFamily} {T ρ : ℝ}
    (xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ) :
    let n : ℕ := (explicitFormulaRectangleSortedYEndpoints T ρ).length - 1
    explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₀))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
      explicitFormulaRectangleListSum
        (fun i : Fin n =>
          explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁),
              explicitFormulaRectangleSortedYEndpointAt T ρ i.1))
        (List.ofFn (fun i : Fin n => i)) := by
  let n : ℕ := (explicitFormulaRectangleSortedYEndpoints T ρ).length - 1
  calc
    explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₀))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁),
                (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i).y₀))
          (List.ofFn (fun i : Fin n => i)) := by
      rfl
    _ =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁),
                explicitFormulaRectangleSortedYEndpointAt T ρ i.1))
          (List.ofFn (fun i : Fin n => i)) := by
      exact congrArg
        (fun g : Fin n → ℂ =>
          explicitFormulaRectangleListSum g (List.ofFn (fun i : Fin n => i)))
        (funext
          (fun i =>
            congrArg
              (fun y : ℝ =>
                explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
                  f ((xpair.x₀, xpair.x₁), y))
              (explicitFormulaRectangleYAdjacentEndpointPairAt_y₀ T ρ i)))

/-- Top horizontal coordinate labels over all vertical adjacent pairs are the forward
endpoint edge sequence shifted by one. -/
theorem explicitFormulaRectangleYAdjacentEndpointPair_totalTopHorizontalListSum_eq_ofFn
    (f : ZetaAdmissibleFunction)
    {F : ExplicitFormulaContourFamily} {T ρ : ℝ}
    (xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ) :
    let n : ℕ := (explicitFormulaRectangleSortedYEndpoints T ρ).length - 1
    explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₁))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
      explicitFormulaRectangleListSum
        (fun i : Fin n =>
          explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁),
              explicitFormulaRectangleSortedYEndpointAt T ρ (i.1 + 1)))
        (List.ofFn (fun i : Fin n => i)) := by
  let n : ℕ := (explicitFormulaRectangleSortedYEndpoints T ρ).length - 1
  calc
    explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₁))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁),
                (explicitFormulaRectangleYAdjacentEndpointPairAt T ρ i).y₁))
          (List.ofFn (fun i : Fin n => i)) := by
      rfl
    _ =
        explicitFormulaRectangleListSum
          (fun i : Fin n =>
            explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁),
                explicitFormulaRectangleSortedYEndpointAt T ρ (i.1 + 1)))
          (List.ofFn (fun i : Fin n => i)) := by
      exact congrArg
        (fun g : Fin n → ℂ =>
          explicitFormulaRectangleListSum g (List.ofFn (fun i : Fin n => i)))
        (funext
          (fun i =>
            congrArg
              (fun y : ℝ =>
                explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
                  f ((xpair.x₀, xpair.x₁), y))
              (explicitFormulaRectangleYAdjacentEndpointPairAt_y₁ T ρ i)))

/-- The paired bottom-minus-top scan over all vertical adjacent pairs telescopes to the
outer bottom-minus-top horizontal slice. -/
theorem explicitFormulaRectangleYAdjacentEndpointPair_totalHorizontalScanSub_eq_outerSub
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    {T ρ : ℝ} (hT_nonneg : 0 ≤ T) (hρ : 0 < ρ)
    (hclosed :
      ∀ a : ℂ,
        a ∈ explicitFormulaRectangleRawSingularCoordinates T →
          Metric.closedBall a ρ ⊆ explicitFormulaContourFamilyInterior F T)
    (xpair : ExplicitFormulaRectangleXAdjacentEndpointPair F T ρ) :
    explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₀))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) -
      explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₁))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
      explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
          f ((xpair.x₀, xpair.x₁), -T) -
        explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
          f ((xpair.x₀, xpair.x₁), T) := by
  let ys : List ℝ := explicitFormulaRectangleSortedYEndpoints T ρ
  let n : ℕ := ys.length - 1
  let endpoint : ℕ → ℂ :=
    fun k =>
      explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
        f ((xpair.x₀, xpair.x₁), explicitFormulaRectangleSortedYEndpointAt T ρ k)
  have hfirst :
      explicitFormulaRectangleSortedYEndpointAt T ρ 0 = -T := by
    have h0 : 0 < ys.length :=
      explicitFormulaRectangleSortedYEndpoints_length_pos T ρ
    calc
      explicitFormulaRectangleSortedYEndpointAt T ρ 0 =
          ys.get ⟨0, h0⟩ := by
        exact explicitFormulaRectangleSortedYEndpointAt_of_lt T ρ h0
      _ = -T := by
        exact
          explicitFormulaRectangleSortedYEndpoints_first_eq_outerLower
            F hT_nonneg hρ hclosed
  have hlast :
      explicitFormulaRectangleSortedYEndpointAt T ρ n = T := by
    have hlast_lt : ys.length - 1 < ys.length :=
      Nat.sub_lt
        (explicitFormulaRectangleSortedYEndpoints_length_pos T ρ)
        Nat.zero_lt_one
    calc
      explicitFormulaRectangleSortedYEndpointAt T ρ n =
          ys.get ⟨ys.length - 1, hlast_lt⟩ := by
        exact explicitFormulaRectangleSortedYEndpointAt_of_lt T ρ hlast_lt
      _ = T := by
        exact
          explicitFormulaRectangleSortedYEndpoints_last_eq_outerUpper
            F hT_nonneg hρ hclosed
  have hpair :
      explicitFormulaRectangleListSum
          (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
            explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁), ypair.y₀))
          (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) -
        explicitFormulaRectangleListSum
          (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
            explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁), ypair.y₁))
          (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n => endpoint i.1 - endpoint (i.1 + 1))
          (List.ofFn (fun i : Fin n => i)) := by
    have hbottom :=
      explicitFormulaRectangleYAdjacentEndpointPair_totalBottomHorizontalListSum_eq_ofFn
        f xpair
    have htop :=
      explicitFormulaRectangleYAdjacentEndpointPair_totalTopHorizontalListSum_eq_ofFn
        f xpair
    calc
      explicitFormulaRectangleListSum
          (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
            explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁), ypair.y₀))
          (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) -
        explicitFormulaRectangleListSum
          (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
            explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁), ypair.y₁))
          (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint i.1)
            (List.ofFn (fun i : Fin n => i)) -
          explicitFormulaRectangleListSum
            (fun i : Fin n =>
              explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
                f ((xpair.x₀, xpair.x₁),
                  explicitFormulaRectangleSortedYEndpointAt T ρ (i.1 + 1)))
            (List.ofFn (fun i : Fin n => i)) := by
        exact congrArg₂ HSub.hSub hbottom htop
      _ =
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint i.1)
            (List.ofFn (fun i : Fin n => i)) -
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint (i.1 + 1))
            (List.ofFn (fun i : Fin n => i)) := by
        exact congrArg
          (fun z : ℂ =>
            explicitFormulaRectangleListSum
              (fun i : Fin n => endpoint i.1)
              (List.ofFn (fun i : Fin n => i)) - z)
          (congrArg
            (fun g : Fin n → ℂ =>
              explicitFormulaRectangleListSum g (List.ofFn (fun i : Fin n => i)))
            (funext
              (fun i =>
                (explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral_eq_top_sameCoordinate
                  f xpair.x₀ xpair.x₁
                  (explicitFormulaRectangleSortedYEndpointAt T ρ (i.1 + 1))).symm)))
      _ =
          explicitFormulaRectangleListSum
            (fun i : Fin n => endpoint i.1 - endpoint (i.1 + 1))
            (List.ofFn (fun i : Fin n => i)) := by
        exact
          (explicitFormulaRectangleListSum_sub
            (fun i : Fin n => endpoint i.1)
            (fun i : Fin n => endpoint (i.1 + 1))
            (List.ofFn (fun i : Fin n => i))).symm
  have htelescope :
      explicitFormulaRectangleListSum
          (fun i : Fin n => endpoint i.1 - endpoint (i.1 + 1))
          (List.ofFn (fun i : Fin n => i)) =
        endpoint 0 - endpoint n :=
    explicitFormulaRectangleListSum_ofFn_consecutiveBackwardDifferences endpoint
  calc
    explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₀))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) -
      explicitFormulaRectangleListSum
        (fun ypair : ExplicitFormulaRectangleYAdjacentEndpointPair T ρ =>
          explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), ypair.y₁))
        (explicitFormulaRectangleYAdjacentEndpointPairsFromSortedEndpoints T ρ) =
        explicitFormulaRectangleListSum
          (fun i : Fin n => endpoint i.1 - endpoint (i.1 + 1))
          (List.ofFn (fun i : Fin n => i)) := by
      exact hpair
    _ = endpoint 0 - endpoint n := by
      exact htelescope
    _ =
        explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), -T) -
          explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), T) := by
      exact congrArg₂ HSub.hSub
        (congrArg
          (fun y : ℝ =>
            explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁), y))
          hfirst)
        (congrArg
          (fun y : ℝ =>
            explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
              f ((xpair.x₀, xpair.x₁), y))
          hlast)
    _ =
        explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), -T) -
          explicitFormulaRectangleTopHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), T) := by
      exact congrArg
        (fun z : ℂ =>
          explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral
            f ((xpair.x₀, xpair.x₁), -T) - z)
        (explicitFormulaRectangleBottomHorizontalEndpointDataEdgeIntegral_eq_top_sameCoordinate
          f xpair.x₀ xpair.x₁ T)

/-- A sorted vertical adjacent-pair subspan lies on the vertical side of a raw
inscribed-square hole.  This is intentionally a containment predicate, not endpoint
equality: other raw squares can add global horizontal subdivision endpoints inside this
hole's vertical side. -/

end ZetaAdmissibleFunction

end
end LFunctions
end Boundary
