import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Presheaves.DescentLocalization.Covers.Owner

/-!
# Cech objects for contour descent

This file owns Cech objects generated by contour descent covers.  Local
equivalences are downstream from these Cech objects.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
The Cech diagram data associated to a contour descent cover and a transfer
presheaf.  It records the finite family of cover pieces and their values under
the presheaf; matching and augmentation maps are added in the local-equivalence
layer.
-/
structure ContourCechObject {F : AnalyticPresheafWithTransfers}
    (C : TransferPresheafDescentCover F) where
  PieceIndex : Type
  finitePieceIndex : Finite PieceIndex
  pieceBulk : PieceIndex → ContourAdmissibleBulk
  pieceValue : (i : PieceIndex) → F.valueAt (pieceBulk i)

namespace ContourCechObject

/-- The bulk at a Cech piece index. -/
def bulkAt {F : AnalyticPresheafWithTransfers}
    {C : TransferPresheafDescentCover F}
    (K : ContourCechObject C) (i : K.PieceIndex) :
    ContourAdmissibleBulk :=
  K.pieceBulk i

/-- The presheaf value selected at a Cech piece index. -/
def valueAt {F : AnalyticPresheafWithTransfers}
    {C : TransferPresheafDescentCover F}
    (K : ContourCechObject C) (i : K.PieceIndex) :
    F.valueAt (K.pieceBulk i) :=
  K.pieceValue i

/-- The target bulk of the descent cover that generated a Cech object. -/
def targetBulk {F : AnalyticPresheafWithTransfers}
    {C : TransferPresheafDescentCover F}
    (K : ContourCechObject C) :
    ContourAdmissibleBulk :=
  C.targetBulk

/-- The contour cover that generated a Cech object. -/
def contourCover {F : AnalyticPresheafWithTransfers}
    {C : TransferPresheafDescentCover F}
    (K : ContourCechObject C) :
    AnalyticContourDescentCover C.target.contour :=
  C.contourCover

/-- The target contour stage of the cover that generated a Cech object. -/
def targetStage {F : AnalyticPresheafWithTransfers}
    {C : TransferPresheafDescentCover F}
    (K : ContourCechObject C) :
    C.target.contour.exhaustion.Stage :=
  C.targetStage

end ContourCechObject

end AnalyticMotives
end LFunctions
end Boundary
