import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceTransport.Objects.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceRewrite.Owner

/-!
# Trace-transport morphisms

This file owns analytic transports between trace presentations.

The intended morphisms are generated by certified rewrite traces: Stokes moves,
residue extraction, channel splitting, refinement, scheduling exchange,
weight-drop reduction, and Fubini coherence.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
A raw trace transport between presentation spines.

The components are source presentation, target presentation, and the rewrite
path used as the computadic trace of the transport.
-/
abbrev TraceTransport :=
  TraceTransportObject × TraceTransportObject × TraceRewritePath

/-- The source presentation of a raw trace transport. -/
def TraceTransport.source (transport : TraceTransport) :
    TraceTransportObject :=
  transport.1

/-- The target presentation of a raw trace transport. -/
def TraceTransport.target (transport : TraceTransport) :
    TraceTransportObject :=
  transport.2.1

/-- The rewrite path carried by a raw trace transport. -/
def TraceTransport.path (transport : TraceTransport) :
    TraceRewritePath :=
  transport.2.2

end AnalyticMotives
end LFunctions
end Boundary
