import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceTransport.Objects.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceRewrite.Owner

/-!
# Trace-transport morphisms

This file owns analytic transports between trace presentations.

The intended morphisms are generated by certified rewrite traces: Stokes moves,
residue extraction, channel splitting, refinement, scheduling exchange,
weight-drop reduction, and Fubini coherence.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
A raw trace transport between certified residue-channel presentations.

The endpoint equalities tie the computadic rewrite path to the analytic source
expressions of the certified presentations.  This prevents a transport from
carrying an unrelated rewrite trace.
-/
structure TraceTransport where
  source : TraceTransportObject
  target : TraceTransportObject
  path : TraceRewritePath
  path_source : path.source = source.source
  path_target : path.target = target.source

end AnalyticMotives
end LFunctions
end Boundary
