import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleRectangleCertificates.Owner

/-!
# Zero-pole rectangle-certified trace correspondences

This file exposes the rectangle-certified zero-pole residue transport as a
`TraceCorQ` generator and singleton formal sum.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The rectangle-certified residue trace-correspondence generator at height `R`. -/
def completedZetaZeroPoleResidueRectangleTraceCorQGenerator
    (R : ℝ) :
    TraceCorQGenerator :=
  completedZetaZeroPoleResidueTransportWithRectangle R

/-- The rectangle-certified residue generator starts at the rectangle-certified presentation. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQGenerator_source
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R).source =
      completedZetaZeroPoleResiduePresentationWithRectangle R :=
  rfl

/-- The rectangle-certified residue generator targets the certified residue output. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQGenerator_target
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R).target =
      completedZetaZeroPoleResidueOutput :=
  rfl

/-- The rectangle-certified residue generator uses the same residue rewrite path. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQGenerator_path
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R).path =
      completedZetaZeroPoleResiduePath :=
  rfl

/--
The rectangle-certified residue trace-correspondence generator is sound at the
height recorded by its rectangle certificate.
-/
theorem completedZetaZeroPoleResidueRectangleTraceCorQGenerator_sound
    (f : ZetaAdmissibleFunction) (hPhi : ZetaPhiAnalyticControl f)
    {R : ℝ} (hR : 0 < R) :
    completedZetaZeroPoleFiniteSquareBoundaryTrace f R =
      completedZetaZeroPoleFiniteSquareResidueTrace f :=
  completedZetaZeroPoleResidueTransportWithRectangle_sound
    f hPhi hR

/--
The rectangle-certified residue trace-correspondence generator is sound when
the recorded rectangle height is positive.
-/
theorem completedZetaZeroPoleResidueRectangleTraceCorQGenerator_sound_of_rectangleHeight
    (f : ZetaAdmissibleFunction) (hPhi : ZetaPhiAnalyticControl f)
    {R : ℝ}
    (hT : 0 < (completedZetaZeroPoleFiniteSquareRectangle R).T) :
    completedZetaZeroPoleFiniteSquareBoundaryTrace f R =
      completedZetaZeroPoleFiniteSquareResidueTrace f :=
  completedZetaZeroPoleResidueRectangleTraceCorQGenerator_sound
    f hPhi hT

/-- The rectangle-certified residue generator carries its transport certificate ledger. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQGenerator_certificateLedger
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R).certificateLedger =
      (completedZetaZeroPoleResidueTransportWithRectangle R).certificateLedger :=
  rfl

/-- The singleton Q-linear correspondence generated by the rectangle-certified residue step. -/
def completedZetaZeroPoleResidueRectangleTraceCorQFormalSum
    (R : ℝ) :
    TraceCorQFormalSum :=
  TraceCorQFormalSum.singleton
    1
    (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R)

/-- The rectangle-certified singleton carries the generator certificate ledger. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQFormalSum_certificateLedger
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQFormalSum R).certificateLedger =
      ResidueChannelCertificateLedger.append
        (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R).certificateLedger
        ResidueChannelCertificateLedger.empty :=
  rfl

/-- The rectangle-certified singleton exposes the imported rectangle through its ledger. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQFormalSum_importedRectangleCount_eq_ledger
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQFormalSum R).importedRectangleCount =
      (completedZetaZeroPoleResidueRectangleTraceCorQFormalSum R).certificateLedger.importedRectangleCount :=
  rfl

/-- The rectangle-certified singleton's imported payload is its generator payload plus zero. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQFormalSum_importedRectangleCount
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQFormalSum R).importedRectangleCount =
      (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R).importedRectangleCount +
        0 :=
  rfl

/-- The rectangle-certified singleton's bookkeeping payload is its generator payload plus zero. -/
theorem completedZetaZeroPoleResidueRectangleTraceCorQFormalSum_traceBookkeepingCount
    (R : ℝ) :
    (completedZetaZeroPoleResidueRectangleTraceCorQFormalSum R).traceBookkeepingCount =
      (completedZetaZeroPoleResidueRectangleTraceCorQGenerator R).traceBookkeepingCount +
        0 :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
