import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Objects.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Objects.Singleton.Owner

/-!
# Bounded localization-input additive objects

This file packages the singleton additive source and target objects attached to
a localization input as bounded finite trace families.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The canonical additive source-object bound of a localization input. -/
def TraceLocalizationInput.additiveSourceObjectWeightBound
    (input : TraceLocalizationInput) :
    Nat :=
  TraceAnalyticAdditiveObject.singletonWeightBound input.sourceObject

/-- The canonical additive target-object bound of a localization input. -/
def TraceLocalizationInput.additiveTargetObjectWeightBound
    (input : TraceLocalizationInput) :
    Nat :=
  TraceAnalyticAdditiveObject.singletonWeightBound input.targetObject

/-- The bounded additive source object generated by a localization input. -/
def TraceLocalizationInput.boundedAdditiveSourceObject
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveObject.BoundedBy
      input.additiveSourceObjectWeightBound :=
  TraceAnalyticAdditiveObject.singletonBoundedBy input.sourceObject

/-- The bounded additive target object generated by a localization input. -/
def TraceLocalizationInput.boundedAdditiveTargetObject
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveObject.BoundedBy
      input.additiveTargetObjectWeightBound :=
  TraceAnalyticAdditiveObject.singletonBoundedBy input.targetObject

/-- The bounded source package has the localization input's additive source object
underneath. -/
theorem TraceLocalizationInput.boundedAdditiveSourceObject_object
    (input : TraceLocalizationInput) :
    input.boundedAdditiveSourceObject.object =
      input.additiveSourceObject :=
  TraceAnalyticAdditiveObject.singletonBoundedBy_object
    input.sourceObject

/-- The bounded target package has the localization input's additive target object
underneath. -/
theorem TraceLocalizationInput.boundedAdditiveTargetObject_object
    (input : TraceLocalizationInput) :
    input.boundedAdditiveTargetObject.object =
      input.additiveTargetObject :=
  TraceAnalyticAdditiveObject.singletonBoundedBy_object
    input.targetObject

/-- The bounded source package is bounded by the input's canonical source-object bound. -/
theorem TraceLocalizationInput.boundedAdditiveSourceObject_weightLevel_le
    (input : TraceLocalizationInput) :
    input.boundedAdditiveSourceObject.object.weightLevel ≤
      input.additiveSourceObjectWeightBound :=
  input.boundedAdditiveSourceObject.weightLevel_le

/-- The bounded target package is bounded by the input's canonical target-object bound. -/
theorem TraceLocalizationInput.boundedAdditiveTargetObject_weightLevel_le
    (input : TraceLocalizationInput) :
    input.boundedAdditiveTargetObject.object.weightLevel ≤
      input.additiveTargetObjectWeightBound :=
  input.boundedAdditiveTargetObject.weightLevel_le

end AnalyticMotives
end LFunctions
end Boundary
