import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourAdmissible.DescentInterval.IntervalHomotopy.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Presheaves.IntervalLocalization.IntervalObject.Owner

/-!
# Interval homotopy equivalences

This file owns the equivalences generated by interval homotopies on
descent-local transfer presheaves.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
An interval homotopy equivalence for a descent-local analytic presheaf.  It
records two rational contour correspondences and the equality of the pullback
maps they induce on the underlying presheaf.
-/
structure PresheafIntervalHomotopyEquivalence
    (F : DescentLocalAnalyticPresheaf) where
  interval : PresheafIntervalObject F
  source : ContourCorrespondenceObject
  target : ContourCorrespondenceObject
  leftEndpoint : RationalContourHom source target
  rightEndpoint : RationalContourHom source target
  endpointAgreement :
    F.underlying.pullbackAlong leftEndpoint =
      F.underlying.pullbackAlong rightEndpoint

namespace PresheafIntervalHomotopyEquivalence

/-- The interval object used by a presheaf-level homotopy equivalence. -/
def intervalObject {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    PresheafIntervalObject F :=
  H.interval

/-- The source object of a presheaf-level interval homotopy equivalence. -/
def sourceObject {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    ContourCorrespondenceObject :=
  H.source

/-- The target object of a presheaf-level interval homotopy equivalence. -/
def targetObject {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    ContourCorrespondenceObject :=
  H.target

/-- The left endpoint correspondence of a presheaf-level interval homotopy equivalence. -/
def left {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    RationalContourHom H.source H.target :=
  H.leftEndpoint

/-- The right endpoint correspondence of a presheaf-level interval homotopy equivalence. -/
def right {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    RationalContourHom H.source H.target :=
  H.rightEndpoint

/-- The pullback map along the left endpoint correspondence. -/
def leftPullback {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    F.underlying.valueAt H.target → F.underlying.valueAt H.source :=
  F.underlying.pullbackAlong H.leftEndpoint

/-- The pullback map along the right endpoint correspondence. -/
def rightPullback {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    F.underlying.valueAt H.target → F.underlying.valueAt H.source :=
  F.underlying.pullbackAlong H.rightEndpoint

/-- The endpoint agreement recorded at the presheaf level. -/
theorem endpoints_agree {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    F.underlying.pullbackAlong H.leftEndpoint =
      F.underlying.pullbackAlong H.rightEndpoint :=
  H.endpointAgreement

/-- The left and right endpoint pullback maps agree. -/
theorem pullbacks_agree {F : DescentLocalAnalyticPresheaf}
    (H : PresheafIntervalHomotopyEquivalence F) :
    H.leftPullback = H.rightPullback :=
  H.endpointAgreement

end PresheafIntervalHomotopyEquivalence

end AnalyticMotives
end LFunctions
end Boundary
