import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Comp.AssociativitySupport.Core.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Comp.Owner

/-!
# Singleton consequences of associativity support

The core child owner exposes the concrete quotient relation generated by the
analytic associativity coherence cell for ledgered trace transports.  This file
turns that ledgered singleton equality into raw-generator singleton composition
associativity.

The arbitrary formal-sum associativity theorem is downstream from this file,
by finite bilinear induction from the singleton theorem owned here.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- Regard a raw trace-correspondence generator as a ledgered transport. -/
def TraceCorQGenerator.toLedgeredTransport
    (generator : TraceCorQGenerator) :
    LedgeredTraceTransport :=
  LedgeredTraceTransport.ofTransportLedger
    generator
    TraceCorQRelationLedger.empty

/-- The raw transport of a generator viewed as ledgered is the generator. -/
theorem TraceCorQGenerator.toLedgeredTransport_transport
    (generator : TraceCorQGenerator) :
    generator.toLedgeredTransport.transport =
      generator :=
  rfl

/-- Singleton composition multiplies coefficients and composes generators. -/
theorem TraceCorQQuotient.comp_singleton_eq_composite
    (firstCoefficient secondCoefficient : Rat)
    (first second : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.singleton firstCoefficient first)
      (TraceCorQQuotient.singleton secondCoefficient second) =
      TraceCorQQuotient.singleton
        (firstCoefficient * secondCoefficient)
        (TraceCorQGenerator.comp first second) :=
  Eq.trans
    (TraceCorQQuotient.comp_ofCandidate
      (TraceCorQQuotient.singletonCandidate
        firstCoefficient
        first
        TraceCorQRelationLedger.empty)
      (TraceCorQQuotient.singletonCandidate
        secondCoefficient
        second
        TraceCorQRelationLedger.empty))
    (TraceCorQQuotient.sound_sameFormalSum
      TraceCorQRelationLedger.empty
      rfl)

/-- Singleton composition of two coefficient-one generators has the raw composite. -/
theorem TraceCorQQuotient.comp_singleton_one_eq_composite
    (first second : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.singleton 1 first)
      (TraceCorQQuotient.singleton 1 second) =
      TraceCorQQuotient.singleton
        1
        (TraceCorQGenerator.comp first second) :=
  Eq.trans
    (TraceCorQQuotient.comp_singleton_eq_composite
      1
      1
      first
      second)
    (congrArg
      (fun coefficient =>
        TraceCorQQuotient.singleton
          coefficient
          (TraceCorQGenerator.comp first second))
      (one_mul 1))

/-- Quotient composition is associative on coefficient-one singleton generators. -/
theorem TraceCorQQuotient.comp_assoc_singleton_one
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton 1 first)
        (TraceCorQQuotient.singleton 1 second))
      (TraceCorQQuotient.singleton 1 third) =
      TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton 1 first)
        (TraceCorQQuotient.comp
          (TraceCorQQuotient.singleton 1 second)
          (TraceCorQQuotient.singleton 1 third)) :=
  Eq.trans
    (congrArg
      (fun leftClass =>
        TraceCorQQuotient.comp
          leftClass
          (TraceCorQQuotient.singleton 1 third))
      (TraceCorQQuotient.comp_singleton_one_eq_composite
        first second))
    (Eq.trans
      (TraceCorQQuotient.comp_singleton_one_eq_composite
        (TraceCorQGenerator.comp first second)
        third)
      (Eq.trans
        (LedgeredTraceTransport.associativitySingletonQuotient_eq
          first.toLedgeredTransport
          second.toLedgeredTransport
          third.toLedgeredTransport)
        (Eq.trans
          (Eq.symm
            (TraceCorQQuotient.comp_singleton_one_eq_composite
              first
              (TraceCorQGenerator.comp second third)))
          (congrArg
            (fun rightClass =>
              TraceCorQQuotient.comp
                (TraceCorQQuotient.singleton 1 first)
                rightClass)
            (Eq.symm
              (TraceCorQQuotient.comp_singleton_one_eq_composite
                second third))))))

/-- The two associated raw generator composites are equal as coefficient-one singletons. -/
theorem TraceCorQQuotient.singleton_one_generator_assoc_eq
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.singleton
      1
      (TraceCorQGenerator.comp
        (TraceCorQGenerator.comp first second)
        third) =
      TraceCorQQuotient.singleton
        1
        (TraceCorQGenerator.comp
          first
          (TraceCorQGenerator.comp second third)) :=
  LedgeredTraceTransport.associativitySingletonQuotient_eq
    first.toLedgeredTransport
    second.toLedgeredTransport
    third.toLedgeredTransport

/-- The two associated raw generator composites are equal with any coefficient. -/
theorem TraceCorQQuotient.singleton_generator_assoc_eq
    (coefficient : Rat)
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.singleton
      coefficient
      (TraceCorQGenerator.comp
        (TraceCorQGenerator.comp first second)
        third) =
      TraceCorQQuotient.singleton
        coefficient
        (TraceCorQGenerator.comp
          first
          (TraceCorQGenerator.comp second third)) :=
  Eq.trans
    (Eq.symm
      (Eq.trans
        (TraceCorQQuotient.smul_singleton
          coefficient
          1
          (TraceCorQGenerator.comp
            (TraceCorQGenerator.comp first second)
            third))
        (congrArg
          (fun scaledCoefficient =>
            TraceCorQQuotient.singleton
              scaledCoefficient
              (TraceCorQGenerator.comp
                (TraceCorQGenerator.comp first second)
                third))
          (mul_one coefficient))))
    (Eq.trans
      (congrArg
        (TraceCorQQuotient.smul coefficient)
        (TraceCorQQuotient.singleton_one_generator_assoc_eq
          first second third))
      (Eq.trans
        (TraceCorQQuotient.smul_singleton
          coefficient
          1
          (TraceCorQGenerator.comp
            first
            (TraceCorQGenerator.comp second third)))
        (congrArg
          (fun scaledCoefficient =>
            TraceCorQQuotient.singleton
              scaledCoefficient
              (TraceCorQGenerator.comp
                first
                (TraceCorQGenerator.comp second third)))
          (mul_one coefficient))))

/-- Quotient composition is associative on weighted singleton generators. -/
theorem TraceCorQQuotient.comp_assoc_singleton
    (firstCoefficient secondCoefficient thirdCoefficient : Rat)
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton firstCoefficient first)
        (TraceCorQQuotient.singleton secondCoefficient second))
      (TraceCorQQuotient.singleton thirdCoefficient third) =
      TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton firstCoefficient first)
        (TraceCorQQuotient.comp
          (TraceCorQQuotient.singleton secondCoefficient second)
          (TraceCorQQuotient.singleton thirdCoefficient third)) :=
  Eq.trans
    (congrArg
      (fun leftClass =>
        TraceCorQQuotient.comp
          leftClass
          (TraceCorQQuotient.singleton thirdCoefficient third))
      (TraceCorQQuotient.comp_singleton_eq_composite
        firstCoefficient
        secondCoefficient
        first
        second))
    (Eq.trans
      (TraceCorQQuotient.comp_singleton_eq_composite
        (firstCoefficient * secondCoefficient)
        thirdCoefficient
        (TraceCorQGenerator.comp first second)
        third)
      (Eq.trans
        (congrArg
          (fun coefficient =>
            TraceCorQQuotient.singleton
              coefficient
              (TraceCorQGenerator.comp
                (TraceCorQGenerator.comp first second)
                third))
          (mul_assoc
            firstCoefficient
            secondCoefficient
            thirdCoefficient))
        (Eq.trans
          (TraceCorQQuotient.singleton_generator_assoc_eq
            (firstCoefficient *
              (secondCoefficient * thirdCoefficient))
            first
            second
            third)
          (Eq.trans
            (Eq.symm
              (TraceCorQQuotient.comp_singleton_eq_composite
                firstCoefficient
                (secondCoefficient * thirdCoefficient)
                first
                (TraceCorQGenerator.comp second third)))
            (congrArg
              (fun rightClass =>
                TraceCorQQuotient.comp
                  (TraceCorQQuotient.singleton firstCoefficient first)
                  rightClass)
              (Eq.symm
                (TraceCorQQuotient.comp_singleton_eq_composite
                  secondCoefficient
                  thirdCoefficient
                  second
                  third)))))))

end AnalyticMotives
end LFunctions
end Boundary
