import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.LedgeredTransports.CoherenceRelations.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Generators.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Relation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Add.Laws.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Comp.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Zero.Owner

/-!
# Associativity support relation for quotient trace composition

This file exposes the concrete quotient relation generated by the analytic
associativity coherence cell for ledgered trace transports, then uses the
concrete Q-linear cancellation rule to turn that support relation into
singleton associativity.

The arbitrary formal-sum associativity theorem is downstream from this file:
it should be proved by finite bilinear induction from the singleton theorem
owned here.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
The quotient candidate represented by the formal support of the associativity
coherence generator for three ledgered trace transports.
-/
def LedgeredTraceTransport.associativitySupportCandidate
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotientCandidate :=
  TraceCorQRelationGenerator.supportCandidate
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/-- The associativity support candidate has the expected formal support. -/
theorem LedgeredTraceTransport.associativitySupportCandidate_formalSum
    (first second third : LedgeredTraceTransport) :
    (LedgeredTraceTransport.associativitySupportCandidate
      first second third).formalSum =
      LedgeredTraceTransport.coherenceSupport
        ((first.comp second).comp third)
        (first.comp (second.comp third)) :=
  rfl

/-- The associativity support candidate has the singleton coherence ledger. -/
theorem LedgeredTraceTransport.associativitySupportCandidate_ledger
    (first second third : LedgeredTraceTransport) :
    (LedgeredTraceTransport.associativitySupportCandidate
      first second third).ledger =
      TraceCorQRelationLedger.singleton
        (LedgeredTraceTransport.associativityRelationGenerator
          first second third) :=
  rfl

/--
The finite witness saying that the associativity support candidate is killed
by the quotient relation.
-/
def LedgeredTraceTransport.associativitySupportWitness
    (first second third : LedgeredTraceTransport) :
    TraceCorQRelationWitness
      (LedgeredTraceTransport.associativitySupportCandidate
        first second third)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationGenerator.supportWitness
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/-- The associativity support witness has the singleton coherence ledger. -/
theorem LedgeredTraceTransport.associativitySupportWitness_ledger
    (first second third : LedgeredTraceTransport) :
    (LedgeredTraceTransport.associativitySupportWitness
      first second third).ledger =
      TraceCorQRelationLedger.singleton
        (LedgeredTraceTransport.associativityRelationGenerator
          first second third) :=
  rfl

/-- The quotient relation generated by associativity coherence support. -/
def LedgeredTraceTransport.associativitySupportRelation
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotientRelation
      (LedgeredTraceTransport.associativitySupportCandidate
        first second third)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (LedgeredTraceTransport.associativitySupportWitness
      first second third)

/--
The formal Q-linear associativity support of three ledgered trace transports
is zero in the quotient.
-/
theorem LedgeredTraceTransport.associativitySupportQuotient_eq_zero
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.associativitySupportCandidate
        first second third) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.sound
    (LedgeredTraceTransport.associativitySupportRelation
      first second third)

/-- The left-parenthesized singleton candidate of associativity coherence. -/
def LedgeredTraceTransport.associativityLeftSingletonCandidate
    (first second third : LedgeredTraceTransport)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQQuotientCandidate :=
  TraceCorQQuotientInput.ofFormalSumLedger
    (TraceCorQFormalSum.singleton
      1
      ((first.comp second).comp third).transport)
    ledger

/-- The right-parenthesized singleton candidate of associativity coherence. -/
def LedgeredTraceTransport.associativityRightSingletonCandidate
    (first second third : LedgeredTraceTransport)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQQuotientCandidate :=
  TraceCorQQuotientInput.ofFormalSumLedger
    (TraceCorQFormalSum.singleton
      1
      (first.comp (second.comp third)).transport)
    ledger

/-- The ledger generated by the associativity coherence relation. -/
def LedgeredTraceTransport.associativitySupportLedger
    (first second third : LedgeredTraceTransport) :
    TraceCorQRelationLedger :=
  TraceCorQRelationLedger.singleton
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/-- The expanded left-minus-right-plus-right candidate used for cancellation. -/
def LedgeredTraceTransport.associativityCancellationCandidate
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotientCandidate :=
  TraceCorQQuotientInput.ofFormalSumLedger
    (TraceCorQFormalSum.singleton
      1
      ((first.comp second).comp third).transport ++
        (-1, (first.comp (second.comp third)).transport) ::
          (1, (first.comp (second.comp third)).transport) ::
            [])
    (LedgeredTraceTransport.associativitySupportLedger
      first second third)

/-- The left singleton is the cancellation candidate after cancelling `-right + right`. -/
theorem LedgeredTraceTransport.associativityLeftSingleton_eq_cancellation
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.associativityLeftSingletonCandidate
        first
        second
        third
        TraceCorQRelationLedger.empty) =
      TraceCorQQuotient.ofCandidate
        (LedgeredTraceTransport.associativityCancellationCandidate
          first second third) :=
  Eq.trans
    (TraceCorQQuotient.sound_sameFormalSum
      (LedgeredTraceTransport.associativitySupportLedger
        first second third)
      rfl)
    (Eq.symm
      (TraceCorQQuotient.sound_cancelAdjacentOpposite
        (LedgeredTraceTransport.associativitySupportLedger
          first second third)
        (TraceCorQFormalSum.singleton
          1
          ((first.comp second).comp third).transport)
        TraceCorQFormalSum.zero
        (-1)
        (first.comp (second.comp third)).transport))

/--
The singleton left and singleton right parenthesizations of a ledgered
transport triple are equal in the quotient.
-/
theorem LedgeredTraceTransport.associativitySingletonQuotient_eq
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.associativityLeftSingletonCandidate
        first
        second
        third
        TraceCorQRelationLedger.empty) =
      TraceCorQQuotient.ofCandidate
        (LedgeredTraceTransport.associativityRightSingletonCandidate
          first
          second
          third
          TraceCorQRelationLedger.empty) :=
  Eq.trans
    (LedgeredTraceTransport.associativityLeftSingleton_eq_cancellation
      first second third)
    (Eq.trans
      (Eq.symm
        (TraceCorQQuotient.add_ofCandidate
          (LedgeredTraceTransport.associativitySupportCandidate
            first second third)
          (LedgeredTraceTransport.associativityRightSingletonCandidate
            first
            second
            third
            TraceCorQRelationLedger.empty)))
      (Eq.trans
        (congrArg
          (fun supportClass =>
            TraceCorQQuotient.add
              supportClass
              (TraceCorQQuotient.ofCandidate
                (LedgeredTraceTransport.associativityRightSingletonCandidate
                  first
                  second
                  third
                  TraceCorQRelationLedger.empty)))
          (LedgeredTraceTransport.associativitySupportQuotient_eq_zero
            first second third))
        (TraceCorQQuotient.zero_add
          (TraceCorQQuotient.ofCandidate
            (LedgeredTraceTransport.associativityRightSingletonCandidate
              first
              second
              third
              TraceCorQRelationLedger.empty)))))

/-- Regard a raw trace-correspondence generator as a ledgered transport. -/
def TraceCorQGenerator.toLedgeredTransport
    (generator : TraceCorQGenerator) :
    LedgeredTraceTransport :=
  LedgeredTraceTransport.ofTransportLedger
    generator
    TraceCorQRelationLedger.empty

/-- The raw transport of a generator viewed as ledgered is the generator. -/
theorem TraceCorQGenerator.toLedgeredTransport_transport
    (generator : TraceCorQGenerator) :
    generator.toLedgeredTransport.transport =
      generator :=
  rfl

/-- Singleton composition multiplies coefficients and composes generators. -/
theorem TraceCorQQuotient.comp_singleton_eq_composite
    (firstCoefficient secondCoefficient : Rat)
    (first second : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.singleton firstCoefficient first)
      (TraceCorQQuotient.singleton secondCoefficient second) =
      TraceCorQQuotient.singleton
        (firstCoefficient * secondCoefficient)
        (TraceCorQGenerator.comp first second) :=
  Eq.trans
    (TraceCorQQuotient.comp_ofCandidate
      (TraceCorQQuotient.singletonCandidate
        firstCoefficient
        first
        TraceCorQRelationLedger.empty)
      (TraceCorQQuotient.singletonCandidate
        secondCoefficient
        second
        TraceCorQRelationLedger.empty))
    (TraceCorQQuotient.sound_sameFormalSum
      TraceCorQRelationLedger.empty
      rfl)

/-- Singleton composition of two coefficient-one generators has the raw composite. -/
theorem TraceCorQQuotient.comp_singleton_one_eq_composite
    (first second : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.singleton 1 first)
      (TraceCorQQuotient.singleton 1 second) =
      TraceCorQQuotient.singleton
        1
        (TraceCorQGenerator.comp first second) :=
  Eq.trans
    (TraceCorQQuotient.comp_singleton_eq_composite
      1
      1
      first
      second)
    (congrArg
      (fun coefficient =>
        TraceCorQQuotient.singleton
          coefficient
          (TraceCorQGenerator.comp first second))
      (one_mul 1))

/-- Quotient composition is associative on coefficient-one singleton generators. -/
theorem TraceCorQQuotient.comp_assoc_singleton_one
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton 1 first)
        (TraceCorQQuotient.singleton 1 second))
      (TraceCorQQuotient.singleton 1 third) =
      TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton 1 first)
        (TraceCorQQuotient.comp
          (TraceCorQQuotient.singleton 1 second)
          (TraceCorQQuotient.singleton 1 third)) :=
  Eq.trans
    (congrArg
      (fun leftClass =>
        TraceCorQQuotient.comp
          leftClass
          (TraceCorQQuotient.singleton 1 third))
      (TraceCorQQuotient.comp_singleton_one_eq_composite
        first second))
    (Eq.trans
      (TraceCorQQuotient.comp_singleton_one_eq_composite
        (TraceCorQGenerator.comp first second)
        third)
      (Eq.trans
        (LedgeredTraceTransport.associativitySingletonQuotient_eq
          first.toLedgeredTransport
          second.toLedgeredTransport
          third.toLedgeredTransport)
        (Eq.trans
          (Eq.symm
            (TraceCorQQuotient.comp_singleton_one_eq_composite
              first
              (TraceCorQGenerator.comp second third)))
          (congrArg
            (fun rightClass =>
              TraceCorQQuotient.comp
                (TraceCorQQuotient.singleton 1 first)
                rightClass)
            (Eq.symm
              (TraceCorQQuotient.comp_singleton_one_eq_composite
                second third))))))

/-- The two associated raw generator composites are equal as coefficient-one singletons. -/
theorem TraceCorQQuotient.singleton_one_generator_assoc_eq
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.singleton
      1
      (TraceCorQGenerator.comp
        (TraceCorQGenerator.comp first second)
        third) =
      TraceCorQQuotient.singleton
        1
        (TraceCorQGenerator.comp
          first
          (TraceCorQGenerator.comp second third)) :=
  LedgeredTraceTransport.associativitySingletonQuotient_eq
    first.toLedgeredTransport
    second.toLedgeredTransport
    third.toLedgeredTransport

/-- The two associated raw generator composites are equal with any coefficient. -/
theorem TraceCorQQuotient.singleton_generator_assoc_eq
    (coefficient : Rat)
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.singleton
      coefficient
      (TraceCorQGenerator.comp
        (TraceCorQGenerator.comp first second)
        third) =
      TraceCorQQuotient.singleton
        coefficient
        (TraceCorQGenerator.comp
          first
          (TraceCorQGenerator.comp second third)) :=
  Eq.trans
    (Eq.symm
      (Eq.trans
        (TraceCorQQuotient.smul_singleton
          coefficient
          1
          (TraceCorQGenerator.comp
            (TraceCorQGenerator.comp first second)
            third))
        (congrArg
          (fun scaledCoefficient =>
            TraceCorQQuotient.singleton
              scaledCoefficient
              (TraceCorQGenerator.comp
                (TraceCorQGenerator.comp first second)
                third))
          (mul_one coefficient))))
    (Eq.trans
      (congrArg
        (TraceCorQQuotient.smul coefficient)
        (TraceCorQQuotient.singleton_one_generator_assoc_eq
          first second third))
      (Eq.trans
        (TraceCorQQuotient.smul_singleton
          coefficient
          1
          (TraceCorQGenerator.comp
            first
            (TraceCorQGenerator.comp second third)))
        (congrArg
          (fun scaledCoefficient =>
            TraceCorQQuotient.singleton
              scaledCoefficient
              (TraceCorQGenerator.comp
                first
                (TraceCorQGenerator.comp second third)))
          (mul_one coefficient))))

/-- Quotient composition is associative on weighted singleton generators. -/
theorem TraceCorQQuotient.comp_assoc_singleton
    (firstCoefficient secondCoefficient thirdCoefficient : Rat)
    (first second third : TraceCorQGenerator) :
    TraceCorQQuotient.comp
      (TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton firstCoefficient first)
        (TraceCorQQuotient.singleton secondCoefficient second))
      (TraceCorQQuotient.singleton thirdCoefficient third) =
      TraceCorQQuotient.comp
        (TraceCorQQuotient.singleton firstCoefficient first)
        (TraceCorQQuotient.comp
          (TraceCorQQuotient.singleton secondCoefficient second)
          (TraceCorQQuotient.singleton thirdCoefficient third)) :=
  Eq.trans
    (congrArg
      (fun leftClass =>
        TraceCorQQuotient.comp
          leftClass
          (TraceCorQQuotient.singleton thirdCoefficient third))
      (TraceCorQQuotient.comp_singleton_eq_composite
        firstCoefficient
        secondCoefficient
        first
        second))
    (Eq.trans
      (TraceCorQQuotient.comp_singleton_eq_composite
        (firstCoefficient * secondCoefficient)
        thirdCoefficient
        (TraceCorQGenerator.comp first second)
        third)
      (Eq.trans
        (congrArg
          (fun coefficient =>
            TraceCorQQuotient.singleton
              coefficient
              (TraceCorQGenerator.comp
                (TraceCorQGenerator.comp first second)
                third))
          (mul_assoc
            firstCoefficient
            secondCoefficient
            thirdCoefficient))
        (Eq.trans
          (TraceCorQQuotient.singleton_generator_assoc_eq
            (firstCoefficient *
              (secondCoefficient * thirdCoefficient))
            first
            second
            third)
          (Eq.trans
            (Eq.symm
              (TraceCorQQuotient.comp_singleton_eq_composite
                firstCoefficient
                (secondCoefficient * thirdCoefficient)
                first
                (TraceCorQGenerator.comp second third)))
            (congrArg
              (fun rightClass =>
                TraceCorQQuotient.comp
                  (TraceCorQQuotient.singleton firstCoefficient first)
                  rightClass)
              (Eq.symm
                (TraceCorQQuotient.comp_singleton_eq_composite
                  secondCoefficient
                  thirdCoefficient
                  second
                  third)))))))

end AnalyticMotives
end LFunctions
end Boundary
