import Boundary.LFunctionsRootedTreeFinal.OutsideRHRootedImportCone.CohomologicalEulerFactor.EndomorphismK0.EndomorphismK0Core.Owner
import Mathlib.Data.Matrix.Block
import Mathlib.FieldTheory.RatFunc.Basic
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Algebra.Exact

/-!
# Virtual finite-dimensional endomorphism classes

This file starts the conceptual owner layer beneath cohomological local factors.
It packages finite-dimensional vector spaces equipped with an endomorphism and
builds the free virtual abelian group on those objects.

The direct-sum relation is recorded as an explicit element, and the determinant
and first trace characters are proved to kill it, so both descend to the
direct-sum quotient.
-/

universe u v

namespace Boundary
namespace EndomorphismK0

noncomputable section

open LinearEulerFactor

variable (K : Type u) [Field K]

/-- The free virtual abelian group on finite-dimensional endomorphism objects. -/
abbrev VirtualEndomorphism :=
  FreeAbelianGroup (EndomorphismObject.{u, v} K)

/-- Generator class of a finite-dimensional endomorphism object. -/
def of (A : EndomorphismObject.{u, v} K) : VirtualEndomorphism K :=
  FreeAbelianGroup.of A

/-- The chosen zero object in the endomorphism category. -/
def zeroObject : EndomorphismObject.{u, v} K where
  carrier := PUnit.{v + 1}
  addCommGroup := Boundary.EndomorphismK0.punitAddCommGroup
  module := Boundary.EndomorphismK0.punitModule K
  finiteDimensional := Boundary.EndomorphismK0.punitFiniteDimensional K
  endomorphism := 0

/-- The direct-sum relation element `[A ⊕ B] - [A] - [B]`. -/
def directSumRelation (A B : EndomorphismObject.{u, v} K) : VirtualEndomorphism K :=
  of K (EndomorphismObject.product A B) - of K A - of K B

/-- The direct-sum relation written as `A ⊕ B - A - B` with the subtraction
grouping made explicit. -/
theorem directSumRelation_eq_sub (A B : EndomorphismObject.{u, v} K) :
    directSumRelation K A B =
      of K (EndomorphismObject.product A B) - (of K A + of K B) := by
  change of K (EndomorphismObject.product A B) - of K A - of K B =
    of K (EndomorphismObject.product A B) - (of K A + of K B)
  exact (sub_add_eq_sub_sub (of K (EndomorphismObject.product A B)) (of K A) (of K B)).symm

/-- The conjugacy relation element `[B, e A e⁻¹] - [A]`. -/
def conjRelation (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) : VirtualEndomorphism K :=
  of K (EndomorphismObject.conj A e) - of K A

/-- The generators for the direct-sum, conjugacy, and zero-object relation subgroup. -/
def directSumGeneratingSet : Set (VirtualEndomorphism K) :=
  {x | (∃ A B : EndomorphismObject.{u, v} K, x = directSumRelation K A B) ∨
    (∃ A B : EndomorphismObject.{u, v} K, ∃ e : A.carrier ≃ₗ[K] B.carrier,
      x = conjRelation K A e) ∨
    ∃ A : EndomorphismObject.{u, v} K, Subsingleton A.carrier ∧ x = of K A}

/-- The subgroup generated by direct-sum relations, conjugacy relations, and
the chosen zero object. -/
def directSumSubgroup : AddSubgroup (VirtualEndomorphism K) :=
  AddSubgroup.closure (directSumGeneratingSet K)

/-- The direct-sum Grothendieck quotient of finite-dimensional endomorphism
objects. -/
abbrev K0 :=
  VirtualEndomorphism K ⧸ directSumSubgroup K

/-- Quotient map from the free virtual group to the direct-sum quotient. -/
def mk : VirtualEndomorphism K →+ K0 K :=
  QuotientAddGroup.mk' (directSumSubgroup K)

/-- The direct-sum relation lies in the subgroup it generates. -/
theorem directSumRelation_mem_directSumSubgroup (A B : EndomorphismObject.{u, v} K) :
    directSumRelation K A B ∈
      (directSumSubgroup K : AddSubgroup (VirtualEndomorphism K)) := by
  exact AddSubgroup.subset_closure (Or.inl ⟨A, B, rfl⟩)

/-- Conjugacy relations lie in the subgroup. -/
theorem conjRelation_mem_directSumSubgroup
    (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    conjRelation K A e ∈
      (directSumSubgroup K : AddSubgroup (VirtualEndomorphism K)) := by
  exact AddSubgroup.subset_closure (Or.inr <| Or.inl ⟨A, B, e, rfl⟩)

/-- Zero-object generators lie in the subgroup. -/
theorem zeroObject_mem_directSumSubgroup (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) :
    of K A ∈
      (directSumSubgroup K : AddSubgroup (VirtualEndomorphism K)) := by
  exact AddSubgroup.subset_closure (Or.inr (Or.inr ⟨A, hA, rfl⟩))

theorem mk_directSumRelation (A B : EndomorphismObject.{u, v} K) :
    mk K (directSumRelation K A B) = 0 := by
  change (directSumRelation K A B : K0 K) = 0
  exact (QuotientAddGroup.eq_zero_iff
    (N := directSumSubgroup K) (directSumRelation K A B)).2
      (directSumRelation_mem_directSumSubgroup K A B)

theorem mk_zeroObject_of_isZero (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) :
    mk K (of K A) = (0 : K0 K) := by
  change (of K A : K0 K) = 0
  exact (QuotientAddGroup.eq_zero_iff
    (N := directSumSubgroup K) (of K A)).2
      (zeroObject_mem_directSumSubgroup K A hA)

theorem mk_zeroObject :
    mk K (of K (zeroObject K)) = (0 : K0 K) := by
  exact mk_zeroObject_of_isZero K (zeroObject K)
    (by
      change Subsingleton PUnit
      exact ⟨fun _ _ => rfl⟩)

/-- In the quotient, a direct sum is the sum of the two classes. -/
theorem mk_directSum_eq_add (A B : EndomorphismObject.{u, v} K) :
    mk K (of K (EndomorphismObject.product A B)) = mk K (of K A) + mk K (of K B) := by
  exact eq_of_sub_eq_zero
    (calc
      mk K (of K (EndomorphismObject.product A B)) - (mk K (of K A) + mk K (of K B))
          = mk K (of K (EndomorphismObject.product A B)) - mk K (of K A + of K B) := by
            exact congrArg (fun x => mk K (of K (EndomorphismObject.product A B)) - x)
              (map_add (mk K) (of K A) (of K B)).symm
      _ = mk K (of K (EndomorphismObject.product A B) - (of K A + of K B)) := by
            exact (map_sub (mk K) (of K (EndomorphismObject.product A B)) (of K A + of K B)).symm
      _ = mk K (directSumRelation K A B) := by
            exact congrArg (mk K) (directSumRelation_eq_sub (K := K) A B).symm
      _ = 0 := by
            exact mk_directSumRelation (K := K) A B)

/-- Conjugate endomorphism objects have the same class in `K0`. -/
theorem mk_conj_eq_mk (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    mk K (of K (EndomorphismObject.conj A e)) = mk K (of K A) := by
  exact eq_of_sub_eq_zero
    ((QuotientAddGroup.eq_zero_iff
      (N := directSumSubgroup K) (conjRelation K A e)).2
        (conjRelation_mem_directSumSubgroup K A e))

/-- The determinant character on the free virtual group, valued additively in
the unit group of `RatFunc K`. -/
def determinantCharacter : VirtualEndomorphism K →+ Additive ((RatFunc K)ˣ) :=
  FreeAbelianGroup.lift fun A => Additive.ofMul (EndomorphismObject.determinantUnit A)

theorem determinantCharacter_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacter K (of K A) =
      Additive.ofMul (EndomorphismObject.determinantUnit A) := by
  exact FreeAbelianGroup.lift.of _ A

/-- The determinant character kills the direct-sum relation. -/
theorem determinantCharacter_directSumRelation (A B : EndomorphismObject.{u, v} K) :
    determinantCharacter K (directSumRelation K A B) = 0 := by
  calc
    determinantCharacter K (directSumRelation K A B)
        = determinantCharacter K (of K (EndomorphismObject.product A B) -
            (of K A + of K B)) := by
            exact congrArg (determinantCharacter K) (directSumRelation_eq_sub (K := K) A B)
    _ = determinantCharacter K (of K (EndomorphismObject.product A B)) -
          determinantCharacter K (of K A + of K B) := by
          exact map_sub (determinantCharacter K) _ _
    _ = determinantCharacter K (of K (EndomorphismObject.product A B)) -
          (determinantCharacter K (of K A) + determinantCharacter K (of K B)) := by
          exact congrArg
            (fun x => determinantCharacter K (of K (EndomorphismObject.product A B)) - x)
            (map_add (determinantCharacter K) (of K A) (of K B))
    _ = Additive.ofMul (EndomorphismObject.determinantUnit (EndomorphismObject.product A B)) -
          (Additive.ofMul (EndomorphismObject.determinantUnit A) +
            Additive.ofMul (EndomorphismObject.determinantUnit B)) := by
          exact congrArg₂ (fun a b => a - b)
            (determinantCharacter_of (K := K) (EndomorphismObject.product A B))
            (congrArg₂ HAdd.hAdd
              (determinantCharacter_of (K := K) A)
              (determinantCharacter_of (K := K) B))
    _ = 0 := by
          exact sub_eq_zero.mpr
            (congrArg Additive.ofMul
              (EndomorphismObject.determinantUnit_product A B))

theorem determinantCharacter_conjRelation
    (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    determinantCharacter K (conjRelation K A e) = 0 := by
  calc
    determinantCharacter K (conjRelation K A e)
        = determinantCharacter K (of K (EndomorphismObject.conj A e) - of K A) := by
            rfl
    _ = determinantCharacter K (of K (EndomorphismObject.conj A e)) -
          determinantCharacter K (of K A) := by
          exact map_sub (determinantCharacter K) _ _
    _ = Additive.ofMul (EndomorphismObject.determinantUnit (EndomorphismObject.conj A e)) -
          Additive.ofMul (EndomorphismObject.determinantUnit A) := by
          exact congrArg₂ (fun a b => a - b)
            (determinantCharacter_of (K := K) (EndomorphismObject.conj A e))
            (determinantCharacter_of (K := K) A)
    _ = 0 := by
          exact sub_eq_zero.mpr
            (congrArg Additive.ofMul (EndomorphismObject.determinantUnit_conj A e))

theorem determinantCharacter_zeroObject (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) :
    determinantCharacter K (of K A) = 0 := by
  exact Eq.trans
    (determinantCharacter_of (K := K) A)
    (congrArg Additive.ofMul (EndomorphismObject.determinantUnit_zeroObject (K := K) A hA))

/-- The determinant character kills the subgroup generated by direct-sum
relations. -/
theorem directSumSubgroup_le_determinantCharacter_ker :
    directSumSubgroup K ≤ (determinantCharacter K).ker := by
  exact (AddSubgroup.closure_le ((determinantCharacter K).ker)).2
    (fun x hx =>
      match hx with
      | Or.inl ⟨A, B, h⟩ =>
          h ▸ determinantCharacter_directSumRelation K A B
      | Or.inr (Or.inl ⟨A, B, e, h⟩) =>
          h ▸ determinantCharacter_conjRelation K A e
      | Or.inr (Or.inr ⟨A, hA, h⟩) =>
          h ▸ determinantCharacter_zeroObject K A hA)

/-- The determinant character descended to the direct-sum quotient. Its target
is written additively because the quotient source is an additive group. -/
def determinantCharacterK0 : K0 K →+ Additive ((RatFunc K)ˣ) :=
  QuotientAddGroup.lift (directSumSubgroup K) (determinantCharacter K)
    (directSumSubgroup_le_determinantCharacter_ker K)

theorem determinantCharacterK0Mul_map_mul (x y : Multiplicative (K0 K)) :
    Additive.toMul (determinantCharacterK0 K (Multiplicative.toAdd (x * y))) =
      Additive.toMul (determinantCharacterK0 K (Multiplicative.toAdd x)) *
        Additive.toMul (determinantCharacterK0 K (Multiplicative.toAdd y)) :=
  Eq.trans
    (congrArg Additive.toMul
      (map_add (determinantCharacterK0 K) (Multiplicative.toAdd x)
        (Multiplicative.toAdd y)))
    (toMul_add _ _)

/-- Multiplicative form of the determinant character on the direct-sum
quotient. -/
def determinantCharacterK0Mul : Multiplicative (K0 K) →* (RatFunc K)ˣ where
  toFun x := Additive.toMul (determinantCharacterK0 K (Multiplicative.toAdd x))
  map_one' := by
    change Additive.toMul (determinantCharacterK0 K 0) = 1
    exact rfl
  map_mul' x y := by
    exact determinantCharacterK0Mul_map_mul (K := K) x y

theorem determinantCharacterK0_mk (x : VirtualEndomorphism K) :
    determinantCharacterK0 K (mk K x) = determinantCharacter K x := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (directSumSubgroup_le_determinantCharacter_ker K) x

theorem determinantCharacterK0_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacterK0 K (mk K (of K A)) =
      Additive.ofMul (EndomorphismObject.determinantUnit A) := by
  calc
    determinantCharacterK0 K (mk K (of K A)) = determinantCharacter K (of K A) := by
      exact determinantCharacterK0_mk (K := K) (of K A)
    _ = Additive.ofMul (EndomorphismObject.determinantUnit A) := by
      exact determinantCharacter_of (K := K) A

theorem determinantCharacterK0Mul_of (A : EndomorphismObject.{u, v} K) :
    determinantCharacterK0Mul K (Multiplicative.ofAdd (mk K (of K A))) =
      EndomorphismObject.determinantUnit A := by
  change Additive.toMul (determinantCharacterK0 K (mk K (of K A))) =
    EndomorphismObject.determinantUnit A
  exact congrArg Additive.toMul (determinantCharacterK0_of (K := K) A)

/-- The determinant character sends a finite K₀ sum of endomorphism generators
to the corresponding additive sum of determinant units. -/
theorem determinantCharacterK0_sum_of {ι : Type*} (s : Finset ι)
    (A : ι → EndomorphismObject.{u, v} K) :
    determinantCharacterK0 K (∑ i in s, mk K (of K (A i))) =
      ∑ i in s, Additive.ofMul (EndomorphismObject.determinantUnit (A i)) :=
  Eq.trans
    (map_sum (determinantCharacterK0 K) (fun i => mk K (of K (A i))) s)
    (Finset.sum_congr (Eq.refl s)
      (fun i _ => determinantCharacterK0_of (K := K) (A i)))

/-- Multiplicative form of `determinantCharacterK0_sum_of`. -/
theorem determinantCharacterK0Mul_sum_of {ι : Type*} (s : Finset ι)
    (A : ι → EndomorphismObject.{u, v} K) :
    determinantCharacterK0Mul K
        (Multiplicative.ofAdd (∑ i in s, mk K (of K (A i)))) =
      ∏ i in s, EndomorphismObject.determinantUnit (A i) :=
  Eq.trans
    (congrArg Additive.toMul
      (determinantCharacterK0_sum_of (K := K) s A))
    (toMul_sum s
      (fun i => Additive.ofMul (EndomorphismObject.determinantUnit (A i))))

/-- The determinant character converts a difference of finite K₀ sums into the
quotient of the corresponding determinant products. -/
theorem determinantCharacterK0Mul_sub_sum_of {ι κ : Type*}
    (s : Finset ι) (t : Finset κ)
    (A : ι → EndomorphismObject.{u, v} K)
    (B : κ → EndomorphismObject.{u, v} K) :
    determinantCharacterK0Mul K
        (Multiplicative.ofAdd
          ((∑ i in s, mk K (of K (A i))) -
            ∑ j in t, mk K (of K (B j)))) =
      (∏ i in s, EndomorphismObject.determinantUnit (A i)) /
        ∏ j in t, EndomorphismObject.determinantUnit (B j) :=
  Eq.trans
    (congrArg Additive.toMul
      (map_sub (determinantCharacterK0 K)
        (∑ i in s, mk K (of K (A i)))
        (∑ j in t, mk K (of K (B j)))))
    (Eq.trans
      (toMul_sub
        (determinantCharacterK0 K (∑ i in s, mk K (of K (A i))))
        (determinantCharacterK0 K (∑ j in t, mk K (of K (B j)))))
      (congrArg₂ HDiv.hDiv
        (Eq.trans
          (congrArg Additive.toMul
            (determinantCharacterK0_sum_of (K := K) s A))
          (toMul_sum s
            (fun i => Additive.ofMul (EndomorphismObject.determinantUnit (A i)))))
        (Eq.trans
          (congrArg Additive.toMul
            (determinantCharacterK0_sum_of (K := K) t B))
          (toMul_sum t
            (fun j => Additive.ofMul (EndomorphismObject.determinantUnit (B j)))))))

theorem tracePower_zeroObject_zero (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) : EndomorphismObject.tracePower 0 A = 0 := by
  letI : Subsingleton A.carrier := hA
  exact Eq.trans
    (show EndomorphismObject.tracePower 0 A =
      LinearMap.trace K A.carrier (1 : A.carrier →ₗ[K] A.carrier) from rfl)
    (Eq.trans
      (LinearMap.trace_one (R := K) (M := A.carrier))
      (Eq.trans
        (congrArg (fun m : ℕ => (m : K))
          (Module.finrank_zero_of_subsingleton : Module.finrank K A.carrier = 0))
        Nat.cast_zero))

theorem endomorphism_pow_succ_eq_zero_of_subsingleton
    (n : ℕ) (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) :
    A.endomorphism ^ (n + 1) = 0 := by
  exact LinearMap.ext (fun x => Subsingleton.elim _ _)

theorem tracePower_succ_eq_trace_zero_of_subsingleton
    (n : ℕ) (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) :
    LinearMap.trace K A.carrier (A.endomorphism ^ (n + 1)) =
      LinearMap.trace K A.carrier (0 : A.carrier →ₗ[K] A.carrier) := by
  exact congrArg (LinearMap.trace K A.carrier)
    (endomorphism_pow_succ_eq_zero_of_subsingleton (K := K) n A hA)

theorem tracePower_zeroObject_succ (n : ℕ) (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) : EndomorphismObject.tracePower (n + 1) A = 0 := by
  exact Eq.trans
    (tracePower_succ_eq_trace_zero_of_subsingleton (K := K) n A hA)
    (map_zero (LinearMap.trace K A.carrier))

/-- The trace-power character on the free virtual group. -/
def traceCharacter (n : ℕ) : VirtualEndomorphism K →+ K :=
  FreeAbelianGroup.lift fun A => EndomorphismObject.tracePower n A

/-- A zero-object endomorphism has vanishing trace powers. -/
theorem tracePower_zeroObject (n : ℕ) (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) : EndomorphismObject.tracePower n A = 0 := by
  cases n with
  | zero =>
      exact tracePower_zeroObject_zero (K := K) A hA
  | succ n =>
      exact tracePower_zeroObject_succ (K := K) n A hA

theorem traceCharacter_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    traceCharacter K n (of K A) = EndomorphismObject.tracePower n A := by
  exact FreeAbelianGroup.lift.of _ A

/-- The trace-power character kills the direct-sum relation. -/
theorem traceCharacter_directSumRelation (n : ℕ) (A B : EndomorphismObject.{u, v} K) :
    traceCharacter K n (directSumRelation K A B) = 0 := by
  calc
    traceCharacter K n (directSumRelation K A B)
        = traceCharacter K n (of K (EndomorphismObject.product A B) -
            (of K A + of K B)) := by
            exact congrArg (traceCharacter K n) (directSumRelation_eq_sub (K := K) A B)
    _ = traceCharacter K n (of K (EndomorphismObject.product A B)) -
          traceCharacter K n (of K A + of K B) := by
          exact map_sub (traceCharacter K n) _ _
    _ = traceCharacter K n (of K (EndomorphismObject.product A B)) -
          (traceCharacter K n (of K A) + traceCharacter K n (of K B)) := by
          exact congrArg
            (fun x => traceCharacter K n (of K (EndomorphismObject.product A B)) - x)
            (map_add (traceCharacter K n) (of K A) (of K B))
    _ = EndomorphismObject.tracePower n (EndomorphismObject.product A B) -
          (EndomorphismObject.tracePower n A + EndomorphismObject.tracePower n B) := by
          exact congrArg₂ (fun a b => a - b)
            (traceCharacter_of (K := K) n (EndomorphismObject.product A B))
            (congrArg₂ HAdd.hAdd (traceCharacter_of (K := K) n A)
              (traceCharacter_of (K := K) n B))
    _ = 0 := by
          exact sub_eq_zero.mpr (EndomorphismObject.tracePower_product A B n)

theorem traceCharacter_conjRelation (n : ℕ) (A : EndomorphismObject.{u, v} K)
    {B : EndomorphismObject.{u, v} K} (e : A.carrier ≃ₗ[K] B.carrier) :
    traceCharacter K n (conjRelation K A e) = 0 := by
  calc
    traceCharacter K n (conjRelation K A e)
        = traceCharacter K n (of K (EndomorphismObject.conj A e) - of K A) := by
            rfl
    _ = traceCharacter K n (of K (EndomorphismObject.conj A e)) -
          traceCharacter K n (of K A) := by
          exact map_sub (traceCharacter K n) _ _
    _ = EndomorphismObject.tracePower n (EndomorphismObject.conj A e) -
          EndomorphismObject.tracePower n A := by
          exact congrArg₂ (fun a b => a - b)
            (traceCharacter_of (K := K) n (EndomorphismObject.conj A e))
            (traceCharacter_of (K := K) n A)
    _ = 0 := by
          exact sub_eq_zero.mpr (EndomorphismObject.tracePower_conj n A e)

theorem traceCharacter_zeroObject (n : ℕ) (A : EndomorphismObject.{u, v} K)
    (hA : Subsingleton A.carrier) :
    traceCharacter K n (of K A) = 0 := by
  exact (traceCharacter_of (K := K) n A).trans (tracePower_zeroObject (K := K) n A hA)

/-- The first trace character kills the direct-sum relation. -/
theorem traceCharacter_one_directSumRelation (A B : EndomorphismObject.{u, v} K) :
    traceCharacter K 1 (directSumRelation K A B) = 0 :=
  traceCharacter_directSumRelation K 1 A B

/-- The trace-power character kills the subgroup generated by direct-sum
relations. -/
theorem directSumSubgroup_le_traceCharacter_ker (n : ℕ) :
    directSumSubgroup K ≤ (traceCharacter K n).ker := by
  exact (AddSubgroup.closure_le ((traceCharacter K n).ker)).2
    (fun x hx =>
      match hx with
      | Or.inl ⟨A, B, h⟩ =>
          h ▸ traceCharacter_directSumRelation K n A B
      | Or.inr (Or.inl ⟨A, B, e, h⟩) =>
          h ▸ traceCharacter_conjRelation K n A e
      | Or.inr (Or.inr ⟨A, hA, h⟩) =>
          h ▸ traceCharacter_zeroObject K n A hA)

/-- The first trace character kills the subgroup generated by direct-sum
relations. -/
theorem directSumSubgroup_le_traceCharacter_one_ker :
    directSumSubgroup K ≤ (traceCharacter K 1).ker :=
  directSumSubgroup_le_traceCharacter_ker K 1

/-- The trace-power character descended to the direct-sum quotient. -/
def traceCharacterK0 (n : ℕ) : K0 K →+ K :=
  QuotientAddGroup.lift (directSumSubgroup K) (traceCharacter K n)
    (directSumSubgroup_le_traceCharacter_ker K n)

theorem traceCharacterK0_mk (n : ℕ) (x : VirtualEndomorphism K) :
    traceCharacterK0 K n (mk K x) = traceCharacter K n x := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (directSumSubgroup_le_traceCharacter_ker K n) x

theorem traceCharacterK0_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    traceCharacterK0 K n (mk K (of K A)) = EndomorphismObject.tracePower n A := by
  calc
    traceCharacterK0 K n (mk K (of K A)) = traceCharacter K n (of K A) := by
      exact traceCharacterK0_mk K n (of K A)
    _ = EndomorphismObject.tracePower n A := by
      exact traceCharacter_of (K := K) n A

/-- The virtual power map `[V,F] ↦ [V,F^n]` on the free group. -/
def powerMapVirtual (n : ℕ) : VirtualEndomorphism K →+ VirtualEndomorphism K :=
  FreeAbelianGroup.lift fun A => of K (EndomorphismObject.power A n)

theorem powerMapVirtual_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    powerMapVirtual K n (of K A) = of K (EndomorphismObject.power A n) := by
  exact FreeAbelianGroup.lift.of _ A

/-- The virtual power map sends direct-sum relations to direct-sum relations. -/
theorem powerMapVirtual_directSumRelation
    (n : ℕ) (A B : EndomorphismObject.{u, v} K) :
    powerMapVirtual K n (directSumRelation K A B) =
      directSumRelation K (EndomorphismObject.power A n)
        (EndomorphismObject.power B n) := by
  calc
    powerMapVirtual K n (directSumRelation K A B)
        = powerMapVirtual K n
            (of K (EndomorphismObject.product A B) - (of K A + of K B)) := by
          exact congrArg (powerMapVirtual K n) (directSumRelation_eq_sub (K := K) A B)
    _ = powerMapVirtual K n (of K (EndomorphismObject.product A B)) -
          powerMapVirtual K n (of K A + of K B) := by
          exact map_sub (powerMapVirtual K n) _ _
    _ = of K (EndomorphismObject.power (EndomorphismObject.product A B) n) -
          (powerMapVirtual K n (of K A) + powerMapVirtual K n (of K B)) := by
          exact congrArg
            (fun x => of K (EndomorphismObject.power (EndomorphismObject.product A B) n) - x)
            (map_add (powerMapVirtual K n) (of K A) (of K B))
    _ = of K (EndomorphismObject.product (EndomorphismObject.power A n)
            (EndomorphismObject.power B n)) -
          (of K (EndomorphismObject.power A n) + of K (EndomorphismObject.power B n)) := by
          exact congrArg (fun X => of K X -
            (of K (EndomorphismObject.power A n) + of K (EndomorphismObject.power B n)))
            (EndomorphismObject.power_product A B n)
    _ = directSumRelation K (EndomorphismObject.power A n)
        (EndomorphismObject.power B n) := by
          exact (directSumRelation_eq_sub (K := K) (EndomorphismObject.power A n)
            (EndomorphismObject.power B n)).symm

theorem power_conj_eq_conj_power
    (n : ℕ) (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    EndomorphismObject.power (EndomorphismObject.conj A e) n =
      EndomorphismObject.conj (EndomorphismObject.power A n) e := by
  exact (EndomorphismObject.conj_eq
    (A := EndomorphismObject.power A n)
    (B := EndomorphismObject.power (EndomorphismObject.conj A e) n) e
    (by
      change e.conj (A.endomorphism ^ n) =
        (e.conj A.endomorphism) ^ n
      exact (EndomorphismObject.conj_pow n A e).symm)).symm

/-- The virtual power map carries a conjugacy relation to the conjugacy
relation of the powered endomorphism objects. -/
theorem powerMapVirtual_conjRelation
    (n : ℕ) (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    powerMapVirtual K n (conjRelation K A e) =
      conjRelation K (EndomorphismObject.power A n) e := by
  calc
    powerMapVirtual K n (conjRelation K A e)
        = powerMapVirtual K n (of K (EndomorphismObject.conj A e) - of K A) := by
          rfl
    _ = powerMapVirtual K n (of K (EndomorphismObject.conj A e)) -
          powerMapVirtual K n (of K A) := by
          exact map_sub (powerMapVirtual K n) _ _
    _ = of K (EndomorphismObject.power (EndomorphismObject.conj A e) n) -
          of K (EndomorphismObject.power A n) := by
          exact congrArg₂ (fun a b => a - b)
            (powerMapVirtual_of (K := K) n (EndomorphismObject.conj A e))
            (powerMapVirtual_of (K := K) n A)
    _ = of K (EndomorphismObject.conj (EndomorphismObject.power A n) e) -
            of K (EndomorphismObject.power A n) := by
          exact congrArg (fun X => of K X - of K (EndomorphismObject.power A n))
            (power_conj_eq_conj_power (K := K) n A e)
    _ = conjRelation K (EndomorphismObject.power A n) e := by
          rfl

/-- The virtual power map sends conjugacy relations into the direct-sum
relation subgroup. -/
theorem powerMapVirtual_conjRelation_mem_directSumSubgroup
    (n : ℕ) (A : EndomorphismObject.{u, v} K) {B : EndomorphismObject.{u, v} K}
    (e : A.carrier ≃ₗ[K] B.carrier) :
    powerMapVirtual K n (conjRelation K A e) ∈ directSumSubgroup K := by
  exact (powerMapVirtual_conjRelation (K := K) n A e) ▸
    conjRelation_mem_directSumSubgroup K (EndomorphismObject.power A n) e

/-- The virtual power map sends direct-sum relations into the direct-sum
relation subgroup. -/
theorem powerMapVirtual_directSumRelation_mem_directSumSubgroup
    (n : ℕ) (A B : EndomorphismObject.{u, v} K) :
    powerMapVirtual K n (directSumRelation K A B) ∈ directSumSubgroup K := by
  exact (powerMapVirtual_directSumRelation (K := K) n A B) ▸
    directSumRelation_mem_directSumSubgroup K
      (EndomorphismObject.power A n) (EndomorphismObject.power B n)

theorem powerMapVirtual_zeroObject_mem_directSumSubgroup
    (n : ℕ) (A : EndomorphismObject.{u, v} K) (hA : Subsingleton A.carrier) :
    powerMapVirtual K n (of K A) ∈ directSumSubgroup K := by
  exact
    (powerMapVirtual_of (K := K) n A).symm ▸
      zeroObject_mem_directSumSubgroup K (EndomorphismObject.power A n) hA

/-- The virtual power map preserves the direct-sum relation subgroup. -/
theorem powerMapVirtual_directSumSubgroup_le (n : ℕ) :
    directSumSubgroup K ≤
      (directSumSubgroup K).comap (powerMapVirtual K n) := by
  exact (AddSubgroup.closure_le ((directSumSubgroup K).comap (powerMapVirtual K n))).2
    (fun x hx =>
      match hx with
      | Or.inl ⟨A, B, h⟩ =>
          h ▸ powerMapVirtual_directSumRelation_mem_directSumSubgroup K n A B
      | Or.inr (Or.inl ⟨A, B, e, h⟩) =>
          h ▸ powerMapVirtual_conjRelation_mem_directSumSubgroup K n A e
      | Or.inr (Or.inr ⟨A, hA, h⟩) =>
          h ▸ powerMapVirtual_zeroObject_mem_directSumSubgroup K n A hA)

/-- The descended power operation on the direct-sum K₀ group. -/
def powerMapK0 (n : ℕ) : K0 K →+ K0 K :=
  QuotientAddGroup.lift (directSumSubgroup K)
    ((mk K).comp (powerMapVirtual K n))
    (by
      intro x hx
      exact (QuotientAddGroup.eq_zero_iff
        (N := directSumSubgroup K) (powerMapVirtual K n x)).2
          (powerMapVirtual_directSumSubgroup_le K n hx))

theorem powerMapK0_mk (n : ℕ) (x : VirtualEndomorphism K) :
    powerMapK0 K n (mk K x) = mk K (powerMapVirtual K n x) := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (by
      intro x hx
      exact (QuotientAddGroup.eq_zero_iff
        (N := directSumSubgroup K) (powerMapVirtual K n x)).2
          (powerMapVirtual_directSumSubgroup_le K n hx))
    x

theorem powerMapK0_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    powerMapK0 K n (mk K (of K A)) =
      mk K (of K (EndomorphismObject.power A n)) := by
  exact powerMapK0_mk K n (of K A)

/-- The trace character compatibility with `powerMapK0` on a generator. -/
theorem traceCharacterK0_one_powerMapK0_of (n : ℕ) (A : EndomorphismObject.{u, v} K) :
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (of K A))) =
      traceCharacterK0 K n (mk K (of K A)) := by
  calc
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (of K A)))
        = traceCharacterK0 K 1 (mk K (of K (EndomorphismObject.power A n))) := by
          rfl
    _ = EndomorphismObject.tracePower 1 (EndomorphismObject.power A n) := by
          exact traceCharacterK0_of (K := K) 1 (EndomorphismObject.power A n)
    _ = EndomorphismObject.tracePower n A := by
          exact EndomorphismObject.tracePower_one_power A n
    _ = traceCharacterK0 K n (mk K (of K A)) := by
          symm
          exact traceCharacterK0_of (K := K) n A

theorem traceCharacterK0_one_powerMapK0_neg_step
    (n : ℕ) (y : EndomorphismObject.{u, v} K)
    (hy : traceCharacterK0 K 1 (powerMapK0 K n (mk K (pure y))) =
      traceCharacterK0 K n (mk K (pure y))) :
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (-pure y))) =
      traceCharacterK0 K n (mk K (-pure y)) := by
  calc
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (-pure y))) =
        traceCharacterK0 K 1 (powerMapK0 K n (-(mk K (pure y)))) := by
          exact congrArg (traceCharacterK0 K 1)
            (congrArg (powerMapK0 K n) (map_neg (mk K) (pure y)))
    _ = traceCharacterK0 K 1 (-(powerMapK0 K n (mk K (pure y)))) := by
          exact congrArg (traceCharacterK0 K 1)
            (map_neg (powerMapK0 K n) (mk K (pure y)))
    _ = -traceCharacterK0 K 1 (powerMapK0 K n (mk K (pure y))) := by
          exact map_neg (traceCharacterK0 K 1)
            (powerMapK0 K n (mk K (pure y)))
    _ = -traceCharacterK0 K n (mk K (pure y)) := by
          exact congrArg Neg.neg hy
    _ = traceCharacterK0 K n (mk K (-pure y)) := by
          symm
          exact map_neg (traceCharacterK0 K n) (mk K (pure y))

theorem traceCharacterK0_one_powerMapK0_add_step
    (n : ℕ) (y z : FreeAbelianGroup (EndomorphismObject.{u, v} K))
    (hy : traceCharacterK0 K 1 (powerMapK0 K n (mk K y)) =
      traceCharacterK0 K n (mk K y))
    (hz : traceCharacterK0 K 1 (powerMapK0 K n (mk K z)) =
      traceCharacterK0 K n (mk K z)) :
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (y + z))) =
      traceCharacterK0 K n (mk K (y + z)) := by
  calc
    traceCharacterK0 K 1 (powerMapK0 K n (mk K (y + z))) =
        traceCharacterK0 K 1 (powerMapK0 K n (mk K y + mk K z)) := by
          exact congrArg (traceCharacterK0 K 1)
            (congrArg (powerMapK0 K n) (map_add (mk K) y z))
    _ = traceCharacterK0 K 1 (powerMapK0 K n (mk K y) +
          powerMapK0 K n (mk K z)) := by
          exact congrArg (traceCharacterK0 K 1)
            (map_add (powerMapK0 K n) (mk K y) (mk K z))
    _ = traceCharacterK0 K 1 (powerMapK0 K n (mk K y)) +
          traceCharacterK0 K 1 (powerMapK0 K n (mk K z)) := by
          exact map_add (traceCharacterK0 K 1)
            (powerMapK0 K n (mk K y)) (powerMapK0 K n (mk K z))
    _ = traceCharacterK0 K n (mk K y) + traceCharacterK0 K n (mk K z) := by
          exact congrArg₂ HAdd.hAdd hy hz
    _ = traceCharacterK0 K n (mk K (y + z)) := by
          symm
          exact map_add (traceCharacterK0 K n) (mk K y) (mk K z)

/-- The trace-power compatibility proof respects additive recursion on the free
abelian group. -/
theorem traceCharacterK0_one_powerMapK0_induction
    (n : ℕ) (y : FreeAbelianGroup (EndomorphismObject.{u, v} K)) :
    traceCharacterK0 K 1 (powerMapK0 K n (mk K y)) =
      traceCharacterK0 K n (mk K y) := by
  induction y using FreeAbelianGroup.induction_on' with
  | C0 =>
      calc
        traceCharacterK0 K 1 (powerMapK0 K n (mk K 0)) = traceCharacterK0 K 1 0 := by
          exact congrArg (traceCharacterK0 K 1) (map_zero (powerMapK0 K n))
        _ = 0 := by
          exact map_zero _
        _ = traceCharacterK0 K n 0 := by
          symm
          exact map_zero _
  | C1 A =>
      exact traceCharacterK0_one_powerMapK0_of (K := K) n A
  | Cn y hy =>
      exact traceCharacterK0_one_powerMapK0_neg_step (K := K) n y hy
  | Cp y z hy hz =>
      exact traceCharacterK0_one_powerMapK0_add_step (K := K) n y z hy hz

/-- Applying the ordinary trace character to the powered K₀ class recovers the
`n`th trace-power character. -/
theorem traceCharacterK0_one_powerMapK0 (n : ℕ) (x : K0 K) :
    traceCharacterK0 K 1 (powerMapK0 K n x) =
      traceCharacterK0 K n x := by
  exact Quotient.inductionOn' x
    (fun y => traceCharacterK0_one_powerMapK0_induction (K := K) n y)

/-- The power map fixes the `n=1` generator. -/
theorem powerMapK0_one_of (A : EndomorphismObject.{u, v} K) :
    powerMapK0 K 1 (mk K (of K A)) = mk K (of K A) := by
  calc
    powerMapK0 K 1 (mk K (of K A))
        = mk K (of K (EndomorphismObject.power A 1)) := by
          exact powerMapK0_of (K := K) 1 A
    _ = mk K (of K A) := by
          exact congrArg (fun X => mk K (of K X)) (EndomorphismObject.power_one A)

theorem powerMapK0_one_neg_step
    (y : EndomorphismObject.{u, v} K)
    (hy : powerMapK0 K 1 (mk K (pure y)) = mk K (pure y)) :
    powerMapK0 K 1 (mk K (-pure y)) = mk K (-pure y) := by
  calc
    powerMapK0 K 1 (mk K (-pure y)) =
        powerMapK0 K 1 (-(mk K (pure y))) := by
          exact congrArg (powerMapK0 K 1) (map_neg (mk K) (pure y))
    _ = -powerMapK0 K 1 (mk K (pure y)) := by
          exact map_neg (powerMapK0 K 1) (mk K (pure y))
    _ = -mk K (pure y) := by
          exact congrArg Neg.neg hy
    _ = mk K (-pure y) := by
          symm
          exact map_neg (mk K) (pure y)

theorem powerMapK0_one_add_step
    (y z : FreeAbelianGroup (EndomorphismObject.{u, v} K))
    (hy : powerMapK0 K 1 (mk K y) = mk K y)
    (hz : powerMapK0 K 1 (mk K z) = mk K z) :
    powerMapK0 K 1 (mk K (y + z)) = mk K (y + z) := by
  calc
    powerMapK0 K 1 (mk K (y + z)) =
        powerMapK0 K 1 (mk K y + mk K z) := by
          exact congrArg (powerMapK0 K 1)
            (map_add (mk K) y z)
    _ = powerMapK0 K 1 (mk K y) + powerMapK0 K 1 (mk K z) := by
          exact map_add (powerMapK0 K 1) (mk K y) (mk K z)
    _ = mk K y + mk K z := by
          exact congrArg₂ HAdd.hAdd hy hz
    _ = mk K (y + z) := by
          symm
          exact map_add (mk K) y z

/-- The `n=1` power-map compatibility proof respects additive recursion on the
free abelian group. -/
theorem powerMapK0_one_induction
    (y : FreeAbelianGroup (EndomorphismObject.{u, v} K)) :
    powerMapK0 K 1 (mk K y) = mk K y := by
  induction y using FreeAbelianGroup.induction_on' with
  | C0 =>
      calc
        powerMapK0 K 1 (mk K 0) = 0 := by
          exact map_zero _
        _ = mk K 0 := by
          symm
          exact map_zero _
  | C1 A =>
      exact powerMapK0_one_of (K := K) A
  | Cn y hy =>
      exact powerMapK0_one_neg_step (K := K) y hy
  | Cp y z hy hz =>
      exact powerMapK0_one_add_step (K := K) y z hy hz

theorem powerMapK0_one (x : K0 K) :
    powerMapK0 K 1 x = x := by
  exact Quotient.inductionOn' x
    (fun y => powerMapK0_one_induction (K := K) y)

/-- The power maps compose on generators by multiplication of exponents. -/
theorem powerMapK0_comp_of (m n : ℕ) (A : EndomorphismObject.{u, v} K) :
    powerMapK0 K n (powerMapK0 K m (mk K (of K A))) =
      powerMapK0 K (m * n) (mk K (of K A)) := by
  calc
    powerMapK0 K n (powerMapK0 K m (mk K (of K A)))
        = mk K (of K (EndomorphismObject.power (EndomorphismObject.power A m) n)) := by
          exact powerMapK0_mk (K := K) n (of K (EndomorphismObject.power A m))
    _ = mk K (of K (EndomorphismObject.power A (m * n))) := by
          exact congrArg (fun X => mk K (of K X)) (EndomorphismObject.power_power A m n)
    _ = powerMapK0 K (m * n) (mk K (of K A)) := by
          symm
          exact powerMapK0_of (K := K) (m * n) A

theorem powerMapK0_comp_neg_step
    (m n : ℕ) (y : EndomorphismObject.{u, v} K)
    (hy : powerMapK0 K n (powerMapK0 K m (mk K (pure y))) =
      powerMapK0 K (m * n) (mk K (pure y))) :
    powerMapK0 K n (powerMapK0 K m (mk K (-pure y))) =
      powerMapK0 K (m * n) (mk K (-pure y)) := by
  calc
    powerMapK0 K n (powerMapK0 K m (mk K (-pure y))) =
        powerMapK0 K n (-(powerMapK0 K m (mk K (pure y)))) := by
          exact congrArg (powerMapK0 K n)
            (map_neg (powerMapK0 K m) (mk K (pure y)))
    _ = -powerMapK0 K n (powerMapK0 K m (mk K (pure y))) := by
          exact map_neg (powerMapK0 K n) (powerMapK0 K m (mk K (pure y)))
    _ = -powerMapK0 K (m * n) (mk K (pure y)) := by
          exact congrArg Neg.neg hy
    _ = powerMapK0 K (m * n) (mk K (-pure y)) := by
          symm
          exact map_neg (powerMapK0 K (m * n)) (mk K (pure y))

theorem powerMapK0_comp_add_step
    (m n : ℕ) (y z : FreeAbelianGroup (EndomorphismObject.{u, v} K))
    (hy : powerMapK0 K n (powerMapK0 K m (mk K y)) =
      powerMapK0 K (m * n) (mk K y))
    (hz : powerMapK0 K n (powerMapK0 K m (mk K z)) =
      powerMapK0 K (m * n) (mk K z)) :
    powerMapK0 K n (powerMapK0 K m (mk K (y + z))) =
      powerMapK0 K (m * n) (mk K (y + z)) := by
  calc
    powerMapK0 K n (powerMapK0 K m (mk K (y + z))) =
        powerMapK0 K n (powerMapK0 K m (mk K y + mk K z)) := by
          exact congrArg (powerMapK0 K n)
            (congrArg (powerMapK0 K m) (map_add (mk K) y z))
    _ = powerMapK0 K n (powerMapK0 K m (mk K y) +
          powerMapK0 K m (mk K z)) := by
          exact congrArg (powerMapK0 K n)
            (map_add (powerMapK0 K m) (mk K y) (mk K z))
    _ = powerMapK0 K n (powerMapK0 K m (mk K y)) +
          powerMapK0 K n (powerMapK0 K m (mk K z)) := by
          exact map_add (powerMapK0 K n)
            (powerMapK0 K m (mk K y)) (powerMapK0 K m (mk K z))
    _ = powerMapK0 K (m * n) (mk K y) + powerMapK0 K (m * n) (mk K z) := by
          exact congrArg₂ HAdd.hAdd hy hz
    _ = powerMapK0 K (m * n) (mk K (y + z)) := by
          symm
          exact map_add (powerMapK0 K (m * n)) (mk K y) (mk K z)

/-- Composition of power maps respects additive recursion on the free abelian
group. -/
theorem powerMapK0_comp_induction
    (m n : ℕ) (y : FreeAbelianGroup (EndomorphismObject.{u, v} K)) :
    powerMapK0 K n (powerMapK0 K m (mk K y)) =
      powerMapK0 K (m * n) (mk K y) := by
  induction y using FreeAbelianGroup.induction_on' with
  | C0 =>
      calc
        powerMapK0 K n (powerMapK0 K m (mk K 0)) = 0 := by
          exact map_zero _
        _ = powerMapK0 K (m * n) (mk K 0) := by
          symm
          exact map_zero _
  | C1 A =>
      exact powerMapK0_comp_of (K := K) m n A
  | Cn y hy =>
      exact powerMapK0_comp_neg_step (K := K) m n y hy
  | Cp y z hy hz =>
      exact powerMapK0_comp_add_step (K := K) m n y z hy hz

/-- Composing K₀ power maps multiplies the exponents. -/
theorem powerMapK0_comp (m n : ℕ) (x : K0 K) :
    powerMapK0 K n (powerMapK0 K m x) =
      powerMapK0 K (m * n) x := by
  exact Quotient.inductionOn' x
    (fun y => powerMapK0_comp_induction (K := K) m n y)

/-- The first trace character descended to the direct-sum quotient. -/
def traceCharacterOneK0 : K0 K →+ K :=
  traceCharacterK0 K 1

theorem traceCharacterOneK0_mk (x : VirtualEndomorphism K) :
    traceCharacterOneK0 K (mk K x) = traceCharacter K 1 x := by
  exact QuotientAddGroup.lift_mk (directSumSubgroup K)
    (directSumSubgroup_le_traceCharacter_one_ker K) x

theorem traceCharacterOneK0_of (A : EndomorphismObject.{u, v} K) :
    traceCharacterOneK0 K (mk K (of K A)) = EndomorphismObject.tracePower 1 A := by
  calc
    traceCharacterOneK0 K (mk K (of K A)) = traceCharacter K 1 (of K A) := by
      exact traceCharacterOneK0_mk K (of K A)
    _ = EndomorphismObject.tracePower 1 A := by
      exact traceCharacter_of (K := K) 1 A

end
end EndomorphismK0
end Boundary
