import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.Exactness.Owner

/-!
# Exactness of localization-input bounded mapping-cone triangles

The bounded mapping-cone triangle generated by a localization input is
distinguished, so its three consecutive composites vanish.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The first two morphisms of a localization-input bounded cone triangle compose to
zero. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_first_comp_second
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.triangle.mor₁ ≫
        input.boundedMappingConeTriangle.triangle.mor₂ =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_first_comp_second
    input.boundedAdditiveComplexHom

/-- The second and third morphisms of a localization-input bounded cone triangle
compose to zero. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_second_comp_third
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.triangle.mor₂ ≫
        input.boundedMappingConeTriangle.triangle.mor₃ =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_second_comp_third
    input.boundedAdditiveComplexHom

/-- The third morphism followed by the shifted first morphism of a localization-input
bounded cone triangle is zero. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_third_comp_shifted_first
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.triangle.mor₃ ≫
        input.boundedMappingConeTriangle.triangle.mor₁⟦(1 : ℤ)⟧' =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_third_comp_shifted_first
    input.boundedAdditiveComplexHom

end AnalyticMotives
end LFunctions
end Boundary
