import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Presheaves.RewriteMaps.Owner

/-!
# By-kind rewrite endpoints

This file names the certified endpoint presentations and trace morphisms for
the seven primitive analytic rewrite kinds.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The source presentation of a Stokes cancellation rewrite. -/
def TraceRewriteGenerator.stokesSourcePresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.stokes source target).sourcePresentation

/-- The target presentation of a Stokes cancellation rewrite. -/
def TraceRewriteGenerator.stokesTargetPresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.stokes source target).targetPresentation

/-- The source presentation of a residue-extraction rewrite. -/
def TraceRewriteGenerator.residueSourcePresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.residue source target).sourcePresentation

/-- The target presentation of a residue-extraction rewrite. -/
def TraceRewriteGenerator.residueTargetPresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.residue source target).targetPresentation

/-- The source presentation of a channel-decomposition rewrite. -/
def TraceRewriteGenerator.channelSourcePresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.channel source target).sourcePresentation

/-- The target presentation of a channel-decomposition rewrite. -/
def TraceRewriteGenerator.channelTargetPresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.channel source target).targetPresentation

/-- The source presentation of a refinement-invariance rewrite. -/
def TraceRewriteGenerator.refinementSourcePresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.refinement source target).sourcePresentation

/-- The target presentation of a refinement-invariance rewrite. -/
def TraceRewriteGenerator.refinementTargetPresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.refinement source target).targetPresentation

/-- The source presentation of a schedule-exchange rewrite. -/
def TraceRewriteGenerator.scheduleSourcePresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.schedule source target).sourcePresentation

/-- The target presentation of a schedule-exchange rewrite. -/
def TraceRewriteGenerator.scheduleTargetPresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.schedule source target).targetPresentation

/-- The source presentation of a weight-drop rewrite. -/
def TraceRewriteGenerator.weightDropSourcePresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.weightDrop source target).sourcePresentation

/-- The target presentation of a weight-drop rewrite. -/
def TraceRewriteGenerator.weightDropTargetPresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.weightDrop source target).targetPresentation

/-- The source presentation of a Fubini coherence rewrite. -/
def TraceRewriteGenerator.fubiniSourcePresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.fubini source target).sourcePresentation

/-- The target presentation of a Fubini coherence rewrite. -/
def TraceRewriteGenerator.fubiniTargetPresentation
    (source target : QTraceExpression) :
    CertifiedResidueChannelPresentation :=
  (TraceRewriteGenerator.fubini source target).targetPresentation

/-- The trace-correspondence morphism generated by a Stokes cancellation rewrite. -/
def TraceRewriteGenerator.stokesTraceHom
    (source target : QTraceExpression) :
    (TraceRewriteGenerator.stokes source target).sourceObject ⟶
      (TraceRewriteGenerator.stokes source target).targetObject :=
  (TraceRewriteGenerator.stokes source target).traceHom

/-- The trace-correspondence morphism generated by a residue-extraction rewrite. -/
def TraceRewriteGenerator.residueTraceHom
    (source target : QTraceExpression) :
    (TraceRewriteGenerator.residue source target).sourceObject ⟶
      (TraceRewriteGenerator.residue source target).targetObject :=
  (TraceRewriteGenerator.residue source target).traceHom

/-- The trace-correspondence morphism generated by a channel-decomposition rewrite. -/
def TraceRewriteGenerator.channelTraceHom
    (source target : QTraceExpression) :
    (TraceRewriteGenerator.channel source target).sourceObject ⟶
      (TraceRewriteGenerator.channel source target).targetObject :=
  (TraceRewriteGenerator.channel source target).traceHom

/-- The trace-correspondence morphism generated by a refinement-invariance rewrite. -/
def TraceRewriteGenerator.refinementTraceHom
    (source target : QTraceExpression) :
    (TraceRewriteGenerator.refinement source target).sourceObject ⟶
      (TraceRewriteGenerator.refinement source target).targetObject :=
  (TraceRewriteGenerator.refinement source target).traceHom

/-- The trace-correspondence morphism generated by a schedule-exchange rewrite. -/
def TraceRewriteGenerator.scheduleTraceHom
    (source target : QTraceExpression) :
    (TraceRewriteGenerator.schedule source target).sourceObject ⟶
      (TraceRewriteGenerator.schedule source target).targetObject :=
  (TraceRewriteGenerator.schedule source target).traceHom

/-- The trace-correspondence morphism generated by a weight-drop rewrite. -/
def TraceRewriteGenerator.weightDropTraceHom
    (source target : QTraceExpression) :
    (TraceRewriteGenerator.weightDrop source target).sourceObject ⟶
      (TraceRewriteGenerator.weightDrop source target).targetObject :=
  (TraceRewriteGenerator.weightDrop source target).traceHom

/-- The trace-correspondence morphism generated by a Fubini coherence rewrite. -/
def TraceRewriteGenerator.fubiniTraceHom
    (source target : QTraceExpression) :
    (TraceRewriteGenerator.fubini source target).sourceObject ⟶
      (TraceRewriteGenerator.fubini source target).targetObject :=
  (TraceRewriteGenerator.fubini source target).traceHom

end AnalyticMotives
end LFunctions
end Boundary
