import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourCorQ.Linearization.Reindexing.Owner

/-!
# Reindexing equivalence for finite rational contour sums

This owner turns explicit finite-index reindexing witnesses into the native
equivalence relation on formal rational sums.  It is the equality layer used
before constructing quotient homs for `ContourCor_Q`.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

namespace ContourCorQFormalSum

/-- Two formal sums are reindexing-equivalent when an explicit reindexing exists. -/
def ReindexingRel {X Y : ContourCorQObject}
    (S T : ContourCorQFormalSum X Y) : Prop :=
  Nonempty (ContourCorQFormalSumReindexing S T)

/-- Reindexing equivalence is reflexive. -/
theorem reindexingRel_refl {X Y : ContourCorQObject}
    (S : ContourCorQFormalSum X Y) :
    ReindexingRel S S :=
  Nonempty.intro (ContourCorQFormalSumReindexing.refl S)

/-- Reindexing equivalence is symmetric. -/
theorem reindexingRel_symm {X Y : ContourCorQObject}
    {S T : ContourCorQFormalSum X Y}
    (h : ReindexingRel S T) :
    ReindexingRel T S :=
  match h with
  | Nonempty.intro R =>
      Nonempty.intro (ContourCorQFormalSumReindexing.symm R)

/-- Reindexing equivalence is transitive. -/
theorem reindexingRel_trans {X Y : ContourCorQObject}
    {S T U : ContourCorQFormalSum X Y}
    (hST : ReindexingRel S T)
    (hTU : ReindexingRel T U) :
    ReindexingRel S U :=
  match hST with
  | Nonempty.intro R =>
      match hTU with
      | Nonempty.intro Q =>
          Nonempty.intro (ContourCorQFormalSumReindexing.trans R Q)

/-- Reindexing equivalence is preserved by coefficient scaling. -/
theorem reindexingRel_scale {X Y : ContourCorQObject}
    {S T : ContourCorQFormalSum X Y}
    (q : Rat)
    (h : ReindexingRel S T) :
    ReindexingRel
      (ContourCorQFormalSum.scale q S)
      (ContourCorQFormalSum.scale q T) :=
  match h with
  | Nonempty.intro R =>
      Nonempty.intro (ContourCorQFormalSumReindexing.scale q R)

/-- Reindexing equivalence is preserved by addition. -/
theorem reindexingRel_add {X Y : ContourCorQObject}
    {S₁ S₂ T₁ T₂ : ContourCorQFormalSum X Y}
    (h₁ : ReindexingRel S₁ T₁)
    (h₂ : ReindexingRel S₂ T₂) :
    ReindexingRel
      (ContourCorQFormalSum.add S₁ S₂)
      (ContourCorQFormalSum.add T₁ T₂) :=
  match h₁ with
  | Nonempty.intro R₁ =>
      match h₂ with
      | Nonempty.intro R₂ =>
          Nonempty.intro (ContourCorQFormalSumReindexing.add R₁ R₂)

/-- Reindexing equivalence is preserved by negation. -/
theorem reindexingRel_neg {X Y : ContourCorQObject}
    {S T : ContourCorQFormalSum X Y}
    (h : ReindexingRel S T) :
    ReindexingRel
      (ContourCorQFormalSum.neg S)
      (ContourCorQFormalSum.neg T) :=
  reindexingRel_scale (-1) h

/-- Reindexing equivalence is preserved by subtraction. -/
theorem reindexingRel_sub {X Y : ContourCorQObject}
    {S₁ S₂ T₁ T₂ : ContourCorQFormalSum X Y}
    (h₁ : ReindexingRel S₁ T₁)
    (h₂ : ReindexingRel S₂ T₂) :
    ReindexingRel
      (ContourCorQFormalSum.sub S₁ S₂)
      (ContourCorQFormalSum.sub T₁ T₂) :=
  reindexingRel_add h₁ (reindexingRel_neg h₂)

/-- The setoid on formal rational contour sums generated by reindexing. -/
def reindexingSetoid (X Y : ContourCorQObject) :
    Setoid (ContourCorQFormalSum X Y) where
  r := ReindexingRel
  iseqv := {
    refl := reindexingRel_refl
    symm := reindexingRel_symm
    trans := reindexingRel_trans
  }

/-- Quotient homs for the rational contour correspondence category. -/
abbrev QuotientHom (X Y : ContourCorQObject) : Type :=
  Quotient (reindexingSetoid X Y)

/-- The quotient class of a finite formal rational contour sum. -/
def quotientClass {X Y : ContourCorQObject}
    (S : ContourCorQFormalSum X Y) :
    QuotientHom X Y :=
  Quotient.mk (reindexingSetoid X Y) S

end ContourCorQFormalSum

end AnalyticMotives
end LFunctions
end Boundary
