import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Source.Bounded.IsoClosure.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Weights.Source.Bounds.Triangles.MappingCone.Stable.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Weights.Source.Bounds.Triangles.MappingCone.ThirdIsoBounded.Owner

/-!
# Iso-closure bounded stable membership for mapping-cone vertices

This file records the stable comparison-source membership of the concrete
mapping-cone third vertex in the predicate generated by degreewise
iso-closure bounded analytic complexes.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

namespace TraceAnalyticMotiveComparison
namespace SourceBoundedMappingCone

/-- The first stable vertex of a bounded analytic mapping-cone triangle belongs
to the iso-closed predicate generated by degreewise iso-closure bounded stable
representatives. -/
theorem stableFirstObject_degreewiseIsoClosureBoundedStableObject
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject
        (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
          .stableFirstObject hom) :=
  Eq.subst
    (motive := fun object =>
      TraceAnalyticDMgmComparisonSource
        .degreewiseIsoClosureBoundedStableObject object)
    (Eq.symm
      (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
        .stableFirstObject_eq hom))
    (TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject_of_sourceStableWeightBoundedObject
        source)

/-- The second stable vertex of a bounded analytic mapping-cone triangle belongs
to the iso-closed predicate generated by degreewise iso-closure bounded stable
representatives. -/
theorem stableSecondObject_degreewiseIsoClosureBoundedStableObject
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject
        (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
          .stableSecondObject hom) :=
  Eq.subst
    (motive := fun object =>
      TraceAnalyticDMgmComparisonSource
        .degreewiseIsoClosureBoundedStableObject object)
    (Eq.symm
      (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
        .stableSecondObject_eq hom))
    (TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject_of_sourceStableWeightBoundedObject
        target)

/-- The third stable vertex of a bounded analytic mapping-cone triangle is
represented by the concrete mapping-cone complex, whose degree objects are
bounded up to iso-closure. -/
theorem stableThirdObject_degreewiseIsoClosureBoundedStableRepresentative
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableRepresentative
        (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
          .stableThirdObject hom) :=
  Exists.intro
    bound
    (Exists.intro
      (CochainComplex.mappingCone hom)
      (And.intro
        (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
          .thirdObject_sourceDegreewiseIsoClosureBoundedBy hom)
        (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
          .stableThirdObject_eq hom)))

/-- The third stable vertex of a bounded analytic mapping-cone triangle belongs
to the iso-closed predicate generated by degreewise iso-closure bounded stable
representatives. -/
theorem stableThirdObject_degreewiseIsoClosureBoundedStableObject
    {bound : Nat}
    {source target :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy bound}
    (hom :
      TraceAnalyticMotiveComparison.SourceComplexWeightBoundedBy.Hom
        source
        target) :
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableObject
        (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
          .stableThirdObject hom) :=
  CategoryTheory.le_isoClosure
    TraceAnalyticDMgmComparisonSource
      .degreewiseIsoClosureBoundedStableRepresentative
    (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
      .stableThirdObject hom)
    (TraceAnalyticMotiveComparison.SourceBoundedMappingCone
      .stableThirdObject_degreewiseIsoClosureBoundedStableRepresentative
        hom)

end SourceBoundedMappingCone
end TraceAnalyticMotiveComparison

end AnalyticMotives
end LFunctions
end Boundary
