import Boundary.LFunctions.Bridge.WeilCriterion
import Boundary.LFunctions.ZetaPacketEnergy
import Boundary.LFunctions.ZetaExplicitFormulaBoundaryTransport
import Boundary.LFunctions.ZetaExplicitFormulaContourBridge

/-!
# Boundary zeta criterion surface

This file is the owner-level checkpoint for the final explicit-formula route.
 The packet-side norm-square theorem is already proved in the packet energy
 layer; this file re-exports that honest theorem surface and keeps the final
 bridge location explicit.

The convolution-autocorrelation lane is proved by transporting the zero-side
Krein form to the Hermitian packet norm square. Raw all-probe Weil positivity
is stronger than this lane and is not exported as a proved theorem here.
-/

namespace Boundary
namespace LFunctions

noncomputable section

/-- The packet norm-square identity in the owner namespace. -/
theorem zetaPacketNormSquare (x : ZetaPacketEnsemble) :
    ZetaPacketEnsemble.normSq x =
      ZetaPacketEnsemble.primePacketGram x +
      ZetaPacketEnsemble.archimedeanPacketGram x +
      ZetaPacketEnsemble.correctionPacketGram x := by
  exact ZetaPacketEnsemble.zetaPacketNormSquare x

/-- The packet energy identity in the owner namespace. -/
theorem zetaPacketEnergy_eq_sum (x : ZetaPacketEnsemble) :
    ZetaPacketEnsemble.packetEnergy x =
      ZetaPacketEnsemble.packetEnergyPrime x +
      ZetaPacketEnsemble.packetEnergyArchimedean x +
      ZetaPacketEnsemble.packetEnergyCorrection x := by
  exact ZetaPacketEnsemble.packetEnergy_eq_sum x

/-- The packet energy is nonnegative in the owner namespace. -/
theorem zetaPacketEnergy_nonneg (x : ZetaPacketEnsemble) :
    0 ≤ ZetaPacketEnsemble.packetEnergy x := by
  exact ZetaPacketEnsemble.packetEnergy_nonneg x

/-- The analytic explicit-formula equality needed for convolution-autocorrelation positivity. -/
theorem zetaCriterion_convolutionAutocorrelation_zeroKreinGram_eq_boundarySum
    (f : ZetaAdmissibleFunction) :
    zetaCompletedZeroKreinGram (ZetaAdmissibleFunction.convolutionAutocorrelation f) =
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum f := by
  exact ZetaAdmissibleFunction.zetaCompletedExplicitFormulaContourBridge_convolutionAutocorrelation f

/-- Historical name for the convolution-autocorrelation zero-side/boundary bridge. -/
theorem zetaCriterion_autocorrelation_zeroKreinGram_eq_boundarySum
    (f : ZetaAdmissibleFunction) :
    zetaCompletedZeroKreinGram (ZetaAdmissibleFunction.convolutionAutocorrelation f) =
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum f := by
  exact zetaCriterion_convolutionAutocorrelation_zeroKreinGram_eq_boundarySum f

/-- Boundary real nonnegativity on autocorrelation seeds implies the criterion's
convolution-autocorrelation Weil-positivity predicate. -/
theorem zetaCriterion_autocorrelation_weilPositivity_predicate :
    (∀ f : ZetaAdmissibleFunction,
      0 ≤
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum
          f) →
    ZetaAutocorrelationWeilPositivity := by
  intro hboundaryAll
  intro φ hφ
  rcases hφ with ⟨f, hφ⟩
  let g : ZetaAdmissibleFunction := ZetaAdmissibleFunction.convolutionAutocorrelation f
  have hφg :
      zetaWeilFormCompleted φ = zetaWeilFormCompleted g :=
    zetaWeilFormCompleted_congr_toZetaTestFunction hφ
  have hzero_boundary :
      zetaCompletedZeroKreinGram g =
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum f := by
    exact zetaCriterion_convolutionAutocorrelation_zeroKreinGram_eq_boundarySum f
  have hboundary :
      0 ≤ ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum f :=
    hboundaryAll f
  have hzero : 0 ≤ zetaCompletedZeroKreinGram g :=
    Eq.subst (motive := fun x : ℝ => 0 ≤ x) hzero_boundary.symm hboundary
  have hweil_zero :
      zetaWeilFormCompleted g = zetaCompletedZeroKreinGram g :=
    zetaWeilFormCompleted_eq_zeroKreinGram g
  have hweil_g : 0 ≤ zetaWeilFormCompleted g :=
    Eq.subst (motive := fun x : ℝ => 0 ≤ x) hweil_zero.symm hzero
  exact Eq.subst (motive := fun x : ℝ => 0 ≤ x) hφg.symm hweil_g

/-- Positivity on autocorrelation probes gives quadratic Weil positivity by evaluating the
restricted positivity theorem on the autocorrelation probe generated by the chosen seed. -/
theorem zetaCriterion_quadraticWeilPositivity_of_autocorrelation
    (h : ZetaAutocorrelationWeilPositivity) :
    ZetaWeilQuadraticPositivity := by
  intro f
  exact h (ZetaAdmissibleFunction.convolutionAutocorrelation f) ⟨f, rfl⟩

/-- Boundary real nonnegativity on autocorrelation seeds implies the criterion's quadratic
Weil positivity predicate. -/
theorem zetaCriterion_quadraticWeilPositivity_predicate :
    (∀ f : ZetaAdmissibleFunction,
      0 ≤
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum
          f) →
    ZetaWeilQuadraticPositivity := by
  intro hboundaryAll
  exact zetaCriterion_quadraticWeilPositivity_of_autocorrelation
    (zetaCriterion_autocorrelation_weilPositivity_predicate hboundaryAll)

/-- Transport from the time-side autocorrelation Krein scalar to the completed ordered-heart
GNS norm-square implies the criterion's quadratic Weil positivity predicate.  The GNS scalar
is nonnegative by construction; the preferred owner-level transport seam is the ordered-heart
quotient scalar below. -/
theorem zetaCriterion_quadraticWeilPositivity_of_GNSTransport
    (htransport :
      ∀ f : ZetaAdmissibleFunction,
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum f =
          ZetaAdmissibleFunction.completedBoundaryGNSNormSq f) :
    ZetaWeilQuadraticPositivity := by
  exact zetaCriterion_quadraticWeilPositivity_predicate
    (fun f : ZetaAdmissibleFunction =>
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum_nonnegative_of_GNSTransport
        f
        (htransport f))

/-- Criterion transport through the completed ordered-heart quotient scalar.  This is the
honest quotient-level version of the finite-part/GNS comparison: the contour-side Krein
scalar must descend to the finite-part ordered-heart class, whose scalar is already the
positive GNS norm-square. -/
theorem zetaCriterion_quadraticWeilPositivity_of_orderedHeartQuotientTransport
    (htransport :
      ∀ f : ZetaAdmissibleFunction,
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum f =
          ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryOrderedHeartScalar
            f) :
    ZetaWeilQuadraticPositivity := by
  exact zetaCriterion_quadraticWeilPositivity_predicate
    (fun f : ZetaAdmissibleFunction =>
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum_nonnegative_of_orderedHeartQuotientTransport
        f
        (htransport f))

/-- Direct ordered-heart payoff: if the zero-side contour theorem lands in the completed
ordered-heart scalar, then autocorrelation Weil positivity follows from the GNS positive
cone.  This bypasses the raw time-side finite-part representative. -/
theorem zetaCriterion_autocorrelation_weilPositivity_of_orderedHeartContourBridge
    (hbridge :
      ∀ f : ZetaAdmissibleFunction,
        zetaCompletedZeroKreinGram
            (ZetaAdmissibleFunction.convolutionAutocorrelation f) =
          ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryOrderedHeartScalar
            f) :
    ZetaAutocorrelationWeilPositivity := by
  intro φ hφ
  rcases hφ with ⟨f, hφ⟩
  let g : ZetaAdmissibleFunction := ZetaAdmissibleFunction.convolutionAutocorrelation f
  have hφg :
      zetaWeilFormCompleted φ = zetaWeilFormCompleted g :=
    zetaWeilFormCompleted_congr_toZetaTestFunction hφ
  have hzero_ordered :
      zetaCompletedZeroKreinGram g =
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryOrderedHeartScalar
          f := by
    exact hbridge f
  have hordered :
      0 ≤
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryOrderedHeartScalar
          f :=
    ZetaAdmissibleFunction
      .zetaCompletedExplicitFormulaAutocorrelationBoundaryOrderedHeartScalar_nonnegative
        f
  have hzero : 0 ≤ zetaCompletedZeroKreinGram g :=
    Eq.subst (motive := fun x : ℝ => 0 ≤ x) hzero_ordered.symm hordered
  have hweil_zero :
      zetaWeilFormCompleted g = zetaCompletedZeroKreinGram g :=
    zetaWeilFormCompleted_eq_zeroKreinGram g
  have hweil_g : 0 ≤ zetaWeilFormCompleted g :=
    Eq.subst (motive := fun x : ℝ => 0 ≤ x) hweil_zero.symm hzero
  exact Eq.subst (motive := fun x : ℝ => 0 ≤ x) hφg.symm hweil_g

/-- Direct ordered-heart payoff for the quadratic criterion. -/
theorem zetaCriterion_quadraticWeilPositivity_of_orderedHeartContourBridge
    (hbridge :
      ∀ f : ZetaAdmissibleFunction,
        zetaCompletedZeroKreinGram
            (ZetaAdmissibleFunction.convolutionAutocorrelation f) =
          ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryOrderedHeartScalar
            f) :
    ZetaWeilQuadraticPositivity := by
  exact zetaCriterion_quadraticWeilPositivity_of_autocorrelation
    (zetaCriterion_autocorrelation_weilPositivity_of_orderedHeartContourBridge
      hbridge)

/-- Direct ordered-heart payoff for the Boundary RH statement. -/
theorem zetaCriterion_boundaryRiemannHypothesis_of_orderedHeartContourBridge
    (hbridge :
      ∀ f : ZetaAdmissibleFunction,
        zetaCompletedZeroKreinGram
            (ZetaAdmissibleFunction.convolutionAutocorrelation f) =
          ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryOrderedHeartScalar
            f) :
    boundaryRiemannHypothesis := by
  exact zetaCriterion_boundaryRiemannHypothesis_of_quadraticWeilPositivity
    (zetaCriterion_quadraticWeilPositivity_of_orderedHeartContourBridge
      hbridge)

/-- The quotient-normalized autocorrelation zero-side positivity predicate.

This is the unconditional ordered-heart payoff currently proved by the GNS-positive route.  It
is deliberately not the raw Weil-positivity predicate: the scalar includes the diagonal-debt
coordinate required by the completed ordered-heart realization. -/
def ZetaAutocorrelationOrderedHeartZeroSidePositivity : Prop :=
  ∀ f : ZetaAdmissibleFunction,
    0 ≤ ZetaAdmissibleFunction.zetaCompletedZeroSideAutocorrelationOrderedHeartScalar f

/-- The ordered-heart route proves quotient-normalized zero-side positivity. -/
theorem zetaCriterion_autocorrelation_orderedHeartZeroSidePositivity :
    ZetaAutocorrelationOrderedHeartZeroSidePositivity := by
  intro f
  exact
    ZetaAdmissibleFunction
      .zetaCompletedZeroSideAutocorrelationOrderedHeartScalar_nonnegative f

/-- Raw ordered-heart contour descent is exactly the extra condition needed to turn
ordered-heart zero-side positivity into raw autocorrelation Weil positivity. -/
theorem zetaCriterion_autocorrelation_weilPositivity_of_orderedHeartZeroSidePositivity
    (hdescent :
      ∀ f : ZetaAdmissibleFunction,
        zetaCompletedZeroKreinGram
            (ZetaAdmissibleFunction.convolutionAutocorrelation f) =
          ZetaAdmissibleFunction.zetaCompletedZeroSideAutocorrelationOrderedHeartScalar f)
    (hpositive : ZetaAutocorrelationOrderedHeartZeroSidePositivity) :
    ZetaAutocorrelationWeilPositivity := by
  intro φ hφ
  rcases hφ with ⟨f, hφ⟩
  let g : ZetaAdmissibleFunction := ZetaAdmissibleFunction.convolutionAutocorrelation f
  have hφg :
      zetaWeilFormCompleted φ = zetaWeilFormCompleted g :=
    zetaWeilFormCompleted_congr_toZetaTestFunction hφ
  have hzero_ordered :
      zetaCompletedZeroKreinGram g =
        ZetaAdmissibleFunction.zetaCompletedZeroSideAutocorrelationOrderedHeartScalar f := by
    exact hdescent f
  have hordered :
      0 ≤ ZetaAdmissibleFunction.zetaCompletedZeroSideAutocorrelationOrderedHeartScalar f :=
    hpositive f
  have hzero : 0 ≤ zetaCompletedZeroKreinGram g :=
    Eq.subst (motive := fun x : ℝ => 0 ≤ x) hzero_ordered.symm hordered
  have hweil_zero :
      zetaWeilFormCompleted g = zetaCompletedZeroKreinGram g :=
    zetaWeilFormCompleted_eq_zeroKreinGram g
  have hweil_g : 0 ≤ zetaWeilFormCompleted g :=
    Eq.subst (motive := fun x : ℝ => 0 ≤ x) hweil_zero.symm hzero
  exact Eq.subst (motive := fun x : ℝ => 0 ≤ x) hφg.symm hweil_g

/-- Criterion transport through the final time-pairing/GNS reconstruction comparison. -/
theorem zetaCriterion_quadraticWeilPositivity_of_timePairingScalar_eq_orderedHeartScalar
    (hcomparison :
      ∀ f : ZetaAdmissibleFunction,
        ZetaAdmissibleFunction.completedBoundaryTimePairingScalar
            (ZetaAdmissibleFunction.completedPositiveBoundaryOrderedHeartClass f) =
          ZetaAdmissibleFunction.completedOrderedHeartScalar
            (ZetaAdmissibleFunction.completedPositiveBoundaryOrderedHeartClass f)) :
    ZetaWeilQuadraticPositivity := by
  exact zetaCriterion_quadraticWeilPositivity_predicate
    (fun f : ZetaAdmissibleFunction =>
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum_nonnegative_of_timePairingScalar_eq_orderedHeartScalar
        f
        (hcomparison f))

/-- Criterion transport through the completed finite-part boundary channel.  This
representative-level seam is retained for compatibility; the quotient-level transport theorem
above is the canonical ordered-heart route. -/
theorem zetaCriterion_quadraticWeilPositivity_of_completedFinitePartGNSTransport
    (htransport :
      ∀ f : ZetaAdmissibleFunction,
        ZetaAdmissibleFunction.completedFinitePartBoundaryChannel f =
          ZetaAdmissibleFunction.completedBoundaryGNSNormSq f) :
    ZetaWeilQuadraticPositivity := by
  exact zetaCriterion_quadraticWeilPositivity_predicate
    (fun f : ZetaAdmissibleFunction =>
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum_nonnegative_of_completedFinitePartGNSTransport
        f
        (htransport f))

/-- Criterion transport through the positive Hermitian GNS boundary scalar.  This
representative-level seam is retained for compatibility with older callers; the quotient
scalar route is the canonical ordered-heart payoff. -/
theorem zetaCriterion_quadraticWeilPositivity_of_weightTriangularPositiveGNSTransport
    (htransport :
      ∀ f : ZetaAdmissibleFunction,
        ZetaAdmissibleFunction.completedFinitePartBoundaryChannel f =
          ZetaAdmissibleFunction.zetaCompletedGNSPositiveBoundaryScalar f) :
    ZetaWeilQuadraticPositivity := by
  exact zetaCriterion_quadraticWeilPositivity_predicate
    (fun f : ZetaAdmissibleFunction =>
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum_nonnegative_of_weightTriangularPositiveGNSTransport
        f
        (htransport f))

/-- Nonnegativity of the finite time-side positive-class scalar implies the criterion's
quadratic Weil positivity predicate.  This finite-precone wrapper is retained for comparison;
the ordered-heart/GNS route is `zetaCriterion_quadraticWeilPositivity_of_GNSTransport`. -/
theorem zetaCriterion_quadraticWeilPositivity_of_positiveClassScalar
    (hclass :
      ∀ f : ZetaAdmissibleFunction,
        0 ≤
          (ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryPositiveClass
            f).scalar) :
    ZetaWeilQuadraticPositivity := by
  exact zetaCriterion_quadraticWeilPositivity_predicate
    (fun f : ZetaAdmissibleFunction =>
      ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum_nonnegative_of_positiveClass
        f
        (hclass f))

/-- The Weil criterion in the quadratic/autocorrelation form. -/
theorem zetaCriterion_boundaryRiemannHypothesis_of_quadraticWeilPositivity
    (h : ZetaWeilQuadraticPositivity) :
    boundaryRiemannHypothesis := by
  exact boundaryRiemannHypothesis_of_zetaWeilQuadraticPositivity h

/-- Boundary real nonnegativity on autocorrelation seeds implies RH through the quadratic
Weil criterion. -/
theorem zetaCriterion_boundaryRiemannHypothesis :
    (∀ f : ZetaAdmissibleFunction,
      0 ≤
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum
          f) →
    boundaryRiemannHypothesis := by
  intro hboundaryAll
  exact zetaCriterion_boundaryRiemannHypothesis_of_quadraticWeilPositivity
    (zetaCriterion_quadraticWeilPositivity_predicate hboundaryAll)

/-- Autocorrelation Weil positivity implies the public Boundary RH statement through the
quadratic Weil criterion seam. -/
theorem zetaCriterion_boundaryRiemannHypothesis_of_autocorrelationWeilPositivity
    (h : ZetaAutocorrelationWeilPositivity) :
    boundaryRiemannHypothesis := by
  exact zetaCriterion_boundaryRiemannHypothesis_of_quadraticWeilPositivity
    (zetaCriterion_quadraticWeilPositivity_of_autocorrelation h)

/-- The quadratic Weil-positivity predicate is pointwise nonnegativity on autocorrelation
seeds. -/
theorem zetaCriterion_quadraticWeilPositivity_iff :
    ZetaWeilQuadraticPositivity ↔
      ∀ f : ZetaAdmissibleFunction,
        0 ≤ zetaWeilFormCompleted (ZetaAdmissibleFunction.convolutionAutocorrelation f) := by
  rfl

/-- The criterion's convolution-autocorrelation Weil-positivity predicate is pointwise
nonnegativity on convolution-autocorrelation probes. -/
theorem zetaCriterion_autocorrelation_weilPositivity_iff_predicate :
    ZetaAutocorrelationWeilPositivity ↔
      ∀ φ : ZetaProbe, IsZetaAutocorrelationProbe φ →
        0 ≤ zetaWeilFormCompleted φ := by
  rfl

/-- The criterion's raw Weil-positivity predicate is pointwise nonnegativity. -/
theorem zetaCriterion_weilPositivity_iff :
    ZetaWeilPositivity ↔
      ∀ φ : ZetaProbe, 0 ≤ zetaWeilFormCompleted φ := by
  rfl

/-- Pointwise nonnegativity is the criterion's raw Weil-positivity predicate. -/
theorem zetaCriterion_weilPositivity_iff' :
    (∀ φ : ZetaProbe, 0 ≤ zetaWeilFormCompleted φ) ↔ ZetaWeilPositivity := by
  rfl

/-- Convolution-autocorrelation-generated probes have nonnegative completed zero-side real sum. -/
theorem zetaCriterion_convolutionAutocorrelation_zeroSide_nonnegative
    (f : ZetaAdmissibleFunction)
    (hboundary :
      0 ≤
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum
          f) :
    0 ≤ zetaCompletedZeroSideRe (ZetaAdmissibleFunction.convolutionAutocorrelation f) := by
  let g : ZetaAdmissibleFunction := ZetaAdmissibleFunction.convolutionAutocorrelation f
  have hzero_boundary :
      zetaCompletedZeroKreinGram g =
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum f := by
    exact zetaCriterion_convolutionAutocorrelation_zeroKreinGram_eq_boundarySum f
  have hzero : 0 ≤ zetaCompletedZeroKreinGram g :=
    Eq.subst (motive := fun x : ℝ => 0 ≤ x) hzero_boundary.symm hboundary
  exact hzero

/-- Historical name for convolution-autocorrelation zero-side nonnegativity. -/
theorem zetaCriterion_autocorrelation_zeroSide_nonnegative
    (f : ZetaAdmissibleFunction)
    (hboundary :
      0 ≤
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum
          f) :
    0 ≤ zetaCompletedZeroSideRe (ZetaAdmissibleFunction.convolutionAutocorrelation f) := by
  exact zetaCriterion_convolutionAutocorrelation_zeroSide_nonnegative f hboundary

/-- Convolution-autocorrelation-generated probes satisfy the criterion's Weil positivity. -/
theorem zetaCriterion_autocorrelation_weilPositivity
    (f : ZetaAdmissibleFunction)
    (hboundary :
      0 ≤
        ZetaAdmissibleFunction.zetaCompletedExplicitFormulaAutocorrelationBoundaryKreinSum
          f) :
    0 ≤ zetaWeilFormCompleted (ZetaAdmissibleFunction.convolutionAutocorrelation f) := by
  exact
    (Boundary.LFunctions.zetaWeilFormCompleted_autocorrelation_eq_zeroSide
      (f := f)).symm ▸
      zetaCriterion_convolutionAutocorrelation_zeroSide_nonnegative f hboundary

/-- The criterion's convolution-autocorrelation Weil positivity is the zero-side
nonnegativity statement. -/
theorem zetaCriterion_autocorrelation_weilPositivity_iff
    (f : ZetaAdmissibleFunction) :
    0 ≤ zetaWeilFormCompleted (ZetaAdmissibleFunction.convolutionAutocorrelation f) ↔
      0 ≤ zetaCompletedZeroSideRe (ZetaAdmissibleFunction.convolutionAutocorrelation f) := by
  exact
    (Boundary.LFunctions.zetaWeilFormCompleted_autocorrelation_eq_zeroSide
      (f := f)).symm ▸ Iff.rfl

/-- The zero-side nonnegativity statement is the criterion's convolution-autocorrelation Weil
positivity. -/
theorem zetaCriterion_autocorrelation_weilPositivity_iff'
    (f : ZetaAdmissibleFunction) :
    0 ≤ zetaCompletedZeroSideRe (ZetaAdmissibleFunction.convolutionAutocorrelation f) ↔
      0 ≤ zetaWeilFormCompleted (ZetaAdmissibleFunction.convolutionAutocorrelation f) := by
  exact
    (Boundary.LFunctions.zetaWeilFormCompleted_autocorrelation_eq_zeroSide
      (f := f)) ▸ Iff.rfl

/-- Zero-side nonnegativity implies criterion Weil positivity for convolution-autocorrelation
probes. -/
theorem zetaCriterion_autocorrelation_weilPositivity_of_zeroSide
    (f : ZetaAdmissibleFunction)
    (h : 0 ≤ zetaCompletedZeroSideRe (ZetaAdmissibleFunction.convolutionAutocorrelation f)) :
    0 ≤ zetaWeilFormCompleted (ZetaAdmissibleFunction.convolutionAutocorrelation f) := by
  exact
    (Boundary.LFunctions.zetaWeilFormCompleted_autocorrelation_eq_zeroSide
      (f := f)).symm ▸ h

end

end LFunctions
end Boundary
