/-
Manuscript alignment note (preserve live code; no surrogate replacement).

Primary TeX intent spans:
- our_paper_draft.tex:1752-1917 (localization and Nisnevich descent prerequisites feeding completion arguments)
- our_paper_draft.tex:1926-2088 (effective presentation, stabilization, and completion-facing steps)
- our_paper_draft.tex:2130-2166 (minimal package, derived soundness, and classical realization interfaces)
- our_paper_draft.tex:2501-2544 (presentation matching and infinity comparison constraints)
- our_paper_draft.tex:5700-5714 (pi0 comparison consequences that rely on completion-level compatibility)

Still missing in this file/module:
- Explicit TeX-label annotations on each exported completion theorem/structure.
- Dependency lemmas restated in the exact signatures required by the manuscript order.
- Export-level dependency graph entries documenting which theorem is consumed by which downstream stage.

Coverage intent for this file:
- Keep implementation live; avoid surrogate abstractions.
- Store manuscript-traceability obligations in this header until declaration-level tags are added.
-/

import Foundation.DG.Basic

/-!
# Free DG Envelopes

This file contains a concrete free dg construction from a quiver of generators. Objects are the
generators themselves, morphisms are formal paths with an adjoined zero morphism, and the
differential is zero.
-/

universe u w

namespace Foundation.Completion

/-- A quiver of generating objects and arrows for the free dg construction. -/
class PresentationQuiver (α : Type u) where
  HomGen : α → α → Type u

/-- Composable paths in the free category on a presentation quiver. -/
inductive PresentationPath (α : Type u) [PresentationQuiver α] : α → α → Type u where
  | nil (X : α) : PresentationPath α X X
  | cons {X Y Z : α} :
      PresentationQuiver.HomGen X Y →
        PresentationPath α Y Z →
          PresentationPath α X Z

namespace PresentationPath

def append {α : Type u} [PresentationQuiver α]
    {X Y Z : α}
    (left : PresentationPath α X Y)
    (right : PresentationPath α Y Z) :
    PresentationPath α X Z :=
  match left with
  | nil _ => right
  | cons gen tail => cons gen (append tail right)

@[simp] theorem nil_append {α : Type u} [PresentationQuiver α]
    {X Y : α}
    (path : PresentationPath α X Y) :
    append (nil X) path = path :=
  rfl

@[simp] theorem append_nil {α : Type u} [PresentationQuiver α]
    {X Y : α}
    (path : PresentationPath α X Y) :
    append path (nil Y) = path := by
  induction path with
  | nil _ => rfl
  | cons gen tail ih => exact congrArg (PresentationPath.cons gen) ih

@[simp] theorem append_assoc {α : Type u} [PresentationQuiver α]
    {W X Y Z : α}
    (first : PresentationPath α W X)
    (second : PresentationPath α X Y)
    (third : PresentationPath α Y Z) :
    append (append first second) third = append first (append second third) := by
  induction first with
  | nil _ => rfl
  | cons gen tail ih => exact congrArg (PresentationPath.cons gen) (ih second)

end PresentationPath

/-- Objects in the free dg category generated by a presentation. -/
inductive FreeDGObject (α : Type u) : Type u where
  | base : α → FreeDGObject α

namespace FreeDGObject

def carrier {α : Type u} : FreeDGObject α → α
  | base X => X

def lift {α : Type u} {β : Type w}
    (includeObj : α → β) :
    FreeDGObject α → β
  | base X => includeObj X

@[simp] theorem carrier_base {α : Type u} (X : α) :
    carrier (base X) = X :=
  rfl

@[simp] theorem lift_base {α : Type u} {β : Type w}
    (includeObj : α → β)
    (X : α) :
    lift includeObj (base X) = includeObj X :=
  rfl

end FreeDGObject

/-- Morphisms in the free dg category: paths in the presentation quiver, plus zero. -/
structure FreeDGMorphism {α : Type u} [PresentationQuiver α]
    (X Y : FreeDGObject α) : Type u where
  path? : Option (PresentationPath α X.carrier Y.carrier)

namespace FreeDGMorphism

def zero {α : Type u} [PresentationQuiver α]
    {X Y : FreeDGObject α} :
    FreeDGMorphism X Y where
  path? := none

def id {α : Type u} [PresentationQuiver α]
    (X : FreeDGObject α) :
    FreeDGMorphism X X where
  path? := some (PresentationPath.nil X.carrier)

def comp {α : Type u} [PresentationQuiver α]
    {X Y Z : FreeDGObject α}
    (f : FreeDGMorphism X Y)
    (g : FreeDGMorphism Y Z) :
    FreeDGMorphism X Z where
  path? :=
    match f.path?, g.path? with
    | some left, some right => some (PresentationPath.append left right)
    | _, _ => none

def differential {α : Type u} [PresentationQuiver α]
    {X Y : FreeDGObject α}
    (_f : FreeDGMorphism X Y) :
    FreeDGMorphism X Y :=
  zero

theorem differential_squared_zero {α : Type u} [PresentationQuiver α]
    {X Y : FreeDGObject α}
    (f : FreeDGMorphism X Y) :
    differential (differential f) = zero :=
  rfl

@[simp] theorem id_comp {α : Type u} [PresentationQuiver α]
    {X Y : FreeDGObject α}
    (f : FreeDGMorphism X Y) :
    comp (id X) f = f := by
  cases f with
  | mk path? =>
      cases path? <;> rfl

@[simp] theorem comp_id {α : Type u} [PresentationQuiver α]
    {X Y : FreeDGObject α}
    (f : FreeDGMorphism X Y) :
    comp f (id Y) = f := by
  cases f with
  | mk path? =>
      cases path? with
      | none => rfl
      | some path => simp [comp, id, PresentationPath.append_nil]

@[simp] theorem comp_assoc {α : Type u} [PresentationQuiver α]
    {W X Y Z : FreeDGObject α}
    (f : FreeDGMorphism W X)
    (g : FreeDGMorphism X Y)
    (h : FreeDGMorphism Y Z) :
    comp (comp f g) h = comp f (comp g h) := by
  cases f with
  | mk fpath =>
      cases g with
      | mk gpath =>
          cases h with
          | mk hpath =>
              cases fpath <;> cases gpath <;> cases hpath <;>
                simp [comp, PresentationPath.append_assoc]

end FreeDGMorphism

/-- The free dg category on a presentation quiver, with zero differential. -/
def freeDGCategory (α : Type u) [PresentationQuiver α] : Foundation.DG.RawDGCategory.{u, u} where
  Obj := FreeDGObject α
  HomComplex := FreeDGMorphism
  zero := FreeDGMorphism.zero
  differential := FreeDGMorphism.differential

end Foundation.Completion
