import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Relation.Owner

/-!
# Setoid for quotient trace correspondences

This file turns the finite-witness-generated relation into the canonical
setoid on raw quotient candidates.

No new mathematical relation is introduced here: the setoid relation is exactly
`TraceCorQQuotientRelation`.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The canonical setoid generated by finite relation witnesses. -/
def TraceCorQQuotientSetoid :
    Setoid TraceCorQQuotientCandidate where
  r := TraceCorQQuotientRelation
  iseqv := {
    refl := TraceCorQQuotientRelation.refl
    symm := fun relation =>
      TraceCorQQuotientRelation.symm relation
    trans := fun first second =>
      TraceCorQQuotientRelation.trans first second
  }

/-- The quotient of raw candidates by the finite-witness relation. -/
abbrev TraceCorQQuotient :=
  Quotient TraceCorQQuotientSetoid

/-- The quotient class of a raw candidate. -/
def TraceCorQQuotient.ofCandidate
    (candidate : TraceCorQQuotientCandidate) :
    TraceCorQQuotient :=
  Quotient.mk TraceCorQQuotientSetoid candidate

/-- A finite-witness relation gives equality of quotient classes. -/
theorem TraceCorQQuotient.sound
    {left right : TraceCorQQuotientCandidate}
    (relation : TraceCorQQuotientRelation left right) :
    TraceCorQQuotient.ofCandidate left =
      TraceCorQQuotient.ofCandidate right :=
  Quotient.sound relation

/-- Candidates with the same formal sum have the same quotient class. -/
theorem TraceCorQQuotient.sound_sameFormalSum
    (ledger : TraceCorQRelationLedger)
    {left right : TraceCorQQuotientCandidate}
    (formalSum_eq : left.formalSum = right.formalSum) :
    TraceCorQQuotient.ofCandidate left =
      TraceCorQQuotient.ofCandidate right :=
  TraceCorQQuotient.sound
    (TraceCorQQuotientRelation.sameFormalSum
      ledger
      formalSum_eq)

/-- Candidates with permuted formal sums have the same quotient class. -/
theorem TraceCorQQuotient.sound_permFormalSum
    (ledger : TraceCorQRelationLedger)
    {left right : TraceCorQQuotientCandidate}
    (formalSum_perm : List.Perm left.formalSum right.formalSum) :
    TraceCorQQuotient.ofCandidate left =
      TraceCorQQuotient.ofCandidate right :=
  TraceCorQQuotient.sound
    (TraceCorQQuotientRelation.permFormalSum
      ledger
      formalSum_perm)

/-- Adjacent opposite rational multiples of the same generator cancel in the quotient. -/
theorem TraceCorQQuotient.sound_cancelAdjacentOpposite
    (ledger : TraceCorQRelationLedger)
    (prefix suffix : TraceCorQFormalSum)
    (coefficient : Rat)
    (generator : TraceCorQGenerator) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQQuotientInput.ofFormalSumLedger
        (prefix ++
          (coefficient, generator) ::
            (-coefficient, generator) ::
              suffix)
        ledger) =
      TraceCorQQuotient.ofCandidate
        (TraceCorQQuotientInput.ofFormalSumLedger
          (prefix ++ suffix)
          ledger) :=
  TraceCorQQuotient.sound
    (TraceCorQQuotientRelation.cancelAdjacentOpposite
      ledger
      prefix
      suffix
      coefficient
      generator)

/-- Adjacent rational multiples of the same generator combine in the quotient. -/
theorem TraceCorQQuotient.sound_combineAdjacentSame
    (ledger : TraceCorQRelationLedger)
    (prefix suffix : TraceCorQFormalSum)
    (leftCoefficient rightCoefficient : Rat)
    (generator : TraceCorQGenerator) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQQuotientInput.ofFormalSumLedger
        (prefix ++
          (leftCoefficient, generator) ::
            (rightCoefficient, generator) ::
              suffix)
        ledger) =
      TraceCorQQuotient.ofCandidate
        (TraceCorQQuotientInput.ofFormalSumLedger
          (prefix ++
            (leftCoefficient + rightCoefficient, generator) ::
              suffix)
          ledger) :=
  TraceCorQQuotient.sound
    (TraceCorQQuotientRelation.combineAdjacentSame
      ledger
      prefix
      suffix
      leftCoefficient
      rightCoefficient
      generator)

end AnalyticMotives
end LFunctions
end Boundary
