import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Realizations.Analytic.Adapters.CompletedZeta.FiniteRectangle.SoundnessSeed.ZeroPoleTransports.Owner

/-!
# Zero-pole scheduled-channel rectangle certificates

This file attaches the concrete scheduled rectangle height used by the
zero-pole channel decomposition to the certified trace-presentation layer.

The height is not a free parameter: it is the scheduled height
`h.height_schedule.height u` from the analytic contour-family package used by
the channel identity.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The scheduled rectangle used by the zero-pole channel decomposition at `u`. -/
def completedZetaZeroPoleScheduledChannelRectangle
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    ZetaAdmissibleFunction.ExplicitFormulaRectangle where
  c := 0
  T := h.height_schedule.height u

/-- The scheduled channel rectangle has center coordinate zero. -/
theorem completedZetaZeroPoleScheduledChannelRectangle_c
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleScheduledChannelRectangle f F h u).c =
      0 :=
  rfl

/-- The scheduled channel rectangle has the contour package's scheduled height. -/
theorem completedZetaZeroPoleScheduledChannelRectangle_T
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleScheduledChannelRectangle f F h u).T =
      h.height_schedule.height u :=
  rfl

/-- Positivity of the scheduled height is positivity of the recorded rectangle height. -/
theorem completedZetaZeroPoleScheduledChannelRectangle_positiveHeight
    {f : ZetaAdmissibleFunction} {F : ExplicitFormulaContourFamily}
    {h : ExplicitFormulaFamilyAnalyticPackage f F} {u : ℝ}
    (hT : 0 < h.height_schedule.height u) :
    0 < (completedZetaZeroPoleScheduledChannelRectangle f F h u).T :=
  hT

/-- The certificate ledger generated by the scheduled channel rectangle. -/
def completedZetaZeroPoleScheduledChannelRectangleCertificateLedger
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    ResidueChannelCertificateLedger :=
  ResidueChannelCertificateLedger.ofExplicitFormulaRectangle
    (completedZetaZeroPoleScheduledChannelRectangle f F h u)

/-- The scheduled channel rectangle ledger carries one imported rectangle. -/
theorem completedZetaZeroPoleScheduledChannelRectangleCertificateLedger_importedRectangleCount
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleScheduledChannelRectangleCertificateLedger
      f F h u).importedRectangleCount =
      1 + 0 :=
  rfl

/-- The scheduled channel rectangle ledger carries no trace-bookkeeping atom. -/
theorem completedZetaZeroPoleScheduledChannelRectangleCertificateLedger_traceBookkeepingCount
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleScheduledChannelRectangleCertificateLedger
      f F h u).traceBookkeepingCount =
      0 + 0 :=
  rfl

/-- The channel presentation with the scheduled rectangle certificate attached. -/
def completedZetaZeroPoleChannelPresentationWithScheduledRectangle
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    CertifiedResidueChannelPresentation :=
  completedZetaZeroPoleChannelPresentation.withAdditionalCertificates
    (completedZetaZeroPoleScheduledChannelRectangleCertificateLedger f F h u)

/-- Adding the scheduled rectangle certificate does not change the channel presentation spine. -/
theorem completedZetaZeroPoleChannelPresentationWithScheduledRectangle_spine
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelPresentationWithScheduledRectangle
      f F h u).spine =
      completedZetaZeroPoleChannelPresentationSpine :=
  rfl

/-- Adding the scheduled rectangle certificate does not change the channel source expression. -/
theorem completedZetaZeroPoleChannelPresentationWithScheduledRectangle_source
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelPresentationWithScheduledRectangle
      f F h u).source =
      completedZetaZeroPoleChannelSourceExpression :=
  rfl

/-- The scheduled-rectangle channel presentation is sound at its schedule parameter. -/
theorem completedZetaZeroPoleChannelPresentationWithScheduledRectangle_sound
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    completedZetaZeroPoleLeftVerticalTrace f F h u =
      completedZetaZeroPoleRightVerticalTrace f F h u +
        completedZetaZeroPoleHorizontalTrace f F h u -
        completedZetaZeroPoleRectangleBoundaryTrace f F h u :=
  completedZetaZeroPoleChannelPresentationSpine_certified
    f F h u

/-- The scheduled-rectangle channel presentation imports the added rectangle certificate. -/
theorem completedZetaZeroPoleChannelPresentationWithScheduledRectangle_importedRectangleCount
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelPresentationWithScheduledRectangle
      f F h u).importedRectangleCount =
      completedZetaZeroPoleChannelPresentation.importedRectangleCount +
        (completedZetaZeroPoleScheduledChannelRectangleCertificateLedger
          f F h u).importedRectangleCount :=
  CertifiedResidueChannelPresentation.withAdditionalCertificates_importedRectangleCount
    completedZetaZeroPoleChannelPresentation
    (completedZetaZeroPoleScheduledChannelRectangleCertificateLedger f F h u)

/-- The scheduled-rectangle channel presentation preserves original bookkeeping plus ledger bookkeeping. -/
theorem completedZetaZeroPoleChannelPresentationWithScheduledRectangle_traceBookkeepingCount
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelPresentationWithScheduledRectangle
      f F h u).traceBookkeepingCount =
      completedZetaZeroPoleChannelPresentation.traceBookkeepingCount +
        (completedZetaZeroPoleScheduledChannelRectangleCertificateLedger
          f F h u).traceBookkeepingCount :=
  CertifiedResidueChannelPresentation.withAdditionalCertificates_traceBookkeepingCount
    completedZetaZeroPoleChannelPresentation
    (completedZetaZeroPoleScheduledChannelRectangleCertificateLedger f F h u)

/-- The channel transport whose source carries the scheduled rectangle certificate. -/
def completedZetaZeroPoleChannelTransportWithScheduledRectangle
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    TraceTransport :=
  {
    source := completedZetaZeroPoleChannelPresentationWithScheduledRectangle
      f F h u
    target := completedZetaZeroPoleChannelOutput
    path := completedZetaZeroPoleChannelPath
    path_source := completedZetaZeroPoleChannelPath_source
    path_target := completedZetaZeroPoleChannelPath_target
  }

/-- The scheduled-rectangle channel transport starts at the scheduled-rectangle presentation. -/
theorem completedZetaZeroPoleChannelTransportWithScheduledRectangle_source
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u).source =
      completedZetaZeroPoleChannelPresentationWithScheduledRectangle f F h u :=
  rfl

/-- The scheduled-rectangle channel transport targets the certified channel output. -/
theorem completedZetaZeroPoleChannelTransportWithScheduledRectangle_target
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u).target =
      completedZetaZeroPoleChannelOutput :=
  rfl

/-- The scheduled-rectangle channel transport carries the channel path. -/
theorem completedZetaZeroPoleChannelTransportWithScheduledRectangle_path
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u).path =
      completedZetaZeroPoleChannelPath :=
  rfl

/-- The scheduled-rectangle channel transport is analytically sound at its schedule parameter. -/
theorem completedZetaZeroPoleChannelTransportWithScheduledRectangle_sound
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    completedZetaZeroPoleLeftVerticalTrace f F h u =
      completedZetaZeroPoleRightVerticalTrace f F h u +
        completedZetaZeroPoleHorizontalTrace f F h u -
        completedZetaZeroPoleRectangleBoundaryTrace f F h u :=
  completedZetaZeroPoleChannelPresentationWithScheduledRectangle_sound
    f F h u

/-- The scheduled-rectangle channel transport exposes its imported rectangle through its ledger. -/
theorem completedZetaZeroPoleChannelTransportWithScheduledRectangle_importedRectangleCount_eq_ledger
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u).importedRectangleCount =
      (completedZetaZeroPoleChannelTransportWithScheduledRectangle
        f F h u).certificateLedger.importedRectangleCount :=
  rfl

/-- The scheduled-rectangle channel transport imports source, target, and path payload. -/
theorem completedZetaZeroPoleChannelTransportWithScheduledRectangle_importedRectangleCount_split
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u).importedRectangleCount =
      (completedZetaZeroPoleChannelPresentationWithScheduledRectangle
        f F h u).importedRectangleCount +
        (completedZetaZeroPoleChannelOutput.importedRectangleCount +
          (completedZetaZeroPoleChannelTransportWithScheduledRectangle
            f F h u).pathCertificateLedger.importedRectangleCount) :=
  TraceTransport.importedRectangleCount_eq_source_target_path
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u)

/-- The scheduled-rectangle channel transport keeps source, target, and path bookkeeping. -/
theorem completedZetaZeroPoleChannelTransportWithScheduledRectangle_traceBookkeepingCount_split
    (f : ZetaAdmissibleFunction) (F : ExplicitFormulaContourFamily)
    (h : ExplicitFormulaFamilyAnalyticPackage f F) (u : ℝ) :
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u).traceBookkeepingCount =
      (completedZetaZeroPoleChannelPresentationWithScheduledRectangle
        f F h u).traceBookkeepingCount +
        (completedZetaZeroPoleChannelOutput.traceBookkeepingCount +
          (completedZetaZeroPoleChannelTransportWithScheduledRectangle
            f F h u).pathCertificateLedger.traceBookkeepingCount) :=
  TraceTransport.traceBookkeepingCount_eq_source_target_path
    (completedZetaZeroPoleChannelTransportWithScheduledRectangle
      f F h u)

end AnalyticMotives
end LFunctions
end Boundary
