import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourAdmissible.BoundarySystem.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.ContourAdmissible.Core.RHContour.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.RiemannHypothesisBridge.Bridge.WeilCriterion.Zero.ZetaWeilShared.ZetaZeroSideDefinitions.ZetaCenteredZeroCounting.ZetaCompletedLogDerivativeBridge.ZetaExplicitFormulaComplexAnalysis.ZetaExplicitFormulaGeometry.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.RiemannHypothesisBridge.Bridge.WeilCriterion.Zero.ZetaWeilShared.ZetaZeroSideDefinitions.ZetaCenteredZeroCounting.ZetaCompletedLogDerivativeBridge.ZetaExplicitFormulaComplexAnalysis.ZetaExplicitFormulaContour.ZetaExplicitFormulaContourPathLemmas.Owner

/-!
# Finite-rectangle boundary system target

This file is the owner target for constructing the boundary-system component of
an `RHContourAdmissibleBulk` from the imported finite-rectangle contour
geometry.

The intended construction uses:

* the four explicit-formula side paths;
* the rectangle interior and boundary definitions;
* the four RH contour boundary-face indices;
* incidence generated by the endpoint intersections of adjacent rectangle
  sides.

No abstract boundary law is introduced here.  The next edit in this file should
define the finite-rectangle compactification and four boundary faces directly
from the imported RH rectangle/path API.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

end AnalyticMotives
end LFunctions
end Boundary
