import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.Named.Projections.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.Rotation.ShortComplex.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.ShortComplex.Owner

/-!
# Concrete acyclic generators for analytic localization

This file owns the triangulated-side generators killed by analytic
localization.  Each generator is the third vertex of the bounded mapping-cone
triangle attached to one concrete analytic localization input.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A concrete additive acyclic generator is a localization input viewed through
its bounded mapping-cone object. -/
structure TraceAnalyticAdditiveAcyclicGenerator where
  input : TraceLocalizationInput

/-- The additive homotopy-category object generated by killing a localization input. -/
def TraceAnalyticAdditiveAcyclicGenerator.object
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    TraceAnalyticAdditiveHomotopyCategory :=
  generator.input.boundedMappingConeTriangle.triangleThirdVertex

/-- The distinguished triangle whose third vertex is the acyclic generator object. -/
def TraceAnalyticAdditiveAcyclicGenerator.triangle
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    CategoryTheory.Triangle TraceAnalyticAdditiveHomotopyCategory :=
  generator.input.boundedMappingConeTriangle.triangle

/-- The rotated distinguished triangle attached to the acyclic generator. -/
def TraceAnalyticAdditiveAcyclicGenerator.rotatedTriangle
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    CategoryTheory.Triangle TraceAnalyticAdditiveHomotopyCategory :=
  generator.input.boundedMappingConeRotatedTriangle

/-- The inverse-rotated distinguished triangle attached to the acyclic generator. -/
def TraceAnalyticAdditiveAcyclicGenerator.inverseRotatedTriangle
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    CategoryTheory.Triangle TraceAnalyticAdditiveHomotopyCategory :=
  generator.input.boundedMappingConeInverseRotatedTriangle

/-- The first map in the acyclic generator cone triangle. -/
def TraceAnalyticAdditiveAcyclicGenerator.firstMap
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.triangle.obj₁ ⟶ generator.triangle.obj₂ :=
  generator.triangle.mor₁

/-- The cone-inclusion map into the acyclic generator object. -/
def TraceAnalyticAdditiveAcyclicGenerator.coneInclusion
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.triangle.obj₂ ⟶ generator.triangle.obj₃ :=
  generator.triangle.mor₂

/-- The connecting map out of the acyclic generator object. -/
def TraceAnalyticAdditiveAcyclicGenerator.connectingMap
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.triangle.obj₃ ⟶ generator.triangle.obj₁⟦(1 : ℤ)⟧ :=
  generator.triangle.mor₃

/-- The short complex cut out by the first two maps of the acyclic generator cone. -/
def TraceAnalyticAdditiveAcyclicGenerator.shortComplex
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    CategoryTheory.ShortComplex TraceAnalyticAdditiveHomotopyCategory :=
  generator.input.boundedMappingConeShortComplex

/-- The rotated short complex exposing the acyclic object as middle vertex. -/
def TraceAnalyticAdditiveAcyclicGenerator.rotatedShortComplex
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    CategoryTheory.ShortComplex TraceAnalyticAdditiveHomotopyCategory :=
  generator.input.boundedMappingConeRotatedShortComplex

/-- The inverse-rotated short complex exposing the shifted acyclic object as left vertex. -/
def TraceAnalyticAdditiveAcyclicGenerator.inverseRotatedShortComplex
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    CategoryTheory.ShortComplex TraceAnalyticAdditiveHomotopyCategory :=
  generator.input.boundedMappingConeInverseRotatedShortComplex

/-- The object of an acyclic generator is the third vertex of its input cone triangle. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.object_eq_triangleThirdVertex
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.object =
      generator.input.boundedMappingConeTriangle.triangleThirdVertex :=
  rfl

/-- The acyclic generator triangle is the bounded cone triangle of its localization input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.triangle_eq
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.triangle =
      generator.input.boundedMappingConeTriangle.triangle :=
  rfl

/-- The acyclic generator cone triangle is distinguished. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.triangle_distinguished
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.triangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  generator.input.boundedMappingConeTriangle.distinguished

/-- The rotated acyclic generator cone triangle is distinguished. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.rotatedTriangle_distinguished
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.rotatedTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceLocalizationInput.boundedMappingConeRotatedTriangle_distinguished
    generator.input

/-- The inverse-rotated acyclic generator cone triangle is distinguished. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.inverseRotatedTriangle_distinguished
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.inverseRotatedTriangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceLocalizationInput.boundedMappingConeInverseRotatedTriangle_distinguished
    generator.input

/-- The third vertex of the acyclic generator triangle is the acyclic object. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.triangle_obj₃
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.triangle.obj₃ =
      generator.object :=
  rfl

/-- The first map is the first morphism of the acyclic generator cone triangle. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.firstMap_eq
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.firstMap =
      generator.triangle.mor₁ :=
  rfl

/-- The cone-inclusion map is the second morphism of the acyclic generator cone triangle. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.coneInclusion_eq
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.coneInclusion =
      generator.triangle.mor₂ :=
  rfl

/-- The connecting map is the third morphism of the acyclic generator cone triangle. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.connectingMap_eq
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.connectingMap =
      generator.triangle.mor₃ :=
  rfl

/-- The acyclic generator short complex is the bounded cone short complex of its input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.shortComplex_eq
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.shortComplex =
      generator.input.boundedMappingConeShortComplex :=
  rfl

/-- The acyclic generator short complex has zero composite. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.shortComplex_zero
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.shortComplex.f ≫
        generator.shortComplex.g =
      0 :=
  TraceLocalizationInput.boundedMappingConeShortComplex_zero
    generator.input

/-- The acyclic object is the right vertex of its unrotated short complex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.shortComplex_X₃
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.shortComplex.X₃ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject
        generator.input.boundedAdditiveComplexHom :=
  TraceLocalizationInput.boundedMappingConeShortComplex_X₃
    generator.input

/-- The rotated short complex is the rotated bounded cone short complex of its input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.rotatedShortComplex_eq
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.rotatedShortComplex =
      generator.input.boundedMappingConeRotatedShortComplex :=
  rfl

/-- The rotated acyclic generator short complex has zero composite. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.rotatedShortComplex_zero
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.rotatedShortComplex.f ≫
        generator.rotatedShortComplex.g =
      0 :=
  TraceLocalizationInput.boundedMappingConeRotatedShortComplex_zero
    generator.input

/-- The acyclic object is the middle vertex of its rotated short complex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.rotatedShortComplex_X₂
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.rotatedShortComplex.X₂ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject
        generator.input.boundedAdditiveComplexHom :=
  TraceLocalizationInput.boundedMappingConeRotatedShortComplex_X₂
    generator.input

/-- The inverse-rotated short complex is the inverse-rotated bounded cone short
complex of its input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.inverseRotatedShortComplex_eq
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.inverseRotatedShortComplex =
      generator.input.boundedMappingConeInverseRotatedShortComplex :=
  rfl

/-- The inverse-rotated acyclic generator short complex has zero composite. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.inverseRotatedShortComplex_zero
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.inverseRotatedShortComplex.f ≫
        generator.inverseRotatedShortComplex.g =
      0 :=
  TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_zero
    generator.input

/-- The shifted acyclic object is the left vertex of its inverse-rotated short complex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.inverseRotatedShortComplex_X₁
    (generator : TraceAnalyticAdditiveAcyclicGenerator) :
    generator.inverseRotatedShortComplex.X₁ =
      (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject
        generator.input.boundedAdditiveComplexHom)⟦(-1 : ℤ)⟧ :=
  TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_X₁
    generator.input

/-- The acyclic generator attached to descent-channel localization. -/
def TraceAnalyticAdditiveAcyclicGenerator.descentChannel
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveAcyclicGenerator where
  input := TraceLocalizationInput.descentChannel source target

/-- Descent-channel acyclic generators remember their localization input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.descentChannel_input
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.descentChannel source target).input =
      TraceLocalizationInput.descentChannel source target :=
  rfl

/-- The descent-channel acyclic object is the descent-channel cone third vertex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.descentChannel_object
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.descentChannel source target).object =
      (TraceLocalizationInput.descentChannel source target).boundedMappingConeTriangle.triangleThirdVertex :=
  rfl

/-- The acyclic generator attached to descent-refinement localization. -/
def TraceAnalyticAdditiveAcyclicGenerator.descentRefinement
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveAcyclicGenerator where
  input := TraceLocalizationInput.descentRefinement source target

/-- Descent-refinement acyclic generators remember their localization input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.descentRefinement_input
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.descentRefinement source target).input =
      TraceLocalizationInput.descentRefinement source target :=
  rfl

/-- The descent-refinement acyclic object is the descent-refinement cone third vertex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.descentRefinement_object
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.descentRefinement source target).object =
      (TraceLocalizationInput.descentRefinement source target).boundedMappingConeTriangle.triangleThirdVertex :=
  rfl

/-- The acyclic generator attached to descent-schedule localization. -/
def TraceAnalyticAdditiveAcyclicGenerator.descentSchedule
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveAcyclicGenerator where
  input := TraceLocalizationInput.descentSchedule source target

/-- Descent-schedule acyclic generators remember their localization input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.descentSchedule_input
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.descentSchedule source target).input =
      TraceLocalizationInput.descentSchedule source target :=
  rfl

/-- The descent-schedule acyclic object is the descent-schedule cone third vertex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.descentSchedule_object
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.descentSchedule source target).object =
      (TraceLocalizationInput.descentSchedule source target).boundedMappingConeTriangle.triangleThirdVertex :=
  rfl

/-- The acyclic generator attached to interval-Stokes localization. -/
def TraceAnalyticAdditiveAcyclicGenerator.intervalStokes
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveAcyclicGenerator where
  input := TraceLocalizationInput.intervalStokes source target

/-- Interval-Stokes acyclic generators remember their localization input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.intervalStokes_input
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.intervalStokes source target).input =
      TraceLocalizationInput.intervalStokes source target :=
  rfl

/-- The interval-Stokes acyclic object is the interval-Stokes cone third vertex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.intervalStokes_object
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.intervalStokes source target).object =
      (TraceLocalizationInput.intervalStokes source target).boundedMappingConeTriangle.triangleThirdVertex :=
  rfl

/-- The acyclic generator attached to interval-Fubini localization. -/
def TraceAnalyticAdditiveAcyclicGenerator.intervalFubini
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveAcyclicGenerator where
  input := TraceLocalizationInput.intervalFubini source target

/-- Interval-Fubini acyclic generators remember their localization input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.intervalFubini_input
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.intervalFubini source target).input =
      TraceLocalizationInput.intervalFubini source target :=
  rfl

/-- The interval-Fubini acyclic object is the interval-Fubini cone third vertex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.intervalFubini_object
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.intervalFubini source target).object =
      (TraceLocalizationInput.intervalFubini source target).boundedMappingConeTriangle.triangleThirdVertex :=
  rfl

/-- The acyclic generator attached to Tate-weight-drop localization. -/
def TraceAnalyticAdditiveAcyclicGenerator.tateWeightDrop
    (source target : QTraceExpression) :
    TraceAnalyticAdditiveAcyclicGenerator where
  input := TraceLocalizationInput.tateWeightDrop source target

/-- Tate-weight-drop acyclic generators remember their localization input. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.tateWeightDrop_input
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.tateWeightDrop source target).input =
      TraceLocalizationInput.tateWeightDrop source target :=
  rfl

/-- The Tate-weight-drop acyclic object is the Tate-weight-drop cone third vertex. -/
theorem TraceAnalyticAdditiveAcyclicGenerator.tateWeightDrop_object
    (source target : QTraceExpression) :
    (TraceAnalyticAdditiveAcyclicGenerator.tateWeightDrop source target).object =
      (TraceLocalizationInput.tateWeightDrop source target).boundedMappingConeTriangle.triangleThirdVertex :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
