import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.LedgeredTransports.CoherenceRelations.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Generators.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Relation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Add.Laws.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Zero.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.Zero.Support.Owner

/-!
# Core associativity support relation for quotient trace composition

This file owns the concrete quotient relation generated by the analytic
associativity coherence cell for ledgered trace transports.  The downstream
parent file turns this ledgered singleton equality into raw-generator singleton
composition associativity.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
The quotient candidate represented by the formal support of the associativity
coherence generator for three ledgered trace transports.
-/
def LedgeredTraceTransport.associativitySupportCandidate
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotientCandidate :=
  TraceCorQRelationGenerator.supportCandidate
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/-- The associativity support candidate has the expected formal support. -/
theorem LedgeredTraceTransport.associativitySupportCandidate_formalSum
    (first second third : LedgeredTraceTransport) :
    (LedgeredTraceTransport.associativitySupportCandidate
      first second third).formalSum =
      LedgeredTraceTransport.coherenceSupport
        ((first.comp second).comp third)
        (first.comp (second.comp third)) :=
  rfl

/-- The associativity support candidate has the singleton relation ledger. -/
theorem LedgeredTraceTransport.associativitySupportCandidate_ledger
    (first second third : LedgeredTraceTransport) :
    (LedgeredTraceTransport.associativitySupportCandidate
      first second third).ledger =
      TraceCorQRelationLedger.singleton
        (LedgeredTraceTransport.associativityRelationGenerator
          first second third) :=
  rfl

/--
The finite witness saying that the associativity support candidate is killed
by the quotient relation.
-/
def LedgeredTraceTransport.associativitySupportWitness
    (first second third : LedgeredTraceTransport) :
    TraceCorQRelationWitness
      (LedgeredTraceTransport.associativitySupportCandidate
        first second third)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQRelationGenerator.supportWitness
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/-- The associativity support witness has the singleton relation ledger. -/
theorem LedgeredTraceTransport.associativitySupportWitness_ledger
    (first second third : LedgeredTraceTransport) :
    (LedgeredTraceTransport.associativitySupportWitness
      first second third).ledger =
      TraceCorQRelationLedger.singleton
        (LedgeredTraceTransport.associativityRelationGenerator
          first second third) :=
  rfl

/-- The quotient relation generated by associativity coherence support. -/
def LedgeredTraceTransport.associativitySupportRelation
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotientRelation
      (LedgeredTraceTransport.associativitySupportCandidate
        first second third)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.supportZero
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/--
The formal Q-linear associativity support of three ledgered trace transports
is zero in the quotient.
-/
theorem LedgeredTraceTransport.associativitySupportQuotient_eq_zero
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.associativitySupportCandidate
        first second third) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.supportZero_eq_zero
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/-- The left-parenthesized singleton candidate of associativity coherence. -/
def LedgeredTraceTransport.associativityLeftSingletonCandidate
    (first second third : LedgeredTraceTransport)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQQuotientCandidate :=
  TraceCorQQuotientInput.ofFormalSumLedger
    (TraceCorQFormalSum.singleton
      1
      ((first.comp second).comp third).transport)
    ledger

/-- The right-parenthesized singleton candidate of associativity coherence. -/
def LedgeredTraceTransport.associativityRightSingletonCandidate
    (first second third : LedgeredTraceTransport)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQQuotientCandidate :=
  TraceCorQQuotientInput.ofFormalSumLedger
    (TraceCorQFormalSum.singleton
      1
      (first.comp (second.comp third)).transport)
    ledger

/-- The ledger generated by the associativity coherence relation. -/
def LedgeredTraceTransport.associativitySupportLedger
    (first second third : LedgeredTraceTransport) :
    TraceCorQRelationLedger :=
  TraceCorQRelationLedger.singleton
    (LedgeredTraceTransport.associativityRelationGenerator
      first second third)

/-- The expanded left-minus-right-plus-right candidate used for cancellation. -/
def LedgeredTraceTransport.associativityCancellationCandidate
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotientCandidate :=
  TraceCorQQuotientInput.ofFormalSumLedger
    (TraceCorQFormalSum.singleton
      1
      ((first.comp second).comp third).transport ++
        (-1, (first.comp (second.comp third)).transport) ::
          (1, (first.comp (second.comp third)).transport) ::
            [])
    (LedgeredTraceTransport.associativitySupportLedger
      first second third)

/-- The left singleton is the cancellation candidate after cancelling `-right + right`. -/
theorem LedgeredTraceTransport.associativityLeftSingleton_eq_cancellation
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.associativityLeftSingletonCandidate
        first
        second
        third
        TraceCorQRelationLedger.empty) =
      TraceCorQQuotient.ofCandidate
        (LedgeredTraceTransport.associativityCancellationCandidate
          first second third) :=
  Eq.trans
    (show
      TraceCorQQuotient.ofCandidate
          (LedgeredTraceTransport.associativityLeftSingletonCandidate
            first
            second
            third
            TraceCorQRelationLedger.empty) =
        TraceCorQQuotient.ofCandidate
          (LedgeredTraceTransport.associativityLeftSingletonCandidate
            first
            second
            third
            (LedgeredTraceTransport.associativitySupportLedger
              first second third)) from
      TraceCorQQuotient.sound_sameFormalSum
        (LedgeredTraceTransport.associativitySupportLedger
          first second third)
        rfl)
    (Eq.symm
      (show
        TraceCorQQuotient.ofCandidate
            (LedgeredTraceTransport.associativityCancellationCandidate
              first second third) =
          TraceCorQQuotient.ofCandidate
            (LedgeredTraceTransport.associativityLeftSingletonCandidate
              first
              second
              third
              (LedgeredTraceTransport.associativitySupportLedger
                first second third)) from
        TraceCorQQuotient.sound_cancelAdjacentOpposite
          (LedgeredTraceTransport.associativitySupportLedger
            first second third)
          (TraceCorQFormalSum.singleton
            1
            ((first.comp second).comp third).transport)
          TraceCorQFormalSum.zero
          (-1)
          (first.comp (second.comp third)).transport))

/--
The singleton left and singleton right parenthesizations of a ledgered
transport triple are equal in the quotient.
-/
theorem LedgeredTraceTransport.associativitySingletonQuotient_eq
    (first second third : LedgeredTraceTransport) :
    TraceCorQQuotient.ofCandidate
      (LedgeredTraceTransport.associativityLeftSingletonCandidate
        first
        second
        third
        TraceCorQRelationLedger.empty) =
      TraceCorQQuotient.ofCandidate
        (LedgeredTraceTransport.associativityRightSingletonCandidate
          first
          second
          third
          TraceCorQRelationLedger.empty) :=
  Eq.trans
    (LedgeredTraceTransport.associativityLeftSingleton_eq_cancellation
      first second third)
    (Eq.trans
      (Eq.symm
        (TraceCorQQuotient.add_ofCandidate
          (LedgeredTraceTransport.associativitySupportCandidate
            first second third)
          (LedgeredTraceTransport.associativityRightSingletonCandidate
            first
            second
            third
            TraceCorQRelationLedger.empty)))
      (Eq.trans
        (congrArg
          (fun supportClass =>
            TraceCorQQuotient.add
              supportClass
              (TraceCorQQuotient.ofCandidate
                (LedgeredTraceTransport.associativityRightSingletonCandidate
                  first
                  second
                  third
                  TraceCorQRelationLedger.empty)))
          (LedgeredTraceTransport.associativitySupportQuotient_eq_zero
            first second third))
        (TraceCorQQuotient.zero_add
          (TraceCorQQuotient.ofCandidate
            (LedgeredTraceTransport.associativityRightSingletonCandidate
              first
              second
              third
              TraceCorQRelationLedger.empty)))))

end AnalyticMotives
end LFunctions
end Boundary
