import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Atoms.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Payload.Lengths.Owner

/-!
# Localized atom-arrow payload length facts

This file owns imported-rectangle length invariants for localized-word category
objects and arrows generated by a single formal localization atom.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A localized atom source object has count equal to rectangle-list length. -/
theorem TraceLocalizationAtom.localizedSourceObject_importedRectangleCount_eq_length
    (atom : TraceLocalizationAtom) :
    atom.localizedSourceObject.importedRectangleCount =
      atom.localizedSourceObject.importedRectangles.length :=
  TraceLocalizedWordObject.importedRectangleCount_eq_length
    atom.localizedSourceObject

/-- A localized atom target object has count equal to rectangle-list length. -/
theorem TraceLocalizationAtom.localizedTargetObject_importedRectangleCount_eq_length
    (atom : TraceLocalizationAtom) :
    atom.localizedTargetObject.importedRectangleCount =
      atom.localizedTargetObject.importedRectangles.length :=
  TraceLocalizedWordObject.importedRectangleCount_eq_length
    atom.localizedTargetObject

/-- A localized atom arrow endpoint count is the length of its endpoint rectangle list. -/
theorem TraceLocalizationAtom.localizedArrow_endpointImportedRectangleCount_eq_length
    (atom : TraceLocalizationAtom) :
    atom.localizedArrow.endpointImportedRectangleCount =
      atom.localizedArrow.endpointImportedRectangles.length :=
  TraceLocalizedWordHom.endpointImportedRectangleCount_eq_length
    atom.localizedArrow

/-- A forward atom localized arrow endpoint count is the length of its endpoint rectangle list. -/
theorem TraceLocalizationAtom.forward_localizedArrow_endpointImportedRectangleCount_eq_length
    (input : TraceLocalizationInput) :
    (TraceLocalizationAtom.forward input).localizedArrow.endpointImportedRectangleCount =
      (TraceLocalizationAtom.forward input).localizedArrow.endpointImportedRectangles.length :=
  TraceLocalizationAtom.localizedArrow_endpointImportedRectangleCount_eq_length
    (TraceLocalizationAtom.forward input)

/-- An inverse atom localized arrow endpoint count is the length of its endpoint rectangle list. -/
theorem TraceLocalizationAtom.inverse_localizedArrow_endpointImportedRectangleCount_eq_length
    (input : TraceLocalizationInput) :
    (TraceLocalizationAtom.inverse input).localizedArrow.endpointImportedRectangleCount =
      (TraceLocalizationAtom.inverse input).localizedArrow.endpointImportedRectangles.length :=
  TraceLocalizationAtom.localizedArrow_endpointImportedRectangleCount_eq_length
    (TraceLocalizationAtom.inverse input)

end AnalyticMotives
end LFunctions
end Boundary
