import Boundary.Realization.AffineComplexPoints
import Mathlib.RingTheory.Kaehler.Basic
import Mathlib.RingTheory.Smooth.Kaehler
import Mathlib.Algebra.Category.AlgebraCat.Basic
import Mathlib.LinearAlgebra.ExteriorAlgebra.Basic
import Mathlib.LinearAlgebra.Finsupp.LSum
import Mathlib.Algebra.Category.ModuleCat.Basic
import Mathlib.Algebra.Homology.HomologicalComplex

/-!
# Affine first de Rham piece

This file records the first genuinely available de Rham-side owner
construction on the affine algebra layer: the module of Kähler differentials
`Ω[S⁄R]`.

It does not define the full algebraic de Rham complex or de Rham realization.
Those need exterior powers, differentials on higher forms, and descent from
affine charts to smooth schemes.

For Kähler differentials and the algebraic de Rham complex, cf. Hartshorne,
*Algebraic Geometry*, II.8 and III.7, and Grothendieck, "On the de Rham
cohomology of algebraic varieties".
-/

universe u

noncomputable section

open scoped TensorProduct
open scoped ModuleCat

namespace Boundary
namespace Realization

variable (R S : Type u)
variable [CommRing R] [CommRing S] [Algebra R S]

/-- The first affine de Rham piece of the `R`-algebra `S`; cf. Hartshorne,
II.8 on Kähler differentials. -/
abbrev affineFirstDeRhamPiece : Type _ :=
  Ω[S⁄R]

instance affineFirstDeRhamPiece.addCommGroup :
    AddCommGroup (affineFirstDeRhamPiece R S) :=
  inferInstance

instance affineFirstDeRhamPiece.module :
    Module S (affineFirstDeRhamPiece R S) :=
  inferInstance

theorem affineFirstDeRhamPiece_eq :
    affineFirstDeRhamPiece R S = Ω[S⁄R] :=
  rfl

/-- The universal derivation into the first affine de Rham piece. -/
abbrev affineDeRhamD : Derivation R S (affineFirstDeRhamPiece R S) :=
  KaehlerDifferential.D R S

theorem affineDeRhamD_apply (x : S) :
    affineDeRhamD R S x = KaehlerDifferential.D R S x :=
  rfl

/-- The affine graded algebra of differential forms generated by `Ω¹`. -/
abbrev affineDeRhamAlgebra : Type _ :=
  ExteriorAlgebra S (affineFirstDeRhamPiece R S)

instance affineDeRhamAlgebra.nonAssocSemiring :
    NonAssocSemiring (affineDeRhamAlgebra R S) :=
  inferInstance

instance affineDeRhamAlgebra.module :
    Module S (affineDeRhamAlgebra R S) :=
  inferInstance

/-- The degree-`n` affine differential forms inside the affine algebra of forms. -/
abbrev affineForms (n : ℕ) : Type _ :=
  (⋀[S]^n (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S)).restrictScalars R

/-- The affine one-forms. -/
abbrev affineOneForms : Type _ :=
  affineForms (R := R) (S := S) 1

/-- The affine two-forms. -/
abbrev affineTwoForms : Type _ :=
  affineForms (R := R) (S := S) 2

/-- The degree-one inclusion of affine differential forms into the algebra of forms. -/
abbrev affineDeRhamι :
    affineFirstDeRhamPiece R S →ₗ[S] affineDeRhamAlgebra R S :=
  ExteriorAlgebra.ι S

/-- The degree-zero affine de Rham differential landing in the algebra of forms. -/
abbrev affineDeRhamD0 : Derivation R S (affineDeRhamAlgebra R S) :=
  (affineDeRhamι R S).compDer (affineDeRhamD R S)

theorem affineDeRhamD0_apply (x : S) :
    affineDeRhamD0 R S x = affineDeRhamι R S (affineDeRhamD R S x) :=
  rfl

/-- The degree-zero affine de Rham differential lands in the degree-one piece. -/
theorem affineDeRhamD0_mem_exteriorPower_one (x : S) :
    affineDeRhamD0 R S x ∈
      (⋀[S]^1 (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S)) := by
  rw [affineDeRhamD0_apply]
  have h :
      ExteriorAlgebra.ιMulti S 1 ![affineDeRhamD R S x] =
        affineDeRhamι R S (affineDeRhamD R S x) := by
    rw [ExteriorAlgebra.ιMulti_succ_apply]
    rw [ExteriorAlgebra.ιMulti_zero_apply, mul_one]
    rfl
  rw [← h]
  exact ExteriorAlgebra.ιMulti_range (R := S) (M := affineFirstDeRhamPiece R S) 1
    ⟨![affineDeRhamD R S x], rfl⟩

/-- The underlying linear map of the degree-zero differential into one-forms. -/
def affineDeRhamD0ToOneFormsLinear :
    S →ₗ[R]
      (⋀[S]^1 (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S)) where
  toFun := fun x =>
    ⟨affineDeRhamD0 R S x, affineDeRhamD0_mem_exteriorPower_one (R := R) (S := S) x⟩
  map_add' := by
    intro x y
    apply Subtype.ext
    change affineDeRhamD0 R S (x + y) =
      affineDeRhamD0 R S x + affineDeRhamD0 R S y
    exact map_add (affineDeRhamD0 R S) x y
  map_smul' := by
    intro r x
    apply Subtype.ext
    change affineDeRhamD0 R S (r • x) = r • affineDeRhamD0 R S x
    exact Derivation.map_smul (affineDeRhamD0 R S) r x

theorem affineDeRhamD0ToOneFormsLinear_apply (x : S) :
    ((affineDeRhamD0ToOneFormsLinear (R := R) (S := S) x :
      (⋀[S]^1 (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S))) :
        affineDeRhamAlgebra R S) =
      affineDeRhamD0 R S x := by
  rfl

/-- The degree-zero affine de Rham differential, viewed as a linear map into one-forms. -/
abbrev affineDeRhamD0ToOneForms :
    S →ₗ[R]
      (⋀[S]^1 (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S)) :=
  affineDeRhamD0ToOneFormsLinear (R := R) (S := S)

theorem affineDeRhamD0ToOneForms_apply (x : S) :
    ((affineDeRhamD0ToOneForms (R := R) (S := S)) x : affineDeRhamAlgebra R S) =
      affineDeRhamD0 R S x :=
  rfl

/-- The `R`-submodule of exact affine one-forms inside the ambient algebra of forms. -/
def affineExactOneForms : Submodule R (affineDeRhamAlgebra R S) :=
  LinearMap.range (affineDeRhamD0 R S : S →ₗ[R] affineDeRhamAlgebra R S)

theorem affineExactOneForms_mem_exteriorPower_one :
    affineExactOneForms (R := R) (S := S) ≤
      (⋀[S]^1 (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S)).restrictScalars R := by
  rintro ω ⟨x, rfl⟩
  exact affineDeRhamD0_mem_exteriorPower_one (R := R) (S := S) x

/-- The canonical inclusion of exact affine one-forms into affine one-forms. -/
def affineExactOneFormsToOneForms :
    affineExactOneForms (R := R) (S := S) →ₗ[R]
      (⋀[S]^1 (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S)).restrictScalars R :=
  Submodule.inclusion (affineExactOneForms_mem_exteriorPower_one (R := R) (S := S))

theorem affineExactOneFormsToOneForms_apply
    (ω : affineExactOneForms (R := R) (S := S)) :
    ((affineExactOneFormsToOneForms (R := R) (S := S) ω :
        (⋀[S]^1 (affineFirstDeRhamPiece R S) : Submodule S (affineDeRhamAlgebra R S)).restrictScalars R) :
      affineDeRhamAlgebra R S) = ω := rfl

/-- The degree-zero de Rham differential, viewed as a linear map into exact one-forms. -/
def affineDeRhamD0ToExactOneForms :
    S →ₗ[R] affineExactOneForms (R := R) (S := S) where
  toFun := fun x => ⟨affineDeRhamD0 R S x, ⟨x, rfl⟩⟩
  map_add' := by
    intro x y
    apply Subtype.ext
    change affineDeRhamD0 R S (x + y) =
      affineDeRhamD0 R S x + affineDeRhamD0 R S y
    exact map_add (affineDeRhamD0 R S) x y
  map_smul' := by
    intro r x
    apply Subtype.ext
    change affineDeRhamD0 R S (r • x) = r • affineDeRhamD0 R S x
    exact Derivation.map_smul (affineDeRhamD0 R S) r x

theorem affineDeRhamD0ToExactOneForms_apply (x : S) :
    ((affineDeRhamD0ToExactOneForms (R := R) (S := S) x :
        affineExactOneForms (R := R) (S := S)) : affineDeRhamAlgebra R S) =
      affineDeRhamD0 R S x := by
  change affineDeRhamD0 R S x = affineDeRhamD0 R S x
  rfl


end Realization
end Boundary
