import Mathlib.Algebra.Homology.HomotopyCategory.SingleFunctors
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Complexes.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homs.LocalizationInput.Owner

/-!
# Localization-input maps as concentrated additive complexes

This file sends a concrete localization input's one-entry additive matrix to
the induced morphism of degree-zero cochain complexes.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The degree-zero cochain-complex morphism generated by a localization input. -/
def TraceLocalizationInput.additiveComplexHom
    (input : TraceLocalizationInput) :
    input.additiveSourceComplex ⟶ input.additiveTargetComplex :=
  (CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject (0 : ℤ)).map
    input.additiveHom

/-- The degree-zero component of the induced complex morphism is the additive
matrix map, transported through the canonical single-complex identifications. -/
theorem TraceLocalizationInput.additiveComplexHom_f_zero
    (input : TraceLocalizationInput) :
    input.additiveComplexHom.f 0 =
      (HomologicalComplex.singleObjXSelf
        (ComplexShape.up ℤ)
        (0 : ℤ)
        input.additiveSourceObject).hom ≫
        input.additiveHom ≫
      (HomologicalComplex.singleObjXSelf
        (ComplexShape.up ℤ)
        (0 : ℤ)
        input.additiveTargetObject).inv :=
  HomologicalComplex.single_map_f_self
    (c := ComplexShape.up ℤ)
    (0 : ℤ)
    input.additiveHom

end AnalyticMotives
end LFunctions
end Boundary
