import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Relations.Owner

/-!
# Relation ledgers for Q-linear trace correspondences

This file owns finite ledgers of trace-correspondence relation generators.

A ledger is pre-quotient data: it records which certified coherences are
available to generate relations.  It does not identify morphisms.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A finite ledger of trace-correspondence relation generators. -/
abbrev TraceCorQRelationLedger :=
  List TraceCorQRelationGenerator

/-- The empty relation ledger. -/
def TraceCorQRelationLedger.empty : TraceCorQRelationLedger :=
  []

/-- A singleton relation ledger. -/
def TraceCorQRelationLedger.singleton
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationLedger :=
  [relation]

/-- Append two relation ledgers. -/
def TraceCorQRelationLedger.append
    (first second : TraceCorQRelationLedger) :
    TraceCorQRelationLedger :=
  first ++ second

/-- The analytic certificate ledger generated by a relation ledger. -/
def TraceCorQRelationLedger.certificateLedger :
    TraceCorQRelationLedger → ResidueChannelCertificateLedger
  | [] => ResidueChannelCertificateLedger.empty
  | relation :: tail =>
      ResidueChannelCertificateLedger.append
        relation.certificateLedger
        (TraceCorQRelationLedger.certificateLedger tail)

/-- The imported finite-rectangle payload carried by a relation ledger. -/
def TraceCorQRelationLedger.importedRectangleCount
    (ledger : TraceCorQRelationLedger) :
    Nat :=
  ledger.certificateLedger.importedRectangleCount

/-- The imported finite explicit-formula rectangles carried by a relation ledger. -/
def TraceCorQRelationLedger.importedRectangles
    (ledger : TraceCorQRelationLedger) :
    List ZetaAdmissibleFunction.ExplicitFormulaRectangle :=
  ledger.certificateLedger.importedRectangles

/-- The internal trace-bookkeeping payload carried by a relation ledger. -/
def TraceCorQRelationLedger.traceBookkeepingCount
    (ledger : TraceCorQRelationLedger) :
    Nat :=
  ledger.certificateLedger.traceBookkeepingCount

/-- The explicit rewrite-step payload carried by a relation ledger. -/
def TraceCorQRelationLedger.rewriteStepCount
    (ledger : TraceCorQRelationLedger) :
    Nat :=
  ledger.certificateLedger.rewriteStepCount

/-- Appending the empty ledger on the left leaves a ledger unchanged. -/
theorem TraceCorQRelationLedger.empty_append
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.append
      TraceCorQRelationLedger.empty
      ledger =
      ledger :=
  rfl

/-- The empty relation ledger carries the empty analytic certificate ledger. -/
theorem TraceCorQRelationLedger.empty_certificateLedger :
    TraceCorQRelationLedger.empty.certificateLedger =
      ResidueChannelCertificateLedger.empty :=
  rfl

/-- The empty relation ledger carries no imported finite-rectangle payload. -/
theorem TraceCorQRelationLedger.empty_importedRectangleCount :
    TraceCorQRelationLedger.empty.importedRectangleCount =
      0 :=
  rfl

/-- The empty relation ledger exposes no imported finite explicit-formula rectangles. -/
theorem TraceCorQRelationLedger.empty_importedRectangles :
    TraceCorQRelationLedger.empty.importedRectangles =
      [] :=
  rfl

/-- The empty relation ledger carries no internal trace-bookkeeping payload. -/
theorem TraceCorQRelationLedger.empty_traceBookkeepingCount :
    TraceCorQRelationLedger.empty.traceBookkeepingCount =
      0 :=
  rfl

/-- The empty relation ledger carries no explicit rewrite-step payload. -/
theorem TraceCorQRelationLedger.empty_rewriteStepCount :
    TraceCorQRelationLedger.empty.rewriteStepCount =
      0 :=
  rfl

/-- A singleton relation ledger carries the relation's certificate ledger. -/
theorem TraceCorQRelationLedger.singleton_certificateLedger
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationLedger.singleton relation).certificateLedger =
      ResidueChannelCertificateLedger.append
        relation.certificateLedger
        ResidueChannelCertificateLedger.empty :=
  rfl

/-- A singleton relation ledger carries the relation's imported finite-rectangle payload. -/
theorem TraceCorQRelationLedger.singleton_importedRectangleCount
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationLedger.singleton relation).importedRectangleCount =
      relation.importedRectangleCount +
        0 :=
  rfl

/-- A singleton relation ledger exposes the relation's imported rectangles. -/
theorem TraceCorQRelationLedger.singleton_importedRectangles
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationLedger.singleton relation).importedRectangles =
      relation.importedRectangles ++
        [] :=
  rfl

/-- A singleton relation ledger carries the relation's internal trace-bookkeeping payload. -/
theorem TraceCorQRelationLedger.singleton_traceBookkeepingCount
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationLedger.singleton relation).traceBookkeepingCount =
      relation.traceBookkeepingCount +
        0 :=
  rfl

/-- A singleton relation ledger carries the relation's explicit rewrite-step payload. -/
theorem TraceCorQRelationLedger.singleton_rewriteStepCount
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationLedger.singleton relation).rewriteStepCount =
      relation.rewriteStepCount +
        0 :=
  rfl

/-- Appending a singleton ledger on the left conses its relation onto the ledger. -/
theorem TraceCorQRelationLedger.singleton_append
    (relation : TraceCorQRelationGenerator)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.append
      (TraceCorQRelationLedger.singleton relation)
      ledger =
      relation :: ledger :=
  rfl

/-- The certificate ledger of a cons relation ledger is relation certificates followed by tail certificates. -/
theorem TraceCorQRelationLedger.cons_certificateLedger
    (relation : TraceCorQRelationGenerator)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.certificateLedger (relation :: ledger) =
      ResidueChannelCertificateLedger.append
        relation.certificateLedger
        ledger.certificateLedger :=
  rfl

/-- The imported payload of a cons relation ledger is head payload plus tail payload. -/
theorem TraceCorQRelationLedger.cons_importedRectangleCount
    (relation : TraceCorQRelationGenerator)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.importedRectangleCount (relation :: ledger) =
      relation.importedRectangleCount +
        ledger.importedRectangleCount :=
  ResidueChannelCertificateLedger.append_importedRectangleCount
    relation.certificateLedger
    ledger.certificateLedger

/-- The imported rectangles of a cons relation ledger are head rectangles followed by tail. -/
theorem TraceCorQRelationLedger.cons_importedRectangles
    (relation : TraceCorQRelationGenerator)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.importedRectangles (relation :: ledger) =
      relation.importedRectangles ++
        ledger.importedRectangles :=
  ResidueChannelCertificateLedger.append_importedRectangles
    relation.certificateLedger
    ledger.certificateLedger

/-- The bookkeeping payload of a cons relation ledger is head payload plus tail payload. -/
theorem TraceCorQRelationLedger.cons_traceBookkeepingCount
    (relation : TraceCorQRelationGenerator)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.traceBookkeepingCount (relation :: ledger) =
      relation.traceBookkeepingCount +
        ledger.traceBookkeepingCount :=
  ResidueChannelCertificateLedger.append_traceBookkeepingCount
    relation.certificateLedger
    ledger.certificateLedger

/-- The rewrite-step payload of a cons relation ledger is head payload plus tail payload. -/
theorem TraceCorQRelationLedger.cons_rewriteStepCount
    (relation : TraceCorQRelationGenerator)
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.rewriteStepCount (relation :: ledger) =
      relation.rewriteStepCount +
        ledger.rewriteStepCount :=
  ResidueChannelCertificateLedger.append_rewriteStepCount
    relation.certificateLedger
    ledger.certificateLedger

/-- Appending the empty ledger on the right leaves a ledger unchanged. -/
theorem TraceCorQRelationLedger.append_empty
    (ledger : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.append
      ledger
      TraceCorQRelationLedger.empty =
      ledger :=
  List.append_nil ledger

/-- Ledger append is associative. -/
theorem TraceCorQRelationLedger.append_assoc
    (first second third : TraceCorQRelationLedger) :
    TraceCorQRelationLedger.append
      (TraceCorQRelationLedger.append first second)
      third =
      TraceCorQRelationLedger.append
        first
        (TraceCorQRelationLedger.append second third) :=
  List.append_assoc first second third

/-- Relation-ledger certificates are compatible with ledger append. -/
theorem TraceCorQRelationLedger.append_certificateLedger
    (first second : TraceCorQRelationLedger) :
    (TraceCorQRelationLedger.append first second).certificateLedger =
      ResidueChannelCertificateLedger.append
        first.certificateLedger
        second.certificateLedger :=
  match first with
  | [] =>
      Eq.symm
        (ResidueChannelCertificateLedger.empty_append
          second.certificateLedger)
  | relation :: tail =>
      Eq.trans
        (congrArg
          (fun certificateLedger =>
            ResidueChannelCertificateLedger.append
              relation.certificateLedger
              certificateLedger)
          (TraceCorQRelationLedger.append_certificateLedger
            tail
            second))
        (Eq.symm
          (ResidueChannelCertificateLedger.append_assoc
            relation.certificateLedger
            (TraceCorQRelationLedger.certificateLedger tail)
            second.certificateLedger))

/-- Appending relation ledgers adds imported finite-rectangle payload. -/
theorem TraceCorQRelationLedger.append_importedRectangleCount
    (first second : TraceCorQRelationLedger) :
    (TraceCorQRelationLedger.append first second).importedRectangleCount =
      first.importedRectangleCount +
        second.importedRectangleCount :=
  Eq.trans
    (congrArg
      ResidueChannelCertificateLedger.importedRectangleCount
      (TraceCorQRelationLedger.append_certificateLedger first second))
    (ResidueChannelCertificateLedger.append_importedRectangleCount
      first.certificateLedger
      second.certificateLedger)

/-- Appending relation ledgers concatenates imported finite explicit-formula rectangles. -/
theorem TraceCorQRelationLedger.append_importedRectangles
    (first second : TraceCorQRelationLedger) :
    (TraceCorQRelationLedger.append first second).importedRectangles =
      first.importedRectangles ++
        second.importedRectangles :=
  Eq.trans
    (congrArg
      ResidueChannelCertificateLedger.importedRectangles
      (TraceCorQRelationLedger.append_certificateLedger first second))
    (ResidueChannelCertificateLedger.append_importedRectangles
      first.certificateLedger
      second.certificateLedger)

/-- A relation ledger's imported-rectangle count is the length of its rectangle list. -/
theorem TraceCorQRelationLedger.importedRectangleCount_eq_length_importedRectangles
    (ledger : TraceCorQRelationLedger) :
    ledger.importedRectangleCount =
      ledger.importedRectangles.length :=
  ResidueChannelCertificateLedger.importedRectangleCount_eq_length_importedRectangles
    ledger.certificateLedger

/-- Appending relation ledgers adds internal trace-bookkeeping payload. -/
theorem TraceCorQRelationLedger.append_traceBookkeepingCount
    (first second : TraceCorQRelationLedger) :
    (TraceCorQRelationLedger.append first second).traceBookkeepingCount =
      first.traceBookkeepingCount +
        second.traceBookkeepingCount :=
  Eq.trans
    (congrArg
      ResidueChannelCertificateLedger.traceBookkeepingCount
      (TraceCorQRelationLedger.append_certificateLedger first second))
    (ResidueChannelCertificateLedger.append_traceBookkeepingCount
      first.certificateLedger
      second.certificateLedger)

/-- Appending relation ledgers adds explicit rewrite-step payload. -/
theorem TraceCorQRelationLedger.append_rewriteStepCount
    (first second : TraceCorQRelationLedger) :
    (TraceCorQRelationLedger.append first second).rewriteStepCount =
      first.rewriteStepCount +
        second.rewriteStepCount :=
  Eq.trans
    (congrArg
      ResidueChannelCertificateLedger.rewriteStepCount
      (TraceCorQRelationLedger.append_certificateLedger first second))
    (ResidueChannelCertificateLedger.append_rewriteStepCount
      first.certificateLedger
      second.certificateLedger)

end AnalyticMotives
end LFunctions
end Boundary
