import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Monotone.Maps.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Owner

/-!
# Monotonicity of bounded mapping-cone triangles

Rebounding the bounded source and target complexes along a larger numeric
weight bound does not change the underlying mapping-cone triangle.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- Rebounding preserves the first bounded representative of a mapping-cone triangle. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject_rebound
    {lower upper : Nat}
    (bound_le : lower ≤ upper)
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy lower}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject
        (hom.rebound bound_le) =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject hom :=
  rfl

/-- Rebounding preserves the second bounded representative of a mapping-cone triangle. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject_rebound
    {lower upper : Nat}
    (bound_le : lower ≤ upper)
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy lower}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject
        (hom.rebound bound_le) =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject hom :=
  rfl

/-- Rebounding preserves the first map of a mapping-cone triangle. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap_rebound
    {lower upper : Nat}
    (bound_le : lower ≤ upper)
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy lower}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap
        (hom.rebound bound_le) =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap hom :=
  rfl

/-- Rebounding preserves the mapping-cone triangle generated by a bounded map. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle_rebound
    {lower upper : Nat}
    (bound_le : lower ≤ upper)
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy lower}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle
        (hom.rebound bound_le) =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle hom :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
