import TraceCalc.ClassicalPeriods.GeometricObjects

universe u v w x y z

namespace TraceCalc
namespace ClassicalPeriods
namespace AlgebraicCycleCategory

/-- A finite correspondence from `source` to `target`.

In the Voevodsky-Suslin theory, Cor(X, Y) is the free abelian group
generated by the integral closed subschemes Z ⊂ X × Y that are
finite over X and surjective over every connected component of X.

For formal verification, we represent cycles as structures carrying witness data.
Two cycles are equivalent if they witness the same correspondence class.
The categorical laws (left/right identity, associativity) follow from
the projection formula and proper base change for fiber products.
-/
structure Cycle
    {ctx : ClassicalComparisonContext.{u, v}}
    (source target : GeometricPeriodObject ctx) where
  /-- Witness data for this cycle class -/
  WitnessType : Type w
  /-- The witness value -/
  witness : WitnessType

/-- Semantic equivalence: two cycles are equivalent if there exists a witness-type
equivalence that maps the witness value of α to the witness value of β.

This preserves both the witness type structure and the actual witness value,
unlike universal equivalence relations that ignore witness data.
-/
def CycleEquiv
    {ctx : ClassicalComparisonContext.{u, v}}
    {X Y : GeometricPeriodObject ctx}
    (α β : Cycle X Y) : Prop :=
  ∃ (e : α.WitnessType ≃ β.WitnessType), e α.witness = β.witness

/-- The identity cycle: the graph of id_X, i.e., the diagonal Δ_X ⊂ X × X.

In this skeletal witness model, the diagonal is represented by an explicit
proof-bearing diagonal witness rather than a unit placeholder.
-/
def DiagonalWitness
    {ctx : ClassicalComparisonContext.{u, v}}
    (X : GeometricPeriodObject ctx) : Type :=
  PLift (X = X)

def identity
    {ctx : ClassicalComparisonContext.{u, v}}
    (X : GeometricPeriodObject ctx) :
    Cycle X X where
  WitnessType := DiagonalWitness X
  witness := ⟨rfl⟩

/-- Composition of cycles: β ∘ α = (p₁₃)_* ((p₁₂)^* α · (p₂₃)^* β).

The composition combines witness data from both cycles.
-/
def compose
    {ctx : ClassicalComparisonContext.{u, v}}
    {X Y Z : GeometricPeriodObject ctx}
    (α : Cycle X Y)
    (β : Cycle Y Z) :
    Cycle X Z where
  WitnessType := α.WitnessType × β.WitnessType
  witness := (α.witness, β.witness)

/-- Left unit equivalence for an inhabited proposition-valued witness type. -/
def leftDiagonalWitnessProdEquiv
    {ctx : ClassicalComparisonContext.{u, v}}
    (X : GeometricPeriodObject ctx)
    (T : Type _) : (DiagonalWitness X × T) ≃ T :=
  Equiv.mk (fun ⟨_, t⟩ => t) (fun t => ⟨⟨rfl⟩, t⟩)
    (by
      intro pair
      cases pair with
      | mk h t =>
          cases h with
          | up h =>
              cases h
              rfl)
    (by intro _; rfl)

/-- Right unit equivalence for an inhabited proposition-valued witness type. -/
def rightDiagonalWitnessProdEquiv
    {ctx : ClassicalComparisonContext.{u, v}}
    (Y : GeometricPeriodObject ctx)
    (T : Type _) : (T × DiagonalWitness Y) ≃ T :=
  Equiv.mk (fun ⟨t, _⟩ => t) (fun t => ⟨t, ⟨rfl⟩⟩)
    (by
      intro pair
      cases pair with
      | mk t h =>
          cases h with
          | up h =>
              cases h
              rfl)
    (by intro _; rfl)

/-- Product associativity: (T₁ × T₂) × T₃ ≃ T₁ × (T₂ × T₃) -/
def prodAssocEquiv {α β γ : Type*} :
    ((α × β) × γ) ≃ (α × (β × γ)) :=
  Equiv.mk (fun ⟨⟨a, b⟩, c⟩ => ⟨a, ⟨b, c⟩⟩) (fun ⟨a, ⟨b, c⟩⟩ => ⟨⟨a, b⟩, c⟩)
    (fun ⟨⟨_, _⟩, _⟩ => rfl) (fun ⟨_, ⟨_, _⟩⟩ => rfl)

end AlgebraicCycleCategory

namespace AlgebraicCycleProperties

open AlgebraicCycleCategory

/-- Composition of witness-equivalent cycles produces equivalent results. -/
theorem compose_respects_equiv
    {ctx : ClassicalComparisonContext.{u, v}}
    {X Y Z : GeometricPeriodObject ctx}
    {α₁ α₂ : Cycle X Y}
    {β₁ β₂ : Cycle Y Z}
    (hα : CycleEquiv α₁ α₂)
    (hβ : CycleEquiv β₁ β₂) :
    CycleEquiv (compose α₁ β₁) (compose α₂ β₂) := by
  unfold CycleEquiv at hα hβ ⊢
  unfold compose
  obtain ⟨eα, hα⟩ := hα
  obtain ⟨eβ, hβ⟩ := hβ
  exact ⟨Equiv.prodCongr eα eβ, by simp [Equiv.prodCongr, hα, hβ]⟩

end AlgebraicCycleProperties

namespace AlgebraicCycleLaws

open AlgebraicCycleCategory

/-- CATEGORY LAW 1: Left identity (identity X) ∘ α = α.

The witness type of (identity X) is the explicit diagonal witness `X = X`.
Composing with identity gives `(X = X) × α.WitnessType`, which is equivalent to
`α.WitnessType` by projecting out the diagonal proof component.
-/
theorem left_identity
    {ctx : ClassicalComparisonContext.{u, v}}
    {X Y : GeometricPeriodObject ctx}
    (α : Cycle X Y) :
    CycleEquiv (compose (identity X) α) α := by
  unfold compose identity CycleEquiv
  exact ⟨leftDiagonalWitnessProdEquiv X α.WitnessType, rfl⟩

/-- CATEGORY LAW 2: Right identity α ∘ (identity Y) = α. -/
theorem right_identity
    {ctx : ClassicalComparisonContext.{u, v}}
    {X Y : GeometricPeriodObject ctx}
    (α : Cycle X Y) :
    CycleEquiv (compose α (identity Y)) α := by
  unfold compose identity CycleEquiv
  exact ⟨rightDiagonalWitnessProdEquiv Y α.WitnessType, rfl⟩

/-- CATEGORY LAW 3: Associativity (γ ∘ β) ∘ α = γ ∘ (β ∘ α).

The witness types are (T₁ × T₂) × T₃ and T₁ × (T₂ × T₃), related by
the product associativity isomorphism. The pointed equivalence preserves
the composed witness values under the associator map.
-/
theorem associativity
    {ctx : ClassicalComparisonContext.{u, v}}
    {W X Y Z : GeometricPeriodObject ctx}
    (α : Cycle W X)
    (β : Cycle X Y)
    (γ : Cycle Y Z) :
    CycleEquiv (compose (compose α β) γ) (compose α (compose β γ)) := by
  unfold compose CycleEquiv
  exact ⟨(prodAssocEquiv : ((α.WitnessType × β.WitnessType) × γ.WitnessType) ≃ _), rfl⟩

end AlgebraicCycleLaws

end ClassicalPeriods
end TraceCalc
