import TraceCalc.ClassicalPeriods.FramedPeriodsConcrete

universe u v w x y z

namespace TraceCalc
namespace ClassicalPeriods

/-- A proof-relevant handle for an object of the recognized motivic category used by formal
period syntax.  The actual realization functors are introduced later; this layer only records the
motivic object together with its de Rham and Betti-side syntactic carriers. -/
structure RecognizedMotiveHandle (ctx : ClassicalComparisonContext.{u, v}) where
  motive : Type w
  deRhamCovectorDatum : Type x
  bettiCycleDatum : Type y
  recognitionCertificate : Type z

/-- A formal period generator, morally `(M, omega, gamma)`.

The scalar value of the period is intentionally absent here; evaluation is a separate interface. -/
structure FormalPeriodGenerator (ctx : ClassicalComparisonContext.{u, v}) where
  motiveHandle : RecognizedMotiveHandle ctx
  motiveObject : motiveHandle.motive
  deRhamCovector : motiveHandle.deRhamCovectorDatum
  bettiCycle : motiveHandle.bettiCycleDatum
  recognitionWitness : motiveHandle.recognitionCertificate

/-- Tags for formal period expression syntax. -/
inductive FormalPeriodExpressionKind
  | generator
  | zero
  | add
  | neg
  | smul

/-- Formal expressions generated by period symbols and algebraic operation tags.

The child/index payloads are explicit syntax data.  This first Crusade-1 layer intentionally does
not quotient expressions or evaluate them. -/
structure FormalPeriodExpression (ctx : ClassicalComparisonContext.{u, v}) where
  generatorIndex : Type w
  generator : generatorIndex → FormalPeriodGenerator ctx
  distinguished : generatorIndex
  kind : FormalPeriodExpressionKind
  support : List generatorIndex
  scalarCoefficient : Option ctx.ScalarField

namespace FormalPeriodExpression

/-- Subtraction is syntax, not a semantic scalar assertion. -/
def sub {ctx : ClassicalComparisonContext.{u, v}}
    (left right : FormalPeriodExpression ctx) : FormalPeriodExpression ctx :=
  { generatorIndex := Sum left.generatorIndex right.generatorIndex
    generator := fun
      | Sum.inl a => left.generator a
      | Sum.inr b => right.generator b
    distinguished := Sum.inl left.distinguished
    kind := FormalPeriodExpressionKind.add
    support := left.support.map Sum.inl ++ right.support.map Sum.inr
    scalarCoefficient := none }

def ofGenerator {ctx : ClassicalComparisonContext.{u, v}}
    (g : FormalPeriodGenerator ctx) : FormalPeriodExpression ctx where
  generatorIndex := Nat
  generator _ := g
  distinguished := 0
  kind := FormalPeriodExpressionKind.generator
  support := [0]
  scalarCoefficient := none

def zero {ctx : ClassicalComparisonContext.{u, v}}
    (ambient : FormalPeriodGenerator ctx) : FormalPeriodExpression ctx where
  generatorIndex := Nat
  generator _ := ambient
  distinguished := 0
  kind := FormalPeriodExpressionKind.zero
  support := []
  scalarCoefficient := none

def add {ctx : ClassicalComparisonContext.{u, v}}
    (left right : FormalPeriodExpression ctx) : FormalPeriodExpression ctx :=
  sub left right

def neg {ctx : ClassicalComparisonContext.{u, v}}
    (expr : FormalPeriodExpression ctx) : FormalPeriodExpression ctx where
  generatorIndex := expr.generatorIndex
  generator := expr.generator
  distinguished := expr.distinguished
  kind := FormalPeriodExpressionKind.neg
  support := expr.support
  scalarCoefficient := none

def smul {ctx : ClassicalComparisonContext.{u, v}}
    (scalar : ctx.ScalarField) (expr : FormalPeriodExpression ctx) : FormalPeriodExpression ctx where
  generatorIndex := expr.generatorIndex
  generator := expr.generator
  distinguished := expr.distinguished
  kind := FormalPeriodExpressionKind.smul
  support := expr.support
  scalarCoefficient := some scalar

@[simp] theorem sub_def {ctx : ClassicalComparisonContext.{u, v}}
    (left right : FormalPeriodExpression ctx) :
    add left right = sub left right := rfl

end FormalPeriodExpression

/-- A named formal relation between two formal period expressions. -/
structure FormalPeriodRelation (ctx : ClassicalComparisonContext.{u, v}) where
  relationName : String
  lhs : FormalPeriodExpression ctx
  rhs : FormalPeriodExpression ctx

/-- A certificate-bearing explanation for a formal period relation.

This is intentionally not a bare proposition and not a quotient relation: the source of the
relation is carried as data for Crusade 5, where motivic explanations are classified. -/
structure PeriodRelationCertificate (ctx : ClassicalComparisonContext.{u, v})
    (relation : FormalPeriodRelation ctx) where
  certificateSource : Type w
  certificate : certificateSource
  sourceDescription : String
  lhsExpression : relation.lhs = relation.lhs
  rhsExpression : relation.rhs = relation.rhs

/-- A structured packet collecting the formal generator with the comparison-side data already
available in the current codebase.  Scalar values are still kept out of the packet. -/
structure StructuredPeriodPacket (ctx : ClassicalComparisonContext.{u, v}) where
  generator : FormalPeriodGenerator ctx
  structuredMorphism : SomeStructuredComparisonMorphism ctx
  framedWitness : SomeConcreteFramedPeriodData ctx
  generatorExpression : FormalPeriodExpression ctx :=
    FormalPeriodExpression.ofGenerator generator

namespace StructuredPeriodPacket

@[simp] theorem mk_generatorExpression
    {ctx : ClassicalComparisonContext.{u, v}}
    (generator : FormalPeriodGenerator ctx)
    (structuredMorphism : SomeStructuredComparisonMorphism ctx)
    (framedWitness : SomeConcreteFramedPeriodData ctx) :
    (StructuredPeriodPacket.mk generator structuredMorphism framedWitness
      (FormalPeriodExpression.ofGenerator generator)).generatorExpression =
      FormalPeriodExpression.ofGenerator generator := rfl

end StructuredPeriodPacket

/-- A separate scalar evaluation interface for formal period expressions.

The map to `ctx.ScalarField` lives here rather than in `FormalPeriodGenerator`, so Crusade 1 keeps
formal periods as syntax/data and does not smuggle scalar complex values into the primitive layer. -/
structure ScalarPeriodEvaluation (ctx : ClassicalComparisonContext.{u, v}) where
  evaluateGenerator : FormalPeriodGenerator ctx → ctx.ScalarField
  evaluateExpression : FormalPeriodExpression ctx → ctx.ScalarField
  evaluates_generator : ∀ g : FormalPeriodGenerator ctx,
    evaluateExpression (FormalPeriodExpression.ofGenerator g) = evaluateGenerator g
  evaluates_zero : ∀ g : FormalPeriodGenerator ctx,
    evaluateExpression (FormalPeriodExpression.zero g) = 0
  evaluates_add : ∀ left right : FormalPeriodExpression ctx,
    evaluateExpression (FormalPeriodExpression.add left right) =
      evaluateExpression left + evaluateExpression right
  evaluates_neg : ∀ expr : FormalPeriodExpression ctx,
    evaluateExpression (FormalPeriodExpression.neg expr) = -evaluateExpression expr
  evaluates_smul : ∀ (scalar : ctx.ScalarField) (expr : FormalPeriodExpression ctx),
    evaluateExpression (FormalPeriodExpression.smul scalar expr) =
      scalar * evaluateExpression expr

namespace ScalarPeriodEvaluation

@[simp] theorem generator_eval {ctx : ClassicalComparisonContext.{u, v}}
    (evaluation : ScalarPeriodEvaluation ctx) (g : FormalPeriodGenerator ctx) :
    evaluation.evaluateExpression (FormalPeriodExpression.ofGenerator g) =
      evaluation.evaluateGenerator g :=
  evaluation.evaluates_generator g

@[simp] theorem zero_eval {ctx : ClassicalComparisonContext.{u, v}}
    (evaluation : ScalarPeriodEvaluation ctx) (g : FormalPeriodGenerator ctx) :
    evaluation.evaluateExpression (FormalPeriodExpression.zero g) = 0 :=
  evaluation.evaluates_zero g

end ScalarPeriodEvaluation

end ClassicalPeriods
end TraceCalc
