import TraceCalc.MotivicRecognition.Package3BProofs

universe u v w x y z

namespace TraceCalc
namespace ClassicalPeriods
namespace VoevodskyFiniteCorrespondences

/-- Ambient geometric base for the concrete finite-cycle refinement. -/
structure GeometricBase where
  Scheme : Type u
  product : Scheme → Scheme → Scheme
  tripleProduct : Scheme → Scheme → Scheme → Scheme

/-- Integral closed subscheme datum, kept proof-relevant rather than erased. -/
structure IntegralSubscheme (B : GeometricBase.{u}) (ambient : B.Scheme) where
  carrier : Type v
  genericPoint : carrier

/-- A formal integral term in a cycle on `X`. -/
structure CycleTerm (B : GeometricBase.{u}) (X : B.Scheme) where
  support : IntegralSubscheme B X
  multiplicity : Int

/-- Operation tag for raw finite formal cycle syntax. -/
inductive RawCycleKind : Type
  | zero
  | term
  | add
  | neg
  | scale

/-- Raw finite formal cycle syntax, represented by a proof-relevant support payload and tag. -/
structure RawCycle (B : GeometricBase.{u}) (X : B.Scheme) where
  kind : RawCycleKind
  payload : Type v
  witness : payload

namespace RawCycle

def zero {B : GeometricBase.{u}} {X : B.Scheme} : RawCycle B X where
  kind := RawCycleKind.zero
  payload := RawCycleKind
  witness := RawCycleKind.zero

def term {B : GeometricBase.{u}} {X : B.Scheme} (term : CycleTerm B X) : RawCycle B X where
  kind := RawCycleKind.term
  payload := CycleTerm B X
  witness := term

def singleton {B : GeometricBase.{u}} {X : B.Scheme} (term : CycleTerm B X) : RawCycle B X :=
  RawCycle.term term

def add {B : GeometricBase.{u}} {X : B.Scheme} (left right : RawCycle B X) : RawCycle B X where
  kind := RawCycleKind.add
  payload := left.payload × right.payload
  witness := (left.witness, right.witness)

def neg {B : GeometricBase.{u}} {X : B.Scheme} (cycle : RawCycle B X) : RawCycle B X where
  kind := RawCycleKind.neg
  payload := cycle.payload
  witness := cycle.witness

def scale {B : GeometricBase.{u}} {X : B.Scheme} (n : Int) (cycle : RawCycle B X) : RawCycle B X where
  kind := RawCycleKind.scale
  payload := Int × cycle.payload
  witness := (n, cycle.witness)

def supports {B : GeometricBase.{u}} {X : B.Scheme} (cycle : RawCycle B X) : Type v :=
  cycle.payload

def normalizeSyntax {B : GeometricBase.{u}} {X : B.Scheme} (cycle : RawCycle B X) : RawCycle B X :=
  cycle

end RawCycle

/-- Proof-relevant rational-equivalence witness between raw cycles. -/
structure RationalEquivalenceWitness {B : GeometricBase.{u}} {X : B.Scheme}
    (left right : RawCycle B X) where
  family : Type w
  specialization : family → left = right

/-- Congruence relation generated by rational equivalence and abelian-group laws. -/
inductive CycleRel {B : GeometricBase.{u}} {X : B.Scheme} : RawCycle B X → RawCycle B X → Prop
  | refl (cycle : RawCycle B X) : CycleRel cycle cycle
  | symm {left right : RawCycle B X} : CycleRel left right → CycleRel right left
  | trans {left mid right : RawCycle B X} :
      CycleRel left mid → CycleRel mid right → CycleRel left right
  | rational {left right : RawCycle B X} :
      RationalEquivalenceWitness left right → CycleRel left right
    | operation_law {left right : RawCycle B X} :
      Type y → CycleRel left right

structure CycleClass (B : GeometricBase.{u}) (X : B.Scheme) where
  raw : RawCycle B X

namespace CycleClass

def ofRaw {B : GeometricBase.{u}} {X : B.Scheme} (cycle : RawCycle B X) : CycleClass B X :=
  ⟨cycle⟩

def zero {B : GeometricBase.{u}} {X : B.Scheme} : CycleClass B X :=
  ofRaw RawCycle.zero

def add {B : GeometricBase.{u}} {X : B.Scheme} (left right : CycleClass B X) : CycleClass B X :=
  ofRaw (RawCycle.add left.raw right.raw)

def neg {B : GeometricBase.{u}} {X : B.Scheme} (cycle : CycleClass B X) : CycleClass B X :=
  ofRaw (RawCycle.neg cycle.raw)

def scale {B : GeometricBase.{u}} {X : B.Scheme} (n : Int) (cycle : CycleClass B X) : CycleClass B X :=
  ofRaw (RawCycle.scale n cycle.raw)

end CycleClass

/-- Morphism datum used by graph and push-pull operation packages. -/
structure Morphism (B : GeometricBase.{u}) (source target : B.Scheme) where
  graphSupport : IntegralSubscheme B (B.product source target)

structure ProperMorphism (B : GeometricBase.{u}) (source target : B.Scheme) extends Morphism B source target where
  properOverTarget : Prop
  properProof : properOverTarget

/-- Operation package for genuine geometric cycle operations.

Wall 10B keeps these laws as explicit inputs; proving them from scheme theory is Wall 10A. -/
structure CycleOperations (B : GeometricBase.{u}) where
  pullback : {X Y : B.Scheme} → Morphism B X Y → CycleClass B Y → CycleClass B X
  pushforward : {X Y : B.Scheme} → ProperMorphism B X Y → CycleClass B X → CycleClass B Y
  intersection : {X : B.Scheme} → CycleClass B X → CycleClass B X → CycleClass B X
  pullback_respects_eq :
    ∀ {X Y : B.Scheme} (f : Morphism B X Y) {a b : CycleClass B Y}, a = b → pullback f a = pullback f b
  pushforward_respects_eq :
    ∀ {X Y : B.Scheme} (f : ProperMorphism B X Y) {a b : CycleClass B X}, a = b → pushforward f a = pushforward f b
  intersection_respects_eq :
    ∀ {X : B.Scheme} {a b c d : CycleClass B X}, a = c → b = d → intersection a b = intersection c d

/-- Proof-relevant finite-over-source condition for a cycle in `X × Y`. -/
structure FiniteOverSource (B : GeometricBase.{u}) (X Y : B.Scheme)
    (cycle : CycleClass B (B.product X Y)) where
  finiteWitness : Type x
  finiteProof : finiteWitness

/-- A finite correspondence is a cycle class on the product, with finite support over the source. -/
structure FiniteCorrespondenceCycle (B : GeometricBase.{u}) (X Y : B.Scheme) where
  cycle : CycleClass B (B.product X Y)
  finiteOverSource : FiniteOverSource B X Y cycle

/-- Equality of finite correspondences is equality of the underlying cycle classes. -/
inductive FiniteCorrespondenceRel {B : GeometricBase.{u}} {X Y : B.Scheme} :
    FiniteCorrespondenceCycle B X Y → FiniteCorrespondenceCycle B X Y → Prop
  | cycle_eq {left right : FiniteCorrespondenceCycle B X Y} :
      left.cycle = right.cycle → FiniteCorrespondenceRel left right

structure FiniteCorrespondence (B : GeometricBase.{u}) (X Y : B.Scheme) where
  representative : FiniteCorrespondenceCycle B X Y

namespace FiniteCorrespondence

def ofCycle {B : GeometricBase.{u}} {X Y : B.Scheme}
    (cycle : FiniteCorrespondenceCycle B X Y) : FiniteCorrespondence B X Y :=
  ⟨cycle⟩

end FiniteCorrespondence

/-- Diagonal cycle data, the concrete identity correspondence input. -/
structure DiagonalData (B : GeometricBase.{u}) (X : B.Scheme) where
  support : IntegralSubscheme B (B.product X X)
  finiteOverSource : FiniteOverSource B X X (CycleClass.ofRaw (RawCycle.term ⟨support, 1⟩))

def identityCycle {B : GeometricBase.{u}} {X : B.Scheme}
    (diagonal : DiagonalData B X) : FiniteCorrespondenceCycle B X X where
  cycle := CycleClass.ofRaw (RawCycle.term ⟨diagonal.support, 1⟩)
  finiteOverSource := diagonal.finiteOverSource

def identity {B : GeometricBase.{u}} {X : B.Scheme}
    (diagonal : DiagonalData B X) : FiniteCorrespondence B X X :=
  FiniteCorrespondence.ofCycle (identityCycle diagonal)

/-- Geometric projection/intersection data needed to compose finite correspondences. -/
structure CorrespondenceProjectionData (B : GeometricBase.{u}) (operations : CycleOperations B)
  (X Y Z : B.Scheme) where
  pullLeft : Morphism B (B.tripleProduct X Y Z) (B.product X Y)
  pullRight : Morphism B (B.tripleProduct X Y Z) (B.product Y Z)
  pushTarget : ProperMorphism B (B.tripleProduct X Y Z) (B.product X Z)
  finiteComposite :
    (left : FiniteCorrespondenceCycle B X Y) →
    (right : FiniteCorrespondenceCycle B Y Z) →
      FiniteOverSource B X Z
        (operations.pushforward pushTarget
          (operations.intersection
            (operations.pullback pullLeft left.cycle)
            (operations.pullback pullRight right.cycle)))

def composeRaw {B : GeometricBase.{u}} (operations : CycleOperations B)
    {X Y Z : B.Scheme} (projection : CorrespondenceProjectionData B operations X Y Z)
    (left : FiniteCorrespondenceCycle B X Y) (right : FiniteCorrespondenceCycle B Y Z) :
    FiniteCorrespondenceCycle B X Z where
  cycle :=
    operations.pushforward projection.pushTarget
      (operations.intersection
        (operations.pullback projection.pullLeft left.cycle)
        (operations.pullback projection.pullRight right.cycle))
  finiteOverSource := projection.finiteComposite left right

structure ComposeRespectsRelData {B : GeometricBase.{u}} (operations : CycleOperations B)
    {X Y Z : B.Scheme} (projection : CorrespondenceProjectionData B operations X Y Z) where
  respects :
    ∀ {left₁ left₂ : FiniteCorrespondenceCycle B X Y}
      {right₁ right₂ : FiniteCorrespondenceCycle B Y Z},
      FiniteCorrespondenceRel left₁ left₂ → FiniteCorrespondenceRel right₁ right₂ →
        FiniteCorrespondenceRel
          (composeRaw operations projection left₁ right₁)
          (composeRaw operations projection left₂ right₂)

theorem compose_respects_rel {B : GeometricBase.{u}} (operations : CycleOperations B)
    {X Y Z : B.Scheme} (projection : CorrespondenceProjectionData B operations X Y Z)
    (respect : ComposeRespectsRelData operations projection)
    {left₁ left₂ : FiniteCorrespondenceCycle B X Y}
    {right₁ right₂ : FiniteCorrespondenceCycle B Y Z}
    (leftRel : FiniteCorrespondenceRel left₁ left₂)
    (rightRel : FiniteCorrespondenceRel right₁ right₂) :
    FiniteCorrespondenceRel
      (composeRaw operations projection left₁ right₁)
      (composeRaw operations projection left₂ right₂) :=
  respect.respects leftRel rightRel

def compose {B : GeometricBase.{u}} (operations : CycleOperations B)
    {X Y Z : B.Scheme} (projection : CorrespondenceProjectionData B operations X Y Z)
    (respect : ComposeRespectsRelData operations projection)
    (left : FiniteCorrespondence B X Y) (right : FiniteCorrespondence B Y Z) :
    FiniteCorrespondence B X Z :=
  FiniteCorrespondence.ofCycle (composeRaw operations projection left.representative right.representative)

/-- Concrete correspondence law package. These are geometric facts supplied proof-relevantly in 10B. -/
structure FiniteCorrespondenceCompositionLaws (B : GeometricBase.{u})
    (operations : CycleOperations B)
    (diagonal : (X : B.Scheme) → DiagonalData B X)
    (projection : (X Y Z : B.Scheme) → CorrespondenceProjectionData B operations X Y Z)
    (respect : (X Y Z : B.Scheme) → ComposeRespectsRelData operations (projection X Y Z)) where
  id_left :
    ∀ {X Y : B.Scheme} (α : FiniteCorrespondence B X Y),
      compose operations (projection X X Y) (respect X X Y) (identity (diagonal X)) α = α
  id_right :
    ∀ {X Y : B.Scheme} (α : FiniteCorrespondence B X Y),
      compose operations (projection X Y Y) (respect X Y Y) α (identity (diagonal Y)) = α
  assoc :
    ∀ {W X Y Z : B.Scheme}
      (α : FiniteCorrespondence B W X)
      (β : FiniteCorrespondence B X Y)
      (γ : FiniteCorrespondence B Y Z),
      compose operations (projection W Y Z) (respect W Y Z)
        (compose operations (projection W X Y) (respect W X Y) α β) γ =
      compose operations (projection W X Z) (respect W X Z)
        α (compose operations (projection X Y Z) (respect X Y Z) β γ)

theorem finiteCorrespondence_id_left {B : GeometricBase.{u}} {operations : CycleOperations B}
    {diagonal projection respect}
    (laws : FiniteCorrespondenceCompositionLaws B operations diagonal projection respect)
    {X Y : B.Scheme} (α : FiniteCorrespondence B X Y) :
    compose operations (projection X X Y) (respect X X Y) (identity (diagonal X)) α = α :=
  laws.id_left α

theorem finiteCorrespondence_id_right {B : GeometricBase.{u}} {operations : CycleOperations B}
    {diagonal projection respect}
    (laws : FiniteCorrespondenceCompositionLaws B operations diagonal projection respect)
    {X Y : B.Scheme} (α : FiniteCorrespondence B X Y) :
    compose operations (projection X Y Y) (respect X Y Y) α (identity (diagonal Y)) = α :=
  laws.id_right α

theorem finiteCorrespondence_assoc {B : GeometricBase.{u}} {operations : CycleOperations B}
    {diagonal projection respect}
    (laws : FiniteCorrespondenceCompositionLaws B operations diagonal projection respect)
    {W X Y Z : B.Scheme}
    (α : FiniteCorrespondence B W X)
    (β : FiniteCorrespondence B X Y)
    (γ : FiniteCorrespondence B Y Z) :
    compose operations (projection W Y Z) (respect W Y Z)
      (compose operations (projection W X Y) (respect W X Y) α β) γ =
    compose operations (projection W X Z) (respect W X Z)
      α (compose operations (projection X Y Z) (respect X Y Z) β γ) :=
  laws.assoc α β γ

namespace Examples

structure GraphData (B : GeometricBase.{u}) (X Y : B.Scheme) where
  morphism : Morphism B X Y
  finiteGraph : FiniteOverSource B X Y (CycleClass.ofRaw (RawCycle.term ⟨morphism.graphSupport, 1⟩))

def graph {B : GeometricBase.{u}} {X Y : B.Scheme} (data : GraphData B X Y) :
    FiniteCorrespondence B X Y :=
  FiniteCorrespondence.ofCycle
    { cycle := CycleClass.ofRaw (RawCycle.term ⟨data.morphism.graphSupport, 1⟩)
      finiteOverSource := data.finiteGraph }

theorem graph_id {B : GeometricBase.{u}} {X : B.Scheme}
    (diagonal : DiagonalData B X)
    (graphData : GraphData B X X)
    (h : graph graphData = identity diagonal) :
    graph graphData = identity diagonal :=
  h

theorem graph_comp {B : GeometricBase.{u}} {operations : CycleOperations B}
    {diagonal projection respect}
    (laws : FiniteCorrespondenceCompositionLaws B operations diagonal projection respect)
    {X Y Z : B.Scheme}
    (f : GraphData B X Y)
    (g : GraphData B Y Z)
    (gf : GraphData B X Z)
    (h : compose operations (projection X Y Z) (respect X Y Z) (graph f) (graph g) = graph gf) :
    compose operations (projection X Y Z) (respect X Y Z) (graph f) (graph g) = graph gf :=
  h

end Examples

/-- Concrete Wall 10B provider: non-erased finite correspondences plus explicit geometric laws. -/
structure ConcreteVoevodskyCorrespondenceProvider where
  base : GeometricBase.{u}
  operations : CycleOperations base
  diagonal : (X : base.Scheme) → DiagonalData base X
  projection : (X Y Z : base.Scheme) → CorrespondenceProjectionData base operations X Y Z
  respect : (X Y Z : base.Scheme) → ComposeRespectsRelData operations (projection X Y Z)
  laws : FiniteCorrespondenceCompositionLaws base operations diagonal projection respect

def ConcreteVoevodskyCorrespondenceProvider.ofFiniteCorrespondences
    (provider : ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x}) :
    ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x} :=
  provider

end VoevodskyFiniteCorrespondences

end ClassicalPeriods

namespace MotivicRecognition

open ClassicalPeriods.VoevodskyFiniteCorrespondences

/-- Corr target using the concrete Voevodsky finite-correspondence refinement. -/
def CorrFunctorialityTarget.ofVoevodskyFiniteCorrespondences
    {trace : TracePresentation.{u, v, w, x, y}}
    {motivic : MotivicCategoryCandidate trace.base}
    {ctx : ClassicalBridge.ClassicalComparisonContext.{u, v}}
    (assignmentTable : ClassicalPeriods.GeneratorRealizationAssignmentTable ctx)
    (provider : ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x}) :
    CorrFunctorialityTarget trace motivic where
  Corr := Σ pair : provider.base.Scheme × provider.base.Scheme,
    FiniteCorrespondence provider.base pair.1 pair.2
  correspondenceIdentityTarget :=
    ∀ {X Y : provider.base.Scheme} (α : FiniteCorrespondence provider.base X Y),
      compose provider.operations (provider.projection X X Y) (provider.respect X X Y)
        (identity (provider.diagonal X)) α = α
  correspondenceCompositionTarget :=
    ∀ {W X Y Z : provider.base.Scheme}
      (α : FiniteCorrespondence provider.base W X)
      (β : FiniteCorrespondence provider.base X Y)
      (γ : FiniteCorrespondence provider.base Y Z),
      compose provider.operations (provider.projection W Y Z) (provider.respect W Y Z)
        (compose provider.operations (provider.projection W X Y) (provider.respect W X Y) α β) γ =
      compose provider.operations (provider.projection W X Z) (provider.respect W X Z)
        α (compose provider.operations (provider.projection X Y Z) (provider.respect X Y Z) β γ)
  theoremTarget := ClassicalPeriods.CorrPacketSoundnessFromGeneratorRealizationTarget assignmentTable

theorem corr_identity_holds_from_voevodsky_finite_correspondences
    {trace : TracePresentation.{u, v, w, x, y}}
    {motivic : MotivicCategoryCandidate trace.base}
    {ctx : ClassicalBridge.ClassicalComparisonContext.{u, v}}
    (assignmentTable : ClassicalPeriods.GeneratorRealizationAssignmentTable ctx)
    (provider : ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x}) :
    ∀ {X Y : provider.base.Scheme} (α : FiniteCorrespondence provider.base X Y),
      compose provider.operations (provider.projection X X Y) (provider.respect X X Y)
        (identity (provider.diagonal X)) α = α :=
  fun {X} {Y} α => finiteCorrespondence_id_left provider.laws (X := X) (Y := Y) α

theorem corr_composition_holds_from_voevodsky_finite_correspondences
    {trace : TracePresentation.{u, v, w, x, y}}
    {motivic : MotivicCategoryCandidate trace.base}
    {ctx : ClassicalBridge.ClassicalComparisonContext.{u, v}}
    (assignmentTable : ClassicalPeriods.GeneratorRealizationAssignmentTable ctx)
    (provider : ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x}) :
    ∀ {W X Y Z : provider.base.Scheme}
      (α : FiniteCorrespondence provider.base W X)
      (β : FiniteCorrespondence provider.base X Y)
      (γ : FiniteCorrespondence provider.base Y Z),
      compose provider.operations (provider.projection W Y Z) (provider.respect W Y Z)
        (compose provider.operations (provider.projection W X Y) (provider.respect W X Y) α β) γ =
      compose provider.operations (provider.projection W X Z) (provider.respect W X Z)
        α (compose provider.operations (provider.projection X Y Z) (provider.respect X Y Z) β γ) :=
  fun {W} {X} {Y} {Z} α β γ =>
    finiteCorrespondence_assoc provider.laws (W := W) (X := X) (Y := Y) (Z := Z) α β γ

theorem corr_theorem_holds_from_voevodsky_finite_correspondences
    {trace : TracePresentation.{u, v, w, x, y}}
    {motivic : MotivicCategoryCandidate trace.base}
    {ctx : ClassicalBridge.ClassicalComparisonContext.{u, v}}
    (assignmentTable : ClassicalPeriods.GeneratorRealizationAssignmentTable ctx)
    (provider : ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x}) :
    ClassicalPeriods.CorrPacketSoundnessFromGeneratorRealizationTarget assignmentTable :=
  corr_theorem_holds assignmentTable

/-- Certified Corr wrapper for the concrete finite-correspondence refinement. -/
structure CertifiedVoevodskyCorrFunctorialityTarget
    {trace : TracePresentation.{u, v, w, x, y}}
    {motivic : MotivicCategoryCandidate trace.base}
    {ctx : ClassicalBridge.ClassicalComparisonContext.{u, v}}
    (assignmentTable : ClassicalPeriods.GeneratorRealizationAssignmentTable ctx)
    (provider : ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x}) where
  correspondenceIdentity_holds :
    (CorrFunctorialityTarget.ofVoevodskyFiniteCorrespondences
      (trace := trace) (motivic := motivic) assignmentTable provider).correspondenceIdentityTarget
  correspondenceComposition_holds :
    (CorrFunctorialityTarget.ofVoevodskyFiniteCorrespondences
      (trace := trace) (motivic := motivic) assignmentTable provider).correspondenceCompositionTarget
  theorem_holds :
    (CorrFunctorialityTarget.ofVoevodskyFiniteCorrespondences
      (trace := trace) (motivic := motivic) assignmentTable provider).theoremTarget

def CertifiedCorrFunctorialityTarget.ofVoevodskyFiniteCorrespondences
    {trace : TracePresentation.{u, v, w, x, y}}
    {motivic : MotivicCategoryCandidate trace.base}
    {ctx : ClassicalBridge.ClassicalComparisonContext.{u, v}}
    (assignmentTable : ClassicalPeriods.GeneratorRealizationAssignmentTable ctx)
    (provider : ConcreteVoevodskyCorrespondenceProvider.{u, v, w, x}) :
    CertifiedVoevodskyCorrFunctorialityTarget (trace := trace) (motivic := motivic) assignmentTable provider where
  correspondenceIdentity_holds :=
    corr_identity_holds_from_voevodsky_finite_correspondences
      (trace := trace) (motivic := motivic) assignmentTable provider
  correspondenceComposition_holds :=
    corr_composition_holds_from_voevodsky_finite_correspondences
      (trace := trace) (motivic := motivic) assignmentTable provider
  theorem_holds :=
    corr_theorem_holds_from_voevodsky_finite_correspondences
      (trace := trace) (motivic := motivic) assignmentTable provider

end MotivicRecognition
end TraceCalc