import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homs.Ext.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homs.Identity.Entries.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Objects.Singleton.Owner

/-!
# Singleton homs in the analytic additive envelope

This file embeds one trace correspondence as the single entry of the matrix
hom between the corresponding singleton additive-envelope objects.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The one-entry additive-envelope matrix generated by a trace correspondence. -/
def TraceAnalyticAdditiveHom.singletonMap
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticAdditiveHom
      (TraceAnalyticAdditiveObject.singleton source)
      (TraceAnalyticAdditiveObject.singleton target) :=
  fun _ _ => hom

/-- The single entry of a singleton matrix is the original trace correspondence. -/
theorem TraceAnalyticAdditiveHom.singletonMap_entry_zero
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    (TraceAnalyticAdditiveHom.singletonMap hom).entry 0 0 =
      hom :=
  rfl

/-- The singleton matrix of a trace identity is the identity matrix on the
singleton additive object. -/
theorem TraceAnalyticAdditiveHom.singletonMap_id
    (object : TraceCorQObject) :
    TraceAnalyticAdditiveHom.id
        (TraceAnalyticAdditiveObject.singleton object) =
      TraceAnalyticAdditiveHom.singletonMap
        (TraceCorQHom.id object) :=
  TraceAnalyticAdditiveHom.ext
    (fun sourceIndex targetIndex =>
      match Subsingleton.elim targetIndex sourceIndex with
      | rfl =>
          Eq.trans
            (TraceAnalyticAdditiveHom.id_entry_self
              (TraceAnalyticAdditiveObject.singleton object)
              sourceIndex)
            (congrArg
              TraceCorQHom.id
              (TraceAnalyticAdditiveObject.singleton_component
                object
                sourceIndex)))

/-- Composition of singleton matrices is the singleton matrix of the composed
trace correspondence. -/
theorem TraceAnalyticAdditiveHom.singletonMap_comp
    {source middle target : TraceCorQObject}
    (left : source ⟶ middle)
    (right : middle ⟶ target) :
    TraceAnalyticAdditiveHom.comp
        (TraceAnalyticAdditiveHom.singletonMap left)
        (TraceAnalyticAdditiveHom.singletonMap right) =
      TraceAnalyticAdditiveHom.singletonMap
        (TraceCorQHom.comp left right) :=
  TraceAnalyticAdditiveHom.ext
    (fun sourceIndex targetIndex =>
      Eq.trans
        (TraceAnalyticAdditiveHom.comp_entry
          (TraceAnalyticAdditiveHom.singletonMap left)
          (TraceAnalyticAdditiveHom.singletonMap right)
          sourceIndex
          targetIndex)
        (Eq.trans
          (Finset.sum_eq_single
            (0 :
              Fin (TraceAnalyticAdditiveObject.singleton middle).length)
            (fun middleIndex _membership middle_ne_zero =>
              False.elim
                (middle_ne_zero
                  (Subsingleton.elim middleIndex 0)))
            (fun zero_not_mem =>
              False.elim
                (zero_not_mem
                  (Finset.mem_univ
                    (0 :
                      Fin
                        (TraceAnalyticAdditiveObject.singleton
                          middle).length)))))
          rfl))

end AnalyticMotives
end LFunctions
end Boundary
