import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Inputs.ByKind.Isomorphisms.Cancellation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Inputs.ByKind.Representatives.Owner

/-!
# Descent localized arrows

This file exposes the channel, refinement, and schedule descent inputs as
invertible arrows in the formal localized word category.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized isomorphism generated by descent channel decomposition. -/
def TraceDescentLocalization.channelIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentChannel source target).localizedSourceObject
      (TraceLocalizationInput.descentChannel source target).localizedTargetObject :=
  TraceLocalizationInput.descentChannelLocalizedIso source target

/-- The localized isomorphism generated by descent refinement. -/
def TraceDescentLocalization.refinementIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentRefinement source target).localizedSourceObject
      (TraceLocalizationInput.descentRefinement source target).localizedTargetObject :=
  TraceLocalizationInput.descentRefinementLocalizedIso source target

/-- The localized isomorphism generated by descent schedule exchange. -/
def TraceDescentLocalization.scheduleIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentSchedule source target).localizedSourceObject
      (TraceLocalizationInput.descentSchedule source target).localizedTargetObject :=
  TraceLocalizationInput.descentScheduleLocalizedIso source target

/-- The hom of the descent-channel isomorphism is the named channel forward arrow. -/
theorem TraceDescentLocalization.channelIso_hom
    (source target : QTraceExpression) :
    (TraceDescentLocalization.channelIso source target).hom =
      TraceLocalizationInput.descentChannelForwardArrow source target :=
  rfl

/-- The inverse of the descent-channel isomorphism is the named channel inverse arrow. -/
theorem TraceDescentLocalization.channelIso_inv
    (source target : QTraceExpression) :
    (TraceDescentLocalization.channelIso source target).inv =
      TraceLocalizationInput.descentChannelInverseArrow source target :=
  rfl

/-- The descent-channel hom has a one-atom chosen representative. -/
theorem TraceDescentLocalization.channelIso_hom_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputForward
      (TraceLocalizationInput.descentChannel source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.descentChannelForwardArrow_representative_atomCount
    source
    target

/-- The descent-channel inverse has a one-atom chosen representative. -/
theorem TraceDescentLocalization.channelIso_inv_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputInverse
      (TraceLocalizationInput.descentChannel source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.descentChannelInverseArrow_representative_atomCount
    source
    target

/-- The hom of the descent-refinement isomorphism is the named refinement forward arrow. -/
theorem TraceDescentLocalization.refinementIso_hom
    (source target : QTraceExpression) :
    (TraceDescentLocalization.refinementIso source target).hom =
      TraceLocalizationInput.descentRefinementForwardArrow source target :=
  rfl

/-- The inverse of the descent-refinement isomorphism is the named refinement inverse arrow. -/
theorem TraceDescentLocalization.refinementIso_inv
    (source target : QTraceExpression) :
    (TraceDescentLocalization.refinementIso source target).inv =
      TraceLocalizationInput.descentRefinementInverseArrow source target :=
  rfl

/-- The descent-refinement hom has a one-atom chosen representative. -/
theorem TraceDescentLocalization.refinementIso_hom_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputForward
      (TraceLocalizationInput.descentRefinement source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.descentRefinementForwardArrow_representative_atomCount
    source
    target

/-- The descent-refinement inverse has a one-atom chosen representative. -/
theorem TraceDescentLocalization.refinementIso_inv_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputInverse
      (TraceLocalizationInput.descentRefinement source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.descentRefinementInverseArrow_representative_atomCount
    source
    target

/-- The hom of the descent-schedule isomorphism is the named schedule forward arrow. -/
theorem TraceDescentLocalization.scheduleIso_hom
    (source target : QTraceExpression) :
    (TraceDescentLocalization.scheduleIso source target).hom =
      TraceLocalizationInput.descentScheduleForwardArrow source target :=
  rfl

/-- The inverse of the descent-schedule isomorphism is the named schedule inverse arrow. -/
theorem TraceDescentLocalization.scheduleIso_inv
    (source target : QTraceExpression) :
    (TraceDescentLocalization.scheduleIso source target).inv =
      TraceLocalizationInput.descentScheduleInverseArrow source target :=
  rfl

/-- The descent-schedule hom has a one-atom chosen representative. -/
theorem TraceDescentLocalization.scheduleIso_hom_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputForward
      (TraceLocalizationInput.descentSchedule source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.descentScheduleForwardArrow_representative_atomCount
    source
    target

/-- The descent-schedule inverse has a one-atom chosen representative. -/
theorem TraceDescentLocalization.scheduleIso_inv_representative_atomCount
    (source target : QTraceExpression) :
    (TraceLocalizationWord.ofInputInverse
      (TraceLocalizationInput.descentSchedule source target)).atomCount =
      0 + 1 :=
  TraceLocalizationInput.descentScheduleInverseArrow_representative_atomCount
    source
    target

/-- Descent-channel hom followed by inverse is identity. -/
theorem TraceDescentLocalization.channelIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceDescentLocalization.channelIso source target).hom
        (TraceDescentLocalization.channelIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentChannel source target).sourceObject :=
  TraceLocalizationInput.descentChannelLocalizedIso_hom_comp_inv source target

/-- Descent-channel inverse followed by hom is identity. -/
theorem TraceDescentLocalization.channelIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceDescentLocalization.channelIso source target).inv
        (TraceDescentLocalization.channelIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentChannel source target).targetObject :=
  TraceLocalizationInput.descentChannelLocalizedIso_inv_comp_hom source target

/-- Descent-channel hom followed by inverse is categorical identity. -/
theorem TraceDescentLocalization.channelIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceDescentLocalization.channelIso source target).hom ≫
        (TraceDescentLocalization.channelIso source target).inv =
      (𝟙 (TraceLocalizationInput.descentChannel source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentChannel source target).localizedSourceObject
          (TraceLocalizationInput.descentChannel source target).localizedSourceObject) :=
  TraceLocalizationInput.descentChannelLocalizedIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Descent-channel inverse followed by hom is categorical identity. -/
theorem TraceDescentLocalization.channelIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceDescentLocalization.channelIso source target).inv ≫
        (TraceDescentLocalization.channelIso source target).hom =
      (𝟙 (TraceLocalizationInput.descentChannel source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentChannel source target).localizedTargetObject
          (TraceLocalizationInput.descentChannel source target).localizedTargetObject) :=
  TraceLocalizationInput.descentChannelLocalizedIso_inv_comp_hom_eq_categoryIdentity
    source
    target

/-- Descent-refinement hom followed by inverse is identity. -/
theorem TraceDescentLocalization.refinementIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceDescentLocalization.refinementIso source target).hom
        (TraceDescentLocalization.refinementIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentRefinement source target).sourceObject :=
  TraceLocalizationInput.descentRefinementLocalizedIso_hom_comp_inv source target

/-- Descent-refinement inverse followed by hom is identity. -/
theorem TraceDescentLocalization.refinementIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceDescentLocalization.refinementIso source target).inv
        (TraceDescentLocalization.refinementIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentRefinement source target).targetObject :=
  TraceLocalizationInput.descentRefinementLocalizedIso_inv_comp_hom source target

/-- Descent-refinement hom followed by inverse is categorical identity. -/
theorem TraceDescentLocalization.refinementIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceDescentLocalization.refinementIso source target).hom ≫
        (TraceDescentLocalization.refinementIso source target).inv =
      (𝟙 (TraceLocalizationInput.descentRefinement source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentRefinement source target).localizedSourceObject
          (TraceLocalizationInput.descentRefinement source target).localizedSourceObject) :=
  TraceLocalizationInput.descentRefinementLocalizedIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Descent-refinement inverse followed by hom is categorical identity. -/
theorem TraceDescentLocalization.refinementIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceDescentLocalization.refinementIso source target).inv ≫
        (TraceDescentLocalization.refinementIso source target).hom =
      (𝟙 (TraceLocalizationInput.descentRefinement source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentRefinement source target).localizedTargetObject
          (TraceLocalizationInput.descentRefinement source target).localizedTargetObject) :=
  TraceLocalizationInput.descentRefinementLocalizedIso_inv_comp_hom_eq_categoryIdentity
    source
    target

/-- Descent-schedule hom followed by inverse is identity. -/
theorem TraceDescentLocalization.scheduleIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceDescentLocalization.scheduleIso source target).hom
        (TraceDescentLocalization.scheduleIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentSchedule source target).sourceObject :=
  TraceLocalizationInput.descentScheduleLocalizedIso_hom_comp_inv source target

/-- Descent-schedule inverse followed by hom is identity. -/
theorem TraceDescentLocalization.scheduleIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceDescentLocalization.scheduleIso source target).inv
        (TraceDescentLocalization.scheduleIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.descentSchedule source target).targetObject :=
  TraceLocalizationInput.descentScheduleLocalizedIso_inv_comp_hom source target

/-- Descent-schedule hom followed by inverse is categorical identity. -/
theorem TraceDescentLocalization.scheduleIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceDescentLocalization.scheduleIso source target).hom ≫
        (TraceDescentLocalization.scheduleIso source target).inv =
      (𝟙 (TraceLocalizationInput.descentSchedule source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentSchedule source target).localizedSourceObject
          (TraceLocalizationInput.descentSchedule source target).localizedSourceObject) :=
  TraceLocalizationInput.descentScheduleLocalizedIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Descent-schedule inverse followed by hom is categorical identity. -/
theorem TraceDescentLocalization.scheduleIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceDescentLocalization.scheduleIso source target).inv ≫
        (TraceDescentLocalization.scheduleIso source target).hom =
      (𝟙 (TraceLocalizationInput.descentSchedule source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.descentSchedule source target).localizedTargetObject
          (TraceLocalizationInput.descentSchedule source target).localizedTargetObject) :=
  TraceLocalizationInput.descentScheduleLocalizedIso_inv_comp_hom_eq_categoryIdentity
    source
    target

end AnalyticMotives
end LFunctions
end Boundary
