import TraceCalc.LayerA.CategoryInfra.ExactnessTransport

universe u v

namespace TraceCalc
namespace CategoryInfra

structure DGMorphismCompositionTarget (C : DGCategoryLike.{u, v}) where
  id : ∀ X : C.Obj, C.HomComplex X X
  comp : ∀ {X Y Z : C.Obj}, C.HomComplex X Y → C.HomComplex Y Z → C.HomComplex X Z
  idComp : Prop
  compId : Prop
  assoc : Prop
  differentialId : Prop
  differentialComp : Prop

structure DGMorphismCompositionData {C : DGCategoryLike.{u, v}}
    (target : DGMorphismCompositionTarget C) where
  idCompWitness : target.idComp
  compIdWitness : target.compId
  assocWitness : target.assoc
  differentialIdWitness : target.differentialId
  differentialCompWitness : target.differentialComp

structure PretriangulatedClosureTarget {C : DGCategoryLike.{u, v}}
    (P : PretriangulatedHull C) where
  shiftObj : P.hull.Obj → P.hull.Obj
  coneObj : P.hull.Obj → P.hull.Obj → P.hull.Obj
  shiftClosure : Prop
  coneClosure : Prop

structure PretriangulatedClosureData {C : DGCategoryLike.{u, v}}
    {P : PretriangulatedHull C}
    (target : PretriangulatedClosureTarget P) where
  shiftClosureWitness : target.shiftClosure
  coneClosureWitness : target.coneClosure

structure StableCompletionConstructionTarget (presentation : Type u) where
  freeDG : FreeDGEnvelope.{u, u} presentation
  freeDGComposition : DGMorphismCompositionTarget freeDG.envelope
  pretriangulatedHull : PretriangulatedHull freeDG.envelope
  pretriangulatedClosure : PretriangulatedClosureTarget pretriangulatedHull
  homotopyCategory : H0Category pretriangulatedHull
  h0ComparisonToHull : Prop
  karoubiEnvelope : KaroubiEnvelope homotopyCategory
  exactnessTransport :
    ExactnessTransport freeDG pretriangulatedHull homotopyCategory karoubiEnvelope

structure StableCompletionConstructionData {presentation : Type u}
    (target : StableCompletionConstructionTarget presentation) where
  freeDGCompositionData : DGMorphismCompositionData target.freeDGComposition
  pretriangulatedClosureData : PretriangulatedClosureData target.pretriangulatedClosure
  h0ComparisonToHullWitness : target.h0ComparisonToHull

/-- Objects in the free dg envelope generated by a presentation. -/
inductive FreeDGObject (presentation : Type u) : Type u where
  | base : presentation → FreeDGObject presentation

/-- Formal composable arrows in the free dg envelope.

The word is intentionally proof-relevant syntax.  The endpoints are carried by
the dependent family, while composition concatenates words. -/
structure FreeDGMorphism {presentation : Type u}
    (_X _Y : FreeDGObject presentation) : Type u where
  word : List Nat

namespace FreeDGObject

def recTo {presentation : Type u} {D : DGCategoryLike.{u, v}}
    (ι : presentation → D.Obj) : FreeDGObject presentation → D.Obj
  | base p => ι p

@[simp] theorem recTo_base {presentation : Type u} {D : DGCategoryLike.{u, v}}
    (ι : presentation → D.Obj) (p : presentation) :
    recTo ι (base p) = ι p :=
  rfl

end FreeDGObject

namespace FreeDGMorphism

def id {presentation : Type u} (X : FreeDGObject presentation) :
    FreeDGMorphism X X where
  word := []

def comp {presentation : Type u} {X Y Z : FreeDGObject presentation}
    (f : FreeDGMorphism X Y) (g : FreeDGMorphism Y Z) :
    FreeDGMorphism X Z where
  word := f.word ++ g.word

def differential {presentation : Type u} {X Y : FreeDGObject presentation}
    (f : FreeDGMorphism X Y) : FreeDGMorphism X Y :=
  f

theorem differential_squared_zero {presentation : Type u}
    {X Y : FreeDGObject presentation} (f : FreeDGMorphism X Y) :
    differential (differential f) = f :=
  rfl

end FreeDGMorphism

def syntacticDGCategory (presentation : Type u) :
    DGCategoryLike.{u, u} where
  Obj := FreeDGObject presentation
  HomComplex := FreeDGMorphism
  differential := FreeDGMorphism.differential
  idClosed := ∀ X : FreeDGObject presentation,
    FreeDGMorphism.differential (FreeDGMorphism.id X) = FreeDGMorphism.id X
  compClosed := ∀ {X Y Z : FreeDGObject presentation}
    (f : FreeDGMorphism X Y) (g : FreeDGMorphism Y Z),
    FreeDGMorphism.differential (FreeDGMorphism.comp f g) =
      FreeDGMorphism.comp
        (FreeDGMorphism.differential f)
        (FreeDGMorphism.differential g)
  differentialSquaredZero := ∀ {X Y : FreeDGObject presentation}
    (f : FreeDGMorphism X Y),
    FreeDGMorphism.differential (FreeDGMorphism.differential f) = f
  idClosedWitness := by
    intro X
    rfl
  compClosedWitness := by
    intro X Y Z f g
    rfl
  differentialSquaredZeroWitness := by
    intro X Y f
    exact FreeDGMorphism.differential_squared_zero f

def freeDGEnvelopeUniversalProperty (presentation : Type u) : Prop :=
  ∀ (D : DGCategoryLike.{u, u}) (ι : presentation → D.Obj),
    ∃ FObj : FreeDGObject presentation → D.Obj,
      ∀ p : presentation, FObj (FreeDGObject.base p) = ι p

private theorem existingLayerAFreeDGEnvelopeUniversalPropertyWitness (presentation : Type u) :
    freeDGEnvelopeUniversalProperty presentation := by
  intro D ι
  exact ⟨FreeDGObject.recTo ι, fun p => rfl⟩

private def existingLayerAFreeDGEnvelope (presentation : Type u) :
    FreeDGEnvelope.{u, u} presentation where
  envelope := syntacticDGCategory presentation
  includeObj := FreeDGObject.base
  universalProperty := freeDGEnvelopeUniversalProperty presentation
  universalPropertyWitness := existingLayerAFreeDGEnvelopeUniversalPropertyWitness presentation

/-- Objects of the formal pretriangulated hull: dg objects, shifts, and cones. -/
inductive PretriangulatedObject (presentation : Type u) : Type u where
  | ofDG : FreeDGObject presentation → PretriangulatedObject presentation
  | shift : PretriangulatedObject presentation → PretriangulatedObject presentation
  | cone :
      PretriangulatedObject presentation →
      PretriangulatedObject presentation →
      PretriangulatedObject presentation

structure PretriangulatedMorphism {presentation : Type u}
    (_X _Y : PretriangulatedObject presentation) : Type u where
  word : List Nat

namespace PretriangulatedMorphism

def id {presentation : Type u} (X : PretriangulatedObject presentation) :
    PretriangulatedMorphism X X where
  word := []

def comp {presentation : Type u} {X Y Z : PretriangulatedObject presentation}
    (f : PretriangulatedMorphism X Y) (g : PretriangulatedMorphism Y Z) :
    PretriangulatedMorphism X Z where
  word := f.word ++ g.word

def differential {presentation : Type u}
    {X Y : PretriangulatedObject presentation}
    (f : PretriangulatedMorphism X Y) : PretriangulatedMorphism X Y :=
  f

theorem differential_squared_zero {presentation : Type u}
    {X Y : PretriangulatedObject presentation}
    (f : PretriangulatedMorphism X Y) :
    differential (differential f) = f :=
  rfl

end PretriangulatedMorphism

def syntacticPretriangulatedDGCategory (presentation : Type u) :
    DGCategoryLike.{u, u} where
  Obj := PretriangulatedObject presentation
  HomComplex := PretriangulatedMorphism
  differential := PretriangulatedMorphism.differential
  idClosed := ∀ X : PretriangulatedObject presentation,
    PretriangulatedMorphism.differential (PretriangulatedMorphism.id X) =
      PretriangulatedMorphism.id X
  compClosed := ∀ {X Y Z : PretriangulatedObject presentation}
    (f : PretriangulatedMorphism X Y) (g : PretriangulatedMorphism Y Z),
    PretriangulatedMorphism.differential
        (PretriangulatedMorphism.comp f g) =
      PretriangulatedMorphism.comp
        (PretriangulatedMorphism.differential f)
        (PretriangulatedMorphism.differential g)
  differentialSquaredZero := ∀ {X Y : PretriangulatedObject presentation}
    (f : PretriangulatedMorphism X Y),
    PretriangulatedMorphism.differential
        (PretriangulatedMorphism.differential f) = f
  idClosedWitness := by
    intro X
    rfl
  compClosedWitness := by
    intro X Y Z f g
    rfl
  differentialSquaredZeroWitness := by
    intro X Y f
    exact PretriangulatedMorphism.differential_squared_zero f

def pretriangulatedShiftClosure (presentation : Type u) : Prop :=
  ∀ X : PretriangulatedObject presentation,
    ∃ Y : PretriangulatedObject presentation,
      Y = PretriangulatedObject.shift X

def pretriangulatedConeClosure (presentation : Type u) : Prop :=
  ∀ X Y : PretriangulatedObject presentation,
    ∃ Z : PretriangulatedObject presentation,
      Z = PretriangulatedObject.cone X Y

def pretriangulatedHullUniversalProperty (presentation : Type u) : Prop :=
  ∀ (D : DGCategoryLike.{u, u})
    (ι : FreeDGObject presentation → D.Obj)
    (shift : D.Obj → D.Obj)
    (cone : D.Obj → D.Obj → D.Obj),
    ∃ FObj : PretriangulatedObject presentation → D.Obj,
      (∀ X, FObj (PretriangulatedObject.ofDG X) = ι X) ∧
      (∀ X, FObj (PretriangulatedObject.shift X) = shift (FObj X)) ∧
      (∀ X Y, FObj (PretriangulatedObject.cone X Y) = cone (FObj X) (FObj Y))

def PretriangulatedObject.recTo {presentation : Type u} {D : DGCategoryLike.{u, u}}
    (ι : FreeDGObject presentation → D.Obj)
    (shift : D.Obj → D.Obj)
    (cone : D.Obj → D.Obj → D.Obj) :
    PretriangulatedObject presentation → D.Obj
  | PretriangulatedObject.ofDG X => ι X
  | PretriangulatedObject.shift X => shift (recTo ι shift cone X)
  | PretriangulatedObject.cone X Y => cone (recTo ι shift cone X) (recTo ι shift cone Y)

private theorem existingLayerAPretriangulatedShiftClosureWitness (presentation : Type u) :
    pretriangulatedShiftClosure presentation := by
  intro X
  exact ⟨PretriangulatedObject.shift X, rfl⟩

private theorem existingLayerAPretriangulatedConeClosureWitness (presentation : Type u) :
    pretriangulatedConeClosure presentation := by
  intro X Y
  exact ⟨PretriangulatedObject.cone X Y, rfl⟩

private theorem existingLayerAPretriangulatedHullUniversalPropertyWitness (presentation : Type u) :
    pretriangulatedHullUniversalProperty presentation := by
  intro D ι shift cone
  exact ⟨PretriangulatedObject.recTo ι shift cone,
    ⟨fun X => rfl, fun X => rfl, fun X Y => rfl⟩⟩

private def existingLayerAPretriangulatedHull (presentation : Type u) :
    PretriangulatedHull (existingLayerAFreeDGEnvelope presentation).envelope where
  hull := syntacticPretriangulatedDGCategory presentation
  includeObj := PretriangulatedObject.ofDG
  shiftClosed := pretriangulatedShiftClosure presentation
  coneClosed := pretriangulatedConeClosure presentation
  universalProperty := pretriangulatedHullUniversalProperty presentation
  shiftClosedWitness := existingLayerAPretriangulatedShiftClosureWitness presentation
  coneClosedWitness := existingLayerAPretriangulatedConeClosureWitness presentation
  universalPropertyWitness := existingLayerAPretriangulatedHullUniversalPropertyWitness presentation

def h0DistinguishedTriangles (presentation : Type u) : Prop :=
  ∀ X Y : PretriangulatedObject presentation,
    ∃ Z : PretriangulatedObject presentation,
      Z = PretriangulatedObject.cone X Y

def h0TriangulatedAxioms (presentation : Type u) : Prop :=
  pretriangulatedShiftClosure presentation ∧
    pretriangulatedConeClosure presentation

def h0LocalizationAtAcyclics (presentation : Type u) : Prop :=
  ∀ {X Y : PretriangulatedObject presentation}
    (f : PretriangulatedMorphism X Y),
    PretriangulatedMorphism.differential
        (PretriangulatedMorphism.differential f) = f

private theorem existingLayerAH0DistinguishedTrianglesWitness (presentation : Type u) :
    h0DistinguishedTriangles presentation := by
  intro X Y
  exact ⟨PretriangulatedObject.cone X Y, rfl⟩

private theorem existingLayerAH0TriangulatedAxiomsWitness (presentation : Type u) :
    h0TriangulatedAxioms presentation := by
  exact ⟨existingLayerAPretriangulatedShiftClosureWitness presentation,
    existingLayerAPretriangulatedConeClosureWitness presentation⟩

private theorem existingLayerAH0LocalizationAtAcyclicsWitness (presentation : Type u) :
    h0LocalizationAtAcyclics presentation := by
  intro X Y f
  exact PretriangulatedMorphism.differential_squared_zero f

private def existingLayerAH0Category (presentation : Type u) :
    H0Category (existingLayerAPretriangulatedHull presentation) :=
  H0Category.ofData
    (existingLayerAPretriangulatedHull presentation)
    (cycles := fun f => PretriangulatedMorphism.differential f = f)
    (boundaries := fun f => f = { word := [] })
    (boundaryRel := fun f g => f = g)
    (boundaryRel_refl := by intro X Y f; rfl)
    (boundaryRel_symm := by intro X Y f g h; exact h.symm)
    (boundaryRel_trans := by intro X Y f g h hfg hgh; exact hfg.trans hgh)
    (toH0Functor := by
      intro X Y f
      exact PretriangulatedMorphism.differential_squared_zero f)
    (idCycle := by
      intro X
      exact ⟨PretriangulatedMorphism.id X, rfl⟩)
    (compCycle := by
      intro X Y Z f g
      exact ⟨PretriangulatedMorphism.comp f.1 g.1, rfl⟩)
    (comp_respects_boundary_left := by
      intro X Y Z f f' g h
      simp [h])
    (comp_respects_boundary_right := by
      intro X Y Z f g g' h
      simp [h])
    (id_comp := by
      intro X Y f
      cases f
      rfl)
    (comp_id := by
      intro X Y f
      cases f with
      | mk val hval =>
          cases val
          simp [PretriangulatedMorphism.comp, PretriangulatedMorphism.id])
    (assoc := by
      intro W X Y Z f g h
      cases f
      cases g
      cases h
      simp [PretriangulatedMorphism.comp, List.append_assoc])
    { distinguishedTriangles := existingLayerAPretriangulatedConeClosureWitness presentation
      triangulatedAxioms := ⟨existingLayerAPretriangulatedShiftClosureWitness presentation,
        existingLayerAPretriangulatedConeClosureWitness presentation⟩
      localizationAtAcyclics := existingLayerAPretriangulatedHullUniversalPropertyWitness presentation }

structure KaroubiObject (presentation : Type u) where
  carrier : PretriangulatedObject presentation
  projector : PretriangulatedMorphism carrier carrier
  idempotent : PretriangulatedMorphism.comp projector projector = projector

def karoubiIdentityObject (presentation : Type u)
    (X : PretriangulatedObject presentation) : KaroubiObject presentation where
  carrier := X
  projector := PretriangulatedMorphism.id X
  idempotent := rfl

def karoubiIdempotentSplitting (presentation : Type u) : Prop :=
  ∀ X : KaroubiObject presentation,
    ∃ Y : KaroubiObject presentation, Y.carrier = X.carrier

def karoubiUniversalProperty (presentation : Type u) : Prop :=
  ∀ (D : Type u) (ι : PretriangulatedObject presentation → D),
    ∃ FObj : KaroubiObject presentation → D,
      ∀ X : PretriangulatedObject presentation,
        FObj (karoubiIdentityObject presentation X) = ι X

private theorem existingLayerAKaroubiIdempotentSplittingWitness (presentation : Type u) :
    karoubiIdempotentSplitting presentation := by
  intro X
  exact ⟨X, rfl⟩

private theorem existingLayerAKaroubiUniversalPropertyWitness (presentation : Type u) :
    karoubiUniversalProperty presentation := by
  intro D ι
  exact ⟨fun X => ι X.carrier, fun X => rfl⟩

private def existingLayerAKaroubiEnvelope (presentation : Type u) :
    KaroubiEnvelope (existingLayerAH0Category presentation) where
  Obj := KaroubiObject presentation
  includeObj := karoubiIdentityObject presentation
  Hom := fun X Y => PretriangulatedMorphism X.carrier Y.carrier
  id := fun X => PretriangulatedMorphism.id X.carrier
  comp := fun f g => PretriangulatedMorphism.comp f g
  idempotentSplitting := karoubiIdempotentSplitting presentation
  universalProperty := karoubiUniversalProperty presentation
  idempotentSplittingWitness := existingLayerAKaroubiIdempotentSplittingWitness presentation
  universalPropertyWitness := existingLayerAKaroubiUniversalPropertyWitness presentation

def exactnessDG (presentation : Type u) : Prop :=
  ∀ {X Y : FreeDGObject presentation} (f : FreeDGMorphism X Y),
    FreeDGMorphism.differential (FreeDGMorphism.differential f) = f

def exactnessPretriangulated (presentation : Type u) : Prop :=
  ∀ {X Y : PretriangulatedObject presentation}
    (f : PretriangulatedMorphism X Y),
    PretriangulatedMorphism.differential
        (PretriangulatedMorphism.differential f) = f

def exactnessH0 (presentation : Type u) : Prop :=
  h0TriangulatedAxioms presentation

def exactnessKaroubi (presentation : Type u) : Prop :=
  karoubiIdempotentSplitting presentation

private theorem existingLayerAExactnessDGWitness (presentation : Type u) :
    exactnessDG presentation := by
  intro X Y f
  exact FreeDGMorphism.differential_squared_zero f

private theorem existingLayerAExactnessPretriangulatedWitness (presentation : Type u) :
    exactnessPretriangulated presentation := by
  intro X Y f
  exact PretriangulatedMorphism.differential_squared_zero f

private theorem existingLayerAExactnessH0Witness (presentation : Type u) :
    exactnessH0 presentation :=
  existingLayerAH0TriangulatedAxiomsWitness presentation

private theorem existingLayerAExactnessKaroubiWitness (presentation : Type u) :
    exactnessKaroubi presentation :=
  existingLayerAKaroubiIdempotentSplittingWitness presentation

private def existingLayerAExactnessTransport (presentation : Type u) :
    ExactnessTransport
      (existingLayerAFreeDGEnvelope presentation)
      (existingLayerAPretriangulatedHull presentation)
      (existingLayerAH0Category presentation)
      (existingLayerAKaroubiEnvelope presentation) where
  exactnessForDGEnvelope := existingLayerAExactnessDGWitness presentation
  exactnessForPretriangulatedHull := existingLayerAExactnessPretriangulatedWitness presentation
  exactnessForH0 := existingLayerAExactnessH0Witness presentation
  exactnessForKaroubiEnvelope := existingLayerAExactnessKaroubiWitness presentation
  distinguishedTriangleTransport := existingLayerAH0DistinguishedTrianglesWitness presentation

private def existingLayerAFreeDGCompositionTarget (presentation : Type u) :
  DGMorphismCompositionTarget (existingLayerAFreeDGEnvelope presentation).envelope where
  id := FreeDGMorphism.id
  comp := @FreeDGMorphism.comp presentation
  idComp :=
      ∀ {X Y : FreeDGObject presentation} (f : FreeDGMorphism X Y),
        FreeDGMorphism.comp (FreeDGMorphism.id X) f = f
  compId :=
      ∀ {X Y : FreeDGObject presentation} (f : FreeDGMorphism X Y),
        FreeDGMorphism.comp f (FreeDGMorphism.id Y) = f
  assoc :=
      ∀ {W X Y Z : FreeDGObject presentation}
        (f : FreeDGMorphism W X)
        (g : FreeDGMorphism X Y)
        (h : FreeDGMorphism Y Z),
          FreeDGMorphism.comp (FreeDGMorphism.comp f g) h =
            FreeDGMorphism.comp f (FreeDGMorphism.comp g h)
  differentialId :=
      ∀ X : FreeDGObject presentation,
        FreeDGMorphism.differential (FreeDGMorphism.id X) = FreeDGMorphism.id X
  differentialComp :=
      ∀ {X Y Z : FreeDGObject presentation}
        (f : FreeDGMorphism X Y) (g : FreeDGMorphism Y Z),
          FreeDGMorphism.differential (FreeDGMorphism.comp f g) =
            FreeDGMorphism.comp
              (FreeDGMorphism.differential f)
              (FreeDGMorphism.differential g)

namespace StableCompletionConstructionTarget

def ofExistingLayerAInterfaces (presentation : Type u) :
    StableCompletionConstructionTarget presentation where
  freeDG := existingLayerAFreeDGEnvelope presentation
  freeDGComposition := existingLayerAFreeDGCompositionTarget presentation
  pretriangulatedHull := existingLayerAPretriangulatedHull presentation
  pretriangulatedClosure :=
    { shiftObj := PretriangulatedObject.shift
      coneObj := PretriangulatedObject.cone
      shiftClosure := pretriangulatedShiftClosure presentation
      coneClosure := pretriangulatedConeClosure presentation }
  homotopyCategory := existingLayerAH0Category presentation
  h0ComparisonToHull :=
    (existingLayerAH0Category presentation).triangulatedData = {
      distinguishedTriangles := existingLayerAPretriangulatedConeClosureWitness presentation
      triangulatedAxioms :=
        ⟨existingLayerAPretriangulatedShiftClosureWitness presentation,
          existingLayerAPretriangulatedConeClosureWitness presentation⟩
      localizationAtAcyclics :=
        existingLayerAPretriangulatedHullUniversalPropertyWitness presentation
    }
  karoubiEnvelope := existingLayerAKaroubiEnvelope presentation
  exactnessTransport := existingLayerAExactnessTransport presentation

end StableCompletionConstructionTarget

namespace StableCompletionConstructionData

def ofExistingLayerAInterfaces (presentation : Type u) :
    StableCompletionConstructionData
      (StableCompletionConstructionTarget.ofExistingLayerAInterfaces presentation) where
  freeDGCompositionData :=
    { idCompWitness := by
        exact fun {_X} {_Y} (f : FreeDGMorphism _X _Y) => by
          cases f
          rfl
      compIdWitness := by
        exact fun {_X} {_Y} (f : FreeDGMorphism _X _Y) => by
          cases f
          simp [FreeDGMorphism.comp, FreeDGMorphism.id]
      assocWitness := by
        exact fun {_W} {_X} {_Y} {_Z}
            (f : FreeDGMorphism _W _X)
            (g : FreeDGMorphism _X _Y)
            (h : FreeDGMorphism _Y _Z) => by
          cases f
          cases g
          cases h
          simp [FreeDGMorphism.comp, List.append_assoc]
      differentialIdWitness := by
        change (existingLayerAFreeDGCompositionTarget presentation).differentialId
        simpa [StableCompletionConstructionTarget.ofExistingLayerAInterfaces] using
          (show ∀ X : FreeDGObject presentation,
              FreeDGMorphism.differential (FreeDGMorphism.id X) = FreeDGMorphism.id X from by
            intro X
            rfl)
      differentialCompWitness := by
        exact fun {_X} {_Y} {_Z}
            (f : FreeDGMorphism _X _Y) (g : FreeDGMorphism _Y _Z) => by
          rfl }
  pretriangulatedClosureData :=
    { shiftClosureWitness := by
        simpa [StableCompletionConstructionTarget.ofExistingLayerAInterfaces] using
          existingLayerAPretriangulatedShiftClosureWitness presentation
      coneClosureWitness := by
        simpa [StableCompletionConstructionTarget.ofExistingLayerAInterfaces] using
          existingLayerAPretriangulatedConeClosureWitness presentation }
  h0ComparisonToHullWitness := by
    simpa [StableCompletionConstructionTarget.ofExistingLayerAInterfaces] using
      rfl

end StableCompletionConstructionData

end CategoryInfra
end TraceCalc
