import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Presheaves.IntervalLocalization.HomotopyEquivalences.Owner

/-!
# Interval-local objects

This file owns objects local with respect to interval homotopy equivalences.
Tate stabilization is downstream from this interval-local layer.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/--
Interval-locality data for a descent-local analytic presheaf.  It records the
homotopy-equivalence datum generated by the interval calculus.
-/
structure IntervalLocalObject
    (F : DescentLocalAnalyticPresheaf) where
  intervalEquivalence : PresheafIntervalHomotopyEquivalence F

namespace IntervalLocalObject

/-- The interval homotopy equivalence carried by interval-locality data. -/
def equivalence {F : DescentLocalAnalyticPresheaf}
    (L : IntervalLocalObject F) :
    PresheafIntervalHomotopyEquivalence F :=
  L.intervalEquivalence

/-- The interval object carried by interval-locality data. -/
def intervalObject {F : DescentLocalAnalyticPresheaf}
    (L : IntervalLocalObject F) :
    PresheafIntervalObject F :=
  L.intervalEquivalence.intervalObject

/-- The left endpoint correspondence carried by interval-locality data. -/
def leftEndpoint {F : DescentLocalAnalyticPresheaf}
    (L : IntervalLocalObject F) :
    RationalContourHom
      L.intervalEquivalence.source
      L.intervalEquivalence.target :=
  L.intervalEquivalence.left

/-- The right endpoint correspondence carried by interval-locality data. -/
def rightEndpoint {F : DescentLocalAnalyticPresheaf}
    (L : IntervalLocalObject F) :
    RationalContourHom
      L.intervalEquivalence.source
      L.intervalEquivalence.target :=
  L.intervalEquivalence.right

/-- The endpoint pullbacks carried by interval-locality data agree. -/
theorem endpoint_pullbacks_agree {F : DescentLocalAnalyticPresheaf}
    (L : IntervalLocalObject F) :
    L.intervalEquivalence.leftPullback =
      L.intervalEquivalence.rightPullback :=
  L.intervalEquivalence.pullbacks_agree

end IntervalLocalObject

/--
Interval-locality data for a functorial descent-local analytic presheaf.  The
interval equivalence calculus is inherited from the forgotten descent-local
object, while functorial transfer laws are retained upstream.
-/
structure FunctorialIntervalLocalObject
    (F : FunctorialDescentLocalAnalyticPresheaf) where
  localObject : IntervalLocalObject F.forget

namespace FunctorialIntervalLocalObject

/-- The underlying interval-locality data after forgetting functorial transfer laws. -/
def underlying {F : FunctorialDescentLocalAnalyticPresheaf}
    (L : FunctorialIntervalLocalObject F) :
    IntervalLocalObject F.forget :=
  L.localObject

/-- The interval homotopy equivalence carried by functorial interval-locality data. -/
def equivalence {F : FunctorialDescentLocalAnalyticPresheaf}
    (L : FunctorialIntervalLocalObject F) :
    PresheafIntervalHomotopyEquivalence F.forget :=
  L.localObject.equivalence

/-- The endpoint pullbacks carried by functorial interval-locality data agree. -/
theorem endpoint_pullbacks_agree
    {F : FunctorialDescentLocalAnalyticPresheaf}
    (L : FunctorialIntervalLocalObject F) :
    L.equivalence.leftPullback = L.equivalence.rightPullback :=
  L.localObject.endpoint_pullbacks_agree

end FunctorialIntervalLocalObject

end AnalyticMotives
end LFunctions
end Boundary
