import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceRewrite.Generators.Owner

/-!
# Rewrite paths

This file owns finite paths in the higher-computadic trace calculus.

A path is the syntactic trace of a computation: identity, one certified
generator, or concatenation.  Analytic soundness is supplied later by
residue-channel certificates.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A finite directed path of analytic trace rewrites. -/
inductive TraceRewritePath where
  | identity (expression : QTraceExpression)
  | step (generator : TraceRewriteGenerator)
  | concat (first second : TraceRewritePath)
  deriving Repr

/-- The identity rewrite path on a Q-linear trace expression. -/
def TraceRewritePath.id (expression : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.identity expression

/-- The one-step rewrite path generated by a rewrite generator. -/
def TraceRewritePath.ofGenerator
    (generator : TraceRewriteGenerator) : TraceRewritePath :=
  TraceRewritePath.step generator

/-- Concatenate two rewrite paths. -/
def TraceRewritePath.comp
    (first second : TraceRewritePath) : TraceRewritePath :=
  TraceRewritePath.concat first second

/-- The source expression read from a raw rewrite path. -/
def TraceRewritePath.source : TraceRewritePath → QTraceExpression
  | identity expression => expression
  | step generator => generator.source
  | concat first _ => first.source

/-- The target expression read from a raw rewrite path. -/
def TraceRewritePath.target : TraceRewritePath → QTraceExpression
  | identity expression => expression
  | step generator => generator.target
  | concat _ second => second.target

end AnalyticMotives
end LFunctions
end Boundary
