import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceRewrite.Generators.Owner

/-!
# Rewrite paths

This file owns finite paths in the higher-computadic trace calculus.

A path is the syntactic trace of a computation: identity, one certified
generator, or concatenation.  Residue-channel certificates record the analytic
soundness payload attached to these paths.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A finite directed path of analytic trace rewrites. -/
inductive TraceRewritePath where
  | identity (expression : QTraceExpression)
  | step (generator : TraceRewriteGenerator)
  | concat (first second : TraceRewritePath)
  deriving Repr

/-- The identity rewrite path on a Q-linear trace expression. -/
def TraceRewritePath.id (expression : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.identity expression

/-- The one-step rewrite path generated by a rewrite generator. -/
def TraceRewritePath.ofGenerator
    (generator : TraceRewriteGenerator) : TraceRewritePath :=
  TraceRewritePath.step generator

/-- The one-step Stokes rewrite path. -/
def TraceRewritePath.stokes
    (source target : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.ofGenerator
    (TraceRewriteGenerator.stokes source target)

/-- The one-step residue rewrite path. -/
def TraceRewritePath.residue
    (source target : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.ofGenerator
    (TraceRewriteGenerator.residue source target)

/-- The one-step channel rewrite path. -/
def TraceRewritePath.channel
    (source target : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.ofGenerator
    (TraceRewriteGenerator.channel source target)

/-- The one-step refinement rewrite path. -/
def TraceRewritePath.refinement
    (source target : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.ofGenerator
    (TraceRewriteGenerator.refinement source target)

/-- The one-step schedule rewrite path. -/
def TraceRewritePath.schedule
    (source target : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.ofGenerator
    (TraceRewriteGenerator.schedule source target)

/-- The one-step weight-drop rewrite path. -/
def TraceRewritePath.weightDrop
    (source target : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.ofGenerator
    (TraceRewriteGenerator.weightDrop source target)

/-- The one-step Fubini rewrite path. -/
def TraceRewritePath.fubini
    (source target : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.ofGenerator
    (TraceRewriteGenerator.fubini source target)

/-- Concatenate two rewrite paths. -/
def TraceRewritePath.comp
    (first second : TraceRewritePath) : TraceRewritePath :=
  TraceRewritePath.concat first second

/-- The source expression read from a raw rewrite path. -/
def TraceRewritePath.source : TraceRewritePath → QTraceExpression
  | identity expression => expression
  | step generator => generator.source
  | concat first _ => first.source

/-- The target expression read from a raw rewrite path. -/
def TraceRewritePath.target : TraceRewritePath → QTraceExpression
  | identity expression => expression
  | step generator => generator.target
  | concat _ second => second.target

/-- The number of one-step rewrite generators occurring in a rewrite path. -/
def TraceRewritePath.stepCount : TraceRewritePath → Nat
  | identity _ => 0
  | step _ => 1
  | concat first second => first.stepCount + second.stepCount

/-- An identity rewrite path has no one-step generators. -/
theorem TraceRewritePath.id_stepCount
    (expression : QTraceExpression) :
    (TraceRewritePath.id expression).stepCount =
      0 :=
  rfl

/-- A one-step rewrite path has exactly one generator. -/
theorem TraceRewritePath.ofGenerator_stepCount
    (generator : TraceRewriteGenerator) :
    (TraceRewritePath.ofGenerator generator).stepCount =
      1 :=
  rfl

/-- Concatenating rewrite paths adds their generator counts. -/
theorem TraceRewritePath.comp_stepCount
    (first second : TraceRewritePath) :
    (TraceRewritePath.comp first second).stepCount =
      first.stepCount + second.stepCount :=
  rfl

/-- The source of an identity path is its expression. -/
theorem TraceRewritePath.id_source
    (expression : QTraceExpression) :
    (TraceRewritePath.id expression).source =
      expression :=
  rfl

/-- The target of an identity path is its expression. -/
theorem TraceRewritePath.id_target
    (expression : QTraceExpression) :
    (TraceRewritePath.id expression).target =
      expression :=
  rfl

/-- The source of a one-step path is the generator source. -/
theorem TraceRewritePath.ofGenerator_source
    (generator : TraceRewriteGenerator) :
    (TraceRewritePath.ofGenerator generator).source =
      generator.source :=
  rfl

/-- The target of a one-step path is the generator target. -/
theorem TraceRewritePath.ofGenerator_target
    (generator : TraceRewriteGenerator) :
    (TraceRewritePath.ofGenerator generator).target =
      generator.target :=
  rfl

/-- A one-step Stokes path has the supplied source. -/
theorem TraceRewritePath.stokes_source
    (source target : QTraceExpression) :
    (TraceRewritePath.stokes source target).source =
      source :=
  rfl

/-- A one-step Stokes path has the supplied target. -/
theorem TraceRewritePath.stokes_target
    (source target : QTraceExpression) :
    (TraceRewritePath.stokes source target).target =
      target :=
  rfl

/-- A one-step Stokes path has one rewrite step. -/
theorem TraceRewritePath.stokes_stepCount
    (source target : QTraceExpression) :
    (TraceRewritePath.stokes source target).stepCount =
      1 :=
  rfl

/-- A one-step residue path has the supplied source. -/
theorem TraceRewritePath.residue_source
    (source target : QTraceExpression) :
    (TraceRewritePath.residue source target).source =
      source :=
  rfl

/-- A one-step residue path has the supplied target. -/
theorem TraceRewritePath.residue_target
    (source target : QTraceExpression) :
    (TraceRewritePath.residue source target).target =
      target :=
  rfl

/-- A one-step residue path has one rewrite step. -/
theorem TraceRewritePath.residue_stepCount
    (source target : QTraceExpression) :
    (TraceRewritePath.residue source target).stepCount =
      1 :=
  rfl

/-- A one-step channel path has the supplied source. -/
theorem TraceRewritePath.channel_source
    (source target : QTraceExpression) :
    (TraceRewritePath.channel source target).source =
      source :=
  rfl

/-- A one-step channel path has the supplied target. -/
theorem TraceRewritePath.channel_target
    (source target : QTraceExpression) :
    (TraceRewritePath.channel source target).target =
      target :=
  rfl

/-- A one-step channel path has one rewrite step. -/
theorem TraceRewritePath.channel_stepCount
    (source target : QTraceExpression) :
    (TraceRewritePath.channel source target).stepCount =
      1 :=
  rfl

/-- A one-step refinement path has the supplied source. -/
theorem TraceRewritePath.refinement_source
    (source target : QTraceExpression) :
    (TraceRewritePath.refinement source target).source =
      source :=
  rfl

/-- A one-step refinement path has the supplied target. -/
theorem TraceRewritePath.refinement_target
    (source target : QTraceExpression) :
    (TraceRewritePath.refinement source target).target =
      target :=
  rfl

/-- A one-step refinement path has one rewrite step. -/
theorem TraceRewritePath.refinement_stepCount
    (source target : QTraceExpression) :
    (TraceRewritePath.refinement source target).stepCount =
      1 :=
  rfl

/-- A one-step schedule path has the supplied source. -/
theorem TraceRewritePath.schedule_source
    (source target : QTraceExpression) :
    (TraceRewritePath.schedule source target).source =
      source :=
  rfl

/-- A one-step schedule path has the supplied target. -/
theorem TraceRewritePath.schedule_target
    (source target : QTraceExpression) :
    (TraceRewritePath.schedule source target).target =
      target :=
  rfl

/-- A one-step schedule path has one rewrite step. -/
theorem TraceRewritePath.schedule_stepCount
    (source target : QTraceExpression) :
    (TraceRewritePath.schedule source target).stepCount =
      1 :=
  rfl

/-- A one-step weight-drop path has the supplied source. -/
theorem TraceRewritePath.weightDrop_source
    (source target : QTraceExpression) :
    (TraceRewritePath.weightDrop source target).source =
      source :=
  rfl

/-- A one-step weight-drop path has the supplied target. -/
theorem TraceRewritePath.weightDrop_target
    (source target : QTraceExpression) :
    (TraceRewritePath.weightDrop source target).target =
      target :=
  rfl

/-- A one-step weight-drop path has one rewrite step. -/
theorem TraceRewritePath.weightDrop_stepCount
    (source target : QTraceExpression) :
    (TraceRewritePath.weightDrop source target).stepCount =
      1 :=
  rfl

/-- A one-step Fubini path has the supplied source. -/
theorem TraceRewritePath.fubini_source
    (source target : QTraceExpression) :
    (TraceRewritePath.fubini source target).source =
      source :=
  rfl

/-- A one-step Fubini path has the supplied target. -/
theorem TraceRewritePath.fubini_target
    (source target : QTraceExpression) :
    (TraceRewritePath.fubini source target).target =
      target :=
  rfl

/-- A one-step Fubini path has one rewrite step. -/
theorem TraceRewritePath.fubini_stepCount
    (source target : QTraceExpression) :
    (TraceRewritePath.fubini source target).stepCount =
      1 :=
  rfl

/-- The source of a concatenated path is the source of the first path. -/
theorem TraceRewritePath.comp_source
    (first second : TraceRewritePath) :
    (TraceRewritePath.comp first second).source =
      first.source :=
  rfl

/-- The target of a concatenated path is the target of the second path. -/
theorem TraceRewritePath.comp_target
    (first second : TraceRewritePath) :
    (TraceRewritePath.comp first second).target =
      second.target :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
