import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceRewrite.Generators.Owner

/-!
# Rewrite paths

This file owns finite paths in the higher-computadic trace calculus.

A path is the syntactic trace of a computation: identity, one certified
generator, or concatenation.  Analytic soundness is supplied later by
residue-channel certificates.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A finite directed path of analytic trace rewrites. -/
inductive TraceRewritePath where
  | identity (expression : QTraceExpression)
  | step (generator : TraceRewriteGenerator)
  | concat (first second : TraceRewritePath)
  deriving Repr

/-- The identity rewrite path on a Q-linear trace expression. -/
def TraceRewritePath.id (expression : QTraceExpression) : TraceRewritePath :=
  TraceRewritePath.identity expression

/-- The one-step rewrite path generated by a rewrite generator. -/
def TraceRewritePath.ofGenerator
    (generator : TraceRewriteGenerator) : TraceRewritePath :=
  TraceRewritePath.step generator

/-- Concatenate two rewrite paths. -/
def TraceRewritePath.comp
    (first second : TraceRewritePath) : TraceRewritePath :=
  TraceRewritePath.concat first second

/-- The source expression read from a raw rewrite path. -/
def TraceRewritePath.source : TraceRewritePath → QTraceExpression
  | identity expression => expression
  | step generator => generator.source
  | concat first _ => first.source

/-- The target expression read from a raw rewrite path. -/
def TraceRewritePath.target : TraceRewritePath → QTraceExpression
  | identity expression => expression
  | step generator => generator.target
  | concat _ second => second.target

/-- The number of one-step rewrite generators occurring in a rewrite path. -/
def TraceRewritePath.stepCount : TraceRewritePath → Nat
  | identity _ => 0
  | step _ => 1
  | concat first second => first.stepCount + second.stepCount

/-- An identity rewrite path has no one-step generators. -/
theorem TraceRewritePath.id_stepCount
    (expression : QTraceExpression) :
    (TraceRewritePath.id expression).stepCount =
      0 :=
  rfl

/-- A one-step rewrite path has exactly one generator. -/
theorem TraceRewritePath.ofGenerator_stepCount
    (generator : TraceRewriteGenerator) :
    (TraceRewritePath.ofGenerator generator).stepCount =
      1 :=
  rfl

/-- Concatenating rewrite paths adds their generator counts. -/
theorem TraceRewritePath.comp_stepCount
    (first second : TraceRewritePath) :
    (TraceRewritePath.comp first second).stepCount =
      first.stepCount + second.stepCount :=
  rfl

/-- The source of an identity path is its expression. -/
theorem TraceRewritePath.id_source
    (expression : QTraceExpression) :
    (TraceRewritePath.id expression).source =
      expression :=
  rfl

/-- The target of an identity path is its expression. -/
theorem TraceRewritePath.id_target
    (expression : QTraceExpression) :
    (TraceRewritePath.id expression).target =
      expression :=
  rfl

/-- The source of a one-step path is the generator source. -/
theorem TraceRewritePath.ofGenerator_source
    (generator : TraceRewriteGenerator) :
    (TraceRewritePath.ofGenerator generator).source =
      generator.source :=
  rfl

/-- The target of a one-step path is the generator target. -/
theorem TraceRewritePath.ofGenerator_target
    (generator : TraceRewriteGenerator) :
    (TraceRewritePath.ofGenerator generator).target =
      generator.target :=
  rfl

/-- The source of a concatenated path is the source of the first path. -/
theorem TraceRewritePath.comp_source
    (first second : TraceRewritePath) :
    (TraceRewritePath.comp first second).source =
      first.source :=
  rfl

/-- The target of a concatenated path is the target of the second path. -/
theorem TraceRewritePath.comp_target
    (first second : TraceRewritePath) :
    (TraceRewritePath.comp first second).target =
      second.target :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
