import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Inputs.ByKind.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.InvertedInputs.ByKind.Owner

/-!
# Named input-level localized isomorphisms by kind

This file connects the input-level localized-isomorphism facade with the
earlier named by-kind isomorphisms.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The input-level localized isomorphism generated by a descent-channel input. -/
def TraceLocalizationInput.descentChannelLocalizedIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentChannel source target).localizedSourceObject
      (TraceLocalizationInput.descentChannel source target).localizedTargetObject :=
  (TraceLocalizationInput.descentChannel source target).localizedIso

/-- The input-level localized isomorphism generated by a descent-refinement input. -/
def TraceLocalizationInput.descentRefinementLocalizedIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentRefinement source target).localizedSourceObject
      (TraceLocalizationInput.descentRefinement source target).localizedTargetObject :=
  (TraceLocalizationInput.descentRefinement source target).localizedIso

/-- The input-level localized isomorphism generated by a descent-schedule input. -/
def TraceLocalizationInput.descentScheduleLocalizedIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentSchedule source target).localizedSourceObject
      (TraceLocalizationInput.descentSchedule source target).localizedTargetObject :=
  (TraceLocalizationInput.descentSchedule source target).localizedIso

/-- The input-level localized isomorphism generated by an interval-Stokes input. -/
def TraceLocalizationInput.intervalStokesLocalizedIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalStokes source target).localizedSourceObject
      (TraceLocalizationInput.intervalStokes source target).localizedTargetObject :=
  (TraceLocalizationInput.intervalStokes source target).localizedIso

/-- The input-level localized isomorphism generated by an interval-Fubini input. -/
def TraceLocalizationInput.intervalFubiniLocalizedIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalFubini source target).localizedSourceObject
      (TraceLocalizationInput.intervalFubini source target).localizedTargetObject :=
  (TraceLocalizationInput.intervalFubini source target).localizedIso

/-- The input-level localized isomorphism generated by a Tate-weight-drop input. -/
def TraceLocalizationInput.tateWeightDropLocalizedIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject
      (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject :=
  (TraceLocalizationInput.tateWeightDrop source target).localizedIso

/-- The input-level descent-channel isomorphism is the by-kind localized-word isomorphism. -/
theorem TraceLocalizationInput.descentChannelLocalizedIso_eq_descentChannelIso
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentChannelLocalizedIso source target =
      TraceLocalizationInput.descentChannelIso source target :=
  rfl

/-- The input-level descent-refinement isomorphism is the by-kind localized-word isomorphism. -/
theorem TraceLocalizationInput.descentRefinementLocalizedIso_eq_descentRefinementIso
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentRefinementLocalizedIso source target =
      TraceLocalizationInput.descentRefinementIso source target :=
  rfl

/-- The input-level descent-schedule isomorphism is the by-kind localized-word isomorphism. -/
theorem TraceLocalizationInput.descentScheduleLocalizedIso_eq_descentScheduleIso
    (source target : QTraceExpression) :
    TraceLocalizationInput.descentScheduleLocalizedIso source target =
      TraceLocalizationInput.descentScheduleIso source target :=
  rfl

/-- The input-level interval-Stokes isomorphism is the by-kind localized-word isomorphism. -/
theorem TraceLocalizationInput.intervalStokesLocalizedIso_eq_intervalStokesIso
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalStokesLocalizedIso source target =
      TraceLocalizationInput.intervalStokesIso source target :=
  rfl

/-- The input-level interval-Fubini isomorphism is the by-kind localized-word isomorphism. -/
theorem TraceLocalizationInput.intervalFubiniLocalizedIso_eq_intervalFubiniIso
    (source target : QTraceExpression) :
    TraceLocalizationInput.intervalFubiniLocalizedIso source target =
      TraceLocalizationInput.intervalFubiniIso source target :=
  rfl

/-- The input-level Tate-weight-drop isomorphism is the by-kind localized-word isomorphism. -/
theorem TraceLocalizationInput.tateWeightDropLocalizedIso_eq_tateWeightDropIso
    (source target : QTraceExpression) :
    TraceLocalizationInput.tateWeightDropLocalizedIso source target =
      TraceLocalizationInput.tateWeightDropIso source target :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
