import Boundary.Realization.AffinePresentation
import Boundary.Realization.AffineSmOver
import Boundary.SmOver
import Mathlib.Algebra.Algebra.Hom
import Mathlib.Algebra.MvPolynomial.Monad
import Mathlib.Analysis.Complex.Basic
import Mathlib.Topology.Algebra.MvPolynomial
import Mathlib.Topology.Sheaves.Presheaf

noncomputable section

open AlgebraicGeometry CategoryTheory

universe u

namespace Boundary
namespace Realization

/-- The common zero set in `ℂⁿ` cut out by a finite family of multivariable polynomials. -/
def finitePolynomialZeroSet {m n : ℕ} (p : Fin m → MvPolynomial (Fin n) ℂ) : Set (Fin n → ℂ) :=
  {z | ∀ i, MvPolynomial.eval z (p i) = 0}

@[simp]
theorem mem_finitePolynomialZeroSet_iff
    {m n : ℕ} (p : Fin m → MvPolynomial (Fin n) ℂ) (z : Fin n → ℂ) :
    z ∈ finitePolynomialZeroSet p ↔ ∀ i, MvPolynomial.eval z (p i) = 0 :=
  Iff.rfl

/-- A finite polynomial zero set in `ℂⁿ` is closed in the Euclidean product topology. -/
theorem isClosed_finitePolynomialZeroSet
    {m n : ℕ} (p : Fin m → MvPolynomial (Fin n) ℂ) :
    IsClosed (finitePolynomialZeroSet p) := by
  classical
  simpa [finitePolynomialZeroSet, Set.setOf_forall] using
    (isClosed_iInter fun i : Fin m =>
      isClosed_eq (MvPolynomial.continuous_eval (p i)) continuous_const)

/-- A tuple of multivariable polynomials defines a map between complex affine spaces. -/
def finitePolynomialMap {m n : ℕ} (q : Fin n → MvPolynomial (Fin m) ℂ) :
    (Fin m → ℂ) → (Fin n → ℂ) :=
  fun z i => MvPolynomial.eval z (q i)

@[simp]
theorem finitePolynomialMap_apply
    {m n : ℕ} (q : Fin n → MvPolynomial (Fin m) ℂ) (z : Fin m → ℂ) (i : Fin n) :
    finitePolynomialMap q z i = MvPolynomial.eval z (q i) :=
  rfl

/-- Polynomial maps between finite-dimensional complex affine spaces are continuous. -/
theorem continuous_finitePolynomialMap
    {m n : ℕ} (q : Fin n → MvPolynomial (Fin m) ℂ) :
    Continuous (finitePolynomialMap q) := by
  exact continuous_pi fun i => MvPolynomial.continuous_eval (q i)

@[simp]
theorem finitePolynomialMap_X
    {n : ℕ} :
    finitePolynomialMap (fun i : Fin n => MvPolynomial.X i) = id := by
  ext z i
  simp [finitePolynomialMap]

@[simp]
theorem finitePolynomialMap_comp
    {m n l : ℕ}
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (u : Fin l → MvPolynomial (Fin n) ℂ)
    (z : Fin m → ℂ) :
    finitePolynomialMap u (finitePolynomialMap q z) =
      finitePolynomialMap (fun i => MvPolynomial.bind₁ q (u i)) z := by
  ext i
  simpa [finitePolynomialMap] using MvPolynomial.eval_assoc q z (u i)

/-- Any polynomial lying in the ideal generated by the defining equations of a zero locus
vanishes at every point of that zero locus. -/
theorem eval_eq_zero_of_mem_span
    {m n : ℕ} {p : Fin m → MvPolynomial (Fin n) ℂ} {z : Fin n → ℂ}
    (hz : z ∈ finitePolynomialZeroSet p) {φ : MvPolynomial (Fin n) ℂ}
    (hφ : φ ∈ Ideal.span (Set.range p)) :
    MvPolynomial.eval z φ = 0 := by
  refine Submodule.span_induction (s := Set.range p)
      (p := fun ψ _ => MvPolynomial.eval z ψ = 0) ?_ ?_ ?_ ?_ hφ
  · intro ψ hψ
    rcases hψ with ⟨i, rfl⟩
    exact hz i
  · simp
  · intro ψ χ _ _ hψ hχ
    simp [MvPolynomial.eval_add, hψ, hχ]
  · intro a ψ _ hψ
    simp [smul_eq_mul, map_mul, hψ]

/-- If each target defining equation pulls back into the source defining ideal, the induced
polynomial map carries the source zero locus into the target zero locus. -/
theorem finitePolynomialMap_mapsTo_zeroSet
    {m n r s : ℕ}
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (t : Fin s → MvPolynomial (Fin n) ℂ)
    (hcompat : ∀ i, MvPolynomial.bind₁ q (t i) ∈ Ideal.span (Set.range p)) :
    Set.MapsTo (finitePolynomialMap q) (finitePolynomialZeroSet p) (finitePolynomialZeroSet t) := by
  intro z hz i
  have hvanish :
      MvPolynomial.eval z (MvPolynomial.bind₁ q (t i)) = 0 :=
    eval_eq_zero_of_mem_span hz (hcompat i)
  have hbind :
      MvPolynomial.eval (finitePolynomialMap q z) (t i) =
        MvPolynomial.eval z (MvPolynomial.bind₁ q (t i)) := by
    change MvPolynomial.eval (fun j => MvPolynomial.eval z (q j)) (t i) =
      MvPolynomial.eval z (MvPolynomial.bind₁ q (t i))
    calc
      MvPolynomial.eval (fun j => MvPolynomial.eval z (q j)) (t i)
          = MvPolynomial.eval z (MvPolynomial.eval₂ MvPolynomial.C q (t i)) := by
              exact (MvPolynomial.eval_assoc q z (t i))
      _ = MvPolynomial.eval z (MvPolynomial.bind₁ q (t i)) := by
            rfl
  exact hbind.trans hvanish

/-- The polynomial map induced by `q` as an actual map between affine complex zero loci,
under the ideal-compatibility condition on the defining equations. -/
def finitePolynomialZeroSetMap
    {m n r s : ℕ}
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (t : Fin s → MvPolynomial (Fin n) ℂ)
    (hcompat : ∀ i, MvPolynomial.bind₁ q (t i) ∈ Ideal.span (Set.range p)) :
    finitePolynomialZeroSet p → finitePolynomialZeroSet t :=
  fun z => ⟨finitePolynomialMap q z.1, finitePolynomialMap_mapsTo_zeroSet p q t hcompat z.2⟩

@[simp]
theorem finitePolynomialZeroSetMap_coe
    {m n r s : ℕ}
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (t : Fin s → MvPolynomial (Fin n) ℂ)
    (hcompat : ∀ i, MvPolynomial.bind₁ q (t i) ∈ Ideal.span (Set.range p))
    (z : finitePolynomialZeroSet p) :
    (finitePolynomialZeroSetMap p q t hcompat z : Fin n → ℂ) = finitePolynomialMap q z := rfl

/-- The induced map between affine complex zero loci is continuous. -/
theorem continuous_finitePolynomialZeroSetMap
    {m n r s : ℕ}
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (t : Fin s → MvPolynomial (Fin n) ℂ)
    (hcompat : ∀ i, MvPolynomial.bind₁ q (t i) ∈ Ideal.span (Set.range p)) :
    Continuous (finitePolynomialZeroSetMap p q t hcompat) := by
  apply Continuous.subtype_mk
  exact (continuous_finitePolynomialMap q).comp continuous_subtype_val

@[simp]
theorem finitePolynomialZeroSetMap_id
    {m r : ℕ}
    (p : Fin r → MvPolynomial (Fin m) ℂ) :
  finitePolynomialZeroSetMap p (fun i : Fin m => MvPolynomial.X i) p
      (fun i => by
        change (MvPolynomial.bind₁ (fun i : Fin m => MvPolynomial.X i)) (p i) ∈
          Ideal.span (Set.range p)
        rw [MvPolynomial.bind₁_X_left]
        exact Ideal.subset_span ⟨i, rfl⟩) = id := by
  ext z i <;> simp [finitePolynomialMap]

theorem finitePolynomialZeroSetMap_comp
    {m n l r s t : ℕ}
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (u : Fin l → MvPolynomial (Fin n) ℂ)
    (v : Fin s → MvPolynomial (Fin n) ℂ)
    (w : Fin t → MvPolynomial (Fin l) ℂ)
    (hq : ∀ i, MvPolynomial.bind₁ q (v i) ∈ Ideal.span (Set.range p))
    (hu : ∀ i, MvPolynomial.bind₁ u (w i) ∈ Ideal.span (Set.range v)) :
    finitePolynomialZeroSetMap v u w hu ∘ finitePolynomialZeroSetMap p q v hq =
      finitePolynomialZeroSetMap p (fun i => MvPolynomial.bind₁ q (u i)) w
        (fun i => by
          have hspan :
              ∀ {φ : MvPolynomial (Fin n) ℂ},
                φ ∈ Ideal.span (Set.range v) →
                  MvPolynomial.bind₁ q φ ∈ Ideal.span (Set.range p) := by
            intro φ hφ
            refine Submodule.span_induction (s := Set.range v)
                (p := fun ψ _ => MvPolynomial.bind₁ q ψ ∈ Ideal.span (Set.range p)) ?_ ?_ ?_ ?_ hφ
            · intro ψ hψ
              rcases hψ with ⟨j, rfl⟩
              exact hq j
            · exact (Ideal.zero_mem (Ideal.span (Set.range p)))
            · intro ψ χ _ _ hψ hχ
              have hmap := map_add (MvPolynomial.bind₁ q) ψ χ
              rw [hmap]
              exact Ideal.add_mem (Ideal.span (Set.range p)) hψ hχ
            · intro a ψ _ hψ
              change MvPolynomial.bind₁ q (a • ψ) ∈ Ideal.span (Set.range p)
              rw [smul_eq_mul, map_mul]
              exact Ideal.mul_mem_left (Ideal.span (Set.range p)) _ hψ
          have hmem : MvPolynomial.bind₁ q (MvPolynomial.bind₁ u (w i)) ∈ Ideal.span (Set.range p) :=
            hspan (hu i)
          change MvPolynomial.bind₁ (fun i => MvPolynomial.bind₁ q (u i)) (w i) ∈
            Ideal.span (Set.range p)
          rw [← MvPolynomial.bind₁_bind₁ (f := u) (g := q) (φ := w i)]
          exact hmem) := by
  ext z i
  change finitePolynomialMap u (finitePolynomialMap q z.1) i =
    finitePolynomialMap (fun i => MvPolynomial.bind₁ q (u i)) z.1 i
  rw [finitePolynomialMap_comp]

/-- Presentation-level pullback identity: if `q` lifts the images of the target coordinate
functions under an affine `ℂ`-algebra map `g`, then substituting `q` and evaluating in `A`
agrees with first evaluating in `B` and then applying `g`. -/
theorem affinePresentation_bind₁_eval
    {m n : ℕ} {A B : Type*} [CommRing A] [CommRing B] [Algebra ℂ A] [Algebra ℂ B]
    (fA : MvPolynomial (Fin m) ℂ →ₐ[ℂ] A)
    (fB : MvPolynomial (Fin n) ℂ →ₐ[ℂ] B)
    (g : B →ₐ[ℂ] A)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (hq : ∀ i, fA (q i) = g (fB (MvPolynomial.X i))) :
    ∀ φ : MvPolynomial (Fin n) ℂ, fA (MvPolynomial.bind₁ q φ) = g (fB φ) := by
  have hhom : fA.comp (MvPolynomial.bind₁ q) = g.comp fB := by
    ext i
    rw [AlgHom.comp_apply, AlgHom.comp_apply, MvPolynomial.bind₁_X_right]
    exact hq i
  intro φ
  exact congrArg (fun h : MvPolynomial (Fin n) ℂ →ₐ[ℂ] A => h φ) hhom

/-- Under the same presentation-level lift data, target kernel elements pull back to source
kernel elements. -/
theorem affinePresentation_bind₁_mem_ker
    {m n : ℕ} {A B : Type*} [CommRing A] [CommRing B] [Algebra ℂ A] [Algebra ℂ B]
    (fA : MvPolynomial (Fin m) ℂ →ₐ[ℂ] A)
    (fB : MvPolynomial (Fin n) ℂ →ₐ[ℂ] B)
    (g : B →ₐ[ℂ] A)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (hq : ∀ i, fA (q i) = g (fB (MvPolynomial.X i)))
    {φ : MvPolynomial (Fin n) ℂ}
    (hφ : φ ∈ RingHom.ker fB.toRingHom) :
    MvPolynomial.bind₁ q φ ∈ RingHom.ker fA.toRingHom := by
  rw [RingHom.mem_ker] at hφ ⊢
  calc
    fA (MvPolynomial.bind₁ q φ) = g (fB φ) := affinePresentation_bind₁_eval fA fB g q hq φ
    _ = 0 := by
      exact (congrArg g hφ).trans (by simp)

/-- For finite equation presentations, a lifted affine algebra map provides the ideal-compatibility
condition needed to build the induced map on affine complex zero loci. -/
theorem affinePresentation_bind₁_generators_mem_span
    {m n r s : ℕ} {A B : Type*} [CommRing A] [CommRing B] [Algebra ℂ A] [Algebra ℂ B]
    (fA : MvPolynomial (Fin m) ℂ →ₐ[ℂ] A)
    (fB : MvPolynomial (Fin n) ℂ →ₐ[ℂ] B)
    (g : B →ₐ[ℂ] A)
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (t : Fin s → MvPolynomial (Fin n) ℂ)
    (hp : Ideal.span (Set.range p) = RingHom.ker fA.toRingHom)
    (ht : Ideal.span (Set.range t) = RingHom.ker fB.toRingHom)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (hq : ∀ i, fA (q i) = g (fB (MvPolynomial.X i))) :
    ∀ i, MvPolynomial.bind₁ q (t i) ∈ Ideal.span (Set.range p) := by
  intro i
  rw [hp]
  apply affinePresentation_bind₁_mem_ker fA fB g q hq
  rw [← ht]
  exact Ideal.subset_span ⟨i, rfl⟩

/-- If substitution by `q` sends each generator of `span (range v)` into `span (range p)`,
then it sends every element of `span (range v)` there. -/
theorem bind₁_mem_span_of_range
    {m n r s : ℕ}
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (q : Fin n → MvPolynomial (Fin m) ℂ)
    (v : Fin s → MvPolynomial (Fin n) ℂ)
    (hq : ∀ i, MvPolynomial.bind₁ q (v i) ∈ Ideal.span (Set.range p))
    {φ : MvPolynomial (Fin n) ℂ}
    (hφ : φ ∈ Ideal.span (Set.range v)) :
    MvPolynomial.bind₁ q φ ∈ Ideal.span (Set.range p) := by
  refine Submodule.span_induction (s := Set.range v)
      (p := fun ψ _ => MvPolynomial.bind₁ q ψ ∈ Ideal.span (Set.range p)) ?_ ?_ ?_ ?_ hφ
  · intro ψ hψ
    rcases hψ with ⟨i, rfl⟩
    exact hq i
  · exact (Ideal.zero_mem (Ideal.span (Set.range p)))
  · intro ψ χ _ _ hψ hχ
    simpa using
      (map_add (MvPolynomial.bind₁ q) ψ χ ▸
        (Ideal.add_mem (Ideal.span (Set.range p)) hψ hχ))
  · intro a ψ _ hψ
    simpa [smul_eq_mul] using Ideal.mul_mem_left (Ideal.span (Set.range p)) _ hψ

/-- Given a surjective affine presentation map for the source coordinate ring, one can choose
polynomial lifts of the target coordinate classes along any affine `ℂ`-algebra map. -/
noncomputable def affinePresentationLiftTuple
    {m n : ℕ} {A B : Type*} [CommRing A] [CommRing B] [Algebra ℂ A] [Algebra ℂ B]
    (fA : MvPolynomial (Fin m) ℂ →ₐ[ℂ] A)
    (fB : MvPolynomial (Fin n) ℂ →ₐ[ℂ] B)
    (g : B →ₐ[ℂ] A)
    (hfA : Function.Surjective fA) :
    Fin n → MvPolynomial (Fin m) ℂ :=
  fun i => Function.surjInv hfA (g (fB (MvPolynomial.X i)))

@[simp]
theorem affinePresentationLiftTuple_spec
    {m n : ℕ} {A B : Type*} [CommRing A] [CommRing B] [Algebra ℂ A] [Algebra ℂ B]
    (fA : MvPolynomial (Fin m) ℂ →ₐ[ℂ] A)
    (fB : MvPolynomial (Fin n) ℂ →ₐ[ℂ] B)
    (g : B →ₐ[ℂ] A)
    (hfA : Function.Surjective fA)
    (i : Fin n) :
    fA (affinePresentationLiftTuple fA fB g hfA i) = g (fB (MvPolynomial.X i)) := by
  exact Function.surjInv_eq hfA _

/-- For finite equation presentations, surjectivity of the source presentation produces
an explicit tuple of polynomial lifts whose substitution sends target defining equations
into the source defining ideal. -/
theorem affinePresentation_liftTuple_generators_mem_span
    {m n r s : ℕ} {A B : Type*} [CommRing A] [CommRing B] [Algebra ℂ A] [Algebra ℂ B]
    (fA : MvPolynomial (Fin m) ℂ →ₐ[ℂ] A)
    (fB : MvPolynomial (Fin n) ℂ →ₐ[ℂ] B)
    (g : B →ₐ[ℂ] A)
    (hfA : Function.Surjective fA)
    (p : Fin r → MvPolynomial (Fin m) ℂ)
    (t : Fin s → MvPolynomial (Fin n) ℂ)
    (hp : Ideal.span (Set.range p) = RingHom.ker fA.toRingHom)
    (ht : Ideal.span (Set.range t) = RingHom.ker fB.toRingHom) :
    ∀ i,
      MvPolynomial.bind₁ (affinePresentationLiftTuple fA fB g hfA) (t i) ∈
        Ideal.span (Set.range p) := by
  apply affinePresentation_bind₁_generators_mem_span fA fB g p t hp ht
  intro i
  exact affinePresentationLiftTuple_spec fA fB g hfA i

variable {k : Type u} [Field k] [PerfectField k]

/-- The canonical `k`-algebra structure on the ring of sections over an open of a smooth
`k`-scheme, induced by the structure morphism to `Spec k`. -/
noncomputable abbrev smSchemeOpenSectionAlgebra
    (X : Geometry.SmSchemeOver k) (U : X.scheme.Opens) :
    Algebra k Γ(X.scheme, U) :=
  (((X.structMap.appLE ⊤ U (by simp)).comp (smBaseSectionRingEquiv (k := k)).toRingHom).toAlgebra)

noncomputable instance
    (X : Geometry.SmSchemeOver k) (U : X.scheme.Opens) :
    Algebra k Γ(X.scheme, U) :=
  smSchemeOpenSectionAlgebra X U

variable {X Y : Geometry.SmSchemeOver ℂ}

/-- The section map on affine opens induced by a morphism in `Sm/ℂ` is compatible with the
base-field algebra structures coming from the structure morphisms to `Spec ℂ`. -/
theorem smOverHom_appLE_baseField
    (f : Boundary.SmOverHom X Y)
    (U : Y.scheme.affineOpens) (V : X.scheme.affineOpens)
    (e : (V : X.scheme.Opens) ≤ f.hom ⁻¹ᵁ (U : Y.scheme.Opens)) :
    let baseU : ℂ →+* Γ(Y.scheme, (U : Y.scheme.Opens)) :=
      (Y.structMap.appLE ⊤ (U : Y.scheme.Opens) (by simp)).comp
        (smBaseSectionRingEquiv (k := ℂ)).toRingHom
    let baseV : ℂ →+* Γ(X.scheme, (V : X.scheme.Opens)) :=
      (X.structMap.appLE ⊤ (V : X.scheme.Opens) (by simp)).comp
        (smBaseSectionRingEquiv (k := ℂ)).toRingHom
    (f.hom.appLE (U : Y.scheme.Opens) (V : X.scheme.Opens) e).comp baseU = baseV := by
  classical
  ext c
  change
    (f.hom.appLE (U : Y.scheme.Opens) (V : X.scheme.Opens) e)
      ((Y.structMap.appLE ⊤ (U : Y.scheme.Opens) (by simp))
        ((smBaseSectionRingEquiv (k := ℂ)).toRingHom c)) =
    (X.structMap.appLE ⊤ (V : X.scheme.Opens) (by simp))
      ((smBaseSectionRingEquiv (k := ℂ)).toRingHom c)
  have hcomp :
      Y.structMap.appLE ⊤ (U : Y.scheme.Opens) (by simp) ≫
          f.hom.appLE (U : Y.scheme.Opens) (V : X.scheme.Opens) e =
        (f.hom ≫ Y.structMap).appLE ⊤ (V : X.scheme.Opens) (by simp) := by
    exact
      (Scheme.appLE_comp_appLE f.hom Y.structMap ⊤ (U : Y.scheme.Opens) (V : X.scheme.Opens)
        (by simp) e)
  calc
    (f.hom.appLE (U : Y.scheme.Opens) (V : X.scheme.Opens) e)
        ((Y.structMap.appLE ⊤ (U : Y.scheme.Opens) (by simp))
          ((smBaseSectionRingEquiv (k := ℂ)).toRingHom c))
      = ((f.hom ≫ Y.structMap).appLE ⊤ (V : X.scheme.Opens) (by simp))
          ((smBaseSectionRingEquiv (k := ℂ)).toRingHom c) := by
            exact congrArg
              (fun h : Γ(Spec (CommRingCat.of ℂ), ⊤) ⟶ Γ(X.scheme, (V : X.scheme.Opens)) =>
                h ((smBaseSectionRingEquiv (k := ℂ)).toRingHom c)) hcomp
    _ = (X.structMap.appLE ⊤ (V : X.scheme.Opens) (by simp))
          ((smBaseSectionRingEquiv (k := ℂ)).toRingHom c) := by
            rw [f.over]

/-- The induced section map on affine opens as a `ℂ`-algebra hom. -/
noncomputable def smOverHom_appLEAlgHom
    (f : Boundary.SmOverHom X Y)
    (U : Y.scheme.affineOpens) (V : X.scheme.affineOpens)
    (e : (V : X.scheme.Opens) ≤ f.hom ⁻¹ᵁ (U : Y.scheme.Opens)) :
    Γ(Y.scheme, (U : Y.scheme.Opens)) →ₐ[ℂ] Γ(X.scheme, (V : X.scheme.Opens)) := by
  exact
    { f.hom.appLE (U : Y.scheme.Opens) (V : X.scheme.Opens) e with
      commutes' := by
        intro c
        exact RingHom.congr_fun (smOverHom_appLE_baseField f U V e) c }

@[simp]
theorem smOverHom_appLEAlgHom_id
    (X : Geometry.SmSchemeOver ℂ) (U : X.scheme.affineOpens) :
    smOverHom_appLEAlgHom (X := X) (Y := X) (𝟙 X) U U le_rfl = AlgHom.id ℂ _ := by
  ext x
  change X.scheme.presheaf.map (𝟙 (Opposite.op ↑U)) x = x
  exact congrArg (fun h => h x) (X.scheme.presheaf.map_id (Opposite.op (↑U)))

theorem smOverHom_appLEAlgHom_comp
    {X Y Z : Geometry.SmSchemeOver ℂ}
    (f : Boundary.SmOverHom X Y) (g : Boundary.SmOverHom Y Z)
    (U : Z.scheme.affineOpens) (V : Y.scheme.affineOpens) (W : X.scheme.affineOpens)
    (e₁ : (V : Y.scheme.Opens) ≤ g.hom ⁻¹ᵁ (U : Z.scheme.Opens))
    (e₂ : (W : X.scheme.Opens) ≤ f.hom ⁻¹ᵁ (V : Y.scheme.Opens)) :
    (smOverHom_appLEAlgHom f V W e₂).comp (smOverHom_appLEAlgHom g U V e₁) =
      smOverHom_appLEAlgHom (Boundary.SmOverHom.comp f g) U W
        (by
          simpa [Boundary.SmOverHom.comp] using
            (show (W : X.scheme.Opens) ≤ (f.hom ≫ g.hom) ⁻¹ᵁ (U : Z.scheme.Opens) from
              e₂.trans ((TopologicalSpace.Opens.map f.hom.base).map (homOfLE e₁)).le)) := by
  ext x
  exact congrArg (fun h => h x)
    (Scheme.appLE_comp_appLE (X := X.scheme) (Y := Y.scheme) (Z := Z.scheme)
      f.hom g.hom (U : Z.scheme.Opens) (V : Y.scheme.Opens)
      (W : X.scheme.Opens) e₁ e₂)

end Realization
end Boundary
