import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.WordQuotient.Category.Owner

/-!
# Inverted localization inputs

This file records the categorical meaning of the formal cancellation laws:
each selected localization input becomes an isomorphism in the formal
localized word category.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The formal localized isomorphism generated by a localization input. -/
def TraceLocalizationInput.localizedWordIso
    (input : TraceLocalizationInput) :
    CategoryTheory.Iso
      (TraceLocalizedWordObject.ofTraceObject input.sourceObject)
      (TraceLocalizedWordObject.ofTraceObject input.targetObject) where
  hom := TraceLocalizationWordClass.ofInputForward input
  inv := TraceLocalizationWordClass.ofInputInverse input
  hom_inv_id :=
    TraceLocalizationWordClass.comp_forward_inverse_eq_identity input
  inv_hom_id :=
    TraceLocalizationWordClass.comp_inverse_forward_eq_identity input

/-- The forward arrow of the localized-word isomorphism is the forward input class. -/
theorem TraceLocalizationInput.localizedWordIso_hom
    (input : TraceLocalizationInput) :
    (TraceLocalizationInput.localizedWordIso input).hom =
      TraceLocalizationWordClass.ofInputForward input :=
  rfl

/-- The inverse arrow of the localized-word isomorphism is the formal inverse input class. -/
theorem TraceLocalizationInput.localizedWordIso_inv
    (input : TraceLocalizationInput) :
    (TraceLocalizationInput.localizedWordIso input).inv =
      TraceLocalizationWordClass.ofInputInverse input :=
  rfl

/-- The forward and inverse arrows compose to the source identity. -/
theorem TraceLocalizationInput.localizedWordIso_hom_inv
    (input : TraceLocalizationInput) :
    TraceLocalizationWordClass.comp
        (TraceLocalizationInput.localizedWordIso input).hom
        (TraceLocalizationInput.localizedWordIso input).inv =
      TraceLocalizationWordClass.identity input.sourceObject :=
  TraceLocalizationWordClass.comp_forward_inverse_eq_identity input

/-- The inverse and forward arrows compose to the target identity. -/
theorem TraceLocalizationInput.localizedWordIso_inv_hom
    (input : TraceLocalizationInput) :
    TraceLocalizationWordClass.comp
        (TraceLocalizationInput.localizedWordIso input).inv
        (TraceLocalizationInput.localizedWordIso input).hom =
      TraceLocalizationWordClass.identity input.targetObject :=
  TraceLocalizationWordClass.comp_inverse_forward_eq_identity input

end AnalyticMotives
end LFunctions
end Boundary
