import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Descent.Localization.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.IntervalHomotopy.Localization.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.TateStabilization.Localization.Owner

/-!
# Calculus localization inventory

This file collects the concrete analytic calculus moves that have been made
invertible in the formal localized word category: descent, interval homotopy,
and Tate weight-drop.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized isomorphism generated by channel descent. -/
def TraceCalculusLocalization.descentChannelIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentChannel source target).localizedSourceObject
      (TraceLocalizationInput.descentChannel source target).localizedTargetObject :=
  TraceDescentLocalization.channelIso source target

/-- The localized isomorphism generated by refinement descent. -/
def TraceCalculusLocalization.descentRefinementIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentRefinement source target).localizedSourceObject
      (TraceLocalizationInput.descentRefinement source target).localizedTargetObject :=
  TraceDescentLocalization.refinementIso source target

/-- The localized isomorphism generated by schedule descent. -/
def TraceCalculusLocalization.descentScheduleIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.descentSchedule source target).localizedSourceObject
      (TraceLocalizationInput.descentSchedule source target).localizedTargetObject :=
  TraceDescentLocalization.scheduleIso source target

/-- The localized isomorphism generated by interval Stokes deformation. -/
def TraceCalculusLocalization.intervalStokesIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalStokes source target).localizedSourceObject
      (TraceLocalizationInput.intervalStokes source target).localizedTargetObject :=
  TraceIntervalHomotopyLocalization.stokesIso source target

/-- The localized isomorphism generated by interval Fubini interchange. -/
def TraceCalculusLocalization.intervalFubiniIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalFubini source target).localizedSourceObject
      (TraceLocalizationInput.intervalFubini source target).localizedTargetObject :=
  TraceIntervalHomotopyLocalization.fubiniIso source target

/-- The localized isomorphism generated by Tate weight-drop. -/
def TraceCalculusLocalization.tateWeightDropIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.tateWeightDrop source target).localizedSourceObject
      (TraceLocalizationInput.tateWeightDrop source target).localizedTargetObject :=
  TraceTateStabilizationLocalization.weightDropIso source target

/-- Channel descent in the calculus inventory is the descent-localization isomorphism. -/
theorem TraceCalculusLocalization.descentChannelIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.descentChannelIso source target =
      TraceDescentLocalization.channelIso source target :=
  rfl

/-- Refinement descent in the calculus inventory is the descent-localization isomorphism. -/
theorem TraceCalculusLocalization.descentRefinementIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.descentRefinementIso source target =
      TraceDescentLocalization.refinementIso source target :=
  rfl

/-- Schedule descent in the calculus inventory is the descent-localization isomorphism. -/
theorem TraceCalculusLocalization.descentScheduleIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.descentScheduleIso source target =
      TraceDescentLocalization.scheduleIso source target :=
  rfl

/-- Interval Stokes in the calculus inventory is the interval-localization isomorphism. -/
theorem TraceCalculusLocalization.intervalStokesIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.intervalStokesIso source target =
      TraceIntervalHomotopyLocalization.stokesIso source target :=
  rfl

/-- Interval Fubini in the calculus inventory is the interval-localization isomorphism. -/
theorem TraceCalculusLocalization.intervalFubiniIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.intervalFubiniIso source target =
      TraceIntervalHomotopyLocalization.fubiniIso source target :=
  rfl

/-- Tate weight-drop in the calculus inventory is the Tate-localization isomorphism. -/
theorem TraceCalculusLocalization.tateWeightDropIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.tateWeightDropIso source target =
      TraceTateStabilizationLocalization.weightDropIso source target :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
