import TraceCalc.MotivicRecognition.TraceDMgmEquivalenceProofs
import TraceCalc.MotivicRecognition.SyntacticDMgmClassicalBridge

namespace AxiomCheckBlock6
open TraceCalc.MotivicRecognition
open TraceCalc.LayerD

-- Package 6: Canonical Trace ≃ DM_gm(Q) equivalence
#print axioms DMgmQPiZeroInterface.certifiedPiZeroRecognition_holds
#print axioms DMgmQPiZeroInterface.ofCertifiedClassicalTarget
#print axioms DMgmQPiZeroInterface.ofCertifiedClassicalTarget_target_eq
#print axioms DMgmQPiZeroInterface.ofCertifiedClassicalTarget_piZeroRecognition_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.commonPresentationComparison_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.corePresentationComparison_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.completedPresentationComparison_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.fullyFaithful_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.essentiallySurjective_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.dualityCompatibility_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.exactSymmetricMonoidalExtension_holds
#print axioms TraceCalc.CategoryInfra.SyntacticTraceDMgm.homotopyCategoryComparison_holds
#print axioms commonPresentationComparison_holds
#print axioms closureEqualityComparison_holds
#print axioms classicalBoundaryCompatibility_holds
#print axioms fullyFaithful_holds_forCanonicalData
#print axioms completedPresentationDuality_holds
#print axioms exactSymmetricMonoidalExtension_holds_forCanonicalData
#print axioms homotopyCategoryComparison_holds
#print axioms CorePresentationEquivalenceTarget.ofSyntacticTraceDMgmComparison
#print axioms CompletedPresentationEquivalenceTarget.ofSyntacticTraceDMgmComparison
#print axioms CanonicalTraceDMgmEquivalenceData.ofSyntacticTraceDMgmComparison
#print axioms CanonicalTraceDMgmEquivalenceTheoremPackage.ofSyntacticTraceDMgmComparison
#print axioms TraceCategoryEquivalentToDMgmQTarget.ofSyntacticTraceDMgmComparison
#print axioms syntacticCanonicalDMgmEquivalenceTarget
#print axioms DMgmUniversalRecognitionData.ofCanonicalDMgmEquivalence
#print axioms DMgmUniversalRecognitionTheoremTarget.ofCanonicalDMgmEquivalence
#print axioms CorePresentationEquivalenceTarget.ofDecomposition
#print axioms CompletedPresentationEquivalenceTarget.ofDecomposition
#print axioms CanonicalTraceDMgmEquivalenceData.commonPresentationCompatibility
#print axioms CanonicalTraceDMgmEquivalenceData.closureCompatibility
#print axioms CanonicalTraceDMgmEquivalenceData.pi0ShadowCompatibility
#print axioms CanonicalTraceDMgmEquivalenceData.fullyFaithfulWitness
#print axioms CanonicalTraceDMgmEquivalenceData.essentiallySurjectiveWitness
#print axioms CanonicalTraceDMgmEquivalenceData.unitComparisonWitness
#print axioms CanonicalTraceDMgmEquivalenceData.counitComparisonWitness
#print axioms CanonicalTraceDMgmEquivalenceData.toTarget
#print axioms CanonicalTraceDMgmEquivalenceData.ofCompletedPresentationAndPi0Shadow
#print axioms CanonicalTraceDMgmEquivalenceTheoremPackage.ofCanonicalData
#print axioms TraceCategoryEquivalentToDMgmQTarget.ofCompletedPresentationAndPi0Shadow
#print axioms objectInterpretationTarget_holds_from_interpretation
#print axioms morphismInterpretationTarget_holds_from_interpretation
#print axioms presentationPreservationTarget_holds_from_interpretation
#print axioms stableCompletionPreservationTarget_holds_from_interpretation
#print axioms piZeroCompatibilityTarget_holds_from_interpretation
#print axioms fullFaithfulnessRecognitionTarget_holds_from_interpretation
#print axioms SyntacticDMgmToClassicalDMgmBridgeData.ofInterpretationData
#print axioms SyntacticDMgmClassicalRecognitionTarget.ofInterpretationData
#print axioms finalPackage6ClassicalSeal_from_interpretation
#print axioms finalPackage6ClassicalSeal_reaches_existing_classical_target
#print axioms finalPackage6ClassicalSeal_bridge_fields_holds
#print axioms SyntacticDMgmClassicalIdentificationInterface.bridgeData
#print axioms SyntacticDMgmClassicalIdentificationInterface.recognitionTarget
#print axioms SyntacticDMgmClassicalIdentificationInterface.recognitionTarget_reaches_existing_classical_target
#print axioms SyntacticDMgmClassicalIdentificationInterface.recognitionTarget_bridge_fields_holds
#print axioms finalPackage6ClassicalSeal_from_identificationInterface
#print axioms finalPackage6ClassicalSeal_interface_reaches_existing_classical_target
#print axioms finalPackage6ClassicalSeal_interface_bridge_fields_holds
#print axioms TraceCalc.MotivicRecognition.ClassicalDMgmQOperationsData.toSealedClassicalOperationsProvider
#print axioms TraceCalc.MotivicRecognition.ClassicalDMgmQOperationsData.ofSealedSources
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.ofClassicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.ofSealedSources
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.interpretBase_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.interpretBaseHom_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalShiftObj_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalShiftMap_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalTensorObj_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalTensorMap_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalCofiberObj_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalDualObj_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.p3bAssignmentTable_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.p3bAdmissibilityComparison_from_classicalOperationsData
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.interpretBase_from_sealedSources
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.interpretBaseHom_from_sealedSources
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalShiftObj_from_sealedSources
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.classicalTensorObj_from_sealedSources
#print axioms TraceCalc.MotivicRecognition.SealedClassicalOperationsProvider.p3bAdmissibilityComparison_from_sealedSources
#print axioms interpret_id_from_provider
#print axioms interpret_comp_from_provider
#print axioms interpret_pi0_class_from_provider
#print axioms interpret_shift_obj_from_provider
#print axioms interpret_shift_hom_from_provider
#print axioms interpret_cofiber_from_provider
#print axioms interpret_tensor_obj_from_provider
#print axioms interpret_tensor_hom_from_provider
#print axioms interpret_dual_from_provider
#print axioms SyntacticDMgmClassicalInterpretationData.ofSealedPackages
#print axioms finalPackage6ClassicalSeal_from_sealedPackages
#print axioms finalPackage6ClassicalSeal_from_sealedPackages_reaches_target
#print axioms finalPackage6ClassicalSeal_from_sealedPackages_bridge_holds
#print axioms finalPackage6ClassicalSeal_from_sealedSources
#print axioms finalPackage6ClassicalSeal_from_sealedSources_reaches_target
#print axioms finalPackage6ClassicalSeal_from_sealedSources_bridge_holds

end AxiomCheckBlock6
