import TraceCalc.MotivicRecognition.InfinityPiZeroProofs

namespace AxiomCheckBlock5
open TraceCalc.MotivicRecognition

-- Package 5: Infinity enhancement / π₀ comparison
#print axioms TraceCalc.CategoryInfra.SyntacticInfinity.pi0_id_left
#print axioms TraceCalc.CategoryInfra.SyntacticInfinity.pi0_id_right
#print axioms TraceCalc.CategoryInfra.SyntacticInfinity.pi0_assoc
#print axioms TraceCalc.CategoryInfra.SyntacticInfinity.shift_descends_to_pi0
#print axioms TraceCalc.CategoryInfra.SyntacticInfinity.tensor_descends_to_pi0
#print axioms TraceInfinityEnhancementOverQ.ofSyntacticInfinityEnhancement
#print axioms TraceInfinityEnhancementTheoremPackage.ofSyntacticInfinityEnhancement
#print axioms syntacticInfinity_realizationCompatibility_holds
#print axioms syntacticInfinity_completedPresentationCompatibility_holds
#print axioms TraceInfinityEnhancementTheoremPackage.ofEnhancementWitnesses
#print axioms TracePi0TriangulatedShadowOverQ.ofInfinityEnhancement
#print axioms TracePi0TriangulatedShadowOverQ.ofSyntacticInfinityEnhancement
#print axioms TraceInfinityToPiZeroShadowComparisonOverQ.ofInfinityEnhancement
#print axioms TraceInfinityToPiZeroShadowComparisonOverQ.ofSyntacticInfinityEnhancement

end AxiomCheckBlock5
