import TraceCalc.ProbeTheory.PeriodTomographyBridge

#print axioms TraceCalc.ProbeTheory.ProbeFamily
#print axioms TraceCalc.ProbeTheory.ProbeObservation
#print axioms TraceCalc.ProbeTheory.SeparatingProbeFamily
#print axioms TraceCalc.ProbeTheory.probe_extensionality
#print axioms TraceCalc.ProbeTheory.separating_probes_detect_morphisms
#print axioms TraceCalc.ProbeTheory.MotivicSphereIndex
#print axioms TraceCalc.ProbeTheory.TateSphereData
#print axioms TraceCalc.ProbeTheory.TateSphereProbeFamily
#print axioms TraceCalc.ProbeTheory.PeriodTomographyProbeBridge.framed_periods_are_probe_observations
#print axioms TraceCalc.ProbeTheory.PeriodTomographyProbeBridge.period_tomography_from_sphere_probe_extensionality
