import TraceCalc.ClassicalPeriods.VoevodskyFiniteCorrespondences

open TraceCalc.ClassicalPeriods.VoevodskyFiniteCorrespondences
open TraceCalc.MotivicRecognition

#print axioms RawCycle.add
#print axioms compose
#print axioms finiteCorrespondence_id_left
#print axioms finiteCorrespondence_id_right
#print axioms finiteCorrespondence_assoc
#print axioms Examples.graph_id
#print axioms Examples.graph_comp
#print axioms ConcreteVoevodskyCorrespondenceProvider.ofFiniteCorrespondences
#print axioms corr_identity_holds_from_voevodsky_finite_correspondences
#print axioms corr_composition_holds_from_voevodsky_finite_correspondences
#print axioms CertifiedCorrFunctorialityTarget.ofVoevodskyFiniteCorrespondences