import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Complexes.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Complexes.LocalizationInput.CommonBound.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Maps.Owner

/-!
# Bounded maps generated by localization inputs

This file regards the degree-zero complex morphism generated by a localization
input as a bounded-complex map after source and target are placed under their
shared common bound.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The bounded-complex map generated by a localization input. -/
def TraceLocalizationInput.boundedAdditiveComplexHom
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom
      input.commonBoundedAdditiveSourceComplex
      input.commonBoundedAdditiveTargetComplex :=
  input.additiveComplexHom

/-- The bounded localization-input map has the same underlying chain map as the
degree-zero additive complex map. -/
theorem TraceLocalizationInput.boundedAdditiveComplexHom_eq
    (input : TraceLocalizationInput) :
    input.boundedAdditiveComplexHom =
      input.additiveComplexHom :=
  rfl

/-- The degree-zero component of the bounded localization-input map is induced by the
one-entry additive matrix. -/
theorem TraceLocalizationInput.boundedAdditiveComplexHom_f_zero
    (input : TraceLocalizationInput) :
    input.boundedAdditiveComplexHom.f 0 =
      (HomologicalComplex.singleObjXSelf
        (ComplexShape.up ℤ)
        (0 : ℤ)
        input.additiveSourceObject).hom ≫
        input.additiveHom ≫
      (HomologicalComplex.singleObjXSelf
        (ComplexShape.up ℤ)
        (0 : ℤ)
        input.additiveTargetObject).inv :=
  TraceLocalizationInput.additiveComplexHom_f_zero input

end AnalyticMotives
end LFunctions
end Boundary
