import Boundary.GeometricEffectiveMotives
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Comparison.Algebraizable.ContourCorQConstruction.ParentMotives.Effective.Owner

/-!
# Parent geometric effective image of an algebraized analytic bulk

This file sends an algebraized contour bulk to the parent geometric effective
subcategory generated by smooth schemes.
-/

universe u

open CategoryTheory

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

noncomputable section

variable {G : PerfectAnalyticGround}
variable (composition : Boundary.CanonicalCompositionData (k := G.carrier))
variable [Abelian (LinearPST (Boundary.canonicalCategory composition))]
variable [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
variable (implementation :
  CanonicalA1NisLocalizationImplementation composition)

/-- The parent geometric effective motive attached to a smooth algebraized bulk. -/
def SmoothAlgebraization.parentGeometricEffectiveMotive
    {X : ContourAdmissibleBulk}
    (A : SmoothAlgebraization G X) :
    canonicalGeometricEffectiveMotives composition implementation :=
  canonicalGeometricEffectiveMotiveObject composition implementation A.scheme

/-- The geometric effective image is the canonical generator object of the algebraization. -/
theorem SmoothAlgebraization.parentGeometricEffectiveMotive_eq
    {X : ContourAdmissibleBulk}
    (A : SmoothAlgebraization G X) :
    A.parentGeometricEffectiveMotive composition implementation =
      canonicalGeometricEffectiveMotiveObject composition implementation A.scheme :=
  rfl

end

end AnalyticMotives
end LFunctions
end Boundary
