import Mathlib.Algebra.Homology.HomotopyCategory.SingleFunctors
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.Endpoints.Source.TraceObject.AdditiveObject.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Complexes.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Homs.Singleton.Owner

/-!
# Degree-zero trace complexes at the comparison source endpoint

This file owns the second source-side passage from a certified trace object to
the comparison source: the singleton additive object is placed in degree zero,
and trace correspondences are sent to the corresponding single-complex maps.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- The degree-zero additive complex generated by a certified trace object. -/
def TraceAnalyticMotiveComparison.sourceTraceComplex
    (object : TraceCorQObject) :
    TraceAnalyticAdditiveCochainComplex :=
  TraceAnalyticAdditiveCochainComplex.concentratedSingleton object

/-- The comparison endpoint trace complex is the concentrated singleton
complex. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplex_eq_concentratedSingleton
    (object : TraceCorQObject) :
    TraceAnalyticMotiveComparison.sourceTraceComplex object =
      TraceAnalyticAdditiveCochainComplex.concentratedSingleton object :=
  rfl

/-- The degree-zero object of the endpoint trace complex is the singleton
additive trace family. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplex_objectAt_zero
    (object : TraceCorQObject) :
    (TraceAnalyticMotiveComparison.sourceTraceComplex object).objectAt 0 =
      TraceAnalyticAdditiveObject.singleton object :=
  TraceAnalyticAdditiveCochainComplex.concentratedSingleton_objectAt_zero
    object

/-- The degree-zero object of the endpoint trace complex is the endpoint
singleton additive object. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplex_objectAt_zero_eq_sourceTraceAdditiveObject
    (object : TraceCorQObject) :
    (TraceAnalyticMotiveComparison.sourceTraceComplex object).objectAt 0 =
      TraceAnalyticMotiveComparison.sourceTraceAdditiveObject object :=
  TraceAnalyticAdditiveCochainComplex.concentratedSingleton_objectAt_zero
    object

/-- The degree-zero object of the endpoint trace complex has one component. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplex_objectAt_zero_length
    (object : TraceCorQObject) :
    ((TraceAnalyticMotiveComparison.sourceTraceComplex object).objectAt 0).length =
      1 :=
  TraceAnalyticAdditiveCochainComplex.concentratedSingleton_objectAt_zero_length
    object

/-- The degree-zero complex morphism generated by one trace correspondence. -/
def TraceAnalyticMotiveComparison.sourceTraceComplexMap
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticMotiveComparison.sourceTraceComplex source ⟶
      TraceAnalyticMotiveComparison.sourceTraceComplex target :=
  (CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject (0 : ℤ)).map
    (TraceAnalyticMotiveComparison.sourceTraceAdditiveMap hom)

/-- The endpoint trace-complex map is the single-complex image of the singleton
additive-envelope matrix. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplexMap_eq_singletonMap
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticMotiveComparison.sourceTraceComplexMap hom =
      (CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject
        (0 : ℤ)).map
        (TraceAnalyticAdditiveHom.singletonMap hom) :=
  rfl

/-- The endpoint trace-complex map is the single-complex image of the endpoint
singleton additive map. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplexMap_eq_sourceTraceAdditiveMap
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticMotiveComparison.sourceTraceComplexMap hom =
      (CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject
        (0 : ℤ)).map
        (TraceAnalyticMotiveComparison.sourceTraceAdditiveMap hom) :=
  rfl

/-- The degree-zero trace-complex functor represented by certified trace
objects. -/
def TraceAnalyticMotiveComparison.sourceTraceComplexFunctor :
    TraceCorQObject ⥤ TraceAnalyticAdditiveCochainComplex :=
  TraceAnalyticAdditiveObject.singletonFunctor ⋙
    CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject (0 : ℤ)

/-- The degree-zero trace-complex functor is the singleton additive functor
followed by the degree-zero single-complex functor. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplexFunctor_eq_singleton_comp_single :
    TraceAnalyticMotiveComparison.sourceTraceComplexFunctor =
      TraceAnalyticAdditiveObject.singletonFunctor ⋙
        CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject
          (0 : ℤ) :=
  rfl

/-- Object formula for the degree-zero trace-complex functor. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplexFunctor_obj
    (object : TraceCorQObject) :
    TraceAnalyticMotiveComparison.sourceTraceComplexFunctor.obj object =
      TraceAnalyticMotiveComparison.sourceTraceComplex object :=
  rfl

/-- Map formula for the degree-zero trace-complex functor. -/
theorem TraceAnalyticMotiveComparison.sourceTraceComplexFunctor_map
    {source target : TraceCorQObject}
    (hom : source ⟶ target) :
    TraceAnalyticMotiveComparison.sourceTraceComplexFunctor.map hom =
      TraceAnalyticMotiveComparison.sourceTraceComplexMap hom :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
