import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Maps.LocalizationInput.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.Projections.Owner

/-!
# Bounded mapping-cone triangles generated by localization inputs

This file sends each localization-input bounded map to its packaged bounded
mapping-cone distinguished triangle.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The bounded mapping-cone triangle generated by a localization input. -/
def TraceLocalizationInput.boundedMappingConeTriangle
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedTriangle
      input.additiveComplexCommonWeightBound :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
    input.boundedAdditiveComplexHom

/-- The first bounded representative of the localization-input cone triangle is the
common-bounded source complex. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_first
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.first =
      input.commonBoundedAdditiveSourceComplex :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_first
    input.boundedAdditiveComplexHom

/-- The second bounded representative of the localization-input cone triangle is the
common-bounded target complex. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_second
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.second =
      input.commonBoundedAdditiveTargetComplex :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_second
    input.boundedAdditiveComplexHom

/-- The localization-input cone triangle has the ordinary bounded mapping-cone triangle
underneath. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_triangle
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.triangle =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_triangle
    input.boundedAdditiveComplexHom

/-- The localization-input bounded mapping-cone triangle is distinguished. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_distinguished
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.triangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_distinguished
    input.boundedAdditiveComplexHom

/-- The first homotopy object of the localization-input cone triangle is the source
object of the bounded mapping-cone construction. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_firstObject
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.firstObject =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_firstObject
    input.boundedAdditiveComplexHom

/-- The second homotopy object of the localization-input cone triangle is the target
object of the bounded mapping-cone construction. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_secondObject
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.secondObject =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_secondObject
    input.boundedAdditiveComplexHom

/-- The first morphism of the localization-input cone triangle is the bounded
localization-input map in the homotopy category. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_firstMap
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.firstMap =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_firstMap
    input.boundedAdditiveComplexHom

/-- The third vertex of the localization-input cone triangle is the mapping cone of the
bounded localization-input map. -/
theorem TraceLocalizationInput.boundedMappingConeTriangle_thirdVertex
    (input : TraceLocalizationInput) :
    input.boundedMappingConeTriangle.triangleThirdVertex =
      (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle
        input.boundedAdditiveComplexHom).obj₃ :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle_thirdVertex
    input.boundedAdditiveComplexHom

end AnalyticMotives
end LFunctions
end Boundary
