import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Comparison.EffectiveRealization.Carrier.TraceHom.RawRelationWitness.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Relation.Owner

/-!
# Raw quotient-relation carriers for analytic effective realization

This file exposes the proof-valued quotient relation generated by concrete
finite relation witnesses.  Data-bearing payloads remain attached to witnesses;
the relation itself is used for quotient descent.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The comparison boundary keeps the actual witness-generated quotient relation. -/
def TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationCarrier
    {left right : TraceCorQQuotientCandidate}
    (relation : TraceCorQQuotientRelation left right) :
    TraceCorQQuotientRelation left right :=
  relation

/-- A concrete raw witness determines the proof-valued raw quotient relation. -/
def TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationOfWitness
    {left right : TraceCorQQuotientCandidate}
    (witness : TraceCorQRelationWitness left right) :
    TraceCorQQuotientRelation left right :=
  TraceCorQQuotientRelation.ofWitness witness

/-- The canonical raw quotient relation killing a relation generator's support. -/
def TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationSupportZero
    (relation : TraceCorQRelationGenerator) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.supportCandidate relation)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.supportZero relation

/-- Reflexive raw quotient relation on a candidate. -/
def TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationRefl
    (candidate : TraceCorQQuotientCandidate) :
    TraceCorQQuotientRelation candidate candidate :=
  TraceCorQQuotientRelation.refl candidate

/-- The raw quotient-relation carrier is definitionally the supplied relation. -/
theorem TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationCarrier_eq
    {left right : TraceCorQQuotientCandidate}
    (relation : TraceCorQQuotientRelation left right) :
    TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationCarrier relation =
      relation :=
  rfl

/-- The support-zero relation is represented by the canonical support witness. -/
theorem TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationSupportZero_eq_ofWitness
    (relation : TraceCorQRelationGenerator) :
    TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationSupportZero
      relation =
      TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationOfWitness
        (TraceCorQRelationGenerator.supportWitness relation) :=
  TraceCorQQuotientRelation.supportZero_eq_ofWitness
    relation

/-- The witness-induced relation is definitionally the raw quotient relation constructor. -/
theorem TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationOfWitness_eq
    {left right : TraceCorQQuotientCandidate}
    (witness : TraceCorQRelationWitness left right) :
    TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationOfWitness witness =
      TraceCorQQuotientRelation.ofWitness witness :=
  rfl

/-- The reflexive raw quotient relation is induced by the reflexive raw witness. -/
theorem TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationRefl_eq_ofWitness
    (candidate : TraceCorQQuotientCandidate) :
    TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationRefl candidate =
      TraceAnalyticEffectiveRealization.traceHomRawQuotientRelationOfWitness
        (TraceCorQRelationWitness.refl candidate) :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
