import Boundary.DMgm

open Boundary

#check boundaryProjectiveLineCanonicalObject
#check boundaryProjectiveLineBasepoint
#check boundaryEffectiveTateObject
#check boundaryEffectiveTateObject_projectiveGeometry
#check boundaryEffectiveTateObject_shifted_iso_reducedProjectiveLine

#check Boundary.Motives.TateStabilizationExtension
#check Boundary.Motives.TateStabilizationExtension.lift
#check Boundary.Motives.tateShiftEquivalence

#check boundaryMotivesOfProjectiveGeometricTateObject
#check boundaryEffectiveMotivesEmbeddingProjectiveGeometricTate
#check boundaryProjectiveGeometricTateShiftEquivalence
#check boundaryProjectiveGeometricTateStabilizationUniversalProperty

#check VoevodskyDMgmQ_Q
#check VoevodskyDMgmEffectiveEmbedding
#check VoevodskyDMgmTateShiftEquivalence
#check VoevodskyDMgmTateStabilizationExtension
#check VoevodskyDMgmTateStabilizationExtension.lift
#check VoevodskyDMgmTateStabilizationUniversalProperty
#check VoevodskyDMgmTateStabilizationUniversalProperty.canonical
