import Boundary.A1Geometry
import Mathlib.Algebra.Homology.DerivedCategory.Basic
import Mathlib.Algebra.Homology.DerivedCategory.ExactFunctor
import Mathlib.Algebra.Homology.DerivedCategory.HomologySequence
import Mathlib.CategoryTheory.Triangulated.Subcategory

/-!
# Canonical effective motives ambient layer

This file starts the effective-motives layer over `canonicalSmCorQ` without
introducing `DMgm`, Tate stabilization, or mixed motives.

The honest ambient categorical substrate available in mathlib is:

* cochain complexes of `LinearPST (canonicalSmCorQ)`;
* the homotopy category of those complexes;
* the derived category, once `LinearPST (canonicalSmCorQ)` is equipped with an
  abelian structure.

What is not yet canonically constructed in the repository is the second-stage
Verdier localization by the thick/triangulated subcategory generated by the
canonical `A1`/Nisnevich relations on the derived layer.  The exact remaining
obligation is isolated below as `CanonicalMotivicAcyclicsDatum`.
-/

universe u

open CategoryTheory

namespace Boundary

noncomputable section

variable {k : Type u} [Field k] [PerfectField k]

/-- The ambient cochain-complex category underlying the effective layer over
`canonicalSmCorQ`. -/
abbrev canonicalEffectiveCochainComplexes
  (composition : Boundary.CanonicalCompositionData (k := k))
  [Limits.HasZeroMorphisms (LinearPST (Boundary.canonicalCategory composition))]
  [Preadditive (LinearPST (Boundary.canonicalCategory composition))] :=
  CochainComplex (LinearPST (Boundary.canonicalCategory composition)) Int

/-- The ambient homotopy category of cochain complexes over
`LinearPST (canonicalSmCorQ)`. -/
abbrev canonicalEffectiveHomotopyCategory
  (composition : Boundary.CanonicalCompositionData (k := k))
  [Limits.HasZeroMorphisms (LinearPST (Boundary.canonicalCategory composition))]
  [Preadditive (LinearPST (Boundary.canonicalCategory composition))] :=
  HomotopyCategory (LinearPST (Boundary.canonicalCategory composition)) (ComplexShape.up Int)

/-- The quasi-isomorphism class on the ambient effective cochain-complex
category. -/
abbrev canonicalEffectiveQuasiIsomorphisms
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Limits.HasZeroMorphisms (LinearPST (Boundary.canonicalCategory composition))]
    [Preadditive (LinearPST (Boundary.canonicalCategory composition))]
    [CategoryWithHomology (LinearPST (Boundary.canonicalCategory composition))] :
    MorphismProperty (canonicalEffectiveCochainComplexes composition) :=
  HomologicalComplex.quasiIso
    (LinearPST (Boundary.canonicalCategory composition)) (ComplexShape.up Int)

/-- The ambient derived category of linear presheaves with transfers over
`canonicalSmCorQ`, before the extra `A1`/Nisnevich Verdier quotient is imposed. -/
abbrev canonicalEffectiveAmbientDerivedCategory
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))] :=
  DerivedCategory (LinearPST (Boundary.canonicalCategory composition))

/-- The localization functor from cochain complexes of linear presheaves with
transfers to their ambient derived category. -/
def canonicalEffectiveAmbientDerivedLocalizationFunctor
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))] :
    canonicalEffectiveCochainComplexes composition ⥤
      canonicalEffectiveAmbientDerivedCategory composition :=
  DerivedCategory.Q

instance canonicalEffectiveAmbientDerivedLocalizationFunctor_isLocalization
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))] :
    (canonicalEffectiveAmbientDerivedLocalizationFunctor composition).IsLocalization
      (canonicalEffectiveQuasiIsomorphisms composition) := by
  dsimp [canonicalEffectiveAmbientDerivedLocalizationFunctor,
    canonicalEffectiveAmbientDerivedCategory, canonicalEffectiveQuasiIsomorphisms]
  infer_instance

/-- Universal property of the ambient derived category: functors out of the
ambient derived category are equivalent to functors on cochain complexes that
invert quasi-isomorphisms. -/
def canonicalEffectiveAmbientDerived_universalProperty
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (D : Type*) [Category D] :
    (canonicalEffectiveAmbientDerivedCategory composition ⥤ D) ≌
      (canonicalEffectiveQuasiIsomorphisms composition).FunctorsInverting D :=
  Localization.functorEquivalence
    (canonicalEffectiveAmbientDerivedLocalizationFunctor composition)
    (canonicalEffectiveQuasiIsomorphisms composition)
    D

/-- Exact missing datum for the effective-motives category.

Once this datum is constructed canonically, the effective-motives category is
obtained by localizing the ambient derived category at `a1NisSubcategory.W`.
The key obligation is to produce a triangulated subcategory of the ambient
derived category whose associated Verdier class contains the degree-zero images
of the canonical saturated `A1`/Nisnevich weak equivalences from
`A1Geometry`. -/
structure CanonicalMotivicAcyclicsDatum
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))] where
  a1NisSubcategory :
    Triangulated.Subcategory (canonicalEffectiveAmbientDerivedCategory composition)
  containsCanonicalA1NisEquivalences :
    ∀ {F G : LinearPST (Boundary.canonicalCategory composition)} (φ : F ⟶ G),
      canonicalA1NisSaturatedWeakEquivalences composition φ →
        a1NisSubcategory.W
          ((DerivedCategory.singleFunctor
              (LinearPST (Boundary.canonicalCategory composition)) 0).map φ)

/-- The Verdier-class morphism property determined by a chosen triangulated
subcategory of canonical motivic acyclics in the ambient derived category. -/
abbrev canonicalMotivicAcyclicMorphisms
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition) :
    MorphismProperty (canonicalEffectiveAmbientDerivedCategory composition) :=
  acyclics.a1NisSubcategory.W

/-- Conditional Verdier quotient of the ambient derived category by the chosen
canonical motivic acyclics.  This is the honest effective-motives category once
`CanonicalMotivicAcyclicsDatum` has been constructed canonically. -/
abbrev canonicalEffectiveMotivesWithAcyclics
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition) :=
  (canonicalMotivicAcyclicMorphisms composition acyclics).Localization

/-- The Verdier-localization functor from the ambient derived category to the
conditional effective-motives quotient determined by the chosen canonical
motivic acyclics. -/
def canonicalEffectiveMotivesLocalizationFunctorWithAcyclics
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition) :
    canonicalEffectiveAmbientDerivedCategory composition ⥤
      canonicalEffectiveMotivesWithAcyclics composition acyclics :=
  (canonicalMotivicAcyclicMorphisms composition acyclics).Q

instance canonicalEffectiveMotivesLocalizationFunctorWithAcyclics_isLocalization
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition) :
    (canonicalEffectiveMotivesLocalizationFunctorWithAcyclics composition acyclics).IsLocalization
      (canonicalMotivicAcyclicMorphisms composition acyclics) := by
  dsimp [canonicalEffectiveMotivesLocalizationFunctorWithAcyclics,
    canonicalEffectiveMotivesWithAcyclics,
    canonicalMotivicAcyclicMorphisms]
  infer_instance

/-- Universal property of the conditional effective-motives Verdier quotient:
functors out of the quotient are equivalent to functors on the ambient derived
category that invert the chosen canonical motivic acyclic morphisms. -/
def canonicalEffectiveMotivesWithAcyclics_universalProperty
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition)
    (D : Type*) [Category D] :
    (canonicalEffectiveMotivesWithAcyclics composition acyclics ⥤ D) ≌
      (canonicalMotivicAcyclicMorphisms composition acyclics).FunctorsInverting D :=
  Localization.functorEquivalence
    (canonicalEffectiveMotivesLocalizationFunctorWithAcyclics composition acyclics)
    (canonicalMotivicAcyclicMorphisms composition acyclics)
    D

/-- The chosen canonical motivic acyclics invert the degree-zero images of the
canonical saturated `A1`/Nisnevich weak equivalences. -/
theorem canonicalMotivicAcyclics_contains_degreeZeroA1Nis
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition)
    {F G : LinearPST (Boundary.canonicalCategory composition)}
    (φ : F ⟶ G)
    (hφ : canonicalA1NisSaturatedWeakEquivalences composition φ) :
    canonicalMotivicAcyclicMorphisms composition acyclics
      ((DerivedCategory.singleFunctor
          (LinearPST (Boundary.canonicalCategory composition)) 0).map φ) :=
  acyclics.containsCanonicalA1NisEquivalences φ hφ

/-- Any candidate canonical motivic-acyclic subcategory already contains the
degree-zero image of each primitive canonical `A1`-projection generator. -/
theorem canonicalMotivicAcyclics_contains_degreeZeroA1Projection
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition)
    (X : Geometry.SmSchemeOver k)
    (D : FiniteIrreducibleComponentDecomposition (productWithA1 X)) :
    canonicalMotivicAcyclicMorphisms composition acyclics
      ((DerivedCategory.singleFunctor
          (LinearPST (Boundary.canonicalCategory composition)) 0).map
        (show QtrLinear (category := Boundary.canonicalCategory composition) (productWithA1 X) ⟶
            QtrLinear (category := Boundary.canonicalCategory composition) X from
          projectionToBase_QtrMapOfDecomposition
            (Boundary.canonicalCategory composition) X D)) := by
  exact canonicalMotivicAcyclics_contains_degreeZeroA1Nis composition acyclics _
    ((canonicalA1NisGenerators_areCanonicalLocalEquivalences composition).1 X D)

/-- Any candidate canonical motivic-acyclic subcategory already contains the
degree-zero image of each primitive Nisnevich descent generator. -/
theorem canonicalMotivicAcyclics_contains_degreeZeroNisnevichDescent
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition)
    (square : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    canonicalMotivicAcyclicMorphisms composition acyclics
      ((DerivedCategory.singleFunctor
          (LinearPST (Boundary.canonicalCategory composition)) 0).map
        square.nisnevichDescentGeneratorMapLinear) := by
  exact canonicalMotivicAcyclics_contains_degreeZeroA1Nis composition acyclics _
    ((canonicalA1NisGenerators_areCanonicalLocalEquivalences composition).2 square)

/-- Primitive-generator packaging for the effective-layer kill problem: the
two basic canonical families already land in any admissible motivic-acyclic
Verdier class. -/
theorem canonicalMotivicAcyclics_contains_degreeZeroPrimitiveGenerators
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition) :
    (∀ (X : Geometry.SmSchemeOver k)
       (D : FiniteIrreducibleComponentDecomposition (productWithA1 X)),
        canonicalMotivicAcyclicMorphisms composition acyclics
          ((DerivedCategory.singleFunctor
              (LinearPST (Boundary.canonicalCategory composition)) 0).map
            (show QtrLinear (category := Boundary.canonicalCategory composition) (productWithA1 X) ⟶
                QtrLinear (category := Boundary.canonicalCategory composition) X from
              projectionToBase_QtrMapOfDecomposition
                (Boundary.canonicalCategory composition) X D))) ∧
    (∀ (square : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)),
        canonicalMotivicAcyclicMorphisms composition acyclics
          ((DerivedCategory.singleFunctor
              (LinearPST (Boundary.canonicalCategory composition)) 0).map
            square.nisnevichDescentGeneratorMapLinear)) := by
  constructor
  · intro X D
    exact canonicalMotivicAcyclics_contains_degreeZeroA1Projection composition acyclics X D
  · intro square
    exact canonicalMotivicAcyclics_contains_degreeZeroNisnevichDescent composition acyclics square

/-- Any admissible canonical motivic-acyclic subcategory contains the
degree-zero image of every raw generator-built canonical weak equivalence on
the linear surface.  This is the direct bridge from the proof-relevant syntax
of generator composites to the semantic saturated class used in the honest
localization interface. -/
theorem canonicalMotivicAcyclics_contains_degreeZeroRawWeakEquivalences
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    (acyclics : CanonicalMotivicAcyclicsDatum composition)
    {F G : LinearPST (Boundary.canonicalCategory composition)}
    (φ : F ⟶ G)
    (hφ : canonicalA1NisWeakEquivalences composition (F := F.toPST) (G := G.toPST) φ) :
    canonicalMotivicAcyclicMorphisms composition acyclics
      ((DerivedCategory.singleFunctor
          (LinearPST (Boundary.canonicalCategory composition)) 0).map φ) := by
  exact canonicalMotivicAcyclics_contains_degreeZeroA1Nis composition acyclics φ
    (canonicalA1NisWeakEquivalences_le_saturated composition φ hφ)

/-- The derived target of the canonical `A1`/Nis localization functor, under
the additional hypothesis that the abelian localization category itself admits a
derived category. -/
abbrev canonicalA1NisLocalizedDerivedCategory
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)] :=
  DerivedCategory (canonicalA1NisLocalization composition)

/-- The canonical `A1`/Nis localization functor sends every canonical local
equivalence to an isomorphism. -/
lemma canonicalA1NisLocalizationFunctor_map_isIso_of_localEquivalence
    (composition : Boundary.CanonicalCompositionData (k := k))
    {X Y : LinearPST (Boundary.canonicalCategory composition)}
    (φ : X ⟶ Y)
    (hφ : canonicalA1NisLocalEquivalences composition φ) :
    IsIso ((canonicalA1NisLocalizationFunctor composition).map φ) := by
  let W : MorphismProperty (LinearPST (Boundary.canonicalCategory composition)) :=
    fun _ _ ψ => canonicalA1NisLocalEquivalences composition ψ
  letI : (canonicalA1NisLocalizationFunctor composition).IsLocalization W := by
    simpa [W] using canonicalA1NisLocalizationFunctor_isLocalization composition
  exact Localization.inverts (canonicalA1NisLocalizationFunctor composition) W φ hφ

/-- The canonical `A1`/Nis localization functor sends every saturated canonical
weak equivalence to an isomorphism. -/
lemma canonicalA1NisLocalizationFunctor_map_isIso_of_saturatedWeakEquivalence
    (composition : Boundary.CanonicalCompositionData (k := k))
    {X Y : LinearPST (Boundary.canonicalCategory composition)}
    (φ : X ⟶ Y)
    (hφ : canonicalA1NisSaturatedWeakEquivalences composition φ) :
    IsIso ((canonicalA1NisLocalizationFunctor composition).map φ) :=
  canonicalA1NisLocalizationFunctor_map_isIso_of_localEquivalence composition φ
    ((canonicalA1NisSaturatedWeakEquivalences_eq_localEquivalences composition φ).mp hφ)

/-- The derived functor induced by the canonical `A1`/Nis localization functor,
assuming the localization category is abelian and the localization functor is
exact in the sense required by mathlib's derived-category API. -/
def canonicalA1NisLocalization_mapDerivedCategory
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
  [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
  [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    canonicalEffectiveAmbientDerivedCategory composition ⥤
      canonicalA1NisLocalizedDerivedCategory composition :=
  (canonicalA1NisLocalizationFunctor composition).mapDerivedCategory

private noncomputable def canonicalA1NisLocalization_mapDerivedCategory_singleFunctorIso
    (composition : Boundary.CanonicalCompositionData (k := k))
    (n : ℤ)
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    DerivedCategory.singleFunctor (LinearPST (Boundary.canonicalCategory composition)) n ⋙
        canonicalA1NisLocalization_mapDerivedCategory composition ≅
      canonicalA1NisLocalizationFunctor composition ⋙
        DerivedCategory.singleFunctor (canonicalA1NisLocalization composition) n := by
  let source := LinearPST (Boundary.canonicalCategory composition)
  let target := canonicalA1NisLocalization composition
  let L := canonicalA1NisLocalizationFunctor composition
  let eSource :=
    (SingleFunctors.evaluation source (DerivedCategory source) n).mapIso
      (DerivedCategory.singleFunctorsPostcompQIso source)
  let eTarget :=
    (SingleFunctors.evaluation target (DerivedCategory target) n).mapIso
      (DerivedCategory.singleFunctorsPostcompQIso target)
  exact
    isoWhiskerRight eSource
      (canonicalA1NisLocalization_mapDerivedCategory composition) ≪≫
      Functor.associator _ _ _ ≪≫
      isoWhiskerLeft _ L.mapDerivedCategoryFactors ≪≫
      (Functor.associator _ _ _).symm ≪≫
      isoWhiskerRight
        (HomologicalComplex.singleMapHomologicalComplex L (ComplexShape.up ℤ) n)
        (DerivedCategory.Q (C := target)) ≪≫
      Functor.associator _ _ _ ≪≫
      isoWhiskerLeft L eTarget.symm

private lemma canonicalA1NisLocalization_mapDerivedCategory_singleFunctor_map_isIso
    (composition : Boundary.CanonicalCompositionData (k := k))
    (n : ℤ)
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)]
    {X Y : LinearPST (Boundary.canonicalCategory composition)}
    (φ : X ⟶ Y)
    [hφ : IsIso ((canonicalA1NisLocalizationFunctor composition).map φ)] :
    IsIso
      ((canonicalA1NisLocalization_mapDerivedCategory composition).map
        ((DerivedCategory.singleFunctor
            (LinearPST (Boundary.canonicalCategory composition)) n).map φ)) := by
  let source := LinearPST (Boundary.canonicalCategory composition)
  let target := canonicalA1NisLocalization composition
  let L := canonicalA1NisLocalizationFunctor composition
  let e := canonicalA1NisLocalization_mapDerivedCategory_singleFunctorIso composition n
  have hright : IsIso (((DerivedCategory.singleFunctor target n).map (L.map φ))) := by
    infer_instance
  have hEq :
      (canonicalA1NisLocalization_mapDerivedCategory composition).map
          ((DerivedCategory.singleFunctor source n).map φ) =
        (e.hom.app X) ≫ ((DerivedCategory.singleFunctor target n).map (L.map φ)) ≫
          (e.inv.app Y) := by
    calc
      (canonicalA1NisLocalization_mapDerivedCategory composition).map
          ((DerivedCategory.singleFunctor source n).map φ)
        = ((canonicalA1NisLocalization_mapDerivedCategory composition).map
            ((DerivedCategory.singleFunctor source n).map φ)) ≫ e.hom.app Y ≫ e.inv.app Y := by
              simp [Category.assoc]
      _ = e.hom.app X ≫ ((L ⋙ DerivedCategory.singleFunctor target n).map φ) ≫ e.inv.app Y := by
            simpa [Category.assoc] using
              congrArg (fun f => f ≫ e.inv.app Y) (e.hom.naturality φ)
      _ = (e.hom.app X) ≫ ((DerivedCategory.singleFunctor target n).map (L.map φ)) ≫
            (e.inv.app Y) := by
            simp [Functor.comp_map, Category.assoc]
  rw [hEq]
  infer_instance

/-- Abelian-valued homological functor obtained by taking degree-zero homology
after applying the derived canonical `A1`/Nis localization functor.  This is a
concrete candidate whose homological kernel should realize the canonical
motivic acyclics once the kill-lemma for canonical `A1`/Nis maps is proved. -/
def canonicalA1NisDerivedHomologyFunctor
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    canonicalEffectiveAmbientDerivedCategory composition ⥤
      canonicalA1NisLocalization composition :=
  canonicalA1NisLocalization_mapDerivedCategory composition ⋙
    DerivedCategory.homologyFunctor (canonicalA1NisLocalization composition) 0

instance canonicalA1NisDerivedHomologyFunctor_isHomological
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    (canonicalA1NisDerivedHomologyFunctor composition).IsHomological := by
  change
    ((canonicalA1NisLocalizationFunctor composition).mapDerivedCategory ⋙
      DerivedCategory.homologyFunctor (canonicalA1NisLocalization composition) 0).IsHomological
  infer_instance

noncomputable instance canonicalA1NisDerivedHomologyFunctor_shiftSequence
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    (canonicalA1NisDerivedHomologyFunctor composition).ShiftSequence ℤ :=
  Functor.ShiftSequence.tautological _ _

/-- The exact degree-zero kill target needed to extract canonical motivic
acyclics from a homological functor on the ambient derived category. -/
def CanonicalDegreeZeroKillTarget
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    {A : Type*} [Category A] [Abelian A]
    (F : canonicalEffectiveAmbientDerivedCategory composition ⥤ A)
    [F.IsHomological] [F.ShiftSequence ℤ] : Prop :=
  ∀ {X Y : LinearPST (Boundary.canonicalCategory composition)} (φ : X ⟶ Y),
    canonicalA1NisSaturatedWeakEquivalences composition φ →
      F.homologicalKernel.W
        ((DerivedCategory.singleFunctor
            (LinearPST (Boundary.canonicalCategory composition)) 0).map φ)

/-- Specialized degree-zero kill predicate for the derived canonical `A1`/Nis
localization followed by degree-zero homology. -/
abbrev canonicalA1NisDerivedHomologyDegreeZeroKillPredicate
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] : Prop :=
  CanonicalDegreeZeroKillTarget composition
    (canonicalA1NisDerivedHomologyFunctor composition)

private lemma canonicalA1NisDerivedHomologyFunctor_singleFunctor_map_isIso
    (composition : Boundary.CanonicalCompositionData (k := k))
    (n : ℤ)
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)]
    {X Y : LinearPST (Boundary.canonicalCategory composition)}
    (φ : X ⟶ Y)
    [hφ : IsIso ((canonicalA1NisLocalizationFunctor composition).map φ)] :
    IsIso
      ((canonicalA1NisDerivedHomologyFunctor composition).map
        ((DerivedCategory.singleFunctor
            (LinearPST (Boundary.canonicalCategory composition)) n).map φ)) := by
  letI := canonicalA1NisLocalization_mapDerivedCategory_singleFunctor_map_isIso
    composition n φ
  change IsIso
    ((DerivedCategory.homologyFunctor (canonicalA1NisLocalization composition) 0).map
      ((canonicalA1NisLocalization_mapDerivedCategory composition).map
        ((DerivedCategory.singleFunctor
            (LinearPST (Boundary.canonicalCategory composition)) n).map φ)))
  infer_instance

/-- The candidate derived canonical `A1`/Nis homology functor kills the
degree-zero images of all saturated canonical weak equivalences. -/
theorem canonicalA1NisDerivedHomologyDegreeZeroKillTarget
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    canonicalA1NisDerivedHomologyDegreeZeroKillPredicate composition := by
  let source := LinearPST (Boundary.canonicalCategory composition)
  let F := canonicalA1NisDerivedHomologyFunctor composition
  intro X Y φ hφ
  letI : IsIso ((canonicalA1NisLocalizationFunctor composition).map φ) :=
    canonicalA1NisLocalizationFunctor_map_isIso_of_saturatedWeakEquivalence composition φ hφ
  refine ((F.mem_homologicalKernel_W_iff
    ((DerivedCategory.singleFunctor source 0).map φ)).2 ?_)
  intro n
  change IsIso (F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧')))
  let s := (DerivedCategory.singleFunctors source).shiftIso n (-n) 0 (by omega)
  have hs :
      (((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧') ≫ s.hom.app Y =
        s.hom.app X ≫ ((DerivedCategory.singleFunctor source (-n)).map φ) := by
    simpa using s.hom.naturality φ
  have hsF :
      F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧')) ≫ F.map (s.hom.app Y) =
        F.map (s.hom.app X) ≫ F.map ((DerivedCategory.singleFunctor source (-n)).map φ) := by
    simpa [Functor.map_comp, Category.assoc] using congrArg (fun f => F.map f) hs
  letI := canonicalA1NisDerivedHomologyFunctor_singleFunctor_map_isIso composition (-n) φ
  have hmap :
      F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧')) =
        F.map (s.hom.app X) ≫ F.map ((DerivedCategory.singleFunctor source (-n)).map φ) ≫
          F.map (s.inv.app Y) := by
    have hcomp :
        ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧') ≫ s.hom.app Y) ≫ s.inv.app Y =
          (((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧') := by
      simpa [Category.assoc] using
        congrArg
          (fun f => (((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧') ≫ f)
          (Iso.hom_inv_id_app s Y)
    have hfirst :
        F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧')) =
          F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧') ≫ s.hom.app Y) ≫
            F.map (s.inv.app Y) := by
      let shiftedMap := (((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧')
      have hfirst' :
          F.map shiftedMap = F.map ((shiftedMap ≫ s.hom.app Y) ≫ s.inv.app Y) := by
        exact congrArg (fun f => F.map f) hcomp.symm
      have hmid :
          F.map ((shiftedMap ≫ s.hom.app Y) ≫ s.inv.app Y) =
            F.map (shiftedMap ≫ s.hom.app Y) ≫ F.map (s.inv.app Y) := by
        rw [Functor.map_comp]
      have hpre :
          F.map shiftedMap ≫ F.map (s.hom.app Y) = F.map (shiftedMap ≫ s.hom.app Y) := by
        simpa using (Functor.map_comp F shiftedMap (s.hom.app Y)).symm
      have hpost :
          F.map shiftedMap ≫ F.map (s.hom.app Y) ≫ F.map (s.inv.app Y) =
            F.map (shiftedMap ≫ s.hom.app Y) ≫ F.map (s.inv.app Y) := by
        simpa [Category.assoc] using congrArg (fun f => f ≫ F.map (s.inv.app Y)) hpre
      have hpost' :
          F.map shiftedMap ≫ F.map (s.hom.app Y) ≫ F.map (s.inv.app Y) =
            F.map
                ((shiftFunctor (canonicalEffectiveAmbientDerivedCategory composition) n).map
                    ((DerivedCategory.singleFunctor source 0).map φ) ≫
                  s.hom.app Y) ≫
              F.map (s.inv.app Y) := by
        simpa [shiftedMap] using hpost
      calc
        F.map shiftedMap = F.map ((shiftedMap ≫ s.hom.app Y) ≫ s.inv.app Y) := hfirst'
        _ = F.map (shiftedMap ≫ s.hom.app Y) ≫ F.map (s.inv.app Y) := hmid
        _ = F.map shiftedMap ≫ F.map (s.hom.app Y) ≫ F.map (s.inv.app Y) := hpost.symm
        _ = F.map
          ((shiftFunctor (canonicalEffectiveAmbientDerivedCategory composition) n).map
              ((DerivedCategory.singleFunctor source 0).map φ) ≫
            s.hom.app Y) ≫
              F.map (s.inv.app Y) := hpost'
    have hsecond :
        F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧') ≫ s.hom.app Y) ≫
            F.map (s.inv.app Y) =
          F.map (s.hom.app X) ≫ F.map ((DerivedCategory.singleFunctor source (-n)).map φ) ≫
            F.map (s.inv.app Y) := by
      simpa [Functor.map_comp, Category.assoc] using
        congrArg (fun f => f ≫ F.map (s.inv.app Y)) hsF
    calc
    F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧'))
      = F.map ((((DerivedCategory.singleFunctor source 0).map φ)⟦n⟧') ≫ s.hom.app Y) ≫
          F.map (s.inv.app Y) := hfirst
    _ = F.map (s.hom.app X) ≫ F.map ((DerivedCategory.singleFunctor source (-n)).map φ) ≫
          F.map (s.inv.app Y) := hsecond
  have hIso :
      IsIso
        (F.map (s.hom.app X) ≫ F.map ((DerivedCategory.singleFunctor source (-n)).map φ) ≫
          F.map (s.inv.app Y)) := by
    infer_instance
  rw [← hmap] at hIso
  exact hIso

/-- Under the degree-zero kill target, the derived canonical `A1`/Nis homology
candidate kills every raw generator-built weak equivalence on the linear
surface. -/
theorem canonicalA1NisDerivedHomology_kills_degreeZeroRawWeakEquivalences
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)]
    (hkill : canonicalA1NisDerivedHomologyDegreeZeroKillPredicate composition)
    {F G : LinearPST (Boundary.canonicalCategory composition)}
    (φ : F ⟶ G)
    (hφ : canonicalA1NisWeakEquivalences composition (F := F.toPST) (G := G.toPST) φ) :
    (canonicalA1NisDerivedHomologyFunctor composition).homologicalKernel.W
      ((DerivedCategory.singleFunctor
          (LinearPST (Boundary.canonicalCategory composition)) 0).map φ) :=
  hkill φ (canonicalA1NisWeakEquivalences_le_saturated composition φ hφ)

/-- Under the degree-zero kill target, the derived canonical `A1`/Nis homology
candidate kills each primitive canonical `A1`-projection generator in degree
zero. -/
theorem canonicalA1NisDerivedHomology_kills_degreeZeroA1Projection
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)]
    (hkill : canonicalA1NisDerivedHomologyDegreeZeroKillPredicate composition)
    (X : Geometry.SmSchemeOver k)
    (D : FiniteIrreducibleComponentDecomposition (productWithA1 X)) :
    (canonicalA1NisDerivedHomologyFunctor composition).homologicalKernel.W
      ((DerivedCategory.singleFunctor
          (LinearPST (Boundary.canonicalCategory composition)) 0).map
        (show QtrLinear (category := Boundary.canonicalCategory composition) (productWithA1 X) ⟶
            QtrLinear (category := Boundary.canonicalCategory composition) X from
          projectionToBase_QtrMapOfDecomposition
            (Boundary.canonicalCategory composition) X D)) :=
  hkill _ ((canonicalA1NisGenerators_areCanonicalLocalEquivalences composition).1 X D)

/-- Under the degree-zero kill target, the derived canonical `A1`/Nis homology
candidate kills each primitive Nisnevich descent generator in degree zero. -/
theorem canonicalA1NisDerivedHomology_kills_degreeZeroNisnevichDescent
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)]
    (hkill : canonicalA1NisDerivedHomologyDegreeZeroKillPredicate composition)
    (square : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    (canonicalA1NisDerivedHomologyFunctor composition).homologicalKernel.W
      ((DerivedCategory.singleFunctor
          (LinearPST (Boundary.canonicalCategory composition)) 0).map
        square.nisnevichDescentGeneratorMapLinear) :=
  hkill _ ((canonicalA1NisGenerators_areCanonicalLocalEquivalences composition).2 square)

/-- A homological functor on the ambient derived category yields canonical
motivic acyclics as soon as its homological kernel inverts the degree-zero
images of the canonical saturated `A1`/Nisnevich weak equivalences.

This packages the most direct mathlib route to the desired Verdier quotient:
construct a homological functor whose kernel is the intended subcategory of
motivic acyclics, then localize at that kernel. -/
def canonicalMotivicAcyclicsOfHomologicalKernel
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
  {A : Type*} [Category A] [Abelian A]
    (F : canonicalEffectiveAmbientDerivedCategory composition ⥤ A)
    [F.IsHomological] [F.ShiftSequence ℤ]
    (hF : CanonicalDegreeZeroKillTarget composition F) :
    CanonicalMotivicAcyclicsDatum composition where
  a1NisSubcategory := F.homologicalKernel
  containsCanonicalA1NisEquivalences := fun φ hφ => hF φ hφ

/-- If the degree-zero homology of the derived canonical `A1`/Nis localization
functor inverts the degree-zero images of the canonical saturated weak
equivalences, then its homological kernel furnishes the desired canonical
motivic acyclics. -/
def canonicalMotivicAcyclicsOfA1NisDerivedHomology
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)]
    (hkill : canonicalA1NisDerivedHomologyDegreeZeroKillPredicate composition) :
    CanonicalMotivicAcyclicsDatum composition :=
  letI := canonicalA1NisDerivedHomologyFunctor_isHomological composition
  letI := canonicalA1NisDerivedHomologyFunctor_shiftSequence composition
  canonicalMotivicAcyclicsOfHomologicalKernel
    composition
    (canonicalA1NisDerivedHomologyFunctor composition)
    (fun φ hφ => hkill φ hφ)

/-- Canonical motivic acyclics obtained from the actual proved degree-zero kill
theorem for the derived canonical `A1`/Nis localization followed by homology. -/
def canonicalMotivicAcyclicsOfCanonicalA1NisDerivedHomology
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    CanonicalMotivicAcyclicsDatum composition :=
  canonicalMotivicAcyclicsOfA1NisDerivedHomology composition
    (canonicalA1NisDerivedHomologyDegreeZeroKillTarget composition)

/-- The Verdier-class morphism property determined by the canonical motivic
acyclic datum produced from derived canonical `A1`/Nis homology. -/
abbrev canonicalEffectiveMotivesMorphismProperty
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    MorphismProperty (canonicalEffectiveAmbientDerivedCategory composition) :=
  canonicalMotivicAcyclicMorphisms composition
    (canonicalMotivicAcyclicsOfCanonicalA1NisDerivedHomology composition)

/-- Honest canonical effective motives: the Verdier/localization quotient of
`D(LinearPST(canonicalSmCorQ))` by the canonical motivic acyclics coming from
the derived canonical `A1`/Nis homology kernel. -/
abbrev canonicalEffectiveMotives
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :=
  canonicalEffectiveMotivesWithAcyclics composition
    (canonicalMotivicAcyclicsOfCanonicalA1NisDerivedHomology composition)

/-- The canonical Verdier-localization functor from the ambient derived
category to the honest effective-motives quotient. -/
def canonicalEffectiveMotivesLocalizationFunctor
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    canonicalEffectiveAmbientDerivedCategory composition ⥤
      canonicalEffectiveMotives composition :=
  canonicalEffectiveMotivesLocalizationFunctorWithAcyclics composition
    (canonicalMotivicAcyclicsOfCanonicalA1NisDerivedHomology composition)

instance canonicalEffectiveMotivesLocalizationFunctor_isLocalization
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)] :
    (canonicalEffectiveMotivesLocalizationFunctor composition).IsLocalization
      (canonicalEffectiveMotivesMorphismProperty composition) := by
  dsimp [canonicalEffectiveMotivesLocalizationFunctor,
    canonicalEffectiveMotivesMorphismProperty, canonicalEffectiveMotives]
  infer_instance

/-- Universal property of honest canonical effective motives: functors out of
the quotient are equivalent to functors on the ambient derived category that
invert the canonical motivic acyclic morphisms. -/
def canonicalEffectiveMotives_universalProperty
    (composition : Boundary.CanonicalCompositionData (k := k))
    [Abelian (LinearPST (Boundary.canonicalCategory composition))]
    [HasDerivedCategory (LinearPST (Boundary.canonicalCategory composition))]
    [Abelian (canonicalA1NisLocalization composition)]
    [HasDerivedCategory (canonicalA1NisLocalization composition)]
    [(canonicalA1NisLocalizationFunctor composition).Additive]
    [Limits.PreservesFiniteLimits (canonicalA1NisLocalizationFunctor composition)]
    [Limits.PreservesFiniteColimits (canonicalA1NisLocalizationFunctor composition)]
    (D : Type*) [Category D] :
    (canonicalEffectiveMotives composition ⥤ D) ≌
      (canonicalEffectiveMotivesMorphismProperty composition).FunctorsInverting D :=
  canonicalEffectiveMotivesWithAcyclics_universalProperty composition
    (canonicalMotivicAcyclicsOfCanonicalA1NisDerivedHomology composition)
    D

end

end Boundary
