import Boundary.CompositionCategory
import Boundary.PrimeSupport
import Boundary.ExternalProduct
import Geometry.Cycles.Components

universe u

variable {k : Type u} [Field k] [PerfectField k]

open AlgebraicGeometry CategoryTheory Limits

namespace Boundary

#check RepresentedPrimeSupport
#check RepresentedPrimeSupport.sourceComponent
#check PrimeFiniteCorrespondenceSupport.externalProductSupport

#check SourceIrreducibleComponent
#check SourceIrreducibleComponent.diagonalRepresentedPrimeSupport
#check SourceIrreducibleComponent.IsoOverAmbient
#check SourceIrreducibleComponent.toAmbient
#check SourceIrreducibleComponent.toAmbient_overBase

#check PrimeFiniteCorrespondenceSupport.product_diagonal_smoothObject
#check PrimeFiniteCorrespondenceSupport.product_diagonal_support
#check PrimeFiniteCorrespondenceSupport.product_diagonal_supportCanonicalImageDecomposition

end Boundary
