import Boundary.TateStabilization

/-!
# Internal Presentation Package

This file bundles the source-side minimal package, derived localization, Tate
stabilization, and envelope exactness into the internal presentation package
used downstream by recognition/comparison layers.
-/

universe u

variable {k : Type u} [Field k] [PerfectField k]

namespace Boundary

noncomputable section

/-- Boundary-side internal presentation package: minimal primitive families,
derived open/closed localization, Tate stabilization, and envelope exactness. -/
structure InternalPresentationPackageQ (category : SmCorQ (k := k)) where
  minimal : MinimalPresentationPackageQ category
  localization : OpenClosedLocalizationPresentationQ category
  stabilization : TateStabilizationPresentationQ category minimal
  envelopeExactnessTarget : Prop

namespace InternalPresentationPackageQ

/-- Forward the primitive `A1`/Nisnevich localizing family carried by the
minimal package inside an internal presentation package. -/
def toLocalizingMorphisms {category : SmCorQ (k := k)}
    (package : InternalPresentationPackageQ category) :
    LocalizingMorphismPresentationQ category :=
  package.minimal.toLocalizingMorphisms

/-- Forward the raw zigzag localization scaffold generated by the primitive
minimal-package relations. -/
def rawZigzagLocalizationConstruction {category : SmCorQ (k := k)}
    (package : InternalPresentationPackageQ category) :
    RawZigzagLocalizationConstructionQ category :=
  package.minimal.rawZigzagLocalizationConstruction

def theoremTarget {category : SmCorQ (k := k)}
    (package : InternalPresentationPackageQ category) : Prop :=
  package.minimal.theoremTarget ∧
    package.localization.theoremTarget ∧
    package.stabilization.theoremTarget ∧
    package.envelopeExactnessTarget

end InternalPresentationPackageQ

/-- Exact relation between the minimal package and the full internal package via
derived soundness. -/
structure PresentationVsDerivedSoundnessQ (category : SmCorQ (k := k)) where
  minimal : MinimalPresentationPackageQ category
  internal : InternalPresentationPackageQ category
  derivedSoundness : DerivedSoundnessQ category minimal
  theoremTarget : Prop

/-- Certified wrapper for the bundled internal package. -/
structure CertifiedInternalPresentationPackageQ (category : SmCorQ (k := k)) where
  target : InternalPresentationPackageQ category
  theorem_holds : target.theoremTarget

end

end Boundary
