import Boundary.PresheavesWithTransfers

/-!
# Raw Zigzag Localization Scaffold For Presheaves With Transfers

This file provides the honest proof-relevant raw zigzag scaffold needed above
presheaves with transfers: chosen morphisms to invert, generated weak
equivalence closure under identity and composition, and raw zigzags generated
by forward morphisms and formal inverses.
-/

universe u

variable {k : Type u} [Field k] [PerfectField k]

open CategoryTheory

namespace Boundary

noncomputable section

/-- Chosen localizing morphisms in the presheaf-with-transfers category.  Later
localization stages supply the concrete generator family, for example
open/closed, Nisnevich, or `A1` maps. -/
structure LocalizingMorphismPresentationQ (category : SmCorQ (k := k)) where
  Generator : Type (u + 1)
  data : Generator → Sigma fun X : PST category =>
    Sigma fun Y : PST category =>
      (X ⟶ Y)

namespace LocalizingMorphismPresentationQ

def source
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
  PST category :=
  (presentation.data g).1

def target
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
  PST category :=
  (presentation.data g).2.1

def map
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
  presentation.source g ⟶ presentation.target g :=
  (presentation.data g).2.2

def generator
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
    Sigma fun X : PST category =>
      Sigma fun Y : PST category =>
        (X ⟶ Y) :=
  presentation.data g

end LocalizingMorphismPresentationQ

/-- Proof-relevant weak equivalences generated by the chosen localizing maps and
closed only under identity and composition. -/
inductive GeneratedWeakEquivalenceQ
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  {X Y : PST category} →
  (X ⟶ Y) → Type _ where
  | ofGenerator (g : presentation.Generator) :
      GeneratedWeakEquivalenceQ presentation (presentation.map g)
  | id (X : PST category) :
    GeneratedWeakEquivalenceQ presentation (𝟙 X)
  | comp
    {X Y Z : PST category}
    {f : X ⟶ Y}
    {g : Y ⟶ Z} :
      GeneratedWeakEquivalenceQ presentation f →
      GeneratedWeakEquivalenceQ presentation g →
    GeneratedWeakEquivalenceQ presentation (f ≫ g)

/-- Explicit later saturation obligation, recorded rather than assumed. -/
def GeneratedWeakEquivalenceTwoOutOfThreeTargetQ
    {category : SmCorQ (k := k)}
  (presentation : LocalizingMorphismPresentationQ category) : Type _ :=
  ∀ {X Y Z : PST category}
    {f : X ⟶ Y}
    {g : Y ⟶ Z},
    GeneratedWeakEquivalenceQ presentation f →
    GeneratedWeakEquivalenceQ presentation (f ≫ g) →
    GeneratedWeakEquivalenceQ presentation g

/-- One step in the raw zigzag localization category.  Backward steps are
formal inverses of chosen weak equivalences. -/
inductive ZigzagStepQ
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  PST category → PST category → Type _ where
  | forward {X Y : PST category} :
    (X ⟶ Y) → ZigzagStepQ presentation X Y
  | backward {X Y : PST category}
    (f : Y ⟶ X) :
      GeneratedWeakEquivalenceQ presentation f →
      ZigzagStepQ presentation X Y

/-- Raw zigzags generated by ordinary morphisms and formal inverses of chosen
weak equivalences. -/
inductive ZigzagHomQ
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  PST category → PST category → Type _ where
  | nil (X : PST category) : ZigzagHomQ presentation X X
  | cons {X Y Z : PST category} :
      ZigzagStepQ presentation X Y →
      ZigzagHomQ presentation Y Z →
      ZigzagHomQ presentation X Z

namespace ZigzagHomQ

def id
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  (X : PST category) :
    ZigzagHomQ presentation X X :=
  .nil X

def comp
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y Z : PST category} :
    ZigzagHomQ presentation X Y →
    ZigzagHomQ presentation Y Z →
    ZigzagHomQ presentation X Z
  | .nil _, g => g
  | .cons step tail, g => .cons step (comp tail g)

def ofForward
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
  (f : X ⟶ Y) :
    ZigzagHomQ presentation X Y :=
  .cons (.forward f) (.nil Y)

def ofBackward
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
  (f : Y ⟶ X)
    (hf : GeneratedWeakEquivalenceQ presentation f) :
    ZigzagHomQ presentation X Y :=
  .cons (.backward f hf) (.nil Y)

@[simp] theorem id_comp
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
    (f : ZigzagHomQ presentation X Y) :
    comp (id X) f = f :=
  rfl

@[simp] theorem comp_id
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
    (f : ZigzagHomQ presentation X Y) :
    comp f (id Y) = f := by
  induction f with
  | nil _ => rfl
  | cons _ tail ih => simp [comp, ih]

@[simp] theorem assoc
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {W X Y Z : PST category}
    (f : ZigzagHomQ presentation W X)
    (g : ZigzagHomQ presentation X Y)
    (h : ZigzagHomQ presentation Y Z) :
    comp (comp f g) h = comp f (comp g h) := by
  induction f with
  | nil _ => rfl
  | cons _ tail ih => simp [comp, ih]

end ZigzagHomQ

/-- Raw zigzag category structure generated by a chosen family of localizing
morphisms.  The quotient identifying equivalent zigzags and the universal
localization property are later steps, deliberately kept separate from this
proof-relevant scaffold. -/
structure RawZigzagLocalizationConstructionQ (category : SmCorQ (k := k)) where
  Obj : Type _
  Hom : Obj → Obj → Type _
  id : ∀ X, Hom X X
  comp : ∀ {X Y Z : Obj}, Hom X Y → Hom Y Z → Hom X Z

namespace RawZigzagLocalizationConstructionQ

/-- Exact remaining obligations before the raw zigzag category can be promoted
to an honest categorical localization of `PST`. -/
structure ZigzagQuotientLocalizationUniversalPropertyObligationQ
    {category : SmCorQ (k := k)} where
  quotientByZigzagEquivalenceTarget : Prop
  localizationFunctorTarget : Prop
  universalPropertyTarget : Prop

def ofLocalizingMorphisms
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
    RawZigzagLocalizationConstructionQ category where
  Obj := PST category
  Hom := ZigzagHomQ presentation
  id := ZigzagHomQ.id
  comp := fun f g => ZigzagHomQ.comp f g

def rawZigzagCategoryStruct
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  CategoryStruct (PST category) where
  Hom X Y := ZigzagHomQ presentation X Y
  id := ZigzagHomQ.id
  comp := fun f g => ZigzagHomQ.comp f g

def toRawZigzagCategory
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  Category (PST category) where
  Hom X Y := ZigzagHomQ presentation X Y
  id := ZigzagHomQ.id
  comp := fun f g => ZigzagHomQ.comp f g
  id_comp := ZigzagHomQ.id_comp
  comp_id := ZigzagHomQ.comp_id
  assoc := ZigzagHomQ.assoc

end RawZigzagLocalizationConstructionQ

end

end Boundary
