import Boundary.PresheavesWithTransfers

/-!
# Raw Zigzag Localization Scaffold For Presheaves With Transfers

This file provides the honest proof-relevant raw zigzag scaffold needed above
presheaves with transfers: chosen morphisms to invert, generated weak
equivalence closure under identity and composition, and raw zigzags generated
by forward morphisms and formal inverses.
-/

universe u

variable {k : Type u} [Field k] [PerfectField k]

open CategoryTheory

namespace Boundary

noncomputable section

/-- Chosen localizing morphisms in the presheaf-with-transfers category.  Later
localization stages supply the concrete generator family, for example
open/closed, Nisnevich, or `A1` maps. -/
structure LocalizingMorphismPresentationQ (category : SmCorQ (k := k)) where
  Generator : Type (u + 1)
  data : Generator → Sigma fun X : PST category =>
    Sigma fun Y : PST category =>
      (X ⟶ Y)

namespace LocalizingMorphismPresentationQ

def source
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
  PST category :=
  (presentation.data g).1

def target
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
  PST category :=
  (presentation.data g).2.1

def map
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
  presentation.source g ⟶ presentation.target g :=
  (presentation.data g).2.2

def generator
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category)
    (g : presentation.Generator) :
    Sigma fun X : PST category =>
      Sigma fun Y : PST category =>
        (X ⟶ Y) :=
  presentation.data g

end LocalizingMorphismPresentationQ

/-- Proof-relevant weak equivalences generated by the chosen localizing maps and
closed only under identity and composition. -/
inductive GeneratedWeakEquivalenceQ
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  {X Y : PST category} →
  (X ⟶ Y) → Type _ where
  | ofGenerator (g : presentation.Generator) :
      GeneratedWeakEquivalenceQ presentation (presentation.map g)
  | id (X : PST category) :
    GeneratedWeakEquivalenceQ presentation (𝟙 X)
  | comp
    {X Y Z : PST category}
    {f : X ⟶ Y}
    {g : Y ⟶ Z} :
      GeneratedWeakEquivalenceQ presentation f →
      GeneratedWeakEquivalenceQ presentation g →
    GeneratedWeakEquivalenceQ presentation (f ≫ g)

/-- One step in the raw zigzag localization category.  Backward steps are
formal inverses of chosen weak equivalences. -/
inductive ZigzagStepQ
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  PST category → PST category → Type _ where
  | forward {X Y : PST category} :
    (X ⟶ Y) → ZigzagStepQ presentation X Y
  | backward {X Y : PST category}
    (f : Y ⟶ X) :
      GeneratedWeakEquivalenceQ presentation f →
      ZigzagStepQ presentation X Y

/-- Raw zigzags generated by ordinary morphisms and formal inverses of chosen
weak equivalences. -/
inductive ZigzagHomQ
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  PST category → PST category → Type _ where
  | nil (X : PST category) : ZigzagHomQ presentation X X
  | cons {X Y Z : PST category} :
      ZigzagStepQ presentation X Y →
      ZigzagHomQ presentation Y Z →
      ZigzagHomQ presentation X Z

namespace ZigzagHomQ

def id
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  (X : PST category) :
    ZigzagHomQ presentation X X :=
  .nil X

def comp
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y Z : PST category} :
    ZigzagHomQ presentation X Y →
    ZigzagHomQ presentation Y Z →
    ZigzagHomQ presentation X Z
  | .nil _, g => g
  | .cons step tail, g => .cons step (comp tail g)

def ofForward
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
  (f : X ⟶ Y) :
    ZigzagHomQ presentation X Y :=
  .cons (.forward f) (.nil Y)

def ofBackward
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
  (f : Y ⟶ X)
    (hf : GeneratedWeakEquivalenceQ presentation f) :
    ZigzagHomQ presentation X Y :=
  .cons (.backward f hf) (.nil Y)

@[simp] theorem id_comp
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
    (f : ZigzagHomQ presentation X Y) :
    comp (id X) f = f :=
  rfl

@[simp] theorem comp_id
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {X Y : PST category}
    (f : ZigzagHomQ presentation X Y) :
    comp f (id Y) = f := by
  induction f with
  | nil _ => rfl
  | cons _ tail ih => simp [comp, ih]

@[simp] theorem assoc
    {category : SmCorQ (k := k)}
    {presentation : LocalizingMorphismPresentationQ category}
  {W X Y Z : PST category}
    (f : ZigzagHomQ presentation W X)
    (g : ZigzagHomQ presentation X Y)
    (h : ZigzagHomQ presentation Y Z) :
    comp (comp f g) h = comp f (comp g h) := by
  induction f with
  | nil _ => rfl
  | cons _ tail ih => simp [comp, ih]

end ZigzagHomQ

/-- Raw zigzag category structure generated by a chosen family of localizing
morphisms. -/
structure RawZigzagLocalizationConstructionQ (category : SmCorQ (k := k)) where
  Obj : Type _
  Hom : Obj → Obj → Type _
  id : ∀ X, Hom X X
  comp : ∀ {X Y Z : Obj}, Hom X Y → Hom Y Z → Hom X Z

namespace RawZigzagLocalizationConstructionQ

def ofLocalizingMorphisms
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
    RawZigzagLocalizationConstructionQ category where
  Obj := PST category
  Hom := ZigzagHomQ presentation
  id := ZigzagHomQ.id
  comp := fun f g => ZigzagHomQ.comp f g

def rawZigzagCategoryStruct
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  CategoryStruct (PST category) where
  Hom X Y := ZigzagHomQ presentation X Y
  id := ZigzagHomQ.id
  comp := fun f g => ZigzagHomQ.comp f g

def toRawZigzagCategory
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  Category (PST category) where
  Hom X Y := ZigzagHomQ presentation X Y
  id := ZigzagHomQ.id
  comp := fun f g => ZigzagHomQ.comp f g
  id_comp := ZigzagHomQ.id_comp
  comp_id := ZigzagHomQ.comp_id
  assoc := ZigzagHomQ.assoc

end RawZigzagLocalizationConstructionQ

/-- Arrow-level retract datum used for saturating a class of weak-equivalences.

This is the standard diagrammatic datum used to prove retract stability, as in
Gabriel–Zisman, *Calculus of Fractions and Homotopy Theory*, §2.2. -/
structure GeneratedWeakEquivalenceRetraction
    {category : SmCorQ (k := k)}
    {X Y X' Y' : PST category}
    (f : X ⟶ Y) (g : X' ⟶ Y') where
  leftTo : X ⟶ X'
  leftFrom : X' ⟶ X
  rightTo : Y ⟶ Y'
  rightFrom : Y' ⟶ Y
  left_retract : leftTo ≫ leftFrom = 𝟙 X
  right_retract : rightTo ≫ rightFrom = 𝟙 Y
  square_to : f ≫ rightTo = leftTo ≫ g
  square_from : g ≫ rightFrom = leftFrom ≫ f

/-- Saturation of generator-built weak equivalences.

This is the canonical closure construction that explicitly adds identities,
composition, two-out-of-three, and retracts to `GeneratedWeakEquivalenceQ`.
We keep the constructors explicit to avoid downstream placeholder abstractions.
-/
inductive GeneratedWeakEquivalenceSaturationQ
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ category) :
  {X Y : PST category} →
  (X ⟶ Y) → Type _ where
  | ofGenerated
      {X Y : PST category}
      {f : X ⟶ Y}
      (h : GeneratedWeakEquivalenceQ presentation f) :
      GeneratedWeakEquivalenceSaturationQ presentation f
  | ofIdentity
      (X : PST category) :
      GeneratedWeakEquivalenceSaturationQ presentation (𝟙 X)
  | ofComposition
      {X Y Z : PST category}
      {f : X ⟶ Y}
      {g : Y ⟶ Z}
      (hf : GeneratedWeakEquivalenceSaturationQ presentation f)
      (hg : GeneratedWeakEquivalenceSaturationQ presentation g) :
      GeneratedWeakEquivalenceSaturationQ presentation (f ≫ g)
  | ofLeftOfComposition
      {X Y Z : PST category}
      {f : X ⟶ Y}
      {g : Y ⟶ Z}
      (hg : GeneratedWeakEquivalenceSaturationQ presentation g)
      (hfg : GeneratedWeakEquivalenceSaturationQ presentation (f ≫ g)) :
      GeneratedWeakEquivalenceSaturationQ presentation f
  | ofRightOfComposition
      {X Y Z : PST category}
      {f : X ⟶ Y}
      {g : Y ⟶ Z}
      (hf : GeneratedWeakEquivalenceSaturationQ presentation f)
      (hfg : GeneratedWeakEquivalenceSaturationQ presentation (f ≫ g)) :
      GeneratedWeakEquivalenceSaturationQ presentation g
  | ofRetraction
      {X Y X' Y' : PST category}
      {f : X ⟶ Y}
      {g : X' ⟶ Y'}
      (r : GeneratedWeakEquivalenceRetraction (category := category) f g)
      (hg : GeneratedWeakEquivalenceSaturationQ presentation g) :
      GeneratedWeakEquivalenceSaturationQ presentation f
  | ofIso
      {X Y : PST category} (f : X ⟶ Y) [CategoryTheory.IsIso f] :
      GeneratedWeakEquivalenceSaturationQ presentation f

/-- Saturation as a `MorphismProperty`. -/
def GeneratedWeakEquivalenceSaturation
    (category : SmCorQ (k := k))
    (presentation : LocalizingMorphismPresentationQ (k := k) category) :
    MorphismProperty (PST category) :=
  fun _ _ f => Nonempty (GeneratedWeakEquivalenceSaturationQ (k := k) presentation f)

/-- Closure of a property under generated-equivalence saturation constructors. -/
structure GeneratedWeakEquivalenceSaturationClosure
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ (k := k) category)
    (W : MorphismProperty (PST category)) : Prop where
  contains_generators :
    ∀ {X Y : PST category} (f : X ⟶ Y),
      GeneratedWeakEquivalenceSaturationQ (k := k) presentation f →
        W f
  identities :
    ∀ X : PST category, W (𝟙 X)
  closed_under_composition :
    ∀ {X Y Z : PST category}
      {f : X ⟶ Y} {g : Y ⟶ Z}, W f → W g → W (f ≫ g)
  two_out_of_three_left :
    ∀ {X Y Z : PST category}
      {f : X ⟶ Y} {g : Y ⟶ Z}, W g → W (f ≫ g) → W f
  two_out_of_three_right :
    ∀ {X Y Z : PST category}
      {f : X ⟶ Y} {g : Y ⟶ Z}, W f → W (f ≫ g) → W g
  retracts :
    ∀ {X Y X' Y' : PST category}
      {f : X ⟶ Y} {g : X' ⟶ Y'},
      GeneratedWeakEquivalenceRetraction (category := category) f g → W g → W f

/-- Raw generated weak-equivalences embed into their saturation. -/
theorem GeneratedWeakEquivalence_to_saturation
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ (k := k) category)
    {X Y : PST category}
    {f : X ⟶ Y}
    (h : GeneratedWeakEquivalenceQ presentation f) :
    GeneratedWeakEquivalenceSaturation (k := k) category presentation f :=
  ⟨GeneratedWeakEquivalenceSaturationQ.ofGenerated h⟩

/-- Closure lemmas for the saturation construction by definition. -/
theorem GeneratedWeakEquivalenceSaturation_closure
    {category : SmCorQ (k := k)}
    (presentation : LocalizingMorphismPresentationQ (k := k) category) :
    GeneratedWeakEquivalenceSaturationClosure (k := k) presentation
      (GeneratedWeakEquivalenceSaturation (k := k) category presentation) := by
  refine
    { contains_generators := ?_
      identities := ?_
      closed_under_composition := ?_
      two_out_of_three_left := ?_
      two_out_of_three_right := ?_
      retracts := ?_ }
  · intro X Y f hf
    exact ⟨hf⟩
  · intro X
    exact ⟨GeneratedWeakEquivalenceSaturationQ.ofIdentity (presentation := presentation) X⟩
  · intro X Y Z f g hf hg
    rcases hf with ⟨hf⟩
    rcases hg with ⟨hg⟩
    exact ⟨GeneratedWeakEquivalenceSaturationQ.ofComposition hf hg⟩
  · intro X Y Z f g hg hfg
    rcases hg with ⟨hg⟩
    rcases hfg with ⟨hfg⟩
    exact ⟨GeneratedWeakEquivalenceSaturationQ.ofLeftOfComposition hg hfg⟩
  · intro X Y Z f g hf hfg
    rcases hf with ⟨hf⟩
    rcases hfg with ⟨hfg⟩
    exact ⟨GeneratedWeakEquivalenceSaturationQ.ofRightOfComposition hf hfg⟩
  · intro X Y X' Y' f g r hg
    rcases hg with ⟨hg⟩
    exact ⟨GeneratedWeakEquivalenceSaturationQ.ofRetraction r hg⟩

end

end Boundary
