import Boundary.A1Invariance
import Boundary.NisnevichDescent

/-!
# Minimal Presentation Package

This file records the source-side minimal presentation package built from the
primitive families `Corr`, `A1`, and `Nis`, together with the exact closure
operations used downstream in the manuscript.
-/

universe u

variable {k : Type u} [Field k] [PerfectField k]

namespace Boundary

noncomputable section

/-- Generator data for the minimal presentation package.  This is the boundary
side version of the manuscript's `M(X,p,m)` data: a smooth scheme, an
idempotent projector in `SmCor_Q`, and an integral twist index. -/
structure MinimalPresentationGeneratorQ (category : SmCorQ (k := k)) where
  scheme : Geometry.SmSchemeOver k
  projector : SmCorQ.Hom category scheme scheme
  projectorIdempotentTarget : category.comp projector projector = projector
  twist : Int

/-- Exact closure operations carried by the minimal presentation package.  These
are recorded as named targets until the later dg/triangulated infrastructure is
threaded through the boundary-side construction. -/
structure MinimalPresentationClosureQ where
  directSumTarget : Prop
  shiftTarget : Prop
  coneTarget : Prop
  karoubiTarget : Prop
  tensorTarget : Prop
  dualTarget : Prop

namespace MinimalPresentationClosureQ

def theoremTarget (closure : MinimalPresentationClosureQ) : Prop :=
  closure.directSumTarget ∧ closure.shiftTarget ∧ closure.coneTarget ∧
    closure.karoubiTarget ∧ closure.tensorTarget ∧ closure.dualTarget

end MinimalPresentationClosureQ

/-- Boundary-side form of the manuscript's minimal presentation package.  The
primitive relation families are the rational correspondence category itself,
`A1`-contraction, and Nisnevich descent. -/
structure MinimalPresentationPackageQ (category : SmCorQ (k := k)) where
  GeneratorIndex : Type (u + 1)
  generator : GeneratorIndex → MinimalPresentationGeneratorQ category
  a1LocalizationTarget : A1LocalizationTargetQ category
  nisnevichLocalizingMapObligation : NisnevichLocalizingMapObligationQ category
  closure : MinimalPresentationClosureQ

namespace MinimalPresentationPackageQ

/-- Primitive localization generators coming from the `A1` and Nisnevich
families carried by a minimal presentation package. -/
inductive PrimitiveLocalizationGeneratorQ
    {category : SmCorQ (k := k)}
    (package : MinimalPresentationPackageQ category) where
  | a1 (witness : package.a1LocalizationTarget.Witness)
  | nisnevich (square : package.nisnevichLocalizingMapObligation.Square)

/-- The raw localizing morphism family generated by the `A1` and Nisnevich
relations in a minimal presentation package. -/
def toLocalizingMorphisms {category : SmCorQ (k := k)}
    (package : MinimalPresentationPackageQ category) :
    LocalizingMorphismPresentationQ category where
  Generator := PrimitiveLocalizationGeneratorQ package
  data := fun
    | .a1 witness =>
        ⟨(package.a1LocalizationTarget.witness witness).sourcePresheaf,
          (package.a1LocalizationTarget.witness witness).targetPresheaf,
          (package.a1LocalizationTarget.witness witness).homotopyMap⟩
    | .nisnevich square => package.nisnevichLocalizingMapObligation.localizingData square

/-- The proof-relevant raw zigzag localization scaffold generated by the
primitive `A1` and Nisnevich relations in a minimal presentation package. -/
def rawZigzagLocalizationConstruction {category : SmCorQ (k := k)}
    (package : MinimalPresentationPackageQ category) :
    RawZigzagLocalizationConstructionQ category :=
  RawZigzagLocalizationConstructionQ.ofLocalizingMorphisms package.toLocalizingMorphisms

def theoremTarget {category : SmCorQ (k := k)}
    (package : MinimalPresentationPackageQ category) : Prop :=
  package.a1LocalizationTarget.theoremTarget ∧
    package.nisnevichLocalizingMapObligation.theoremTarget ∧
    package.closure.theoremTarget

end MinimalPresentationPackageQ

/-- Exact theorem surface for the manuscript's derived-soundness proposition on
top of the minimal package. -/
structure DerivedSoundnessQ (category : SmCorQ (k := k))
    (package : MinimalPresentationPackageQ category) where
  envelopeDerivedTarget : Prop
  localizationDerivedTarget : Prop
  stabilizationDerivedTarget : Prop
  theoremTarget : Prop

/-- Certified wrapper for the source-side minimal package. -/
structure CertifiedMinimalPresentationPackageQ (category : SmCorQ (k := k)) where
  target : MinimalPresentationPackageQ category
  theorem_holds : target.theoremTarget

end

end Boundary
