import Boundary.NisnevichPullbackTransfer
import Mathlib.CategoryTheory.Sites.Coverage
import Mathlib.CategoryTheory.Sites.LeftExact

/-!
# Nisnevich Presieve Definitions for Sm/k

This file defines the generating presieve for a Nisnevich distinguished square,
the canonical Nisnevich covering families on each object of `Geometry.SmSchemeOver k`,
and the resulting coverage/topology objects.

Nisnevich distinguished squares and their associated covers are the standard
cd-structure generators for the Nisnevich topology; cf. Nisnevich, "The
completely decomposed topology on schemes and associated descent spectral
sequences", and Morel-Voevodsky, "A¹-homotopy theory of schemes", §3.

## What is here

- `nisnevichCoverPresieve sq` — the two-morphism presieve
  `{openToBase, patchToBase}` on `sq.base` for a distinguished square `sq`.

- `NisnevichCovering ... X` — the canonical Nisnevich covering presieves
  on `X`, generated by distinguished squares valued in the concrete canonical
  correspondence category.
- `NisnevichCoverage ...` — the canonical coverage on `Sm/k`.
- `NisnevichTopology ...` — the associated Grothendieck topology.

The canonical pullback closure is now packaged through
`NisnevichDistinguishedSquareDataQ.pullback`, so the remaining work in this file
is to prove the presieve-level factorization needed for `Coverage.pullback` and
to package the resulting canonical coverage and topology.
-/

universe u

variable {k : Type u} [Field k] [PerfectField k]

open AlgebraicGeometry CategoryTheory

namespace Boundary

noncomputable section

/-!
## Generating presieve for a Nisnevich distinguished square
-/

private theorem openToBase_isSmooth
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    IsSmooth sq.openToBase.hom := by
  letI := sq.openToBase_isOpenImmersion
  infer_instance

private theorem openToBase_isSeparated
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    IsSeparated sq.openToBase.hom := by
  letI := sq.openToBase_isOpenImmersion
  infer_instance

private theorem openToBase_isFiniteType
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    Geometry.IsOfFiniteType sq.openToBase.hom := by
  letI := sq.openToBase_isOpenImmersion
  exact ⟨inferInstance, inferInstance⟩

private theorem patchToBase_isSmooth
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    IsSmooth sq.patchToBase.hom :=
  sq.patchToBase_isEtale.isSmooth

private theorem patchToBase_isSeparated
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    IsSeparated sq.patchToBase.hom := by
  letI : IsSeparated sq.base.structMap := sq.base.separated
  letI : IsSeparated (sq.patchToBase.hom ≫ sq.base.structMap) := by
    simpa [sq.patchToBase.over] using sq.patchPiece.separated
  exact IsSeparated.of_comp (f := sq.patchToBase.hom) (g := sq.base.structMap)

private theorem patchToBase_isFiniteType
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition)) :
    Geometry.IsOfFiniteType sq.patchToBase.hom := by
  letI : LocallyOfFiniteType (sq.patchToBase.hom ≫ sq.base.structMap) := by
    simpa [sq.patchToBase.over] using sq.patchPiece.locallyOfFiniteType_structMap
  exact ⟨inferInstance,
    locallyOfFiniteType_of_comp (f := sq.patchToBase.hom) (g := sq.base.structMap)⟩

private def baseChange_open_to_open
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition))
    {Y : Geometry.SmSchemeOver k}
    (f : SmOverHom Y sq.base) :
    SmOverHom (NisnevichDistinguishedSquareDataQ.baseChange_open sq f) sq.openPiece :=
  SmSchemeOver.pullbackFst
    sq.openToBase
    f
    (openToBase_isSmooth composition sq)
    (openToBase_isSeparated composition sq)
    (openToBase_isFiniteType composition sq)

private theorem baseChange_open_to_open_comp_eq
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition))
    {Y : Geometry.SmSchemeOver k}
    (f : SmOverHom Y sq.base) :
    baseChange_open_to_open composition sq f ≫ sq.openToBase =
      NisnevichDistinguishedSquareDataQ.baseChange_open_to_base sq f ≫ f := by
  simpa [baseChange_open_to_open,
      NisnevichDistinguishedSquareDataQ.baseChange_open_to_base,
      NisnevichDistinguishedSquareDataQ.baseChange_open] using
    SmSchemeOver.pullbackFst_comp_eq
      sq.openToBase
      f
      (openToBase_isSmooth composition sq)
      (openToBase_isSeparated composition sq)
      (openToBase_isFiniteType composition sq)

private def baseChange_patch_to_patch
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition))
    {Y : Geometry.SmSchemeOver k}
    (f : SmOverHom Y sq.base) :
    SmOverHom (NisnevichDistinguishedSquareDataQ.baseChange_patch sq f) sq.patchPiece :=
  SmSchemeOver.pullbackFst
    sq.patchToBase
    f
    (patchToBase_isSmooth composition sq)
    (patchToBase_isSeparated composition sq)
    (patchToBase_isFiniteType composition sq)

private theorem baseChange_patch_to_patch_comp_eq
    (composition : Boundary.CanonicalCompositionData (k := k))
    (sq : NisnevichDistinguishedSquareDataQ (Boundary.canonicalCategory composition))
    {Y : Geometry.SmSchemeOver k}
    (f : SmOverHom Y sq.base) :
    baseChange_patch_to_patch composition sq f ≫ sq.patchToBase =
      NisnevichDistinguishedSquareDataQ.baseChange_patch_to_base sq f ≫ f := by
  simpa [baseChange_patch_to_patch,
      NisnevichDistinguishedSquareDataQ.baseChange_patch_to_base,
      NisnevichDistinguishedSquareDataQ.baseChange_patch] using
    SmSchemeOver.pullbackFst_comp_eq
      sq.patchToBase
      f
      (patchToBase_isSmooth composition sq)
      (patchToBase_isSeparated composition sq)
      (patchToBase_isFiniteType composition sq)

/-- The two-morphism generating presieve on `sq.base` determined by a Nisnevich
distinguished square: a morphism `f : Y ⟶ sq.base` belongs to this presieve
iff it equals the open-piece inclusion **or** the patch-piece étale map. -/
def nisnevichCoverPresieve
    {category : SmCorQ (k := k)}
    (sq : NisnevichDistinguishedSquareDataQ category) :
    Presieve sq.base :=
  fun Y f =>
    (∃ h : Y = sq.openPiece, h ▸ f = sq.openToBase) ∨
    (∃ h : Y = sq.patchPiece, h ▸ f = sq.patchToBase)

/-- `openToBase` belongs to the generating presieve of its distinguished square. -/
theorem nisnevichCoverPresieve_openToBase
    {category : SmCorQ (k := k)}
    (sq : NisnevichDistinguishedSquareDataQ category) :
    nisnevichCoverPresieve sq sq.openToBase :=
  Or.inl ⟨rfl, rfl⟩

/-- `patchToBase` belongs to the generating presieve of its distinguished square. -/
theorem nisnevichCoverPresieve_patchToBase
    {category : SmCorQ (k := k)}
    (sq : NisnevichDistinguishedSquareDataQ category) :
    nisnevichCoverPresieve sq sq.patchToBase :=
  Or.inr ⟨rfl, rfl⟩

/-!
## Nisnevich covering families
-/

/-- The collection of Nisnevich covering presieves on `X`: those equal to the
generating presieve of some Nisnevich distinguished square with base `X`.

A presieve `S` on `X` is in `nisnevichCovering X` iff there exist a
rationalization category `cat` and a distinguished square `sq` with
`sq.base = X` such that `S = nisnevichCoverPresieve sq` (after transport
along `sq.base = X`). -/
def nisnevichCovering
    (X : Geometry.SmSchemeOver k) : Set (Presieve X) :=
  { S | ∃ (cat : SmCorQ (k := k))
           (sq : NisnevichDistinguishedSquareDataQ cat)
           (h : sq.base = X),
         S = h ▸ nisnevichCoverPresieve sq }

/-- The generating presieve of a square with base `X` lies in
`nisnevichCovering X`. -/
theorem nisnevichCoverPresieve_mem_nisnevichCovering
    {category : SmCorQ (k := k)}
    (sq : NisnevichDistinguishedSquareDataQ category) :
    nisnevichCoverPresieve sq ∈ nisnevichCovering sq.base :=
  ⟨category, sq, rfl, rfl⟩

section ConcreteCanonical

variable
  (diagonalDecomposition :
    (X : Geometry.SmSchemeOver k) → Boundary.FiniteIrreducibleComponentDecomposition X)
  (packages : ConcreteLiftedPackages (k := k))
  (leftIdentityPackage : ConcreteLiftedIdentityPackages (k := k))
  (leftIdentity_constant :
      ∀ {X Y : Geometry.SmSchemeOver k}
        (P : Boundary.RepresentedPrimeSupport X Y)
        (component : Boundary.SourceIrreducibleComponent X)
      (toComponent : P.sourceImage.carrier.scheme ⟶ component.carrier.scheme)
      (_htoComponent : toComponent ≫ component.toAmbient = P.sourceImage.toAmbient),
        packages (Boundary.SourceIrreducibleComponent.diagonalPrimeGeom component)
            (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented P) =
          leftIdentityPackage (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented P))
  (rightIdentityPackage : ConcreteLiftedIdentityPackages (k := k))
  (rightIdentity_constant :
    ∀ {X Y : Geometry.SmSchemeOver k}
      (prime : Boundary.PrimeFiniteCorrespondenceGeom X Y)
      (diagClass : Boundary.PrimeFiniteCorrespondenceGeom Y Y),
        diagClass ∈ (diagonalDecomposition Y).diagonalPrimeClasses →
          packages prime diagClass = rightIdentityPackage prime)
  (landing_eq_diagonalRightIdentity :
    ∀ {X Y : Geometry.SmSchemeOver k}
      (P : Boundary.RepresentedPrimeSupport X Y),
        Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductImageCompositionPackageFamily.decomposition
            (fun {X} {Y} {Z} x y =>
              Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductLiftedImageCompositionPackage.toSupportFiberProductImageCompositionPackage
                (packages (X := X) (Y := Y) (Z := Z) x y))
            P
            (Boundary.SourceIrreducibleComponent.diagonalRepresentedPrimeSupport
              ((Boundary.FiniteIrreducibleComponentDecomposition.landingComponent_of_finite
                (diagonalDecomposition Y) P).1.1)) =
          Boundary.RepresentedPrimeCompositionDatum.diagonalRightIdentityImageDecomposition
            P
            ((Boundary.FiniteIrreducibleComponentDecomposition.landingComponent_of_finite
              (diagonalDecomposition Y) P).1.1)
            ((Boundary.FiniteIrreducibleComponentDecomposition.landingComponent_of_finite
              (diagonalDecomposition Y) P).2.1)
            ((Boundary.FiniteIrreducibleComponentDecomposition.landingComponent_of_finite
              (diagonalDecomposition Y) P).2.2))
  (leftPresentation :
    ∀ {W X Y Z : Geometry.SmSchemeOver k},
      Boundary.RepresentedPrimeSupport W X →
      Boundary.RepresentedPrimeSupport X Y →
      Boundary.RepresentedPrimeSupport Y Z →
        Boundary.FiniteCorrespondencePresentation W Z)
  (rightPresentation :
    ∀ {W X Y Z : Geometry.SmSchemeOver k},
      Boundary.RepresentedPrimeSupport W X →
      Boundary.RepresentedPrimeSupport X Y →
      Boundary.RepresentedPrimeSupport Y Z →
        Boundary.FiniteCorrespondencePresentation W Z)
  (hpresentation :
    ∀ {W X Y Z : Geometry.SmSchemeOver k}
      (P : Boundary.RepresentedPrimeSupport W X)
      (Q : Boundary.RepresentedPrimeSupport X Y)
      (R : Boundary.RepresentedPrimeSupport Y Z),
        rightPresentation P Q R = leftPresentation P Q R)
  (hleft :
    ∀ {W X Y Z : Geometry.SmSchemeOver k}
      (P : Boundary.RepresentedPrimeSupport W X)
      (Q : Boundary.RepresentedPrimeSupport X Y)
      (R : Boundary.RepresentedPrimeSupport Y Z),
        Boundary.FiniteCorrespondenceCompositionData.comp
          (Boundary.RepresentedPrimeFiniteCorrespondenceComposition.toFiniteCorrespondenceCompositionData
            (Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductImageCompositionPackageFamily.data
              diagonalDecomposition
              (fun {X} {Y} {Z} x y =>
                Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductLiftedImageCompositionPackage.toSupportFiberProductImageCompositionPackage
                  (packages (X := X) (Y := Y) (Z := Z) x y))))
          (Boundary.FiniteCorrespondencePresentation.toGeom
            (Boundary.SupportFiberProductImageDecomposition.toPresentation
              (Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductImageCompositionPackageFamily.decomposition
                (fun {X} {Y} {Z} x y =>
                  Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductLiftedImageCompositionPackage.toSupportFiberProductImageCompositionPackage
                    (packages (X := X) (Y := Y) (Z := Z) x y))
                P Q)))
          (Finsupp.single (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented R) 1) =
            Boundary.FiniteCorrespondencePresentation.toGeom (leftPresentation P Q R))
  (hright :
    ∀ {W X Y Z : Geometry.SmSchemeOver k}
      (P : Boundary.RepresentedPrimeSupport W X)
      (Q : Boundary.RepresentedPrimeSupport X Y)
      (R : Boundary.RepresentedPrimeSupport Y Z),
        Boundary.FiniteCorrespondenceCompositionData.comp
          (Boundary.RepresentedPrimeFiniteCorrespondenceComposition.toFiniteCorrespondenceCompositionData
            (Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductImageCompositionPackageFamily.data
              diagonalDecomposition
              (fun {X} {Y} {Z} x y =>
                Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductLiftedImageCompositionPackage.toSupportFiberProductImageCompositionPackage
                  (packages (X := X) (Y := Y) (Z := Z) x y))))
          (Finsupp.single (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented P) 1)
          (Boundary.FiniteCorrespondencePresentation.toGeom
            (Boundary.SupportFiberProductImageDecomposition.toPresentation
              (Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductImageCompositionPackageFamily.decomposition
                (fun {X} {Y} {Z} x y =>
                  Boundary.RepresentedPrimeFiniteCorrespondenceComposition.SupportFiberProductLiftedImageCompositionPackage.toSupportFiberProductImageCompositionPackage
                    (packages (X := X) (Y := Y) (Z := Z) x y))
                Q R))) =
            Boundary.FiniteCorrespondencePresentation.toGeom (rightPresentation P Q R))
  (graphPair_yes :
    ∀ {X Y Z : Geometry.SmSchemeOver k}
      (C : Boundary.SourceIrreducibleComponent X)
      (f : Boundary.SmOverHom X Y)
      (D : Boundary.SourceIrreducibleComponent Y)
      (g : Boundary.SmOverHom Y Z)
      (h : C.carrier.scheme ⟶ D.carrier.scheme)
      (hh : h ≫ D.toAmbient = C.toAmbient ≫ f.hom),
        ((packages
          (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented
            (Geometry.ordinaryMorphismGraphPrimeSupport C f))
          (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented
            (Geometry.ordinaryMorphismGraphPrimeSupport D g))).liftedDecomposition
            (Geometry.ordinaryMorphismGraphPrimeSupport C f)
            (Geometry.ordinaryMorphismGraphPrimeSupport D g)).toSupportFiberProductImageDecomposition =
          Geometry.graphPrimeSupportFiberProductImageDecomposition C f D g h hh)
  (graphPair_no :
    ∀ {X Y Z : Geometry.SmSchemeOver k}
      (C : Boundary.SourceIrreducibleComponent X)
      (f : Boundary.SmOverHom X Y)
      (D : Boundary.SourceIrreducibleComponent Y)
      (g : Boundary.SmOverHom Y Z),
        (¬ Nonempty { h : C.carrier.scheme ⟶ D.carrier.scheme //
            h ≫ D.toAmbient = C.toAmbient ≫ f.hom }) →
          IsEmpty (((packages
            (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented
              (Geometry.ordinaryMorphismGraphPrimeSupport C f))
            (Boundary.PrimeFiniteCorrespondenceGeom.ofRepresented
              (Geometry.ordinaryMorphismGraphPrimeSupport D g))).liftedDecomposition
              (Geometry.ordinaryMorphismGraphPrimeSupport C f)
              (Geometry.ordinaryMorphismGraphPrimeSupport D g)).toSupportFiberProductImageDecomposition.index))

local notation "concreteCompositionData" =>
  concreteCanonicalComposition
    diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
    rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
    leftPresentation rightPresentation hpresentation hleft hright

local notation "concreteCategoryData" =>
  concreteCanonicalCategory
    diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
    rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
    leftPresentation rightPresentation hpresentation hleft hright

local notation "canonicalConcretePullback" => fun sq f =>
  NisnevichDistinguishedSquareDataQ.pullback
    diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
    rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
    leftPresentation rightPresentation hpresentation hleft hright
    graphPair_yes graphPair_no sq f
    (NisnevichDistinguishedSquareDataQ.canonicalBaseChangeDecompositions
      concreteCompositionData sq f)

/-- Once the canonical pulled-back Nisnevich square is constructed, its
generating presieve is again a Nisnevich covering family on the new base. This
is the immediate presieve-level input needed for `Coverage.pullback`. -/
theorem nisnevichCoverPresieve_mem_nisnevichCovering_pullback
    (sq : NisnevichDistinguishedSquareDataQ concreteCategoryData)
    {Y : Geometry.SmSchemeOver k}
    (f : SmOverHom Y sq.base)
    (decomps : NisnevichDistinguishedSquareDataQ.BaseChangeDecompositions sq f) :
    nisnevichCoverPresieve
        (NisnevichDistinguishedSquareDataQ.pullback
          diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
          rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
          leftPresentation rightPresentation hpresentation hleft hright
          graphPair_yes graphPair_no sq f decomps) ∈
      nisnevichCovering Y := by
  exact
    nisnevichCoverPresieve_mem_nisnevichCovering
      (sq := NisnevichDistinguishedSquareDataQ.pullback
        diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
        rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
        leftPresentation rightPresentation hpresentation hleft hright
        graphPair_yes graphPair_no sq f decomps)

/-- The generating presieve of the canonical pulled-back square factors through
the generating presieve of the original square along the base-change morphism. -/
theorem nisnevichCoverPresieve_pullback
    (sq : NisnevichDistinguishedSquareDataQ concreteCategoryData)
    {Y : Geometry.SmSchemeOver k}
    (f : SmOverHom Y sq.base) :
    (nisnevichCoverPresieve
        (canonicalConcretePullback sq f)).FactorsThruAlong
      (nisnevichCoverPresieve sq) f := by
  intro Z g hg
  rcases hg with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · refine ⟨sq.openPiece, baseChange_open_to_open concreteCompositionData sq f, sq.openToBase, ?_, ?_⟩
    · exact nisnevichCoverPresieve_openToBase sq
    · exact baseChange_open_to_open_comp_eq concreteCompositionData sq f
  · refine ⟨sq.patchPiece, baseChange_patch_to_patch concreteCompositionData sq f, sq.patchToBase, ?_, ?_⟩
    · exact nisnevichCoverPresieve_patchToBase sq
    · exact baseChange_patch_to_patch_comp_eq concreteCompositionData sq f

/-- Canonical Nisnevich covering presieves on `X`, generated by distinguished
squares valued in the concrete canonical rational correspondence category. -/
def NisnevichCovering
    (X : Geometry.SmSchemeOver k) : Set (Presieve X) :=
  { S | ∃ (sq : NisnevichDistinguishedSquareDataQ concreteCategoryData)
           (h : sq.base = X),
         S = h ▸ nisnevichCoverPresieve sq }

namespace NisnevichCovering

/-- The generating presieve of a canonical square lies in the corresponding
canonical Nisnevich covering family. -/
theorem of_square
    (sq : NisnevichDistinguishedSquareDataQ concreteCategoryData) :
    nisnevichCoverPresieve sq ∈ Boundary.NisnevichCovering
      diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
      rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
      leftPresentation rightPresentation hpresentation hleft hright sq.base :=
  ⟨sq, rfl, rfl⟩

end NisnevichCovering

/-- The canonical Nisnevich coverage on `Sm/k`. -/
def NisnevichCoverage :
    CategoryTheory.Coverage (Geometry.SmSchemeOver k) where
  covering := Boundary.NisnevichCovering
    diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
    rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
    leftPresentation rightPresentation hpresentation hleft hright
  pullback := by
    intro X Y f S hS
    rcases hS with ⟨sq, hbase, hSsq⟩
    subst hbase
    subst hSsq
    refine ⟨nisnevichCoverPresieve
        (canonicalConcretePullback sq f), ?_, ?_⟩
    · exact Boundary.NisnevichCovering.of_square
        diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
        rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
        leftPresentation rightPresentation hpresentation hleft hright
        (canonicalConcretePullback sq f)
    · exact nisnevichCoverPresieve_pullback
        diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
        rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
        leftPresentation rightPresentation hpresentation hleft hright
        graphPair_yes graphPair_no sq f

namespace NisnevichCoverage

/-- The pullback axiom for the canonical Nisnevich coverage. -/
theorem pullback
    {X Y : Geometry.SmSchemeOver k}
    (f : Y ⟶ X)
    (S : Presieve X)
    (hS : S ∈ (Boundary.NisnevichCoverage
      diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
      rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
      leftPresentation rightPresentation hpresentation hleft hright
      graphPair_yes graphPair_no).covering X) :
    ∃ (T : Presieve Y),
      T ∈ (Boundary.NisnevichCoverage
        diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
        rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
        leftPresentation rightPresentation hpresentation hleft hright
        graphPair_yes graphPair_no).covering Y ∧
        T.FactorsThruAlong S f :=
  (Boundary.NisnevichCoverage
    diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
    rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
    leftPresentation rightPresentation hpresentation hleft hright
    graphPair_yes graphPair_no).pullback f S hS

end NisnevichCoverage

/-- The Grothendieck topology generated by the canonical Nisnevich coverage. -/
def NisnevichTopology :
    CategoryTheory.GrothendieckTopology (Geometry.SmSchemeOver k) :=
  CategoryTheory.Coverage.toGrothendieck _
    (Boundary.NisnevichCoverage
      diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
      rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
      leftPresentation rightPresentation hpresentation hleft hright
      graphPair_yes graphPair_no)

namespace NisnevichTopology

/-- The canonical Nisnevich Grothendieck topology is stable under pullback. -/
theorem pullback_stable
    {X Y : Geometry.SmSchemeOver k}
    {S : Sieve X}
    (hS : S ∈ Boundary.NisnevichTopology
      diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
      rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
      leftPresentation rightPresentation hpresentation hleft hright
      graphPair_yes graphPair_no X)
    (f : Y ⟶ X) :
    S.pullback f ∈ Boundary.NisnevichTopology
      diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
      rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
      leftPresentation rightPresentation hpresentation hleft hright
      graphPair_yes graphPair_no Y :=
  (Boundary.NisnevichTopology
    diagonalDecomposition packages leftIdentityPackage leftIdentity_constant
    rightIdentityPackage rightIdentity_constant landing_eq_diagonalRightIdentity
    leftPresentation rightPresentation hpresentation hleft hright
    graphPair_yes graphPair_no).pullback_stable f hS

end NisnevichTopology

end ConcreteCanonical

end

end Boundary
