import Mathlib.Tactic
import Boundary.PolynomialReduction

noncomputable section

open scoped MonomialOrder

namespace Boundary
namespace PolynomialNormalForm

variable {σ : Type*} [Fintype σ]
variable [DecidableEq σ]
variable {k : Type*} [Field k]

/-- A polynomial is reducible by a finite list if it is nonzero and some element of the list
has a dividing leading monomial. -/
def reducibleByList (m : MonomialOrder σ) (G : List (MvPolynomial σ k))
    (f : MvPolynomial σ k) : Prop :=
  f ≠ 0 ∧ ∃ g ∈ G, Boundary.PolynomialReduction.reducibleByLeadingTerm (m := m) g f

/-- The finite family of divisors indexed by their position in a list. -/
def listGenerators (G : List (MvPolynomial σ k)) : Fin G.length → MvPolynomial σ k :=
  fun i => G[i]

/-- The ideal generated by a finite list of polynomials. -/
def listSpan (G : List (MvPolynomial σ k)) : Ideal (MvPolynomial σ k) :=
  Ideal.span (Set.range (listGenerators (σ := σ) (k := k) G))

theorem listGenerators_mem (G : List (MvPolynomial σ k)) (i : Fin G.length) :
    listGenerators (σ := σ) (k := k) G i ∈ listSpan (σ := σ) (k := k) G := by
  refine Ideal.subset_span ?_
  exact ⟨i, rfl⟩

theorem mem_listSpan_of_mem_list {G : List (MvPolynomial σ k)}
    {g : MvPolynomial σ k} (hg : g ∈ G) :
    g ∈ listSpan (σ := σ) (k := k) G := by
  rcases List.mem_iff_getElem.mp hg with ⟨i, hi, rfl⟩
  refine Ideal.subset_span ?_
  exact ⟨⟨i, hi⟩, rfl⟩

/-- Division by a finite list: every polynomial admits a remainder that is irreducible with
respect to the list and differs from the original polynomial by an element of the span of the
list. This is the constructive normal-form theorem used downstream. -/
theorem exists_normalForm
    (m : MonomialOrder σ) (G : List (MvPolynomial σ k)) (f : MvPolynomial σ k) :
    ∃ r : MvPolynomial σ k,
      ¬ reducibleByList (m := m) G r ∧
      f - r ∈ listSpan (σ := σ) (k := k) G := by
  classical
  let P : m.syn → Prop :=
    fun a =>
      ∀ f : MvPolynomial σ k,
        m.toSyn (PolynomialGroebnerBasics.leadingMonomial m f) = a →
          ∃ r : MvPolynomial σ k,
            ¬ reducibleByList (m := m) G r ∧
            f - r ∈ listSpan (σ := σ) (k := k) G
  have hP : ∀ a : m.syn, P a := by
    intro a
    have hwf : WellFounded (· < · : m.syn → m.syn → Prop) :=
      (MonomialOrder.wf m).wf
    exact
      WellFounded.induction hwf a (fun x ih f hf => by
          by_cases hred : reducibleByList (m := m) G f
          · rcases hred with ⟨hf0, hred'⟩
            rcases hred' with ⟨g, hg, hpred⟩
            have hg0 : g ≠ 0 := hpred.2.1
            have hdiv : Boundary.PolynomialReduction.monomialDivides
                (PolynomialGroebnerBasics.leadingMonomial m g)
                (PolynomialGroebnerBasics.leadingMonomial m f) := hpred.2.2
            let r := Boundary.PolynomialReduction.reductionStep (m := m) g f
              ⟨hf0, hg0, hdiv⟩
            by_cases hr : r = 0
            · have hmem : g ∈ listSpan (σ := σ) (k := k) G :=
                mem_listSpan_of_mem_list (σ := σ) (k := k) (G := G) hg
              have hmul :
                  MvPolynomial.monomial
                    (Boundary.PolynomialReduction.monomialQuotient
                      (PolynomialGroebnerBasics.leadingMonomial m g)
                      (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                    (PolynomialGroebnerBasics.leadingCoeff m f /
                      PolynomialGroebnerBasics.leadingCoeff m g) * g ∈
                  listSpan (σ := σ) (k := k) G := by
                exact Ideal.mul_mem_left _ _ hmem
              have hlist :
                  r +
                    (MvPolynomial.monomial
                      (Boundary.PolynomialReduction.monomialQuotient
                        (PolynomialGroebnerBasics.leadingMonomial m g)
                        (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                      (PolynomialGroebnerBasics.leadingCoeff m f /
                        PolynomialGroebnerBasics.leadingCoeff m g) * g) = f := by
                dsimp [r, Boundary.PolynomialReduction.reductionStep]
                exact sub_add_cancel _ _
              have hf_eq :
                  f = MvPolynomial.monomial
                    (Boundary.PolynomialReduction.monomialQuotient
                      (PolynomialGroebnerBasics.leadingMonomial m g)
                      (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                    (PolynomialGroebnerBasics.leadingCoeff m f /
                      PolynomialGroebnerBasics.leadingCoeff m g) * g := by
                calc
                  f = r +
                      (MvPolynomial.monomial
                        (Boundary.PolynomialReduction.monomialQuotient
                          (PolynomialGroebnerBasics.leadingMonomial m g)
                          (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                        (PolynomialGroebnerBasics.leadingCoeff m f /
                          PolynomialGroebnerBasics.leadingCoeff m g) * g) := hlist.symm
                  _ = _ := by
                    rw [hr]
                    simp
              refine ⟨0, ?_, ?_⟩
              · intro hz
                exact hz.1 rfl
              · rw [hf_eq]
                have hzeroeq :
                    (MvPolynomial.monomial
                      (Boundary.PolynomialReduction.monomialQuotient
                        (PolynomialGroebnerBasics.leadingMonomial m g)
                        (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                      (PolynomialGroebnerBasics.leadingCoeff m f /
                        PolynomialGroebnerBasics.leadingCoeff m g) * g -
                      0 : MvPolynomial σ k) =
                    MvPolynomial.monomial
                      (Boundary.PolynomialReduction.monomialQuotient
                        (PolynomialGroebnerBasics.leadingMonomial m g)
                        (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                      (PolynomialGroebnerBasics.leadingCoeff m f /
                        PolynomialGroebnerBasics.leadingCoeff m g) * g := by
                  simp
                rw [hzeroeq]
                exact hmul
            · have hlt :
                m.toSyn (PolynomialGroebnerBasics.leadingMonomial m r) < x := by
                rw [← hf]
                exact
                  Boundary.PolynomialReduction.leadingMonomial_reductionStep_lt
                    (m := m) (g := g) (f := f) hf0 ⟨hf0, hg0, hdiv⟩ hr
              rcases ih (m.toSyn (PolynomialGroebnerBasics.leadingMonomial m r)) hlt r rfl with
                ⟨r', hrirr, hrsub⟩
              have hmem : g ∈ listSpan (σ := σ) (k := k) G :=
                mem_listSpan_of_mem_list (σ := σ) (k := k) (G := G) hg
              have hmul :
                  MvPolynomial.monomial
                    (Boundary.PolynomialReduction.monomialQuotient
                      (PolynomialGroebnerBasics.leadingMonomial m g)
                      (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                    (PolynomialGroebnerBasics.leadingCoeff m f /
                      PolynomialGroebnerBasics.leadingCoeff m g) * g ∈
                  listSpan (σ := σ) (k := k) G := by
                exact Ideal.mul_mem_left _ _ hmem
              have hlist :
                  r +
                    (MvPolynomial.monomial
                      (Boundary.PolynomialReduction.monomialQuotient
                        (PolynomialGroebnerBasics.leadingMonomial m g)
                        (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                      (PolynomialGroebnerBasics.leadingCoeff m f /
                        PolynomialGroebnerBasics.leadingCoeff m g) * g) = f := by
                dsimp [r, Boundary.PolynomialReduction.reductionStep]
                exact sub_add_cancel _ _
              have hfr :
                  f - r =
                    MvPolynomial.monomial
                      (Boundary.PolynomialReduction.monomialQuotient
                        (PolynomialGroebnerBasics.leadingMonomial m g)
                        (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                      (PolynomialGroebnerBasics.leadingCoeff m f /
                        PolynomialGroebnerBasics.leadingCoeff m g) * g := by
                calc
                  f - r =
                      (r +
                        (MvPolynomial.monomial
                          (Boundary.PolynomialReduction.monomialQuotient
                            (PolynomialGroebnerBasics.leadingMonomial m g)
                            (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                          (PolynomialGroebnerBasics.leadingCoeff m f /
                            PolynomialGroebnerBasics.leadingCoeff m g) * g)) - r := by
                    rw [hlist]
                  _ = _ := by simp [add_comm, add_left_comm, add_assoc]
              have hstep : f - r ∈ listSpan (σ := σ) (k := k) G := by
                have hstep' :
                    (MvPolynomial.monomial
                      (Boundary.PolynomialReduction.monomialQuotient
                        (PolynomialGroebnerBasics.leadingMonomial m g)
                        (PolynomialGroebnerBasics.leadingMonomial m f) hdiv)
                      (PolynomialGroebnerBasics.leadingCoeff m f /
                        PolynomialGroebnerBasics.leadingCoeff m g) * g -
                      0 : MvPolynomial σ k) ∈ listSpan (σ := σ) (k := k) G := by
                  simpa using hmul
                simpa [hfr] using hstep'
              have hsum : (f - r) + (r - r') ∈ listSpan (σ := σ) (k := k) G :=
                Ideal.add_mem _ hstep hrsub
              have hcalc : f - r' = (f - r) + (r - r') := by
                rw [sub_add_sub_cancel]
              have hsum' : f - r' ∈ listSpan (σ := σ) (k := k) G := by
                rw [hcalc]
                exact hsum
              exact ⟨r', hrirr, hsum'⟩
          · refine ⟨f, hred, ?_⟩
            have h0 : (0 : MvPolynomial σ k) ∈ listSpan (σ := σ) (k := k) G :=
              Ideal.zero_mem _
            simpa using h0)
  exact hP (m.toSyn (PolynomialGroebnerBasics.leadingMonomial m f)) f rfl

/-- A division theorem with explicit quotient witnesses. -/
theorem exists_division
    (m : MonomialOrder σ) (G : List (MvPolynomial σ k)) (f : MvPolynomial σ k) :
    ∃ r : MvPolynomial σ k,
      ¬ reducibleByList (m := m) G r ∧
      ∃ q : Fin G.length →₀ MvPolynomial σ k,
        f = r + q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) := by
  obtain ⟨r, hrirr, hrspan⟩ := exists_normalForm (m := m) (G := G) (f := f)
  rw [listSpan] at hrspan
  have hq :
      ∃ q : Fin G.length →₀ MvPolynomial σ k,
        q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) = f - r := by
    exact Finsupp.mem_span_range_iff_exists_finsupp.mp hrspan
  rcases hq with ⟨q, hq⟩
  refine ⟨r, hrirr, q, ?_⟩
  calc
    f = r + (f - r) := by
      rw [add_comm]
      rw [sub_add_cancel]
    _ = r + q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) := by
      rw [hq]

/-- Membership in the list span is equivalent to an explicit finite sum of list generators. -/
theorem mem_listSpan_iff_exists_finsupp
    (G : List (MvPolynomial σ k)) (f : MvPolynomial σ k) :
    f ∈ listSpan (σ := σ) (k := k) G ↔
      ∃ q : Fin G.length →₀ MvPolynomial σ k,
        q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) = f := by
  simpa [listSpan, listGenerators] using
    (Finsupp.mem_span_range_iff_exists_finsupp
      (v := listGenerators (σ := σ) (k := k) G) (x := f))

/-- Membership in the list span produces a pure quotient expression with zero remainder. -/
theorem exists_division_of_mem_listSpan
    (G : List (MvPolynomial σ k)) {f : MvPolynomial σ k} (hf : f ∈ listSpan (σ := σ) (k := k) G) :
    ∃ q : Fin G.length →₀ MvPolynomial σ k,
      f = q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) := by
  rw [mem_listSpan_iff_exists_finsupp] at hf
  rcases hf with ⟨q, hq⟩
  exact ⟨q, hq.symm⟩

/-- The zero polynomial is never reducible by a finite list. -/
theorem zero_not_reducibleByList
    (m : MonomialOrder σ) (G : List (MvPolynomial σ k)) :
    ¬ reducibleByList (m := m) G (0 : MvPolynomial σ k) := by
  intro h
  exact h.1 rfl

/-- Membership in the list span yields a division witness with zero remainder. -/
theorem exists_division_zero_remainder_of_mem_listSpan
    (m : MonomialOrder σ) (G : List (MvPolynomial σ k))
    {f : MvPolynomial σ k} (hf : f ∈ listSpan (σ := σ) (k := k) G) :
    ∃ q : Fin G.length →₀ MvPolynomial σ k,
      ¬ reducibleByList (m := m) G (0 : MvPolynomial σ k) ∧
      f = (0 : MvPolynomial σ k) + q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) := by
  rcases exists_division_of_mem_listSpan (σ := σ) (k := k) G hf with ⟨q, hq⟩
  refine ⟨q, zero_not_reducibleByList (m := m) G, ?_⟩
  simpa using hq

/-- Membership in the list span is equivalent to the existence of a division witness with
zero remainder. -/
theorem mem_listSpan_iff_exists_division_zero_remainder
    (m : MonomialOrder σ) (G : List (MvPolynomial σ k)) (f : MvPolynomial σ k) :
    f ∈ listSpan (σ := σ) (k := k) G ↔
      ∃ q : Fin G.length →₀ MvPolynomial σ k,
        ¬ reducibleByList (m := m) G (0 : MvPolynomial σ k) ∧
        f = (0 : MvPolynomial σ k) + q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) := by
  constructor
  · intro hf
    exact exists_division_zero_remainder_of_mem_listSpan (σ := σ) (k := k) m G hf
  · intro h
    rcases h with ⟨q, hzero, hfq⟩
    rw [hfq]
    have hmem : q.sum (fun i a => a * listGenerators (σ := σ) (k := k) G i) ∈
        listSpan (σ := σ) (k := k) G := by
      rw [mem_listSpan_iff_exists_finsupp]
      exact ⟨q, rfl⟩
    simpa using hmem

end PolynomialNormalForm
end Boundary
