import Boundary.PolynomialSmoothness.PresentationCombinatorics
import Boundary.PolynomialSmoothness.SplitPresentation
import Boundary.PolynomialSmoothness.JacobianTransport
import Boundary.PolynomialSmoothness.SubmersiveSplit
import Boundary.PolynomialSmoothness.StandardSmoothDimensionZero
import Boundary.PolynomialSmoothness.StandardSmoothConstructions
import Boundary.PolynomialSmoothness.StandardSmoothRingHomTransport
import Boundary.PolynomialSmoothness.StandardSmoothDimensionZero_LocalDomain
import Boundary.PolynomialSmoothness.StandardSmoothSplitTransport
import Boundary.PolynomialSmoothness.StandardSmoothReducedness

-- Intentionally only re-exports the split declarations.
