import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.StableCategory.ContourCorQConstruction.Stabilized.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Bulk.Presheaves.CompactGeometric.ContourCorQConstruction.Owner

/-!
# Constructed compact analytic motives

This owner names the compact layer generated by constructed compact geometric
analytic motives.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A compact analytic motive in the constructed lane. -/
structure ConstructedCompactAnalyticMotive where
  stabilized : ConstructedStabilizedAnalyticMotive
  compactGeometric : ConstructedCompactGeometricAnalyticMotive
  compact_closed_eq :
    compactGeometric.closedObject = stabilized.stabilizedPresheaf

namespace ConstructedCompactAnalyticMotive

/-- The stabilized layer of a constructed compact analytic motive. -/
def stabilizedLayer (M : ConstructedCompactAnalyticMotive) :
    ConstructedStabilizedAnalyticMotive :=
  M.stabilized

/-- The compact-geometric layer. -/
def compactGeometricLayer (M : ConstructedCompactAnalyticMotive) :
    ConstructedCompactGeometricAnalyticMotive :=
  M.compactGeometric

/-- The constructed Tate-stabilized presheaf of the compact layer. -/
def stabilizedPresheaf (M : ConstructedCompactAnalyticMotive) :
    ConstructedTateStabilizedAnalyticPresheaf :=
  M.stabilized.stabilizedPresheaf

/-- The compact-geometric closed object. -/
def compactClosedObject (M : ConstructedCompactAnalyticMotive) :
    ConstructedTateStabilizedAnalyticPresheaf :=
  M.compactGeometric.closedObject

/-- The compact-geometric closed object agrees with the stabilized presheaf. -/
theorem compactClosedObject_eq_stabilizedPresheaf
    (M : ConstructedCompactAnalyticMotive) :
    M.compactClosedObject = M.stabilizedPresheaf :=
  M.compact_closed_eq

end ConstructedCompactAnalyticMotive

end AnalyticMotives
end LFunctions
end Boundary
