import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Complexes.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Complexes.Singleton.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Objects.LocalizationInput.Owner

/-!
# Bounded localization-input concentrated complexes

This file packages the degree-zero source and target complexes attached to a
localization input as bounded additive analytic complexes.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The bounded degree-zero source complex generated by a localization input. -/
def TraceLocalizationInput.boundedAdditiveSourceComplex
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveCochainComplex.WeightBoundedBy
      input.additiveSourceObjectWeightBound :=
  TraceAnalyticAdditiveCochainComplex.concentratedSingletonBoundedBy
    input.sourceObject

/-- The bounded degree-zero target complex generated by a localization input. -/
def TraceLocalizationInput.boundedAdditiveTargetComplex
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveCochainComplex.WeightBoundedBy
      input.additiveTargetObjectWeightBound :=
  TraceAnalyticAdditiveCochainComplex.concentratedSingletonBoundedBy
    input.targetObject

/-- The bounded source-complex package has the localization input's source complex
underneath. -/
theorem TraceLocalizationInput.boundedAdditiveSourceComplex_complex
    (input : TraceLocalizationInput) :
    input.boundedAdditiveSourceComplex.complex =
      input.additiveSourceComplex :=
  rfl

/-- The bounded target-complex package has the localization input's target complex
underneath. -/
theorem TraceLocalizationInput.boundedAdditiveTargetComplex_complex
    (input : TraceLocalizationInput) :
    input.boundedAdditiveTargetComplex.complex =
      input.additiveTargetComplex :=
  rfl

/-- The bounded source complex satisfies its canonical source weight bound in every
degree. -/
theorem TraceLocalizationInput.boundedAdditiveSourceComplex_degreeWeight_le
    (input : TraceLocalizationInput)
    (degree : ℤ) :
    input.boundedAdditiveSourceComplex.complex.degreeWeight degree ≤
      input.additiveSourceObjectWeightBound :=
  input.boundedAdditiveSourceComplex.degreeWeight_le degree

/-- The bounded target complex satisfies its canonical target weight bound in every
degree. -/
theorem TraceLocalizationInput.boundedAdditiveTargetComplex_degreeWeight_le
    (input : TraceLocalizationInput)
    (degree : ℤ) :
    input.boundedAdditiveTargetComplex.complex.degreeWeight degree ≤
      input.additiveTargetObjectWeightBound :=
  input.boundedAdditiveTargetComplex.degreeWeight_le degree

end AnalyticMotives
end LFunctions
end Boundary
