import Mathlib.Algebra.Homology.HomotopyCategory.SingleFunctors
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Complexes.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Stabilization.AdditiveEnvelope.Objects.LocalizationInput.Owner

/-!
# Concentrated singleton complexes in the analytic additive envelope

This file places singleton additive-envelope objects in degree zero as concrete
cochain complexes.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The degree-zero cochain complex generated by one certified trace object. -/
def TraceAnalyticAdditiveCochainComplex.concentratedSingleton
    (object : TraceCorQObject) :
    TraceAnalyticAdditiveCochainComplex :=
  (CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject (0 : ℤ)).obj
    (TraceAnalyticAdditiveObject.singleton object)

/-- The degree-zero object of a concentrated singleton complex is the singleton
additive-envelope object. -/
theorem TraceAnalyticAdditiveCochainComplex.concentratedSingleton_objectAt_zero
    (object : TraceCorQObject) :
    (TraceAnalyticAdditiveCochainComplex.concentratedSingleton object).objectAt 0 =
      TraceAnalyticAdditiveObject.singleton object :=
  HomologicalComplex.single_obj_X_self
    (c := ComplexShape.up ℤ)
    (0 : ℤ)
    (TraceAnalyticAdditiveObject.singleton object)

/-- The degree-zero object of a concentrated singleton complex has one component. -/
theorem TraceAnalyticAdditiveCochainComplex.concentratedSingleton_objectAt_zero_length
    (object : TraceCorQObject) :
    ((TraceAnalyticAdditiveCochainComplex.concentratedSingleton object).objectAt
      0).length =
      1 :=
  Eq.trans
    (congrArg
      List.length
      (TraceAnalyticAdditiveCochainComplex.concentratedSingleton_objectAt_zero
        object))
    (TraceAnalyticAdditiveObject.singleton_length object)

/-- The degree-zero cochain complex generated by the source object of a localization
input. -/
def TraceLocalizationInput.additiveSourceComplex
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveCochainComplex :=
  (CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject (0 : ℤ)).obj
    input.additiveSourceObject

/-- The degree-zero cochain complex generated by the target object of a localization
input. -/
def TraceLocalizationInput.additiveTargetComplex
    (input : TraceLocalizationInput) :
    TraceAnalyticAdditiveCochainComplex :=
  (CochainComplex.singleFunctor TraceAnalyticAdditiveCategoryObject (0 : ℤ)).obj
    input.additiveTargetObject

/-- The degree-zero object of a localization input's source complex is its additive
source object. -/
theorem TraceLocalizationInput.additiveSourceComplex_objectAt_zero
    (input : TraceLocalizationInput) :
    input.additiveSourceComplex.objectAt 0 =
      input.additiveSourceObject :=
  HomologicalComplex.single_obj_X_self
    (c := ComplexShape.up ℤ)
    (0 : ℤ)
    input.additiveSourceObject

/-- The degree-zero object of a localization input's target complex is its additive
target object. -/
theorem TraceLocalizationInput.additiveTargetComplex_objectAt_zero
    (input : TraceLocalizationInput) :
    input.additiveTargetComplex.objectAt 0 =
      input.additiveTargetObject :=
  HomologicalComplex.single_obj_X_self
    (c := ComplexShape.up ℤ)
    (0 : ℤ)
    input.additiveTargetObject

/-- A localization input's source complex has one degree-zero component. -/
theorem TraceLocalizationInput.additiveSourceComplex_objectAt_zero_length
    (input : TraceLocalizationInput) :
    (input.additiveSourceComplex.objectAt 0).length =
      1 :=
  Eq.trans
    (congrArg
      List.length
      (TraceLocalizationInput.additiveSourceComplex_objectAt_zero input))
    (TraceLocalizationInput.additiveSourceObject_length input)

/-- A localization input's target complex has one degree-zero component. -/
theorem TraceLocalizationInput.additiveTargetComplex_objectAt_zero_length
    (input : TraceLocalizationInput) :
    (input.additiveTargetComplex.objectAt 0).length =
      1 :=
  Eq.trans
    (congrArg
      List.length
      (TraceLocalizationInput.additiveTargetComplex_objectAt_zero input))
    (TraceLocalizationInput.additiveTargetObject_length input)

end AnalyticMotives
end LFunctions
end Boundary
