import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.ReductionClosure.Owner

/-!
# Quotient classes of formal localization words

This file owns the quotient of formal localization words by the generated
localization-word relation.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The setoid on formal localization words generated by reduction closure. -/
def TraceLocalizationWordSetoid
    (source target : TraceCorQObject) :
    Setoid (TraceLocalizationWord source target) where
  r := fun left right =>
    Nonempty (TraceLocalizationWordRelation left right)
  iseqv := {
    refl := fun word =>
      Nonempty.intro
        (TraceLocalizationWordRelation.refl word)
    symm := fun relation =>
      match relation with
      | Nonempty.intro witness =>
          Nonempty.intro
            (TraceLocalizationWordRelation.symm witness)
    trans := fun first second =>
      match first with
      | Nonempty.intro firstWitness =>
          match second with
          | Nonempty.intro secondWitness =>
              Nonempty.intro
                (TraceLocalizationWordRelation.trans
                  firstWitness
                  secondWitness)
  }

/-- A formal localized word class from source to target. -/
abbrev TraceLocalizationWordClass
    (source target : TraceCorQObject) :=
  Quotient (TraceLocalizationWordSetoid source target)

/-- The quotient class represented by a formal localization word. -/
def TraceLocalizationWordClass.ofWord
    {source target : TraceCorQObject}
    (word : TraceLocalizationWord source target) :
    TraceLocalizationWordClass source target :=
  Quotient.mk (TraceLocalizationWordSetoid source target) word

/-- The identity formal localized word class. -/
def TraceLocalizationWordClass.identity
    (object : TraceCorQObject) :
    TraceLocalizationWordClass object object :=
  TraceLocalizationWordClass.ofWord
    (TraceLocalizationWord.identity object)

/-- The one-forward-input formal localized word class. -/
def TraceLocalizationWordClass.ofInputForward
    (input : TraceLocalizationInput) :
    TraceLocalizationWordClass input.sourceObject input.targetObject :=
  TraceLocalizationWordClass.ofWord
    (TraceLocalizationWord.ofInputForward input)

/-- The one-inverse-input formal localized word class. -/
def TraceLocalizationWordClass.ofInputInverse
    (input : TraceLocalizationInput) :
    TraceLocalizationWordClass input.targetObject input.sourceObject :=
  TraceLocalizationWordClass.ofWord
    (TraceLocalizationWord.ofInputInverse input)

/-- A generated word relation gives equality of word classes. -/
theorem TraceLocalizationWordClass.sound
    {source target : TraceCorQObject}
    {left right : TraceLocalizationWord source target}
    (relation : TraceLocalizationWordRelation left right) :
    TraceLocalizationWordClass.ofWord left =
      TraceLocalizationWordClass.ofWord right :=
  Quotient.sound (Nonempty.intro relation)

/-- Forward followed by inverse is equal to identity in word classes. -/
theorem TraceLocalizationWordClass.forward_inverse_eq_identity
    (input : TraceLocalizationInput) :
    TraceLocalizationWordClass.ofWord
        (TraceLocalizationWord.forwardThenInverse input) =
      TraceLocalizationWordClass.identity input.sourceObject :=
  TraceLocalizationWordClass.sound
    (TraceLocalizationWordRelation.forwardInverse input)

/-- Inverse followed by forward is equal to identity in word classes. -/
theorem TraceLocalizationWordClass.inverse_forward_eq_identity
    (input : TraceLocalizationInput) :
    TraceLocalizationWordClass.ofWord
        (TraceLocalizationWord.inverseThenForward input) =
      TraceLocalizationWordClass.identity input.targetObject :=
  TraceLocalizationWordClass.sound
    (TraceLocalizationWordRelation.inverseForward input)

end AnalyticMotives
end LFunctions
end Boundary
