import Boundary.PolynomialSmoothness.SubmersiveSplit
import Boundary.PolynomialSmoothness.JacobianTransport
import Mathlib.AlgebraicGeometry.Morphisms.Etale
import Mathlib.AlgebraicGeometry.Properties
import Mathlib.Algebra.Polynomial.Basic
import Mathlib.Algebra.Module.Presentation.Differentials
import Mathlib.RingTheory.Etale.Field
import Mathlib.RingTheory.Smooth.Kaehler
import Mathlib.RingTheory.EssentialFiniteness
import Mathlib.RingTheory.FinitePresentation
import Mathlib.RingTheory.Flat.Algebra
import Mathlib.AlgebraicGeometry.PrimeSpectrum.Jacobson
import Mathlib.RingTheory.LocalRing.Module

universe u

namespace Boundary

noncomputable section

namespace _root_.Algebra

variable {k : Type u} [Field k]

/-- Standard-smooth algebras are finitely presented. This is immediate from a
finite submersive presentation in the definition. -/
theorem standardSmooth_finitePresentation
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
    [Algebra.IsStandardSmooth R A] :
    Algebra.FinitePresentation R A := by
  obtain ⟨⟨P⟩⟩ := ‹Algebra.IsStandardSmooth R A›
  letI : P.toPresentation.IsFinite := P.isFinite
  exact Algebra.Presentation.finitePresentation_of_isFinite P.toPresentation

/-- A finitely presented local formally étale algebra over a field is a field.

Mathematically: let `(A, m)` be local and formally étale over `k`. The residue
field `κ = A / m` is a quotient of a formally unramified `k`-algebra, hence is
separable over `k`. Therefore `κ` is formally étale over `k`. Applying formal
smoothness to the square-zero extension
`A / m² -> (A / m²) / (m / m²) = κ` gives a section `κ -> A / m²`. Composing
with `A -> κ` yields a second lift of `A -> κ` through `A -> A / m²`. Formal
unramifiedness forces this lift to equal the quotient map `A -> A / m²`, so
every element of `m` already lies in `m²`. Thus `m = m²`, and in a local ring
an idempotent finitely generated ideal is generated by an idempotent. Finite
presentation over the field supplies the noetherian input, so this idempotent
is either `0` or `1`; since `m ≠ ⊤`, we get `m = ⊥`, so `A` is a field. -/
theorem formallyEtale_isField_of_field_of_isLocalRing
    {A : Type u} [CommRing A] [Algebra k A] [IsLocalRing A]
    [Algebra.FormallyEtale k A] [Algebra.FinitePresentation k A] :
    IsField A := by
  let I : Ideal A := IsLocalRing.maximalIdeal A
  letI : Field (A ⧸ I) :=
    (Ideal.Quotient.maximal_ideal_iff_isField_quotient I).mp
      (IsLocalRing.maximalIdeal.isMaximal A) |>.toField
  let B : Type u := A ⧸ I ^ 2
  let C : Type u := B ⧸ (I.cotangentIdeal)
  letI : CommRing B := inferInstance
  letI : CommRing C := inferInstance
  letI : Algebra k (A ⧸ I) := inferInstance
  letI : Algebra k B := inferInstance
  letI : Algebra k C := inferInstance
  letI : Algebra.FiniteType k A := inferInstance
  letI : Algebra.FiniteType k (A ⧸ I) :=
    Algebra.FiniteType.of_surjective
      (show Algebra.FiniteType k A from inferInstance)
      (Ideal.Quotient.mkₐ k I)
      Ideal.Quotient.mk_surjective
  letI : Algebra.EssFiniteType k (A ⧸ I) :=
    by
      letI : Algebra.FiniteType k (A ⧸ I) := inferInstance
      infer_instance
  letI : Algebra.FormallyUnramified k (A ⧸ I) :=
    Algebra.FormallyUnramified.of_surjective
      (IsScalarTower.toAlgHom k A (A ⧸ I))
      Ideal.Quotient.mk_surjective
  letI : Algebra.IsSeparable k (A ⧸ I) :=
    Algebra.FormallyUnramified.isSeparable k (A ⧸ I)
  letI : Algebra.FormallyEtale k (A ⧸ I) :=
    Algebra.FormallyEtale.of_isSeparable k (A ⧸ I)
  letI : Algebra.FormallySmooth k (A ⧸ I) :=
    Algebra.FormallyEtale.to_smooth
  let e : C ≃ₐ[k] (A ⧸ I) := by
    refine
      { __ := Ideal.quotCotangent I
        commutes' := ?_ }
    intro r
    rfl
  let g : B →ₐ[k] C := Ideal.Quotient.mkₐ k I.cotangentIdeal
  have hg_surj : Function.Surjective g := by
    change Function.Surjective (Ideal.Quotient.mk I.cotangentIdeal)
    exact Ideal.Quotient.mk_surjective
  have hg_nil :
      IsNilpotent (RingHom.ker (g : B →+* C)) := by
    refine ⟨2, ?_⟩
    have hker : RingHom.ker (g : B →+* C) = I.cotangentIdeal := by
      change RingHom.ker (Ideal.Quotient.mkₐ k I.cotangentIdeal : B →+* C) = I.cotangentIdeal
      ext x
      change Ideal.Quotient.mk I.cotangentIdeal x = 0 ↔ x ∈ I.cotangentIdeal
      exact Ideal.Quotient.eq_zero_iff_mem
    calc
      (RingHom.ker (g : B →+* C)) ^ 2 = (I.cotangentIdeal : Ideal B) ^ 2 := by
        rw [hker]
      _ = ⊥ := Ideal.cotangentIdeal_square I
  let s : (A ⧸ I) →ₐ[k] B :=
    Algebra.FormallySmooth.liftOfSurjective
      (f := e.symm.toAlgHom) (g := g) hg_surj hg_nil
  let π : A →ₐ[k] B := Ideal.Quotient.mkₐ k (I ^ 2)
  let ρ : A →ₐ[k] (A ⧸ I) := Ideal.Quotient.mkₐ k I
  have hs : g.comp s = e.symm.toAlgHom :=
    Algebra.FormallySmooth.comp_liftOfSurjective
      (f := e.symm.toAlgHom) (g := g) hg_surj hg_nil
  have hπρ : g.comp π = e.symm.toAlgHom.comp ρ := by
    ext x
    change Ideal.Quotient.mkₐ k I.cotangentIdeal (π x) = e.symm.toAlgHom (ρ x)
    rfl
  have hEqLift : ∀ x : A, g (π x) = g (s (ρ x)) := by
    intro x
    calc
        g (π x) = e.symm (ρ x) := by
          exact congrArg (fun h : A →ₐ[k] C => h x) hπρ
        _ = g (s (ρ x)) := by
          symm
          exact congrArg (fun h : A ⧸ I →ₐ[k] C => h (ρ x)) hs
  have huniq : π = s.comp ρ := by
    apply Algebra.FormallyUnramified.lift_unique_of_ringHom
      (f := (g : B →+* C)) (hf := hg_nil)
    ext x
    exact hEqLift x
  have hle : I ≤ I ^ 2 := by
    intro x hx
    have hxρ : ρ x = 0 := by
      exact Ideal.Quotient.eq_zero_iff_mem.mpr hx
    have hπx : π x = s (ρ x) := by
      change π x = (s.comp ρ) x
      exact congrArg (fun f : A →ₐ[k] B => f x) huniq
    have hzero : s (ρ x) = 0 := by
      rw [hxρ]
      exact map_zero s
    have hx' : π x = 0 := by
      calc
        π x = s (ρ x) := hπx
        _ = 0 := hzero
    have hx'' : Ideal.Quotient.mk (I ^ 2) x = 0 := by
      exact hx'
    exact Ideal.Quotient.eq_zero_iff_mem.mp hx''
  have hEqIdeal : I = I ^ 2 := by
    refine le_antisymm hle ?_
    rw [pow_two]
    exact Ideal.mul_le_left (I := I) (J := I)
  letI : IsNoetherianRing A :=
    Algebra.FiniteType.isNoetherianRing (R := k) (S := A)
  have hIdem : IsIdempotentElem I := by
    rw [IsIdempotentElem]
    change I * I = I
    rw [← pow_two]
    exact hEqIdeal.symm
  have hFG : I.FG :=
    (isNoetherianRing_iff_ideal_fg (R := A)).1 (inferInstance : IsNoetherianRing A) I
  obtain ⟨e, hE, hI⟩ := (Ideal.isIdempotentElem_iff_of_fg I hFG).mp hIdem
  have htop : I ≠ ⊤ := (IsLocalRing.maximalIdeal.isMaximal A).ne_top
  have hbot_or_top : I = ⊥ ∨ I = ⊤ := by
    exact
      (Ideal.isIdempotentElem_iff_eq_bot_or_top_of_isLocalRing (R := A) (I := I)).mp hIdem
  have hIbot : I = ⊥ := by
    cases hbot_or_top with
    | inl hz => exact hz
    | inr ho =>
        exfalso
        exact htop ho
  exact (IsLocalRing.isField_iff_maximalIdeal_eq (R := A)).2 hIbot

namespace IsStandardSmoothOfRelativeDimension

/-- A standard-smooth algebra of relative dimension `0` is formally
unramified. The proof uses the presentation of `Ω[S⁄R]` by the Jacobian
matrix: in relative dimension `0`, the relation-to-variable map is bijective,
the Jacobian is a unit, hence the differentials relation map is surjective and
the quotient presentation of `Ω[S⁄R]` is trivial. -/
theorem formallyUnramified
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [h : Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.FormallyUnramified R S := by
  classical
  obtain ⟨P, hP⟩ := h.out
  let hbij : Function.Bijective P.toPreSubmersivePresentation.map :=
    Algebra.PreSubmersivePresentation.map_bijective_of_dimension_zero
      P.toPreSubmersivePresentation hP
  letI : Fintype P.rels := Fintype.ofFinite P.rels
  letI : DecidableEq P.rels := Classical.decEq _
  letI : Finite P.vars := P.isFinite.finite_vars
  letI : DecidableEq P.vars := Classical.decEq _
  have hSurj :
      Function.Surjective P.toPresentation.differentialsRelations.map :=
    Algebra.PreSubmersivePresentation.surjective_differentialsRelations_map_of_bijective
      P.toPreSubmersivePresentation
      hbij P.jacobian_isUnit
  have hSpan :
      Submodule.span S (Set.range P.toPresentation.differentialsRelations.relation) = ⊤ := by
    rw [← Module.Relations.range_map, LinearMap.range_eq_top]
    exact hSurj
  have hQuotSub :
      Subsingleton P.toPresentation.differentialsRelations.Quotient := by
    change Subsingleton
      ((P.toPresentation.differentialsRelations.G →₀ S) ⧸
        Submodule.span S (Set.range P.toPresentation.differentialsRelations.relation))
    exact (Submodule.subsingleton_quotient_iff_eq_top).2 hSpan
  let hDiff := P.toPresentation.differentialsSolution_isPresentation
  constructor
  refine ⟨?_⟩
  intro x y
  have hxy : hDiff.linearEquiv.symm x = hDiff.linearEquiv.symm y := Subsingleton.elim _ _
  exact hDiff.linearEquiv.symm.injective hxy

/-- A standard-smooth algebra of relative dimension `0` is formally smooth.
The Jacobian presentation becomes a square isomorphism, so the induced
presentation of `Ω[S⁄R]` is trivial and the cotangent-complex map is
injective. Thus `H¹(L_{S/R}) = 0` and `Ω[S⁄R]` is projective. -/
theorem formallySmooth
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [h : Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.FormallySmooth R S := by
  classical
  obtain ⟨P, hP⟩ := h.out
  let hbij : Function.Bijective P.toPreSubmersivePresentation.map :=
    Algebra.PreSubmersivePresentation.map_bijective_of_dimension_zero
      P.toPreSubmersivePresentation hP
  letI : Fintype P.rels := Fintype.ofFinite P.rels
  letI : DecidableEq P.rels := Classical.decEq _
  letI : Finite P.vars := P.isFinite.finite_vars
  letI : DecidableEq P.vars := Classical.decEq _
  have hMapBij :
      Function.Bijective P.toPresentation.differentialsRelations.map :=
    Algebra.PreSubmersivePresentation.bijective_differentialsRelations_map_of_bijective
      P.toPreSubmersivePresentation
      hbij P.jacobian_isUnit
  have hSpan :
      Submodule.span S (Set.range P.toPresentation.differentialsRelations.relation) = ⊤ := by
    rw [← Module.Relations.range_map, LinearMap.range_eq_top]
    exact hMapBij.surjective
  have hQuotSub :
      Subsingleton P.toPresentation.differentialsRelations.Quotient := by
    change Subsingleton
      ((P.toPresentation.differentialsRelations.G →₀ S) ⧸
        Submodule.span S (Set.range P.toPresentation.differentialsRelations.relation))
    exact (Submodule.subsingleton_quotient_iff_eq_top).2 hSpan
  let hDiff := P.toPresentation.differentialsSolution_isPresentation
  letI : Subsingleton (Ω[S⁄R]) := by
    refine ⟨?_⟩
    intro x y
    have hxy : hDiff.linearEquiv.symm x = hDiff.linearEquiv.symm y := Subsingleton.elim _ _
    exact hDiff.linearEquiv.symm.injective hxy
  have hCotInj : Function.Injective P.toExtension.cotangentComplex := by
    intro x y hxy
    obtain ⟨a, rfl⟩ := Algebra.Presentation.differentials.surjective_hom₁ P.toPresentation x
    obtain ⟨b, rfl⟩ := Algebra.Presentation.differentials.surjective_hom₁ P.toPresentation y
    have hxy' :
        P.differentialsRelations.map a =
          P.differentialsRelations.map b := by
      have hxy'' :
          P.cotangentSpaceBasis.repr.symm (P.differentialsRelations.map a) =
            P.cotangentSpaceBasis.repr.symm (P.differentialsRelations.map b) := by
        calc
          P.cotangentSpaceBasis.repr.symm (P.differentialsRelations.map a) =
              P.toExtension.cotangentComplex
                (Algebra.Presentation.differentials.hom₁ P.toPresentation a) := by
            symm
            exact congrArg (fun f => f a)
              (Algebra.Presentation.differentials.comm₁₂ (pres := P.toPresentation))
          _ = P.toExtension.cotangentComplex
                (Algebra.Presentation.differentials.hom₁ P.toPresentation b) := hxy
          _ = P.cotangentSpaceBasis.repr.symm (P.differentialsRelations.map b) := by
            exact congrArg (fun f => f b)
              (Algebra.Presentation.differentials.comm₁₂ (pres := P.toPresentation))
      exact P.cotangentSpaceBasis.repr.symm.injective hxy''
    change Algebra.Presentation.differentials.hom₁ P.toPresentation a =
      Algebra.Presentation.differentials.hom₁ P.toPresentation b
    exact congrArg (Algebra.Presentation.differentials.hom₁ P.toPresentation)
      (hMapBij.injective hxy')
  have hH1 :
    Subsingleton (Algebra.H1Cotangent R S) := by
    let hP : Subsingleton P.toExtension.H1Cotangent :=
      (Algebra.Extension.subsingleton_h1Cotangent P.toExtension).2 hCotInj
    let eH1 : P.toGenerators.toExtension.H1Cotangent ≃ₗ[S] Algebra.H1Cotangent R S :=
      Algebra.Generators.equivH1Cotangent (R := R) (S := S) P.toGenerators
    refine ⟨?_⟩
    intro x y
    have hxy' : eH1.symm x = eH1.symm y := Subsingleton.elim _ _
    exact eH1.symm.injective hxy'
  letI : Module.Free S (Ω[S⁄R]) := Module.Free.of_subsingleton (R := S) (N := Ω[S⁄R])
  letI : Module.Projective S (Ω[S⁄R]) := Module.Projective.of_free
  exact
    (Algebra.FormallySmooth.iff_subsingleton_and_projective (R := R) (S := S)).2
      ⟨hH1, inferInstance⟩

/-- Relative-dimension-zero standard smooth algebras are formally étale. -/
theorem formallyEtale
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.FormallyEtale R S := by
  letI : Algebra.FormallyUnramified R S :=
    Algebra.IsStandardSmoothOfRelativeDimension.formallyUnramified
  letI : Algebra.FormallySmooth R S :=
    Algebra.IsStandardSmoothOfRelativeDimension.formallySmooth
  exact Algebra.FormallyEtale.of_unramified_and_smooth

/-- Relative-dimension-zero standard smooth algebras are étale. -/
theorem etale
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.Etale R S := by
  letI : Algebra.FormallyEtale R S :=
    Algebra.IsStandardSmoothOfRelativeDimension.formallyEtale
  letI : Algebra.IsStandardSmooth R S :=
    Algebra.IsStandardSmoothOfRelativeDimension.isStandardSmooth (n := 0) (R := R) (S := S)
  letI : Algebra.FinitePresentation R S :=
    standardSmooth_finitePresentation
  exact ⟨inferInstance, inferInstance⟩

/-- A local relative-dimension-zero standard smooth algebra over a field is a
field. This is the owner corollary used by the étale-chart local-geometry
arguments. -/
theorem standardSmoothOfRelativeDimensionZero_isField_of_isLocalRing
    {A : Type u} [CommRing A] [Algebra k A] [IsLocalRing A]
    [Algebra.IsStandardSmoothOfRelativeDimension 0 k A] :
    IsField A := by
  letI : Algebra.IsStandardSmooth k A :=
    Algebra.IsStandardSmoothOfRelativeDimension.isStandardSmooth (n := 0) (R := k) (S := A)
  letI : Algebra.FinitePresentation k A :=
    standardSmooth_finitePresentation
  letI : Algebra.FormallyEtale k A :=
    Algebra.IsStandardSmoothOfRelativeDimension.formallyEtale
  exact formallyEtale_isField_of_field_of_isLocalRing (k := k)

end IsStandardSmoothOfRelativeDimension

end _root_.Algebra

theorem standardSmooth_finitePresentation
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
    [Algebra.IsStandardSmooth R A] :
    Algebra.FinitePresentation R A :=
  Boundary._root_.Algebra.standardSmooth_finitePresentation (R := R) (A := A)

theorem standardSmoothOfRelativeDimensionZero_formallyUnramified
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.FormallyUnramified R S :=
  Boundary._root_.Algebra.IsStandardSmoothOfRelativeDimension.formallyUnramified
    (R := R) (S := S)

theorem standardSmoothOfRelativeDimensionZero_formallySmooth
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.FormallySmooth R S :=
  Boundary._root_.Algebra.IsStandardSmoothOfRelativeDimension.formallySmooth
    (R := R) (S := S)

theorem standardSmoothOfRelativeDimensionZero_formallyEtale
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.FormallyEtale R S :=
  Boundary._root_.Algebra.IsStandardSmoothOfRelativeDimension.formallyEtale
    (R := R) (S := S)

theorem standardSmoothOfRelativeDimensionZero_etale
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    [Algebra.IsStandardSmoothOfRelativeDimension 0 R S] :
    Algebra.Etale R S :=
  Boundary._root_.Algebra.IsStandardSmoothOfRelativeDimension.etale
    (R := R) (S := S)
