import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Objects.Owner

/-!
# Singleton objects in the analytic additive envelope

This file embeds one certified trace-correspondence object as a one-component
object of the additive envelope.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The one-component additive-envelope object generated by a certified trace object. -/
def TraceAnalyticAdditiveObject.singleton
    (object : TraceCorQObject) :
    TraceAnalyticAdditiveObject :=
  [object]

/-- A singleton additive-envelope object has one component. -/
theorem TraceAnalyticAdditiveObject.singleton_length
    (object : TraceCorQObject) :
    (TraceAnalyticAdditiveObject.singleton object).length =
      1 :=
  rfl

/-- The zero-index component of a singleton additive-envelope object is its generator. -/
theorem TraceAnalyticAdditiveObject.singleton_component_zero
    (object : TraceCorQObject) :
    (TraceAnalyticAdditiveObject.singleton object).component 0 =
      object :=
  rfl

/-- Every component of a singleton additive-envelope object is its generator. -/
theorem TraceAnalyticAdditiveObject.singleton_component
    (object : TraceCorQObject)
    (index : Fin (TraceAnalyticAdditiveObject.singleton object).length) :
    (TraceAnalyticAdditiveObject.singleton object).component index =
      object :=
  Eq.trans
    (congrArg
      (fun singletonIndex =>
        (TraceAnalyticAdditiveObject.singleton object).component
          singletonIndex)
      (Subsingleton.elim index 0))
    (TraceAnalyticAdditiveObject.singleton_component_zero object)

/-- The source expression of the zero-index singleton component is the source expression
of the generator. -/
theorem TraceAnalyticAdditiveObject.singleton_component_zero_source
    (object : TraceCorQObject) :
    ((TraceAnalyticAdditiveObject.singleton object).component 0).source =
      object.source :=
  congrArg
    TraceCorQObject.source
    (TraceAnalyticAdditiveObject.singleton_component_zero object)

/-- The weight level of a singleton additive-envelope object is the maximum of the
generator weight and zero. -/
theorem TraceAnalyticAdditiveObject.singleton_weightLevel
    (object : TraceCorQObject) :
    (TraceAnalyticAdditiveObject.singleton object).weightLevel =
      Nat.max object.weightLevel 0 :=
  rfl

/-- The singleton additive-envelope object has the generator as its first list entry. -/
theorem TraceAnalyticAdditiveObject.singleton_get_zero
    (object : TraceCorQObject) :
    (TraceAnalyticAdditiveObject.singleton object).get 0 =
      object :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
