import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Public.Generators.Core.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Root.TraceCorQ.Quotient.RelationWitness.Generators.NamedCoherence.Owner

/-!
# Top-root generated relation witnesses

This file exposes the generic support input, support candidate, closure, and
witness attached to a single trace-correspondence relation generator.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The top root exposes the support quotient input of a relation generator. -/
def AnalyticMotivesRoot.traceCorQRelationGenerator_supportQuotientInput
    (relation : TraceCorQRelationGenerator) :
    TraceCorQQuotientInput :=
  TraceCorQ.relationGenerator_supportQuotientInput
    relation

/-- The top root exposes support-input formal sums. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportQuotientInput_formalSum
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportQuotientInput relation).formalSum =
      relation.support :=
  TraceCorQ.relationGenerator_supportQuotientInput_formalSum
    relation

/-- The top root exposes support-input singleton ledgers. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportQuotientInput_ledger
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportQuotientInput relation).ledger =
      TraceCorQRelationLedger.singleton relation :=
  TraceCorQ.relationGenerator_supportQuotientInput_ledger
    relation

/-- The top root exposes the support candidate of a relation generator. -/
def AnalyticMotivesRoot.traceCorQRelationGenerator_supportCandidate
    (relation : TraceCorQRelationGenerator) :
    TraceCorQQuotientCandidate :=
  TraceCorQ.relationGenerator_supportCandidate
    relation

/-- The top root exposes the input representing a support candidate. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportCandidate_input
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportCandidate relation).input =
      TraceCorQRelationGenerator.supportQuotientInput relation :=
  TraceCorQ.relationGenerator_supportCandidate_input
    relation

/-- The top root exposes support-candidate formal sums. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportCandidate_formalSum
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportCandidate relation).formalSum =
      relation.support :=
  TraceCorQ.relationGenerator_supportCandidate_formalSum
    relation

/-- The top root exposes support-candidate singleton ledgers. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportCandidate_ledger
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportCandidate relation).ledger =
      TraceCorQRelationLedger.singleton relation :=
  TraceCorQ.relationGenerator_supportCandidate_ledger
    relation

/-- The top root exposes the singleton-ledger closure generated by a relation generator. -/
def AnalyticMotivesRoot.traceCorQRelationGenerator_supportClosure
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationClosure
      (TraceCorQRelationLedger.singleton relation)
      (TraceCorQRelationGenerator.supportCandidate relation)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQ.relationGenerator_supportClosure
    relation

/-- The top root exposes the closure as a transported primitive step. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportClosure_eq_transport_step
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationGenerator.supportClosure relation =
      TraceCorQRelationClosure.transportLedger
        (TraceCorQRelationLedger.append_empty
          (TraceCorQRelationLedger.singleton relation))
        (TraceCorQRelationClosure.stepDerivation
          TraceCorQRelationLedger.empty
          relation) :=
  TraceCorQ.relationGenerator_supportClosure_eq_transport_step
    relation

/-- The top root exposes the canonical support witness generated by a relation generator. -/
def AnalyticMotivesRoot.traceCorQRelationGenerator_supportWitness
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationWitness
      (TraceCorQRelationGenerator.supportCandidate relation)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQ.relationGenerator_supportWitness
    relation

/-- The top root exposes the support witness as a ledger derivation. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportWitness_eq_ofClosure
    (relation : TraceCorQRelationGenerator) :
    TraceCorQRelationGenerator.supportWitness relation =
      TraceCorQRelationWitness.ofLedgerDerivation
        (TraceCorQRelationLedger.singleton relation)
        (TraceCorQRelationGenerator.supportClosure relation) :=
  TraceCorQ.relationGenerator_supportWitness_eq_ofClosure
    relation

/-- The top root exposes support-witness singleton ledgers. -/
theorem AnalyticMotivesRoot.traceCorQRelationGenerator_supportWitness_ledger
    (relation : TraceCorQRelationGenerator) :
    (TraceCorQRelationGenerator.supportWitness relation).ledger =
      TraceCorQRelationLedger.singleton relation :=
  TraceCorQ.relationGenerator_supportWitness_ledger
    relation

end AnalyticMotives
end LFunctions
end Boundary
