import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Relation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Generators.NamedCoherence.Owner

/-!
# Named-coherence quotient relations

This file turns named coherence support witnesses into quotient relations.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The quotient relation generated by a Fubini coherence support. -/
def TraceCorQQuotientRelation.fubiniSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.fubiniSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.fubiniSupportWitness
      source
      target
      support)

/-- The quotient relation generated by a schedule-exchange coherence support. -/
def TraceCorQQuotientRelation.scheduleExchangeSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.scheduleExchangeSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.scheduleExchangeSupportWitness
      source
      target
      support)

/-- The quotient relation generated by a residue-channel coherence support. -/
def TraceCorQQuotientRelation.residueChannelSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.residueChannelSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.residueChannelSupportWitness
      source
      target
      support)

/-- The quotient relation generated by a Stokes-residue coherence support. -/
def TraceCorQQuotientRelation.stokesResidueSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.stokesResidueSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.stokesResidueSupportWitness
      source
      target
      support)

/-- The quotient relation generated by a refinement coherence support. -/
def TraceCorQQuotientRelation.refinementSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.refinementSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.refinementSupportWitness
      source
      target
      support)

/-- The quotient relation generated by an associativity coherence support. -/
def TraceCorQQuotientRelation.associativitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.associativitySupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.associativitySupportWitness
      source
      target
      support)

/-- The quotient relation generated by a left-identity coherence support. -/
def TraceCorQQuotientRelation.leftIdentitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.leftIdentitySupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.leftIdentitySupportWitness
      source
      target
      support)

/-- The quotient relation generated by a right-identity coherence support. -/
def TraceCorQQuotientRelation.rightIdentitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.rightIdentitySupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.ofWitness
    (TraceCorQRelationGenerator.rightIdentitySupportWitness
      source
      target
      support)

end AnalyticMotives
end LFunctions
end Boundary
