import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.RelationWitness.Public.Generators.Candidates.Payload.Owner

/-!
# Public generated support candidates

This file aggregates public payload facades for support candidates generated by
relation generators under the `TraceCorQ` namespace.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

end AnalyticMotives
end LFunctions
end Boundary
