import Mathlib.Data.Rat.Defs
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceExpression.FormalSum.Owner

/-!
# Rational trace-expression combinations

This file owns the rational linear span of formal trace expressions.

The intended object is the concrete Q-linear syntax on trace atoms.  This is
where motivic rationalization first appears on the analytic side: as formal
Q-linear combinations of trace expressions and later trace transports.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A rationally weighted trace atom. -/
abbrev QTraceTerm :=
  Rat × TraceAtom

/-- A finite Q-linear trace expression. -/
abbrev QTraceExpression :=
  List QTraceTerm

/-- The zero Q-linear trace expression. -/
def QTraceExpression.zero : QTraceExpression :=
  []

/-- The singleton Q-linear trace expression generated by a weighted atom. -/
def QTraceExpression.singleton (coefficient : Rat) (atom : TraceAtom) : QTraceExpression :=
  [(coefficient, atom)]

/-- Addition in the free Q-linear trace syntax is list concatenation. -/
def QTraceExpression.add (left right : QTraceExpression) : QTraceExpression :=
  left ++ right

/-- Scalar multiplication multiplies only the rational coefficient of each term. -/
def QTraceExpression.smul (coefficient : Rat) (expression : QTraceExpression) :
    QTraceExpression :=
  expression.map (fun term => (coefficient * term.1, term.2))

end AnalyticMotives
end LFunctions
end Boundary
