import Mathlib.Data.Rat.Defs
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceExpression.FormalSum.Owner

/-!
# Rational trace-expression combinations

This file owns the rational linear span of formal trace expressions.

The object defined here is the concrete Q-linear syntax on trace atoms.  This
is where motivic rationalization first appears on the analytic side: as formal
Q-linear combinations of trace expressions and later trace transports.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- A rationally weighted trace atom. -/
abbrev QTraceTerm :=
  Rat × TraceAtom

/-- A finite Q-linear trace expression. -/
abbrev QTraceExpression :=
  List QTraceTerm

/-- The zero Q-linear trace expression. -/
def QTraceExpression.zero : QTraceExpression :=
  []

/-- The singleton Q-linear trace expression generated by a weighted atom. -/
def QTraceExpression.singleton (coefficient : Rat) (atom : TraceAtom) : QTraceExpression :=
  [(coefficient, atom)]

/-- Addition in the free Q-linear trace syntax is list concatenation. -/
def QTraceExpression.add (left right : QTraceExpression) : QTraceExpression :=
  left ++ right

/-- Scalar multiplication multiplies only the rational coefficient of each term. -/
def QTraceExpression.smul (coefficient : Rat) (expression : QTraceExpression) :
    QTraceExpression :=
  expression.map (fun term => (coefficient * term.1, term.2))

/-- The zero Q-linear trace expression is the empty list. -/
theorem QTraceExpression.zero_eq_nil :
    QTraceExpression.zero = [] :=
  rfl

/-- A singleton Q-linear trace expression is the one-term list. -/
theorem QTraceExpression.singleton_eq_cons
    (coefficient : Rat)
    (atom : TraceAtom) :
    QTraceExpression.singleton coefficient atom =
      (coefficient, atom) :: [] :=
  rfl

/-- Q-linear trace-expression addition is list concatenation. -/
theorem QTraceExpression.add_eq_append
    (left right : QTraceExpression) :
    QTraceExpression.add left right =
      left ++ right :=
  rfl

/-- Q-linear trace-expression scalar multiplication maps coefficients termwise. -/
theorem QTraceExpression.smul_eq_map
    (coefficient : Rat)
    (expression : QTraceExpression) :
    QTraceExpression.smul coefficient expression =
      expression.map (fun term => (coefficient * term.1, term.2)) :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
