import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.ThirdIsoBounded.Degrees.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Shift.Owner

/-!
# Full bounded packages for shifted mapping-cone triangles

The shift of a bounded analytic map is again a bounded analytic map, so its
mapping cone carries the full bounded-triangle package with an iso-bounded
third representative.  The shifted original cone is related to this concrete
package by Mathlib's shifted mapping-cone isomorphisms.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- The full bounded mapping-cone package generated by the shifted bounded map. -/
def TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedTriangleWithThirdIsoBounded
      bound :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded
    (hom.shift shift)

/-- The shifted full package has the concrete shifted source as first bounded representative. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage_first
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
      hom
      shift).trianglePackage.first =
      source.shift shift :=
  rfl

/-- The shifted full package has the concrete shifted target as second bounded representative. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage_second
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
      hom
      shift).trianglePackage.second =
      target.shift shift :=
  rfl

/-- The shifted full package is the mapping-cone triangle of the shifted bounded map. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage_triangle
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
      hom
      shift).trianglePackage.triangle =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.triangle
        (hom.shift shift) :=
  rfl

/-- The shifted full package's third representative is the cone of the shifted map. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage_thirdComplex
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
      hom
      shift).thirdRepresentativeComplex =
      CochainComplex.mappingCone (hom.shift shift) :=
  rfl

/-- The shifted original mapping-cone triangle is isomorphic to the shifted-map full package. -/
def TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedTriangleIsoShiftedFullPackage
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangle
      hom).shiftedTriangle shift ≅
      (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
        hom
        shift).trianglePackage.triangle :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedTriangleIsoShiftedMap
    hom
    shift

/-- The shifted-triangle comparison is the shifted-map mapping-cone comparison. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedTriangleIsoShiftedFullPackage_eq
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedTriangleIsoShiftedFullPackage
        hom
        shift =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedTriangleIsoShiftedMap
        hom
        shift :=
  rfl

/-- The shifted original third vertex is isomorphic to the full package's third vertex. -/
def TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedThirdObjectIsoShiftedFullPackage
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    TraceAnalyticAdditiveHomotopyCategory.shiftedObject
        (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject hom)
        shift ≅
      (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
        hom
        shift).trianglePackage.triangleThirdVertex :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedThirdObjectIsoShiftedMap
    hom
    shift

/-- The shifted-third comparison is the shifted-map cone-third comparison. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedThirdObjectIsoShiftedFullPackage_eq
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedThirdObjectIsoShiftedFullPackage
        hom
        shift =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedThirdObjectIsoShiftedMap
        hom
        shift :=
  rfl

/-- The shifted full package is distinguished as a concrete mapping-cone package. -/
theorem TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage_distinguished
    {bound : Nat}
    {source target :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy bound}
    (hom :
      TraceAnalyticAdditiveCochainComplex.WeightBoundedBy.Hom source target)
    (shift : ℤ) :
    (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
      hom
      shift).trianglePackage.triangle ∈
      TraceAnalyticAdditiveHomotopyCategory.distinguishedTriangles :=
  (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.shiftedFullPackage
    hom
    shift).trianglePackage.triangle_distinguished

end AnalyticMotives
end LFunctions
end Boundary
