import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.LocalizationInput.Cancellation.Owner

/-!
# Reduction closure for formal localization words

This file owns the generated word relation obtained from primitive cancellation
cells by symmetry, transitivity, and word contexts.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The generated relation on formal localization words. -/
inductive TraceLocalizationWordRelation :
    {source target : TraceCorQObject} →
      TraceLocalizationWord source target →
      TraceLocalizationWord source target →
      Type where
  | ofReduction
      {source target : TraceCorQObject}
      {left right : TraceLocalizationWord source target}
      (reduction : TraceLocalizationWordReduction left right) :
      TraceLocalizationWordRelation left right
  | refl
      {source target : TraceCorQObject}
      (word : TraceLocalizationWord source target) :
      TraceLocalizationWordRelation word word
  | symm
      {source target : TraceCorQObject}
      {left right : TraceLocalizationWord source target}
      (relation : TraceLocalizationWordRelation left right) :
      TraceLocalizationWordRelation right left
  | trans
      {source target : TraceCorQObject}
      {left middle right : TraceLocalizationWord source target}
      (first : TraceLocalizationWordRelation left middle)
      (second : TraceLocalizationWordRelation middle right) :
      TraceLocalizationWordRelation left right
  | prefix
      {first second third : TraceCorQObject}
      {left right : TraceLocalizationWord second third}
      (prefix : TraceLocalizationWord first second)
      (relation : TraceLocalizationWordRelation left right) :
      TraceLocalizationWordRelation
        (TraceLocalizationWord.comp prefix left)
        (TraceLocalizationWord.comp prefix right)
  | suffix
      {first second third : TraceCorQObject}
      {left right : TraceLocalizationWord first second}
      (relation : TraceLocalizationWordRelation left right)
      (suffix : TraceLocalizationWord second third) :
      TraceLocalizationWordRelation
        (TraceLocalizationWord.comp left suffix)
        (TraceLocalizationWord.comp right suffix)

/-- A primitive reduction generates a word relation. -/
def TraceLocalizationWordRelation.ofCancellation
    {source target : TraceCorQObject}
    {left right : TraceLocalizationWord source target}
    (reduction : TraceLocalizationWordReduction left right) :
    TraceLocalizationWordRelation left right :=
  TraceLocalizationWordRelation.ofReduction reduction

/-- Forward-inverse cancellation generates a word relation. -/
def TraceLocalizationWordRelation.forwardInverse
    (input : TraceLocalizationInput) :
    TraceLocalizationWordRelation
      (TraceLocalizationWord.forwardThenInverse input)
      (TraceLocalizationWord.identity input.sourceObject) :=
  TraceLocalizationWordRelation.ofCancellation
    (TraceLocalizationWordReduction.forwardInverseCell input)

/-- Inverse-forward cancellation generates a word relation. -/
def TraceLocalizationWordRelation.inverseForward
    (input : TraceLocalizationInput) :
    TraceLocalizationWordRelation
      (TraceLocalizationWord.inverseThenForward input)
      (TraceLocalizationWord.identity input.targetObject) :=
  TraceLocalizationWordRelation.ofCancellation
    (TraceLocalizationWordReduction.inverseForwardCell input)

/-- A word relation can be placed after a fixed prefix word. -/
def TraceLocalizationWordRelation.withPrefix
    {first second third : TraceCorQObject}
    {left right : TraceLocalizationWord second third}
    (prefix : TraceLocalizationWord first second)
    (relation : TraceLocalizationWordRelation left right) :
    TraceLocalizationWordRelation
      (TraceLocalizationWord.comp prefix left)
      (TraceLocalizationWord.comp prefix right) :=
  TraceLocalizationWordRelation.prefix prefix relation

/-- A word relation can be placed before a fixed suffix word. -/
def TraceLocalizationWordRelation.withSuffix
    {first second third : TraceCorQObject}
    {left right : TraceLocalizationWord first second}
    (relation : TraceLocalizationWordRelation left right)
    (suffix : TraceLocalizationWord second third) :
    TraceLocalizationWordRelation
      (TraceLocalizationWord.comp left suffix)
      (TraceLocalizationWord.comp right suffix) :=
  TraceLocalizationWordRelation.suffix relation suffix

/-- The named forward-inverse relation is generated by the corresponding cancellation cell. -/
theorem TraceLocalizationWordRelation.forwardInverse_eq_ofCancellation
    (input : TraceLocalizationInput) :
    TraceLocalizationWordRelation.forwardInverse input =
      TraceLocalizationWordRelation.ofCancellation
        (TraceLocalizationWordReduction.forwardInverseCell input) :=
  rfl

/-- The named inverse-forward relation is generated by the corresponding cancellation cell. -/
theorem TraceLocalizationWordRelation.inverseForward_eq_ofCancellation
    (input : TraceLocalizationInput) :
    TraceLocalizationWordRelation.inverseForward input =
      TraceLocalizationWordRelation.ofCancellation
        (TraceLocalizationWordReduction.inverseForwardCell input) :=
  rfl

end AnalyticMotives
end LFunctions
end Boundary
