import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.LocalizationInput.Rotation.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.ThirdIsoBounded.InverseRotation.ShortComplex.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.Weights.AdditiveEnvelope.Bounds.Triangles.MappingCone.Package.ThirdIsoBounded.Rotation.ShortComplex.Owner

/-!
# Short complexes of localization-input rotated bounded mapping-cone triangles

This file specializes the rotated and inverse-rotated full bounded mapping-cone
short complexes to concrete bounded maps generated by localization inputs.
-/

noncomputable section

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

open CategoryTheory

/-- The short complex attached to the localization-input rotated bounded mapping-cone
triangle. -/
def TraceLocalizationInput.boundedMappingConeRotatedShortComplex
    (input : TraceLocalizationInput) :
    ShortComplex TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedShortComplex
    input.boundedAdditiveComplexHom

/-- The localization-input rotated short complex has the target object as its left
vertex. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedShortComplex_X₁
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedShortComplex.X₁ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedShortComplex_X₁
    input.boundedAdditiveComplexHom

/-- The localization-input rotated short complex has the cone object as its middle
vertex. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedShortComplex_X₂
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedShortComplex.X₂ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedShortComplex_X₂
    input.boundedAdditiveComplexHom

/-- The localization-input rotated short complex has the shifted source object as its
right vertex. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedShortComplex_X₃
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedShortComplex.X₃ =
      (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject
        input.boundedAdditiveComplexHom)⟦(1 : ℤ)⟧ :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedShortComplex_X₃
    input.boundedAdditiveComplexHom

/-- The first morphism of the localization-input rotated short complex is the cone
inclusion. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedShortComplex_f
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedShortComplex.f =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondMap
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedShortComplex_f
    input.boundedAdditiveComplexHom

/-- The second morphism of the localization-input rotated short complex is the
connecting map. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedShortComplex_g
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedShortComplex.g =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.connectingMap
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedShortComplex_g
    input.boundedAdditiveComplexHom

/-- The localization-input rotated short complex has zero composite. -/
theorem TraceLocalizationInput.boundedMappingConeRotatedShortComplex_zero
    (input : TraceLocalizationInput) :
    input.boundedMappingConeRotatedShortComplex.f ≫
        input.boundedMappingConeRotatedShortComplex.g =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_rotatedShortComplex_zero
    input.boundedAdditiveComplexHom

/-- The short complex attached to the localization-input inverse-rotated bounded
mapping-cone triangle. -/
def TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex
    (input : TraceLocalizationInput) :
    ShortComplex TraceAnalyticAdditiveHomotopyCategory :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedShortComplex
    input.boundedAdditiveComplexHom

/-- The localization-input inverse-rotated short complex has the shifted cone object as
its left vertex. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_X₁
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedShortComplex.X₁ =
      (TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.thirdObject
        input.boundedAdditiveComplexHom)⟦(-1 : ℤ)⟧ :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedShortComplex_X₁
    input.boundedAdditiveComplexHom

/-- The localization-input inverse-rotated short complex has the source object as its
middle vertex. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_X₂
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedShortComplex.X₂ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedShortComplex_X₂
    input.boundedAdditiveComplexHom

/-- The localization-input inverse-rotated short complex has the target object as its
right vertex. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_X₃
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedShortComplex.X₃ =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.secondObject
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedShortComplex_X₃
    input.boundedAdditiveComplexHom

/-- The first morphism of the localization-input inverse-rotated short complex is the
shifted negative connecting map with unit transport. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_f
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedShortComplex.f =
      -(TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.connectingMap
        input.boundedAdditiveComplexHom)⟦(-1 : ℤ)⟧' ≫
        (shiftEquiv TraceAnalyticAdditiveHomotopyCategory
          (1 : ℤ)).unitIso.inv.app _ :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedShortComplex_f
    input.boundedAdditiveComplexHom

/-- The second morphism of the localization-input inverse-rotated short complex is the
bounded map. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_g
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedShortComplex.g =
      TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.firstMap
        input.boundedAdditiveComplexHom :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedShortComplex_g
    input.boundedAdditiveComplexHom

/-- The localization-input inverse-rotated short complex has zero composite. -/
theorem TraceLocalizationInput.boundedMappingConeInverseRotatedShortComplex_zero
    (input : TraceLocalizationInput) :
    input.boundedMappingConeInverseRotatedShortComplex.f ≫
        input.boundedMappingConeInverseRotatedShortComplex.g =
      0 :=
  TraceAnalyticAdditiveHomotopyCategory.BoundedMappingCone.boundedTriangleWithThirdIsoBounded_inverseRotatedShortComplex_zero
    input.boundedAdditiveComplexHom

end AnalyticMotives
end LFunctions
end Boundary
