import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.CalculusLocalization.Descent.Owner
import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.Motives.IntervalHomotopy.Localization.Owner

/-!
# Interval-homotopy calculus localization inventory
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The localized isomorphism generated by interval Stokes deformation. -/
def TraceCalculusLocalization.intervalStokesIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalStokes source target).localizedSourceObject
      (TraceLocalizationInput.intervalStokes source target).localizedTargetObject :=
  TraceIntervalHomotopyLocalization.stokesIso source target

/-- The localized isomorphism generated by interval Fubini interchange. -/
def TraceCalculusLocalization.intervalFubiniIso
    (source target : QTraceExpression) :
    CategoryTheory.Iso
      (TraceLocalizationInput.intervalFubini source target).localizedSourceObject
      (TraceLocalizationInput.intervalFubini source target).localizedTargetObject :=
  TraceIntervalHomotopyLocalization.fubiniIso source target

/-- Interval Stokes in the calculus inventory is the interval-localization isomorphism. -/
theorem TraceCalculusLocalization.intervalStokesIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.intervalStokesIso source target =
      TraceIntervalHomotopyLocalization.stokesIso source target :=
  rfl

/-- Interval Stokes in the calculus inventory has the Stokes forward arrow as hom. -/
theorem TraceCalculusLocalization.intervalStokesIso_hom
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalStokesIso source target).hom =
      TraceLocalizationInput.intervalStokesForwardArrow source target :=
  rfl

/-- Interval Stokes in the calculus inventory has the Stokes inverse arrow as inverse. -/
theorem TraceCalculusLocalization.intervalStokesIso_inv
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalStokesIso source target).inv =
      TraceLocalizationInput.intervalStokesInverseArrow source target :=
  rfl

/-- Interval Fubini in the calculus inventory is the interval-localization isomorphism. -/
theorem TraceCalculusLocalization.intervalFubiniIso_eq
    (source target : QTraceExpression) :
    TraceCalculusLocalization.intervalFubiniIso source target =
      TraceIntervalHomotopyLocalization.fubiniIso source target :=
  rfl

/-- Interval Fubini in the calculus inventory has the Fubini forward arrow as hom. -/
theorem TraceCalculusLocalization.intervalFubiniIso_hom
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalFubiniIso source target).hom =
      TraceLocalizationInput.intervalFubiniForwardArrow source target :=
  rfl

/-- Interval Fubini in the calculus inventory has the Fubini inverse arrow as inverse. -/
theorem TraceCalculusLocalization.intervalFubiniIso_inv
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalFubiniIso source target).inv =
      TraceLocalizationInput.intervalFubiniInverseArrow source target :=
  rfl

/-- Interval Stokes hom followed by inverse is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalStokesIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.intervalStokesIso source target).hom
        (TraceCalculusLocalization.intervalStokesIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalStokes source target).sourceObject :=
  TraceIntervalHomotopyLocalization.stokesIso_hom_comp_inv
    source
    target

/-- Interval Stokes inverse followed by hom is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalStokesIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.intervalStokesIso source target).inv
        (TraceCalculusLocalization.intervalStokesIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalStokes source target).targetObject :=
  TraceIntervalHomotopyLocalization.stokesIso_inv_comp_hom
    source
    target

/-- Interval Stokes hom followed by inverse is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalStokesIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalStokesIso source target).hom ≫
        (TraceCalculusLocalization.intervalStokesIso source target).inv =
      (𝟙 (TraceLocalizationInput.intervalStokes source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.intervalStokes source target).localizedSourceObject
          (TraceLocalizationInput.intervalStokes source target).localizedSourceObject) :=
  TraceIntervalHomotopyLocalization.stokesIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Interval Stokes inverse followed by hom is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalStokesIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalStokesIso source target).inv ≫
        (TraceCalculusLocalization.intervalStokesIso source target).hom =
      (𝟙 (TraceLocalizationInput.intervalStokes source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.intervalStokes source target).localizedTargetObject
          (TraceLocalizationInput.intervalStokes source target).localizedTargetObject) :=
  TraceIntervalHomotopyLocalization.stokesIso_inv_comp_hom_eq_categoryIdentity
    source
    target

/-- Interval Fubini hom followed by inverse is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalFubiniIso_hom_comp_inv
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.intervalFubiniIso source target).hom
        (TraceCalculusLocalization.intervalFubiniIso source target).inv =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalFubini source target).sourceObject :=
  TraceIntervalHomotopyLocalization.fubiniIso_hom_comp_inv
    source
    target

/-- Interval Fubini inverse followed by hom is identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalFubiniIso_inv_comp_hom
    (source target : QTraceExpression) :
    TraceLocalizationWordClass.comp
        (TraceCalculusLocalization.intervalFubiniIso source target).inv
        (TraceCalculusLocalization.intervalFubiniIso source target).hom =
      TraceLocalizationWordClass.identity
        (TraceLocalizationInput.intervalFubini source target).targetObject :=
  TraceIntervalHomotopyLocalization.fubiniIso_inv_comp_hom
    source
    target

/-- Interval Fubini hom followed by inverse is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalFubiniIso_hom_comp_inv_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalFubiniIso source target).hom ≫
        (TraceCalculusLocalization.intervalFubiniIso source target).inv =
      (𝟙 (TraceLocalizationInput.intervalFubini source target).localizedSourceObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.intervalFubini source target).localizedSourceObject
          (TraceLocalizationInput.intervalFubini source target).localizedSourceObject) :=
  TraceIntervalHomotopyLocalization.fubiniIso_hom_comp_inv_eq_categoryIdentity
    source
    target

/-- Interval Fubini inverse followed by hom is categorical identity in the calculus inventory. -/
theorem TraceCalculusLocalization.intervalFubiniIso_inv_comp_hom_eq_categoryIdentity
    (source target : QTraceExpression) :
    (TraceCalculusLocalization.intervalFubiniIso source target).inv ≫
        (TraceCalculusLocalization.intervalFubiniIso source target).hom =
      (𝟙 (TraceLocalizationInput.intervalFubini source target).localizedTargetObject :
        TraceLocalizedWordHom
          (TraceLocalizationInput.intervalFubini source target).localizedTargetObject
          (TraceLocalizationInput.intervalFubini source target).localizedTargetObject) :=
  TraceIntervalHomotopyLocalization.fubiniIso_inv_comp_hom_eq_categoryIdentity
    source
    target

end AnalyticMotives
end LFunctions
end Boundary
