import Boundary.LFunctionsRootedTreeFinal.Final.AnalyticMotives.TraceCorQ.Quotient.Operations.FormalSumClass.NamedCoherence.Owner

/-!
# Top-root named-coherence quotient zero theorems

This file exposes the ambient quotient chain for named coherence supports:
relation generators give quotient relations, quotient soundness identifies the
support candidate with zero, and formal sums equipped with the named ledger
become the zero quotient class.
-/

namespace Boundary
namespace LFunctions
namespace AnalyticMotives

/-- The top root exposes the quotient relation generated by a Fubini support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_fubiniSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.fubiniSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.fubiniSupportZero
    source
    target
    support

/-- The top root exposes the quotient relation generated by a schedule-exchange support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_scheduleExchangeSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.scheduleExchangeSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.scheduleExchangeSupportZero
    source
    target
    support

/-- The top root exposes the quotient relation generated by a residue-channel support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_residueChannelSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.residueChannelSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.residueChannelSupportZero
    source
    target
    support

/-- The top root exposes the quotient relation generated by a Stokes-residue support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_stokesResidueSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.stokesResidueSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.stokesResidueSupportZero
    source
    target
    support

/-- The top root exposes the quotient relation generated by a refinement support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_refinementSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.refinementSupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.refinementSupportZero
    source
    target
    support

/-- The top root exposes the quotient relation generated by an associativity support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_associativitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.associativitySupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.associativitySupportZero
    source
    target
    support

/-- The top root exposes the quotient relation generated by a left-identity support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_leftIdentitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.leftIdentitySupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.leftIdentitySupportZero
    source
    target
    support

/-- The top root exposes the quotient relation generated by a right-identity support. -/
def AnalyticMotivesRoot.traceCorQQuotientRelation_rightIdentitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotientRelation
      (TraceCorQRelationGenerator.rightIdentitySupportCandidate
        source
        target
        support)
      TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotientRelation.rightIdentitySupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for Fubini supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_fubiniSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.fubiniSupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_fubiniSupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for schedule-exchange supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_scheduleExchangeSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.scheduleExchangeSupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_scheduleExchangeSupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for residue-channel supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_residueChannelSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.residueChannelSupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_residueChannelSupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for Stokes-residue supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_stokesResidueSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.stokesResidueSupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_stokesResidueSupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for refinement supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_refinementSupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.refinementSupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_refinementSupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for associativity supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_associativitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.associativitySupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_associativitySupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for left-identity supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_leftIdentitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.leftIdentitySupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_leftIdentitySupportZero
    source
    target
    support

/-- The top root exposes quotient soundness for right-identity supports. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_sound_rightIdentitySupportZero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofCandidate
      (TraceCorQRelationGenerator.rightIdentitySupportCandidate
        source
        target
        support) =
      TraceCorQQuotient.ofCandidate
        TraceCorQQuotientCandidate.empty :=
  TraceCorQQuotient.sound_rightIdentitySupportZero
    source
    target
    support

/-- The top root exposes Fubini formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_fubini_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.fubini source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_fubini_eq_zero
    source
    target
    support

/-- The top root exposes schedule-exchange formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_scheduleExchange_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.scheduleExchange source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_scheduleExchange_eq_zero
    source
    target
    support

/-- The top root exposes residue-channel formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_residueChannel_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.residueChannel source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_residueChannel_eq_zero
    source
    target
    support

/-- The top root exposes Stokes-residue formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_stokesResidue_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.stokesResidue source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_stokesResidue_eq_zero
    source
    target
    support

/-- The top root exposes refinement formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_refinement_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.refinement source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_refinement_eq_zero
    source
    target
    support

/-- The top root exposes associativity formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_associativity_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.associativity source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_associativity_eq_zero
    source
    target
    support

/-- The top root exposes left-identity formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_leftIdentity_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.leftIdentity source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_leftIdentity_eq_zero
    source
    target
    support

/-- The top root exposes right-identity formal-sum ledgers as zero quotient classes. -/
theorem AnalyticMotivesRoot.traceCorQQuotient_ofFormalSumLedger_rightIdentity_eq_zero
    (source target : TraceRewritePath)
    (support : TraceCorQFormalSum) :
    TraceCorQQuotient.ofFormalSumLedger
      support
      (TraceCorQRelationLedger.rightIdentity source target support) =
      TraceCorQQuotient.zero :=
  TraceCorQQuotient.ofFormalSumLedger_rightIdentity_eq_zero
    source
    target
    support

end AnalyticMotives
end LFunctions
end Boundary
